### ISSUE TITLE
TypeError: Cannot read property 'getComponentFromError' of null

### ISSUE THREAD

**Issue by Janatbek** [wallabyjs/public#1976] opened 2019-01-18 19:04 UTC
### Issue description or question
Getting this error:
TypeError: Cannot read property 'getComponentFromError' of null

### Wallaby.js configuration file
[same as this](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js)

### Code editor or IDE name and version
WebStorm 2018.2.5

### OS name and version

Windows

**Comment by ArtemGovorov** [comment] 2019-01-18 23:08
I'm assuming the issue is resolved by https://github.com/wallabyjs/ngCliWebpackSample/pull/41.

**Closed by ArtemGovorov** 2019-01-18 23:08 UTC
