### ISSUE TITLE
[Error] Error: write EPIPE

### ISSUE THREAD

**Issue by JoshWhite** [wallabyjs/public#2349] opened 2020-02-20 18:00 UTC
### Issue description or question
After stopping / starting wallaby, I am getting the following output in the Wallaby.js Console. I had made some local changes to my code, but have undone any changes and I am still getting the error. 

I've tried :
- Stopping / starting again
- Closing / opening VS Code
- Restarting the machine

Jest appears to run fine, so I'm pretty sure this isn't a code issue. 

### Error
```
[Info]  2020-02-20T17:45:03.161Z project Wallaby Node version: v12.16.0
[Info]  2020-02-20T17:45:03.162Z project Wallaby config: C:\work\im\G_IM2\IM2.Core.UI\IM2.Core.UI\Scripts\wallaby.js
[Info]  Started Wallaby.js Core v1.0.854
[Info]  2020-02-20T17:45:03.933Z project File cache: C:\Users\josh\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.176\projects\4623de863b1fa81b
[Info]  2020-02-20T17:45:04.004Z uiService Listening port 51235
[Error] No files with tests found, check your tests list patterns. 
[Info]  2020-02-20T17:45:05.148Z workers Parallelism for initial run: 6, for regular run: 3
[Info]  2020-02-20T17:45:05.148Z workers Starting run worker instance #0
[Info]  2020-02-20T17:45:05.148Z workers Starting run worker instance #1
[Info]  2020-02-20T17:45:05.149Z workers Starting run worker instance #2
[Info]  2020-02-20T17:45:05.149Z workers Starting run worker instance #3
[Info]  2020-02-20T17:45:05.149Z workers Starting run worker instance #4
[Info]  2020-02-20T17:45:05.149Z workers Starting run worker instance #5
[Info]  2020-02-20T17:45:05.174Z workers Web server is listening at 60171
[Info]  2020-02-20T17:45:07.068Z project Stopping process pool
[Info]  2020-02-20T17:45:07.070Z project File cache is up-to-date, starting full test run
[Error] Error: write EPIPE 
[Error]     at ChildProcess.target._send (internal/child_process.js:806:20) 
[Error]     at ChildProcess.target.send (internal/child_process.js:677:19) 
[Error]     at r.emit (events.js:321:20) 
[Error]     at Object.onceWrapper (events.js:428:26) 
[Error]     at ChildProcess.emit (events.js:321:20) 
[Error]     at emit (internal/child_process.js:876:12) 
[Error]     at processTicksAndRejections (internal/process/task_queues.js:85:21) 
[Error] Error: write EPIPE 
[Error]     at ChildProcess.target._send (internal/child_process.js:806:20) 
[Error]     at ChildProcess.target.send (internal/child_process.js:677:19) 
[Error]     at r.emit (events.js:321:20) 
[Error]     at Object.onceWrapper (events.js:428:26) 
[Error]     at ChildProcess.emit (events.js:321:20) 
[Error]     at emit (internal/child_process.js:876:12) 
[Error]     at processTicksAndRejections (internal/process/task_queues.js:85:21) 
[Error] Error: write EPIPE 
[Error]     at ChildProcess.target._send (internal/child_process.js:806:20) 
[Error]     at ChildProcess.target.send (internal/child_process.js:677:19) 
[Error]     at r.emit (events.js:321:20) 
[Error]     at Object.onceWrapper (events.js:428:26) 
[Error]     at ChildProcess.emit (events.js:321:20) 
[Error]     at emit (internal/child_process.js:876:12) 
[Error]     at processTicksAndRejections (internal/process/task_queues.js:85:21) 
[Error] Error: write EPIPE 
[Error]     at ChildProcess.target._send (internal/child_process.js:806:20) 
[Error]     at ChildProcess.target.send (internal/child_process.js:677:19) 
[Error]     at r.emit (events.js:321:20) 
[Error]     at Object.onceWrapper (events.js:428:26) 
[Error]     at ChildProcess.emit (events.js:321:20) 
[Error]     at emit (internal/child_process.js:876:12) 
[Error]     at processTicksAndRejections (internal/process/task_queues.js:85:21) 
[Error] Error: write EPIPE 
[Error]     at ChildProcess.target._send (internal/child_process.js:806:20) 
[Error]     at ChildProcess.target.send (internal/child_process.js:677:19) 
[Error]     at r.emit (events.js:321:20) 
[Error]     at Object.onceWrapper (events.js:428:26) 
[Error]     at ChildProcess.emit (events.js:321:20) 
[Error]     at emit (internal/child_process.js:876:12) 
[Error]     at processTicksAndRejections (internal/process/task_queues.js:85:21) 
[Error] Error: write EPIPE 
[Error]     at ChildProcess.target._send (internal/child_process.js:806:20) 
[Error]     at ChildProcess.target.send (internal/child_process.js:677:19) 
[Error]     at r.emit (events.js:321:20) 
[Error]     at Object.onceWrapper (events.js:428:26) 
[Error]     at ChildProcess.emit (events.js:321:20) 
[Error]     at emit (internal/child_process.js:876:12) 
[Error]     at processTicksAndRejections (internal/process/task_queues.js:85:21) 
[Error] Error: write EPIPE 
[Error]     at ChildProcess.target._send (internal/child_process.js:806:20) 
[Error]     at ChildProcess.target.send (internal/child_process.js:677:19) 
[Error]     at r.emit (events.js:321:20) 
[Error]     at Object.onceWrapper (events.js:428:26) 
[Error]     at ChildProcess.emit (events.js:321:20) 
[Error]     at emit (internal/child_process.js:876:12) 
[Error]     at processTicksAndRejections (internal/process/task_queues.js:85:21) 
[Error] Error: write EPIPE 
[Error]     at ChildProcess.target._send (internal/child_process.js:806:20) 
[Error]     at ChildProcess.target.send (internal/child_process.js:677:19) 
[Error]     at r.emit (events.js:321:20) 
[Error]     at Object.onceWrapper (events.js:428:26) 
[Error]     at ChildProcess.emit (events.js:321:20) 
[Error]     at emit (internal/child_process.js:876:12) 
[Error]     at processTicksAndRejections (internal/process/task_queues.js:85:21) 
[Info]  2020-02-20T17:45:07.608Z workers Started run worker instance (delayed) #0
[Info]  2020-02-20T17:45:07.609Z workers Started run worker instance (delayed) #5
[Info]  2020-02-20T17:45:07.610Z workers Started run worker instance (delayed) #3
[Info]  2020-02-20T17:45:07.610Z workers Started run worker instance (delayed) #1
[Info]  2020-02-20T17:45:07.610Z workers Started run worker instance (delayed) #2
[Info]  2020-02-20T17:45:07.611Z workers Started run worker instance (delayed) #4
```

### Wallaby diagnostics report

```
{
  editorVersion: '1.42.1',
  pluginVersion: '1.0.176',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.18362',
  nodeVersion: 'v12.16.0',
  coreVersion: '1.0.854',
  config: {
    files: [
      { pattern: '**/im2.*.js', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
      { pattern: '**/im2.*.test.js', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: '*.test.js', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: 'testHelpers/**', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
      { pattern: '**/im2.*.test.js.snap', ignore: false, instrument: false, trigger: true, load: true, order: 3 },
      { pattern: 'testHelpers/**.snap', ignore: true, instrument: false, trigger: true, load: true },
      { pattern: 'package.json', ignore: false, instrument: false, trigger: true, load: true, order: 4 }
    ],
    tests: [ { pattern: '**/im2.*.test.js', ignore: false, trigger: true, load: true, test: true, order: 5 }, { pattern: 'testHelpers/**', ignore: true, trigger: true, load: true, test: true } ],
    debug: true,
    env: { type: 'node', runner: 'node', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    testFramework: { version: 'jest@0.4.3', configurator: 'jest@0.4.3', reporter: 'jest@0.4.3', starter: 'jest@0.4.3' },
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    compilers: { '**/*.?(lit)coffee?(.md)': [Function] },
    preprocessors: { 'package.json': [Function] },
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'module.exports = function (wallaby) {\r\n' +
      "  var path = require('path');\r\n" +
      '    process.env.NODE_PATH +=\r\n' +
      '        path.delimiter +\r\n' +
      "        path.join(__dirname, 'node_modules') +\r\n" +
      '        path.delimiter +\r\n' +
      "        path.join(__dirname, 'node_modules/react-scripts/node_modules');\r\n" +
      "    require('module').Module._initPaths();\r\n" +
      '\r\n' +
      '    return {\r\n' +
      '      files: [\r\n' +
      "        './**/im2.*.js',\r\n" +
      "        '!./**/im2.*.test.js',\r\n" +
      "        '!*.test.js',\r\n" +
      "        './testHelpers/**',\r\n" +
      '      ],\r\n' +
      '  \r\n' +
      '      tests: [\r\n' +
      "        './**/im2.*.test.js',\r\n" +
      "        '!./testHelpers/**'\r\n" +
      '      ],\r\n' +
      '\r\n' +
      '      debug: true,\r\n' +
      '  \r\n' +
      '      env: {\r\n' +
      "        type: 'node',\r\n" +
      "        runner: 'node'\r\n" +
      '      },\r\n' +
      '\r\n' +
      "      testFramework: 'jest'\r\n" +
      '    };\r\n' +
      '  };\r\n' +
      '  '
  },
  packageJSON: {
    dependencies: {
      'doc-cookies': '^1.0.2',
      'es6-promise': '3.2.1',
      hammerjs: '^2.0.4',
      highcharts: '^6.1.1',
      'im-external-lib-bootstrap': '2.1.1',
      'im-external-lib-colpick': '1.0.0',
      'im-external-lib-fullcalendar': '1.6.4',
      'im-external-lib-fullcalendar-2': '2.8.0',
      'im-external-lib-jquery': '1.0.0',
      'im-external-lib-jquery-ui-2': '1.9.2',
      'im-external-lib-jquery-ui-barcode': '1.0.0',
      'im-external-lib-jquery-ui-datepicker-locales': '1.0.0',
      'im-external-lib-jquery-ui-scrolling': '1.0.0',
      'im-external-lib-knockout-mapping': '2.4.2',
      'im-external-lib-modernizr': '2.5.2',
      'im-external-lib-moment-locales': '1.0.0',
      'im-external-lib-plupload': '1.0.0',
      'im-external-lib-select2-locales': '1.0.0',
      'im-external-lib-telerik': '1.0.0',
      'im-external-lib-tinymce': '1.0.3',
      'im-js-core': '1.2.1',
      'jquery-placeholder': '^2.0.7',
      'jquery-tiny-pubsub': '^0.7.1',
      'jquery-validation-unobtrusive': '^3.2.5',
      knockout: '3.4.2',
      'knockout-mapping': '2.5.0',
      moment: '^2.24.0',
      'moment-range': '^2.1.0',
      'powerbi-client': '2.5.1',
      ramda: '^0.24.1',
      select2: '^3.5.2-browserify',
      webfontloader: '^1.6.28'
    },
    devDependencies: { 'babel-plugin-transform-object-rest-spread': '^6.26.0', eslint: '^6.7.1', 'im-external-lib-tiny-pub-sub': '^0.8.0', jest: '^25.1.0' }
  },
  fs: { numberOfFiles: 415 },
  debug: [
    '2020-02-20T17:56:11.243Z project Wallaby Node version: v12.16.0\n',
    '2020-02-20T17:56:11.243Z project Wallaby config: C:\\work\\im\\G_IM2\\IM2.Core.UI\\IM2.Core.UI\\Scripts\\wallaby.js\n',
    '2020-02-20T17:56:12.015Z project File cache: C:\\Users\\josh\\.vscode\\extensions\\wallabyjs.wallaby-vscode-1.0.176\\projects\\4623de863b1fa81b\n',
    '2020-02-20T17:56:12.071Z uiService Listening port 51235\n',
    '2020-02-20T17:56:12.799Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2020-02-20T17:56:12.799Z workers Starting run worker instance #0\n',
    '2020-02-20T17:56:12.799Z workers Starting run worker instance #1\n',
    '2020-02-20T17:56:12.799Z workers Starting run worker instance #2\n',
    '2020-02-20T17:56:12.799Z workers Starting run worker instance #3\n',
    '2020-02-20T17:56:12.799Z workers Starting run worker instance #4\n',
    '2020-02-20T17:56:12.799Z workers Starting run worker instance #5\n',
    '2020-02-20T17:56:12.803Z workers Web server is listening at 50955\n',
    '2020-02-20T17:56:14.911Z project Stopping process pool\n',
    '2020-02-20T17:56:14.911Z project File cache is up-to-date, starting full test run\n',
    '2020-02-20T17:56:14.966Z workers Started run worker instance (delayed) #1\n',
    '2020-02-20T17:56:14.967Z workers Started run worker instance (delayed) #0\n',
    '2020-02-20T17:56:14.967Z workers Started run worker instance (delayed) #3\n',
    '2020-02-20T17:56:14.968Z workers Started run worker instance (delayed) #5\n',
    '2020-02-20T17:56:14.968Z workers Started run worker instance (delayed) #2\n',
    '2020-02-20T17:56:14.968Z workers Started run worker instance (delayed) #4\n',
    '2020-02-20T17:56:16.891Z project Re-attaching document block comment\n',
    '2020-02-20T17:56:16.921Z project Re-attaching document block comment\n'
  ]
}
```

**Comment by smcenlly** [comment] 2020-02-20 20:52
Your project dependencies indicate that you are using jest v25. Could you please try switching to use Wallaby with [automatic configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) instead of a configuration file to see if that fixes your problem?

If you're still having the problem after switching to automatic configuration can you please:
1) Provide us with an updated diagnostic report.
2) Try re-installing your Wallaby VS Code extension?

**Comment by JoshWhite** [comment] 2020-02-21 17:11
Interesting...

I hadn't switched to using automatic config, as I am working in a monolith repo, with multiple small apps under a nested folder structure (which all use their own wallaby.config.js file). 

I initially tried uninstalling / reinstalling the extension, but the same error occurred. 

I then switched to automatic config and picked the appropriate directory, at which point tests all ran according to plan. 

I assumed the wallaby config file must be incorrect in my directory, but after switching back to selecting my config file, it is still working 😕 .

Either way, my tests are now running and wallaby is working again, so thanks! 🎉 .

**Comment by vjau** [comment] 2020-02-29 09:25
I have the same problem here in Webstorm on Linux
```
wallaby.js started
core v1.0.856
2020-02-29T09:18:22.973Z project Wallaby Node version: v12.16.1
2020-02-29T09:18:22.973Z project Wallaby config: /home/vincent/dev/Cadendar/wallaby.plouf
2020-02-29T09:18:28.137Z fs File system scan has finished by timeout
2020-02-29T09:18:28.192Z project File cache: /home/vincent/.WebStorm2019.3/system/wallaby/projects/8d78ac0d1b975a68
2020-02-29T09:18:28.199Z uiService Listening port 51235
2020-02-29T09:18:28.990Z workers Parallelism for initial run: 6, for regular run: 3
2020-02-29T09:18:28.990Z workers Starting run worker instance #0
2020-02-29T09:18:28.990Z workers Starting run worker instance #1
2020-02-29T09:18:28.990Z workers Starting run worker instance #2
2020-02-29T09:18:28.990Z workers Starting run worker instance #3
2020-02-29T09:18:28.990Z workers Starting run worker instance #4
2020-02-29T09:18:28.990Z workers Starting run worker instance #5
2020-02-29T09:18:29.047Z workers Web server is listening at 40807
2020-02-29T09:18:31.611Z workers Started run worker instance (delayed) #0
2020-02-29T09:18:31.612Z workers Started run worker instance (delayed) #1
2020-02-29T09:18:31.612Z workers Started run worker instance (delayed) #2
2020-02-29T09:18:31.612Z workers Started run worker instance (delayed) #3
2020-02-29T09:18:31.612Z workers Started run worker instance (delayed) #4
2020-02-29T09:18:31.612Z workers Started run worker instance (delayed) #5
2020-02-29T09:18:31.619Z project Stopping process pool
2020-02-29T09:18:31.620Z project File cache is up-to-date, starting full test run
Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:677:19)
    at r.emit (events.js:311:20)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:677:19)
    at r.emit (events.js:311:20)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:677:19)
    at r.emit (events.js:311:20)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:677:19)
    at r.emit (events.js:311:20)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:677:19)
    at r.emit (events.js:311:20)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:677:19)
    at r.emit (events.js:311:20)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:677:19)
    at r.emit (events.js:311:20)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:677:19)
    at r.emit (events.js:311:20)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```
For some reason copy diagnostic report doesn't work on my computer (says sucess, but it is not copied in the clipboard).

My settings are here : 
```
module.exports = function (wallaby) {

  return {
    files: [
      { pattern: 'client/**/tests/*.js', ignore: true },
      { pattern: 'server/**/tests/*.js', ignore: true },
      { pattern: 'imports/**/tests/*.js', ignore: true },
      { pattern: 'server/**/tests/*.jsx', ignore: true },
      { pattern: 'client/**/tests/*.jsx', ignore: true },
      { pattern: '**/tests/*.ts', ignore: true},
      'client/imports/**/*.js',
      'client/imports/**/*.jsx',
      'imports/**/*.js',
      'server/**/*.js',
      '**/*.ts'
    ],
    tests: [
      'client/**/tests/*.js*',
      'imports/**/tests/*.js',
      'server/**/tests/*.js',
      '**/tests/**/*.ts',

    ],
    compilers: {
      '**/*.js*': wallaby.compilers.babel({
      babel: require('@babel/core'),
              presets: ['@babel/preset-env',  "@babel/preset-react"]
      })
    },
    preprocessors: {
                '**/*.js': file => require('@babel/core').transform(
                  file.content,
                  {sourceMap: true, compact: false, filename: file.path, babelrc: true})
              },
    env: {
      type: 'node'
    },
    testFramework: 'mocha',
    setup: function() {
      global.React = require('react');
    },
     workers: {
           recycle: true
         },
         debug : true
  };
};
```

**Comment by ArtemGovorov** [comment] 2020-02-29 10:36
@vjau 
- Has the issue started to show up recently (maybe with some system updates)?
- Can you try downgrading to node v12.15.0 (or 12.14.1) to see if it fixes the issue for you?

**Comment by vjau** [comment] 2020-02-29 12:17
@ArtemGovorov i have this issue 100% of the time since latest wallaby plugin update in webstorm, but i had also somehow this issue for a few weeks. 
Same error message with 12.15.0, 12.14,1, 12.13.1
With 8.17.0, i don't get the error message, but the processing doesn't go further than this:
```
wallaby.js started
core v1.0.856
2020-02-29T12:13:38.774Z project Wallaby Node version: v8.17.0
2020-02-29T12:13:38.774Z project Wallaby config: /home/vincent/dev/Cadendar/wallaby.plouf
2020-02-29T12:13:42.081Z fs File system scan has finished by timeout
2020-02-29T12:13:42.140Z project File cache: /home/vincent/.WebStorm2019.3/system/wallaby/projects/8d78ac0d1b975a68
2020-02-29T12:13:42.147Z uiService Listening port 51235
2020-02-29T12:13:43.018Z workers Parallelism for initial run: 6, for regular run: 3
2020-02-29T12:13:43.018Z workers Starting run worker instance #0
2020-02-29T12:13:43.018Z workers Starting run worker instance #1
2020-02-29T12:13:43.018Z workers Starting run worker instance #2
2020-02-29T12:13:43.018Z workers Starting run worker instance #3
2020-02-29T12:13:43.018Z workers Starting run worker instance #4
2020-02-29T12:13:43.018Z workers Starting run worker instance #5
2020-02-29T12:13:43.085Z workers Web server is listening at 45399
2020-02-29T12:13:49.619Z project Stopping process pool
2020-02-29T12:13:49.619Z project File cache is up-to-date, starting full test run
2020-02-29T12:13:50.003Z workers Started run worker instance (delayed) #2
2020-02-29T12:13:50.004Z workers Started run worker instance (delayed) #1
2020-02-29T12:13:50.004Z workers Started run worker instance (delayed) #0
2020-02-29T12:13:50.005Z workers Started run worker instance (delayed) #4
2020-02-29T12:13:50.005Z workers Started run worker instance (delayed) #3
2020-02-29T12:13:50.005Z workers Started run worker instance (delayed) #5
```

And i get no error, but no result either. Perhaps the problem is Typescript related.

**Comment by smcenlly** [comment] 2020-03-02 00:37
@vjau - could you please try our [create-react-app sample repo](https://github.com/wallabyjs/wallaby-create-react-app) that is described in our [create react app tutorial](https://wallabyjs.com/docs/tutorial/react.html) to help us work out if this is project related vs. a system issue?

If Wallaby is not working for you in our sample application, can you please try running WebStorm as super-user and see if that works for you?

If our sample project works for you, are you able to provide us with a cut-down sample of your repo that has the same problem so that we can attempt to duplicate?

Finally,  you mention that perhaps the problem is related to TypeScript. Is there any reason you mention that? Is TypeScript something that you recently added or updated in your project?

**Comment by vjau** [comment] 2020-03-02 19:52
@smcenlly i have removed the line 
```
{
      babel: require('@babel/core'),
              presets: ['@babel/preset-env',  "@babel/preset-react"]
      }
```
as argument to  wallaby.compiler.babel(), and that seems to fix the problem, thank you.

**Comment by vjau** [comment] 2020-03-02 20:03
@smcenlly oh no, sorry, it doesn't work. I got strange result, so i relaunched the tests and i get again the wrrite EPIPE error.
I have two projects with the same wallaby setting, same webstorm installation, same wallaby plugin, one work and not the other.
I fear it's Typescript related because i recently added it to the not working project.


 It's hard to do a minimal repo since it's a very big meteor app with a lot a LOCs.



I got this JAVA stacktrace in webstorm related to Wallaby, not sure if this helps : 
```
java.lang.NullPointerException
	at com.wallaby.javascript.execution.n.a(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by smcenlly** [comment] 2020-03-03 02:24
Could you please download and install Wallaby for IntelliJ [from here](https://wallaby-downloads.s3.amazonaws.com/temp/wallaby-intellij-v1.0.164.zip), and then report your stack trace?

For your project that's not working, it seems that something is causing the worker processes to fail (could be babel/typescript), but we're not sure.

If you're able to provide us with a cut-down sample that has the problem, we can investigate for you. If you are worried about sharing code publicly, you may email us: hello@wallabyjs.com.

**Comment by smcenlly** [comment] 2020-03-03 02:26
We are also wondering if there is something about the path to your project that is not working (e.g. space in path, unicode character in path, on a network drive, etc.). Could you try cloning your project to a fresh/different directory in the same root folder as the project that is working and see if the fresh clone of your project is working?

**Comment by vjau** [comment] 2020-03-03 19:28
Ok, this is enzyme related. Removing the tests written in .jsx cause the other tests to succeed.

**Comment by vjau** [comment] 2020-03-03 19:30
Oh no, sorry again, at the second run i get the Epipe thing.

**Comment by vjau** [comment] 2020-03-03 19:32
I don't think this is path related, since it's a seven years old project that didn't ever change path. The other working project lies in the same place on my hard drive.

**Comment by vjau** [comment] 2020-03-03 21:33
I have created a minimal repo. 
https://github.com/vjau/wallabytest
When i run wallaby one time it works, when i restart it, i get the error.
If it's related to my Webstorm settings, i can share them with you.

**Comment by smcenlly** [comment] 2020-03-03 23:26
Thanks for sending through the sample repo. I'm not sure how close this configuration/project structure is to the project that's not working for you but we noticed a couple of problems:

1. In your sample project, your TypeScript and JavaScript files are sitting beside each other in the same directories (with the same names and different extensions). The way Wallaby is configured, it's actually running tests on both the `.js` files and the `.ts` files which is incorrect.

2. Your way Wallaby is configured, any `.ts` files under your `node_modules` directory are being compiled by TypeScript, transformed by babel and then instrumented by Wallaby, which we don't think is what you are intending to do.

3. Your configuration file is specifying the recycle the wallaby worker processes between test runs; this may be necessary for your production code but is definitely not required for the sample that you sent to us. This won't impact you apart from causing your tests to take a little longer.

---

Could you please try updating your configuration file as shown below to see if this solves your problem (everything is working for us with this configuration):

```javascript
module.exports = function(wallaby) {
  return {
    files: [
      'imports/**/*.ts', 
      '!imports/**/tests/*.ts', 
    ],
    tests: [
      'imports/**/tests/*.ts', 
    ],
    compilers: {
      '**/*.js*': wallaby.compilers.babel()
    },
    preprocessors: {
      '**/*.js': file => require('@babel/core').transform(file.content, { sourceMap: true, compact: false, filename: file.path, babelrc: true })
    },
    env: {
      type: 'node'
    },
    testFramework: 'mocha',
    setup: function() {
      global.React = require('react');
    }
  };
};
```

If the configuration above works for you, then you need to apply the same fixes to your existing configuration:
1. Ensure that you only include the `.ts` source files and not their `.js` compiled output.
2. Ensure that your file/test patterns do not result in files under `node_modules` being used by Wallaby.

**Comment by vjau** [comment] 2020-03-04 09:16
>     1. In your sample project, your TypeScript and JavaScript files are sitting beside each other in the same directories (with the same names and different extensions). The way Wallaby is configured, it's actually running tests on both the `.js` files and the `.ts` files which is incorrect.

It is a progressive migration from js to ts so there is mixed code and mixed test. AFAIK, this is correct.


> 
>     2. Your way Wallaby is configured, any `.ts` files under your `node_modules` directory are being compiled by TypeScript, transformed by babel and then instrumented by Wallaby, which we don't think is what you are intending to do.

That's right, i have tried adding a ```{pattern: 'node_modules/*.**, ignore:true'}``` directive, but that didn't fix the problem.



> 
>     3. Your configuration file is specifying the recycle the wallaby worker processes between test runs; this may be necessary for your production code but is definitely not required for the sample that you sent to us. This won't impact you apart from causing your tests to take a little longer.

Removing this directive didn't fix the problem in my actual project.

However, i succeeded in getting Wallaby to work by rewriting my config includes like this 

```
files: [
      '!client/**/tests/*.js',
            '!client/**/tests/*.jsx',
            '!client/**/tests/*.ts',
            '!imports/**/tests/*.js',
            '!imports/**/tests/*.ts',
            '!server/**/tests/*.js',
            '!server/**/tests/*.ts',

      'client/**/*.js',
      'client/**/*.jsx',
      'client/**/*.ts',
      'imports/**/*.js',
      'imports/**/*.ts',
      'server/**/*.js',
      'server/**/*.ts',

    ],
    tests: [
      'client/**/tests/*.js',
      'client/**/tests/*.jsx',
      'client/**/tests/*.ts',
      'imports/**/tests/*.js',
      'imports/**/tests/*.ts',
      'server/**/tests/*.js',
      'server/**/tests/*.ts'

    ],
```

>     1. Ensure that you only include the `.ts` source files and not their `.js` compiled output.

There was no compiled output (tsconfig with `noEmit :true`)


Anyway, thank you very much for your help.

If i could have a suggestion, these include/exclude patterns have been the source of many configuration problem for me in the past, would'nt it be possible for Wallaby to automatically exclude from the `files` section everything that match the `tests` section ?

**Comment by smcenlly** [comment] 2020-03-04 22:43
Glad to hear that you got this working. If you can reliably reproduce the EPIPE issue, we'd like to understand how to duplicate the problem so we can either fix it, or else improve our error reporting (please let us know).

I have created [this feature request](https://github.com/wallabyjs/public/issues/2362) to track your suggestion.

**Closed by smcenlly** 2020-03-04 22:43 UTC

**Comment by nvrr** [comment] 2020-08-20 11:55
heoll
