### ISSUE TITLE
Electron Test Runner Error

### ISSUE THREAD

**Issue by teddyhwang** [wallabyjs/public#518] opened 2016-03-14 18:20 UTC
### Issue description or question

When trying to run the tests with Electron, I get the following error:

> `/Users/teddy.hwang/Sites/Points/apollo/storefront/storefront-ng-core/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron: bad option: --harmony_arrow_functions`

### Wallaby.js configuration file

```javascript
var wallabify = require('wallabify');
var _ = require('lodash');
var ngHtml2Js = require('browserify-ng-html2js');

var wallabyPostprocessor = wallabify({
    entryPatterns: [
      'tests/client/**/*.js'
    ],
    extensions: ['.coffee']
  },
  function(b) {
    b.transform(ngHtml2Js, {ext: '.html', global: true});
  }
);

module.exports = function() {
  return {
    files: [
      {pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrumented: false},
      {pattern: 'node_modules/intl/dist/Intl.min.js', instrumented: false},
      {pattern: 'node_modules/intl/locale-data/complete.js', instrumented: false},
      {pattern: 'node_modules/jquery/dist/jquery.min.js', instrumented: false},
      {pattern: 'node_modules/sinon/pkg/sinon-1.17.3.js', instrumented: false},
      {pattern: 'node_modules/chai/chai.js', instrumented: false},
      {pattern: 'node_modules/chai-jquery/chai-jquery.js', instrumented: false},
      {pattern: 'node_modules/sinon-chai/lib/sinon-chai.js', instrumented: false},
      {pattern: 'src/scripts/**/*.coffee', load: false},
      {pattern: 'src/scripts/**/*.js', load: false, instrumented: false},
      {pattern: 'src/scripts/**/*.html', load: false},
      {pattern: 'node_modules/@points/**/*.coffee', load: false, instrumented: false},
      {pattern: 'node_modules/@points/**/*.html', load: false, instrumented: false},
      {pattern: 'node_modules/@points/pts-fixtures/storefront/**/*.json', load: false, instrumented: false},
      {pattern: 'tests/selectors/**/*.coffee', load: false},
      {pattern: 'tests/defaultFormValues.coffee', load: false},
      {pattern: 'tests/generators.coffee', load: false},
      {pattern: 'tests/client/*.coffee', load: false},
      {pattern: 'tests/client/integration/mixins/*.coffee', load: false}
    ],
    tests: [
      {pattern: 'tests/client/unit/**/*.coffee', load: false}
      // Integration tests are too slow
      // , {pattern: 'tests/client/integration/*.coffee', load: false}
    ],
    testFramework: 'mocha',
    postprocessor: wallabyPostprocessor,
    env: {
      kind: 'electron'
    },
    bootstrap: function (wallaby) {
      var mocha = wallaby.testFramework;
      mocha.timeout(20000);
      window.__moduleBundler.loadTests();
      window.expect = chai.expect;
    }
  };
};
```

### Code editor or IDE name and version

Atom v1.x
Electron-prebuilt v0.37.2

### OS name and version

OSX

**Comment by ArtemGovorov** [comment] 2016-03-15 04:10
Thanks for the report. The issue is fixed in core v1.0.200. The core will be updated automatically in a few minutes, to get the update ASAP, you may [force the core update](https://github.com/wallabyjs/public/issues/413#issuecomment-173174486).

**Closed** 2016-03-15 04:09 UTC
