### ISSUE TITLE
Visual Studio wallaby start problem

### ISSUE THREAD

**Issue by brettjacobson** [wallabyjs/public#283] opened 2015-10-03 17:31 UTC
WallabyJS is no longer working for me, with an exception that offers little guidance as to where the problem is.
When I try and start wallabyJS (by right clicking the wallaby.json file), I'm now getting the following text in the console log:
<pre>
wallaby.js started
core v1.0.123
wallaby.js stopped
</pre>

The .wallaby/*.log file contains the following exception detail:
<pre>
2015-10-03 17:23:41Z [46] Error Wallaby.Runner 0: Failed to start Runner.
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.ParallelEnumerable.ToDictionary[TSource,TKey,TElement](ParallelQuery`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Linq.ParallelEnumerable.ToDictionary[TSource,TKey,TElement](ParallelQuery`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at ⁭⁭⁪⁯‬⁫⁭‬⁬‮‌‮‬‬⁯‪⁫⁪⁫‮⁪‪‍‪⁫‌⁪‬⁪‍‫⁭⁯⁯‍⁭‎‍⁭‮.⁭⁮‌⁭‎‏‬‪​⁮‎‏‬‌⁯‏‏⁭⁮⁫‫‭‮‎‭‮⁭⁬‫‌⁭⁪‬⁮‬‪‫‬‫‮.‍⁭‍⁭‫⁪⁯‮‭​⁮⁪⁭⁯‍‏‪⁫‪⁭‌⁬‬⁪‌‮‏‮‫‬‪‏⁬⁫⁪‬⁮‍‭‮()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at ⁭⁭⁪⁯‬⁫⁭‬⁬‮‌‮‬‬⁯‪⁫⁪⁫‮⁪‪‍‪⁫‌⁪‬⁪‍‫⁭⁯⁯‍⁭‎‍⁭‮.\]CMH|ML"~qtBYAz^t%|#OJGc.MoveNext()
---> (Inner Exception #0) System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.ParallelEnumerable.ToDictionary[TSource,TKey,TElement](ParallelQuery`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)<---
</pre>

So two things that may have affected this (since it used to work); but my memory is fuzzy if I tried wallaby after the changes.  One thing was that I upgraded to v1.0.16 from v1.0.15.  The other thing that I did in a similar time frame was changing my "testFramework" tag from jasmine@2.2.1 to just plain "jasmine".  I've tried going back to @2.2.1 with no luck.

Last, here is my wallaby.json file:
<pre>
{
  "files": [
    "Scripts/sinon-1.9.1.js",
    "Scripts/angular.js",
    "Scripts/angular-ui-router.js",
    "Scripts/angular-mocks.js",
    "Scripts/angular-sanitize.js",
    "Scripts/select.js",
    "Scripts/ngDialog.js",
    "Scripts/tree-grid-directive.js",
    "Scripts/ui-grid.js",

    "JSTests/lib/specHelper.js",
    "JSTests/**/mock*.js",

    "app/**/*.module.js",
    "app/**/*.js"
  ],
  "tests": [
    "JSTests/**/*.spec.js",
    "JSTests/**/*Tests.js",
    "JSTests/**/*Test.js"
  ],
  "testFramework": "jasmine"
}
</pre>

I also added "debug": true to the json file, but saw nothing extra in the console or the .log file.

**Comment by ArtemGovorov** [comment] 2015-10-03 22:24
Can't yet reproduce it, could you please try to downgrade to 1.0.15 and see if the issue is reproduced for you there as well? You may [download it from here](http://update.wallabyjs.com/wallaby-vs-2015-v1.0.15.vsix), uninstall the current version and install the downloaded VSIX.

**Comment by ArtemGovorov** [comment] 2015-10-04 01:44
Thanks for providing the log, was very helpful. We are still not able to reproduce the issue locally, but according to the stack it looks like it may be related to some files that you may have added to your solution recently. More specifically, VS extension API reports the exact same file path more than once, that we were not expecting in out code. Perhaps some file was added as link (and more than once?), not sure if/how it's possible. We are going to fix it shortly anyway so no matter how it happened, wallaby will be ok with it.

Another (non related to the issue) thing I have noticed is that your libraries are instrumented (like all files in the `files` list by default). I'd recommend [setting `instrument: false` flag](http://wallabyjs.com/docs/config/files.html#file-object) for those files, that'll make your tests run faster because wallaby will not have to track code coverage for them.

**Comment by ArtemGovorov** [comment] 2015-10-04 02:26
The issue should be fixed in 1.0.17. Please try the latest version (should prompt to update automatically) and let me know if the issue has gone.

**Closed by ArtemGovorov** 2015-10-04 02:26 UTC
Labels: bug, Visual Studio

**Comment by brettjacobson** [comment] 2015-10-04 15:13
Yep, fixed it!  After upgrading to .17, I also found what was probably triggering the bug.

Due to a merge conflict, one particular .js file was included in the .csproj file twice, so I suspect that is what was triggering the exception.

Thank you for fixing my screwup! :)
