### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.$_$coverage[i][n][this._spec]=t++')

### ISSUE THREAD

**Issue by Almenit** [wallabyjs/public#464] opened 2016-02-17 09:53 UTC
We have gotten this error two times now in different files. One test file and one application file. Can't see any strange cases. It disappears when I restart wallaby. We use babel and proxyquireify, typescript, jsx and ES6.

I understand it's hard for you, without more information...

**Comment by ArtemGovorov** [comment] 2016-02-17 10:11
It looks like a caching issue, especially considering that it disappears after a restart. So when you restart wallaby, it disappears and you can't reproduce it, correct?

Do you remember what were you doing with the code right before it happened? Perhaps adding/removing files, adding new `import`/`require` at the top of a file?

**Comment by Almenit** [comment] 2016-02-17 10:23
Yes it disappears when I restart.

Yes I do. I change this:
throw new Error(`Cannot create filter for table type ${dataSource.type}`);
to
throw new Error(`Cannot create filter for column type ${dataSource.type}`);
Yes and it happen again when I changed it back. Looks like it is the template string...

**Comment by ArtemGovorov** [comment] 2016-02-17 10:28
Trying a test like this:
```javascript
  it('template string', () => {
    let dataSource = {type: ''};
    throw new Error(`Cannot create filter for table type ${dataSource.type}`);
  })
```
and the error doesn't show up. Something else must be involved.
Would it be possible for you to isolate the scenario from the rest of your code and create a sample repo (or email it to me)?

**Comment by Almenit** [comment] 2016-02-17 15:50
Sorry but that will take to much time from me. I have tried to find out more about the problem. But I can't find any clues.

**Comment by ArtemGovorov** [comment] 2016-02-17 22:27
I have added a better error checking for this error, so now it at least should better reported.

**Comment by Almenit** [comment] 2016-02-18 07:35
I didn't get anything in the console or in the log. I think I have the latest version, v1.0.186. I run in debug mode.

**Comment by ArtemGovorov** [comment] 2016-02-18 07:38
Did you get the exact same error? I didn't fix because I can't reproduce it, but I have improved the error reporting and the error report should now say that the cache is corrupted as opposed to just saying `TypeError: undefined is not an object (evaluating 'e.$_$coverage[i][n][this._spec]=t++')`

**Comment by Almenit** [comment] 2016-02-18 07:39
Yes I did.

**Comment by ArtemGovorov** [comment] 2016-02-18 07:45
Does it get reported as of one of your test errors or as a global run error (in Failing Tests and Wallaby Console)?

**Comment by Almenit** [comment] 2016-02-18 07:47
It's reported as a test error. Nothing is reported in the Wallaby Console

**Comment by ArtemGovorov** [comment] 2016-02-18 07:48
Got it, thanks. I have improved the reporting for global errors of this type, but not for test level ones, will do for these as well.

**Comment by ArtemGovorov** [comment] 2016-03-09 05:05
Closing as a duplicate of already opened bug https://github.com/wallabyjs/public/issues/81. 

If anyone getting this issue can find a way to reproduce it, please let me know.

**Closed by ArtemGovorov** 2016-03-09 05:05 UTC
Labels: duplicate
