### ISSUE TITLE
TypeError thrown from 'require' statement in jest-environment-jsdom

### ISSUE THREAD

**Issue by jonboiser** [wallabyjs/public#973] opened 2017-01-25 21:33 UTC
### Issue description or question

Just starting today, my entire test suite will not run, and this error appears in the console:

```
TypeError:jest-environment-jsdom module throws "TypeError: require(...).evalVMScript is not a function"
```

[this](https://github.com/facebook/jest/blob/master/packages/jest-environment-jsdom/src/index.js#L56) is the offending line in the stack trace.

In the console, the errors appear after the files are loaded and these "running tests in sandbox" messages:

```
Wallaby Console: Wed, 25 Jan 2017 21:31:20 GMT wallaby:workers Running tests in sandbox [worker #2, session #1ntxh]...
```
Jest CLI runs fine. Before filing this issue, #961 seemed relevant, because it is also related to node_modules resolution. 

### Wallaby.js configuration file

<details>

```javascript
const wallabyWebpack = require('wallaby-webpack');

module.exports = (wallaby) => {
  const webpackPostprocessor = wallabyWebpack({
    resolve: {
      extensions: ['', '.js', '.jsx'],
    },
  });
  return {
    tests: [
      'src/**/*.spec.js',
      { pattern: 'tests/**/*.snap' },
    ],
    files: [
      '!src/**/*.spec.js',
      { pattern: 'src/**/*.jsx', load: false },
      { pattern: 'src/**/*.js', load: false },
    ],
    compilers: {
      '**/*.js*': wallaby.compilers.babel(),
    },
    env: {
      type: 'node',
      runner: 'node',
    },
    testFramework: 'jest',
    postProcessor: webpackPostprocessor,
    debug: true,
    bootstrap(w) {
      w.testFramework.configure({
        setupFiles: [
          './config/jestConfig.js',
        ],
        moduleFileExtensions: [
          'js',
          'jsx',
          'json',
        ],
        coverageDirectory: './coverage',
      });
    },
  };
};
```
</details>

### Code editor or IDE name and version

Atom v1.13.1

### OS name and version

OSX 10.11.6

**Comment by ArtemGovorov** [comment] 2017-01-25 23:45
I'm not sure if it's related to the issue or not, but what you're doing in your config (using webpack + node env) is not supported by wallaby.js. Try removing webpack (neither jest, not wallaby.js needs it to run your tests):

```javascript
module.exports = (wallaby) => {
  return {
    tests: [
      'src/**/*.spec.js'
    ],
    files: [
      '!src/**/*.spec.js',
      { pattern: 'src/**/*.jsx', load: false },
      { pattern: 'src/**/*.js', load: false },
      { pattern: 'tests/**/*.snap' }
    ],
    compilers: {
      '**/*.js*': wallaby.compilers.babel(),
    },
    env: {
      type: 'node',
      runner: 'node',
    },
    testFramework: 'jest',
    debug: true,
    bootstrap(w) {
      w.testFramework.configure({
        setupFiles: [
          './config/jestConfig.js',
        ],
        moduleFileExtensions: [
          'js',
          'jsx',
          'json',
        ],
        coverageDirectory: './coverage',
      });
    },
  };
};
```

**Comment by jonboiser** [comment] 2017-01-26 14:58
I removed the `postProcessor: webpackPostprocessor,`(and also moved `{ pattern: 'tests/**/*.snap' }`), like above, but still getting the error.

**Comment by ArtemGovorov** [comment] 2017-01-26 15:03
Could you please share a sample repo where I could reproduce the issue to have a look?

**Comment by jonboiser** [comment] 2017-01-26 16:54
I created a simple repo here https://github.com/jonboiser/wallaby-jest-problem with some instruction in the README, which seems to isolate the issue to conflicting versions of jsdom (one in the root of node_modules, and one that is a dependency of jest).

A simple fix for my project will be to remove the extra jsdom dependency, but it seems there might be a new issue in Wallaby, since I've been working with this configuration for months and have only run into this issue yesterday.

**Comment by ipostol** [comment] 2017-01-26 21:13
Have this problem to

**Comment by ArtemGovorov** [comment] 2017-01-27 05:21
Thanks for the repo! The issue is a regression from our very recent changes in the algorithms of node module resolution for the node runner. The issue is fixed in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Closed by ArtemGovorov** 2017-01-27 05:21 UTC
Labels: bug, reproducible example required
