### ISSUE TITLE
Wallaby swallows errors from supertest

### ISSUE THREAD

**Issue by Martaver** [wallabyjs/public#1376] opened 2017-11-07 19:28 UTC
### Issue description or question

I'm using `supertest` to mock superagent calls for e2e tests, and I'm running them with wallaby. When a superagent test fails, the indicators in the editor's sidebar show the failure correctly, but the error text isn't displayed.

Ideally, I should be able to see the error displayed inline like everywhere else.

Test code is:

```
    it(`/GET cats`, () => {
        return request(server)
            .get('/cats')
            .expect(200)
            .expect({
                data: catsService.findAll(),
            });
    });
```

### Wallaby.js configuration file

```javascript
const transform = require("fuse-test-runner").wallabyFuseTestLoader;
const path = require('path');

module.exports = function (wallaby) {
    // var load = require;

    return {
        files: [
            "src/**/*.ts*",
            "!src/**/*.spec.tsx",
            "!src/**/*.e2e-spec.tsx",
            "!src/**/*.spec.ts",
            "!src/**/*.e2e-spec.ts",
            "!src/**/*.d.ts*"
        ],
        tests: [
            "src/**/*.spec.tsx",
            "src/**/*.e2e-spec.tsx",
            "src/**/*.spec.ts",
            "src/**/*.e2e-spec.ts",
            "src/**/snapshots/*.json",
        ],
        compilers: {
            '**/*.ts?(x)': wallaby.compilers.typeScript({
                jsx: 'react',
                module: 'commonjs'
            })
        },
        preprocessors: {
            "**/*.ts": file => transform(file.content),
            "**/*.tsx": file => transform(file.content)
        },
        env: {
            type: "node"
        },
        testFramework: "jest",
        debug: false
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.17.2?

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment] 2017-11-08 03:12
Wallaby doesn't swallow errors from `supertest`, it's a limitation of `supertest`. 

The problem is that `supertest` throws an error with a stack that doesn't point back to the test: https://github.com/visionmedia/supertest/issues/317. It means that it's impossible to display the error inline because the error stack doesn't contain the line (of the test). 

Not sure if it's a viable alternative in your case, but if you throw a error from a test (so that the error stack contains a line from the test), then it'll show the error inline:

![screen shot 2017-11-08 at 1 08 39 pm](https://user-images.githubusercontent.com/979966/32529821-59c552aa-c486-11e7-89f7-a005d4c427c5.png)


Also there's the pull request in the `supertest` repo https://github.com/visionmedia/supertest/pull/395 that seems to fix the issue, but it's not merged.

**Closed by ArtemGovorov** 2017-11-08 03:12 UTC
Labels: configuration question

**Comment by Martaver** [comment] 2017-11-08 08:05
Brilliant! Thanks v. much for your quick response!

**Comment by dkuida** [comment] 2018-01-27 12:28
if someone encounters this topic - I believe it was fixed already. I am using the following test successfully

`describe('countries', () => {
    test('get page', async () => {
        await request(app.callback()).get('/').expect(200, {});
    });
});`
