### ISSUE TITLE
Feature request: Integration with fast-check

### ISSUE THREAD

**Issue by dbartholomae** [wallabyjs/public#2459] opened 2020-06-24 18:01 UTC
Hi there!

Love to use Wallaby! One of the other testing tools I use a lot is [fast-check](https://github.com/dubzzz/fast-check) for property based testing. 99% of this works with Wallaby as it can just be run with jest. The only thing missing is to be able to look at diffs. Not sure how much work this would be, but if it is easy to do, it would be quite valuable for me :)

**Comment by ArtemGovorov** [comment] 2020-06-25 01:44
Thanks for creating the feature request. 

> The only thing missing is to be able to look at diffs

We haven't seen `fast-check` before, could you please paste an example of `fast-check` assertion where Wallaby could generate a diff?

**Comment by dbartholomae** [comment] 2020-06-25 08:33
For this test:
```
function fizzBuzz(n) {
  return n.toString()
}

const posNat = () => nat().map((n) => n + 1);

it("returns fizzbuzz for multiples of 15", () => {
  assert(
    property(
      posNat().map((n) => n * 15),
      (n) => {
        expect(fizzBuzz(n)).toContain("fizzbuzz");
      }
    )
  );
});
```

Wallaby fails with this text:
```
src/fizzBuzz.test.ts  returns fizzbuzz for multiples of 15 [21 ms]

	Error: Property failed after 1 tests
	{ seed: 1760036719, path: "0:0", endOnFailure: true }
	Counterexample: [15]
	Shrunk 1 time(s)
	Got error: Error: expect(received).toContain(expected) // indexOf
	
	Expected substring: "fizzbuzz"
	Received string:    "15"
	
	Stack trace: Error: expect(received).toContain(expected) // indexOf
	
	Expected substring: "fizzbuzz"
	Received string:    "15"
	    at .\src\fizzBuzz.test.ts:23:47
```

**Comment by ArtemGovorov** [comment] 2020-06-26 00:40
Thanks for providing the example. In this case the absence of diff is expected and is not related to `fast-check`. If you run 

```
expect("some string").toContain("fizzbuzz");
```

in Wallaby or Jest without `fast-check`, the reported result will be pretty similar to what you are getting, and will not contain a  formatted diff. It is because in the context of the `toContain` matcher, it doesn't make sense to compare objects side-by-side in the same way as for equality matchers, such as `toEqual`. In the `.toContain` case if the expected string does not contain the expected substring, the diff is not really helpful, because it shows the difference between things that never expected to be the same.

Hope it makes sense.

**Comment by dbartholomae** [comment] 2020-06-26 07:56
Thanks! To be honest I would prefer to also see a diff for `toContain` as it makes it a lot easier to spot the problems.
But apart from this, the problem also appears if I use `toEqual`.

**Comment by ArtemGovorov** [comment] 2020-06-29 01:21
Yeah, I see the issue exists with `toEqual` in `fast-check` too. Wallaby generates diffs if thrown error object contains `expected` and `actual` properties. The problem is that `fast-check` converts errors to strings [at some point](https://github.com/dubzzz/fast-check/blob/c341c714b526733c1795c6f2a556fd219a1f693c/src/check/property/Property.generic.ts#L37), and later on throws an error with that message. However the original error from Jest contains `expected` and `actual` properties that are lost.

**Comment by dbartholomae** [comment] 2020-06-29 11:55
So if `fast-check` were to add these properties, it would work right away with Wallaby? I'll open an issue there then :)

**Comment by dbartholomae** [comment] 2020-06-29 14:20
Does it make sense to open a separate issue for showing a diff in `toContain`, or would I have to open that with jest?

**Comment by ArtemGovorov** [comment] 2020-06-30 00:50
> So if fast-check were to add these properties, it would work right away with Wallaby? I'll open an issue there then :)

Yes, once the error that is thrown contains `expected` and `actual` properties, Wallaby will automatically display the diff.

> Does it make sense to open a separate issue for showing a diff in toContain, or would I have to open that with jest?

`toContain` matcher error from Jest doesn't contain `expected` and `actual` properties, so yes, before Wallaby can show the diff, Jest needs to start to report `expected` and `actual` properties in errors from the matcher. 

However, I still don't think it is a good idea to display diffs for `toContain` (neither for Jest, nor for Wallaby). 

The only time the diff will show up is when a string doesn't contain another substring (or an array doesn't contain an element, because [according to Jest's docs](https://jestjs.io/docs/en/expect#tocontainitem) checking arrays is another if not the main purpose of the `toContain` matcher). 

What it typically means for the displayed diff is that it will try to compare things that are not even supposed to be close/comparable. What you will see in the diff is 2 strings (that you already see in the failing tests output) and meaningless highlighting of how those strings are different (it's totally normal and expected that they are different).

Maybe I'm missing something, but can you please explain how diff for `toContain` makes it a lot easier to spot the problems?

**Comment by dbartholomae** [comment] 2020-06-30 07:54
The main reason is that opening just the expected and actual values without all the other test related logs around it makes it easier to explore them, especially for bigger values (e. g. a long array that is supposed to contain some object, and it almost contains the object but there is a typo in one sub-property). The Wallaby feature around it would be to make it easier to open values like expected or actual in a separate window to make it easier to play around and deep dive into them.

**Comment by dubzzz** [comment] 2022-05-10 20:11
For the report, as told in https://github.com/dubzzz/fast-check/issues/660#issuecomment-1122806441 I'm currently working on forwarding all the details coming from the original error onto the final one. So far, I only have a minimal POC to play with and check that it will work fine but if confirmed I will prod-ify it for the upcoming v3 of fast-check.

**Comment by smcenlly** [comment] 2022-05-10 21:52
@dubzzz - our integration with Jest knows about `matcherResult` and can process it accordingly. If `fast-check` does the same, it's possible that Wallaby will just work. When you have it working, please share a sample repo and we'll take a look and confirm whether it works with Wallaby for you.

**Comment by dubzzz** [comment] 2022-05-10 22:10
I expect it to work with this iteration:

```sh
yarn add https://627ac44fa85f791b2a3ab67a--dazzling-goodall-4f0e38.netlify.app/fast-check.tgz
npm i https://627ac44fa85f791b2a3ab67a--dazzling-goodall-4f0e38.netlify.app/fast-check.tgz
```

You can give it a try via:

```ts
const fc = require('fats-check');

test('my test', () => {
  fc.assert(
    fc.property(
      fc.boolean(),
      b => {
        expect(b).toBe(false); // Should fail with Expected: false, Actual: true
      }
    )
  );
})
```

In the custom build of fast-check I sent you above (the one from netlify), the Error produced by fast-check copies all the keys of the original Error onto the thrown one.

By the way: Is there a plan to support the newly added `Error::cause` in next releases of WallabyJS? It seems that it would even be better if instead of copying the attributes of the underlying Error on mine I could just return the underlying Error (or original one) as the cause of mine.

**Comment by smcenlly** [comment] 2022-05-12 00:50
I can confirm that the diff now works, but because the `fast-check` error is more verbose and doesn't have quite the same structure as the jest error message, the output is not as nice as when using the native jest expectations.

**jest (native)**
![image](https://user-images.githubusercontent.com/2074089/167970145-ed78545a-0068-4115-9010-ec392392d5f6.png)

**fast-check**
![image](https://user-images.githubusercontent.com/2074089/167970110-65e145fa-b0ca-4b38-9e30-01b94de86f4e.png)

If you wanted to fix this, you would need to inspect the shape/content of jest expectation failures (e.g. for circus runner, look at the `test_done` event and inspect/compare `event.test.errors`).

**Comment by smcenlly** [comment] 2022-06-14 04:35
Closing this issue as I believe this is now addressed. Any further improvements would need to be made by the `fast-check` team.

**Closed by smcenlly** 2022-06-14 04:35 UTC
Labels: feature request

**Comment by boneskull** [comment] 2025-08-29 20:37
Ref: dubzzz/fast-check#6133 for further improvements
