### ISSUE TITLE
Wallaby doesn't work with PhpStorm 2024.1

### ISSUE THREAD

**Issue by DontRepeatYourself** [wallabyjs/public#3355] opened 2024-04-05 10:11 UTC
After upgrading PhpStorm from 2023.3.6 to 2024.1 wallaby plugin raises error:

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.wallaby.javascript.actions.CopyDiagnosticsReportAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: wallaby.js]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by smcenlly** [comment] 2024-04-05 23:38
Closing as a duplicate of https://github.com/wallabyjs/public/issues/3327.

This is not actually an error, it is only a warning. Wallaby will still work for you.

> We aim to support at least the last 2 years of editors released by JetBrains (currently we support 2.5 years). Fixing this issue would decrease the editors we support to less than 1.2 years.

**Closed by smcenlly** 2024-04-05 23:38 UTC
