### ISSUE TITLE
java.nio.file.InvalidPathException in Webstorm with WSL2

### ISSUE THREAD

**Issue by GraemeF** [wallabyjs/public#2695] opened 2021-05-05 11:28 UTC
### Issue description or question

I've run into an exception in the Wallaby.js plugin for Webstorm when using with WSL2:

```
java.nio.file.InvalidPathException: Illegal char <:> at index 8: 9cc2086f://wsl$/Ubuntu/home/graeme/development/twyn/twyn-cms-ui://wsl$/Ubuntu/home/graeme/development/twyn/twyn-cms-ui/src/twyn/episodes/clips/Clip.tsx
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.wallaby.javascript.b.a.a(Unknown Source)
	at com.wallaby.javascript.WallabyController.b(Unknown Source)
	at com.wallaby.javascript.t.a(Unknown Source)
	at com.wallaby.javascript.t.editorCreated(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:123)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:86)
	at com.sun.proxy.$Proxy84.editorCreated(Unknown Source)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:203)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:158)
	at com.intellij.diff.util.DiffUtil.createEditor(DiffUtil.java:238)
	at com.intellij.diff.tools.holders.TextEditorHolder.create(TextEditorHolder.java:96)
	at com.intellij.diff.tools.holders.TextEditorHolder$TextEditorHolderFactory.create(TextEditorHolder.java:107)
	at com.intellij.diff.tools.holders.TextEditorHolder$TextEditorHolderFactory.create(TextEditorHolder.java:101)
	at com.intellij.diff.tools.util.side.TwosideDiffViewer.createEditorHolders(TwosideDiffViewer.java:106)
	at com.intellij.diff.tools.util.side.TwosideTextDiffViewer.createEditorHolders(TwosideTextDiffViewer.java:115)
	at com.intellij.diff.tools.util.side.TwosideDiffViewer.<init>(TwosideDiffViewer.java:53)
	at com.intellij.diff.tools.util.side.TwosideTextDiffViewer.<init>(TwosideTextDiffViewer.java:67)
	at com.intellij.diff.tools.simple.SimpleDiffViewer.<init>(SimpleDiffViewer.java:63)
	at com.intellij.diff.tools.simple.SimpleDiffTool.createComponent(SimpleDiffTool.java:31)
	at com.intellij.diff.impl.DiffRequestProcessor.createState(DiffRequestProcessor.java:273)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$doApplyRequest$4(DiffRequestProcessor.java:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:218)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$doApplyRequest$5(DiffRequestProcessor.java:342)
	at com.intellij.diff.util.DiffUtil.runPreservingFocus(DiffUtil.java:760)
	at com.intellij.diff.impl.DiffRequestProcessor.doApplyRequest(DiffRequestProcessor.java:332)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$applyRequest$3(DiffRequestProcessor.java:314)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:182)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:101)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:188)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:140)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:173)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:179)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:41)
	at com.intellij.diff.impl.DiffRequestProcessor.applyRequest(DiffRequestProcessor.java:322)
	at com.intellij.diff.impl.DiffRequestProcessor.applyRequest(DiffRequestProcessor.java:301)
	at com.intellij.diff.impl.CacheDiffRequestProcessor.lambda$updateRequest$0(CacheDiffRequestProcessor.java:117)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.finish(BackgroundTaskUtil.java:111)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.executeAndTryWait(BackgroundTaskUtil.java:99)
	at com.intellij.diff.util.DiffTaskQueue.executeAndTryWait(DiffTaskQueue.java:47)
	at com.intellij.diff.util.DiffTaskQueue.executeAndTryWait(DiffTaskQueue.java:38)
	at com.intellij.diff.impl.CacheDiffRequestProcessor.updateRequest(CacheDiffRequestProcessor.java:112)
	at com.intellij.diff.impl.CacheDiffRequestProcessor.updateRequest(CacheDiffRequestProcessor.java:91)
	at com.intellij.diff.impl.DiffRequestProcessor.updateRequest(DiffRequestProcessor.java:184)
	at com.intellij.diff.impl.DiffRequestProcessor.updateRequest(DiffRequestProcessor.java:179)
	at com.intellij.openapi.vcs.changes.ChangeViewDiffRequestProcessor.setCurrentChange(ChangeViewDiffRequestProcessor.java:178)
	at com.intellij.openapi.vcs.changes.ChangeViewDiffRequestProcessor.refresh(ChangeViewDiffRequestProcessor.java:159)
	at com.intellij.openapi.vcs.changes.ChangeViewDiffRequestProcessor.updatePreview(ChangeViewDiffRequestProcessor.java:85)
	at git4idea.index.ui.GitStageDiffPreview$1$1.invoke(GitStageDiffPreview.kt:28)
	at git4idea.index.ui.GitStageDiffPreview$1$1.invoke(GitStageDiffPreview.kt:21)
	at com.intellij.vcs.log.BaseSingleTaskControllerKt$sam$java_lang_Runnable$0.run(BaseSingleTaskController.kt)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Wallaby diagnostics report

Can't copy to clipboard from WSL2 as xclip won't work without a display (another issue?):

```
Diagnostics report has been successfully copied to clipboard.
May have failed to copy to clipboard. Linux/Ubuntu environments require "xclip" to be installed. Error: Can't open display: (null)
```

**Comment by smcenlly** [comment] 2021-05-06 04:22
We have tried the latest version of WebStorm with a fresh WSL2 project and everything appears to be working for us.

Can you please provide us with the following additional details:

1. What is the folder that you are opening in WebStorm? For example, on my machine it is `\\wsl$\Ubuntu\home\username\repos\sample-project`.
2. Your WebStorm version number (**WebStorm -> Help -> About**)
3. Your Wallaby plugin version (**WebStorm -> File -> Settings -> Plugins -> Installed -> Wallaby**)
4. A screenshot of your Wallaby Run Configuration, for example:

![image](https://user-images.githubusercontent.com/2074089/117241173-ddc4c900-ae75-11eb-814b-96e68fb45c91.png)

What exactly were you doing when you got the error. It looks like perhaps it was during some sort of file diff? 

Do you always get the error when you're using Wallaby with WSL2 or only sometimes?

**Comment by smcenlly** [comment] 2021-05-06 04:32
Also, is it possible that you have a folder with a `:` (colon) in it on your WSL system? Files/folders with `:` are supported by linux but not by Windows. 

We still cannot duplicate your problem by doing this but file coverage does not work and certain functionality is also broken in WebStorm (e.g. file rename).

**Comment by GraemeF** [comment] 2021-05-06 07:43
Hello, thanks for following up!

I'm not doing anything fancy - I opened my project at `\\wsl$\Ubuntu\home\graeme\development\twyn\twyn-cms-ui`. No colons anywhere - it looks like maybe something incorrectly assumed it was going to get a drive letter and added the colon?

The error occurred when I viewed local changes on a file - so yes a diff. I appreciate that there are a few rough edges to be sorted out in WebStorm+WSL2 (even without plugins) but I hope this report helps with one of them :)

Version info:

> *WebStorm 2021.1.1*
> Build #WS-211.7142.46, built on April 30, 2021
> Runtime version: 11.0.10+9-b1341.41 amd64
> VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
> Windows 10 10.0
> GC: G1 Young Generation, G1 Old Generation
> Memory: 2048M
> Cores: 32
> Non-Bundled Plugins: ... quokka.js (1.0.295), *wallaby.js (1.0.216)*

![image](https://user-images.githubusercontent.com/80714/117259972-7c393600-ae46-11eb-81e8-eb572e3cb35f.png)

**Comment by smcenlly** [comment] 2021-05-07 04:50
Unfortunately I am still unable to reproduce your problem.

Could you please provide me with step-by-step instructions from the point that you start WebStorm in case I'm missing something?

Do you get the problem outside of looking at diff changes? (i.e. when using Wallaby normally)?

**Comment by smcenlly** [comment] 2021-05-11 23:38
@GraemeF - would you mind answering my questions above?

**Comment by GraemeF** [comment] 2021-05-12 07:52
Hi, sorry, I've had to switch back to Windows to get on with the day job. I'd been meaning to try again but haven't had a chance. It was fairly straightforward though; from memory I just made some changes, viewed them in the Commit tool window (as opposed to the modal) and selected a file. I didn't see the problem anywhere else, but as I said I switched back to Windows so didn't test exhaustively.

Could it be another plugin messing with the paths? I reported here because the error dialog said it was a problem in Wallaby.js

**Comment by smcenlly** [comment] 2021-05-12 22:56
I still can't replicate your problem but I am getting another similar error using the latest version of WebStorm (see below), and I can see this has already been reported to JetBrains. Perhaps something has been broken in a more recent version of IntelliJ editors or the `sun.nio.fs.WindowsPathParser` library??

I can see that there is an issue in JetBrains YouTrack repository related to this to support WSL 2: [RIDER-44186 - Support WSL2](https://youtrack.jetbrains.com/issue/RIDER-44186) relates to [RIDER-34143 - Illegal char <:> at index](https://youtrack.jetbrains.com/issue/RIDER-34143). I expect that once these are addressed, your problem would also be resolved.

We could change Wallaby to ignore the error but I don't think that's it's correct (or a good thing) as something else may go wrong parsing paths and we wouldn't know about it. It also means Wallaby is not going to work properly when displaying coverage indicators, etc. I really think we need to wait for JetBrains to fix the problem.

I'm going to close this issue as at this point in time, we believe the problem needs to be resolved by JetBrains.

```
2021-05-06 14:16:03,155 [ 500672]   WARN - j.ide.plugins.newui.PluginLogo - Illegal char <:> at index 4: file:\C:\Users\Simon McEnlly\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-1\211.7142.46\lib\icons.jar!\plugins\pluginLogo.svg 
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:\C:\Users\Simon McEnlly\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-1\211.7142.46\lib\icons.jar!\plugins\pluginLogo.svg
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.io.File.toPath(File.java:2292)
	at com.intellij.ide.plugins.newui.PluginLogo.reloadIcon(PluginLogo.java:130)
	at com.intellij.ide.plugins.newui.PluginLogo.getDefault(PluginLogo.java:114)
	at com.intellij.ide.plugins.newui.PluginLogo.getOrLoadIcon(PluginLogo.java:171)
	at com.intellij.ide.plugins.newui.PluginLogo.getIcon(PluginLogo.java:92)
	at com.intellij.ide.plugins.newui.PluginLogo.getIcon(PluginLogo.java:87)
	at com.intellij.ide.plugins.newui.MyPluginModel.getIcon(MyPluginModel.java:1174)
	at com.intellij.ide.plugins.newui.ListPluginComponent.updateIcon(ListPluginComponent.java:541)
	at com.intellij.ide.plugins.newui.ListPluginComponent.<init>(ListPluginComponent.java:111)
	at com.intellij.ide.plugins.PluginManagerConfigurable$6.lambda$createPluginsPanel$0(PluginManagerConfigurable.java:347)
	at com.intellij.ide.plugins.newui.PluginsGroupComponent.addToGroup(PluginsGroupComponent.java:200)
	at com.intellij.ide.plugins.newui.PluginsGroupComponent.addGroup(PluginsGroupComponent.java:182)
	at com.intellij.ide.plugins.newui.PluginsGroupComponent.addGroup(PluginsGroupComponent.java:73)
	at com.intellij.ide.plugins.newui.PluginsGroupComponent.addGroup(PluginsGroupComponent.java:69)
	at com.intellij.ide.plugins.PluginManagerConfigurable$6.lambda$createPluginsPanel$2(PluginManagerConfigurable.java:396)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:203)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:797)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:694)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:436)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1702)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1661)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:134)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:107)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:99)
	at com.intellij.ide.actions.ShowPluginManagerAction.actionPerformed(ShowPluginManagerAction.java:19)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:273)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:273)
	at com.intellij.ide.actions.GotoActionAction.lambda$performAction$2(GotoActionAction.java:108)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Closed by smcenlly** 2021-05-12 22:56 UTC
