### ISSUE TITLE
Error while running vitest from within wallaby

### ISSUE THREAD

**Issue by excursus** [wallabyjs/public#3187] opened 2023-03-23 18:28 UTC
### Issue description or question

I've created a minimally reproducible repo of my example, which you can find [here](https://github.com/excursus/wallaby-solidjs-vitest-broken/). The repo has only one test file containing one test. The test runs fine from the command line, but when run through wallaby in vscode it errors out with the message: `TypeError: DEV$1.hashValue is not a function`.

While digging around, I found that running the test from the command line causes vitest to import `node_modules/solid-js/web/dist/server.cjs` but while running from wallaby, it imports `node_modules/solid-js/web/dist/dev.js`, which might be the source of the disconnect.

### Wallaby diagnostics report

```
{
  editorVersion: '1.73.0',
  pluginVersion: '1.0.348',
  editorType: 'VSCode',
  osVersion: 'darwin 22.2.0',
  nodeVersion: 'v18.10.0',
  coreVersion: '1.0.1398',
  checksum: 'OTlmNzNkNTcyY2FlNjUwMzAyYWFkODIwMTNjNDQ1ODAsMTcwOTMzNzYwMDAwMCww',
  config: {
    diagnostics: {
      vitest: {
        file: {
          config: "import { defineConfig } from 'vite'\nimport solidPlugin from 'vite-plugin-solid'\n\nexport default defineConfig({\n    plugins: [solidPlugin()],\n    test: {\n\n    }\n})"
        },
        config: {
          allowOnly: true,
          watch: true,
          globals: true,
          environment: 'jsdom',
          threads: true,
          clearMocks: false,
          restoreMocks: false,
          mockReset: false,
          include: [ '**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}' ],
          exclude: [
            '**/node_modules/**',
            '**/dist/**',
            '**/cypress/**',
            '**/.{idea,git,cache,output,temp}/**',
            '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*'
          ],
          testTimeout: 5000,
          hookTimeout: 10000,
          teardownTimeout: 10000,
          isolate: true,
          browser: { enabled: false, headless: false, api: { port: 63315 } },
          watchExclude: [ '**/node_modules/**', '**/dist/**' ],
          forceRerunTriggers: [ '**/package.json/**', '**/{vitest,vite}.config.*/**' ],
          update: false,
          reporters: [ 'default' ],
          silent: false,
          ui: false,
          uiBase: '/__vitest__/',
          open: true,
          css: { include: [], modules: { classNameStrategy: 'stable' } },
          coverage: {
            provider: 'c8',
            enabled: false,
            clean: true,
            cleanOnRerun: true,
            reportsDirectory: './coverage',
            exclude: [
              'coverage/**',
              'dist/**',
              'packages/*/test{,s}/**',
              '**/*.d.ts',
              'cypress/**',
              'test{,s}/**',
              'test{,-*}.{js,cjs,mjs,ts,tsx,jsx}',
              '**/*{.,-}test.{js,cjs,mjs,ts,tsx,jsx}',
              '**/*{.,-}spec.{js,cjs,mjs,ts,tsx,jsx}',
              '**/__tests__/**',
              '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*',
              '**/.{eslint,mocha,prettier}rc.{js,cjs,yml}'
            ],
            reporter: [ [ 'text', {} ], [ 'html', {} ], [ 'clover', {} ], [ 'json', {} ] ],
            extension: [
              '.js',  '.cjs',
              '.mjs', '.ts',
              '.mts', '.cts',
              '.tsx', '.jsx',
              '.vue', '.svelte'
            ]
          },
          fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
          maxConcurrency: 5,
          dangerouslyIgnoreUnhandledErrors: false,
          typecheck: {
            checker: 'tsc',
            include: [ '**/*.{test,spec}-d.{ts,js}' ],
            exclude: [
              '**/node_modules/**',
              '**/dist/**',
              '**/cypress/**',
              '**/.{idea,git,cache,output,temp}/**',
              '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*'
            ]
          },
          slowTestThreshold: 300,
          transformMode: { web: [ {} ] },
          deps: { registerNodeLoader: true, inline: [ {}, {}, {}, '@nuxt/test-utils' ], cacheDir: 'node_modules/.vite' },
          defines: {},
          root: '<homeDir>/Code/play/wallaby-solidjs-vitest-broken',
          mode: [],
          snapshotOptions: { snapshotFormat: {}, updateSnapshot: 'new' },
          setupFiles: [],
          cache: { dir: '<homeDir>/Code/play/wallaby-solidjs-vitest-broken/node_modules/.vitest' },
          sequence: { hooks: 'parallel' },
          environmentMatchGlobs: [],
          package: {
            version: '0.29.7',
            urls: { hooks: 'file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby540ff5/runners/node/hooks.mjs' },
            paths: { root: '<homeDir>/Code/play/wallaby-solidjs-vitest-broken/node_modules/vitest', dist: '<homeDir>/Code/play/wallaby-solidjs-vitest-broken/node_modules/vitest/dist' }
          }
        }
      }
    },
    testFramework: { version: 'vitest@0.14.0', configurator: 'vitest@0.14.0', reporter: 'vitest@0.14.0', starter: 'vitest@0.14.0', autoDetected: true },
    preserveComments: false,
    extractComments: true,
    files: [
      { pattern: '**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/*.*', ignore: false, trigger: true, load: true, order: 1 }
    ],
    tests: [
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}', ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    workers: { initial: 1, regular: 1, recycle: false },
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: {
      type: 'node',
      params: { runner: '--experimental-loader=file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.348/wallaby540ff5/runners/node/hooks.mjs' },
      runner: '/nix/store/m3za3mblwg9az7vpkkvlfm04z66mcr6y-nodejs-18.10.0/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: true,
    symlinkNodeModules: true,
    configCode: 'auto.detect#-927380447'
  },
  packageJSON: {
    dependencies: { 'solid-js': '^1.6.5' },
    devDependencies: {
      '@types/jest': '^29.2.4',
      '@vitest/browser': '^0.29.7',
      'jest-environment-jsdom': '^29.3.1',
      'solid-testing-library': '^0.5.1',
      typescript: '^4.9.4',
      vite: '^4.2.1',
      'vite-plugin-solid': '^2.5.0',
      vitest: '^0.29.7'
    }
  },
  fs: { numberOfFiles: 7 },
  debug: []
}
```

**Comment by smcenlly** [comment] 2023-03-24 05:52
Thanks for reporting the problem. It is fixed in  Wallaby core `v1.0.1400`.

The cause was that `solid.js` uses [conditional exports](https://nodejs.org/api/packages.html#conditional-exports) and the `vite-solid-plugin` [sets these with vite's `resolve.conditions`](https://github.com/solidjs/vite-plugin-solid/blob/e57f55d6e55afe0bd52cb4f02ced0b221dc8a2c3/src/index.ts#L340) and also requires the use of [vitest node loader](https://github.com/solidjs/vite-plugin-solid/blob/e57f55d6e55afe0bd52cb4f02ced0b221dc8a2c3/src/index.ts#L327).

Wallaby has its own ESM node loader and so the vitest loader was being ignored in your scenario, resulting in the difference in behavior that you saw. We have updated Wallaby to chain the vitest node loader when it is configured to be used.

**Closed by smcenlly** 2023-03-24 05:52 UTC
