### ISSUE TITLE
Sublime Text Double Click MutliSelect

### ISSUE THREAD

**Issue by dalner** [wallabyjs/public#940] opened 2017-01-09 18:44 UTC
### Issue description or question
Wallaby disables selecting multiple text elements using the Ctrl + Double Click feature. If you try to double click two words on ST using the Ctrl+Double Click feature it is supposed to select both whole words, but if you enable WallabyJS, that feature breaks, only selecting where the cursor clicks.

### Code editor or IDE name and version
Sublime Text v3

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment] 2017-01-10 03:09
Thanks for reporting it. The issue is fixed in Wallaby package 1.0.30 (published, will be available for an update within ah hour). Now to click links in Wallaby output panel you may use `Ctrl + Shift + Double Click`.

**Closed by ArtemGovorov** 2017-01-10 03:09 UTC
Labels: Sublime Text
