### ISSUE TITLE
Wallaby.js not honoring tsconfig.json for strict TypeScript compilation

### ISSUE THREAD

**Issue by craigsmitham** [wallabyjs/public#1241] opened 2017-07-27 19:20 UTC
### Issue description or question

I have turned on the `noImplicitAny` compilation flag within my Angular CLI project and plan on enabling other strict null checks in the future. Running tests via the Angular CLI fails on many of the test files where the `any` type is not explicitly annotated, as expected. However, Wallaby.js seems to still run the tests just fine. I want it to also fail on compilation if there are any errors. 

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');
const typescript = require('typescript');

var compilerOptions = Object.assign(
  { typescript: typescript },
  require('./tsconfig.json').compilerOptions,
  require('./client/tsconfig.spec.json').compilerOptions
);
console.log('TS Version: ' + compilerOptions.typescript.version); // Outputs: TS Version: 2.4.2
console.log('noImplicitAny: ' + compilerOptions.noImplicitAny); // Outputs: noImplicitAny: true

module.exports = function(wallaby) {
  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: ['client/wallabyTest.js', 'client/**/*spec.js'],

    module: {
      loaders: [
        { test: /\.css$/, loader: 'raw-loader' },
        { test: /\.html$/, loader: 'raw-loader' },
        {
          test: /\.js$/,
          loader: 'angular2-template-loader',
          exclude: /node_modules/,
        },
        { test: /\.json$/, loader: 'json-loader' },
        { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
        { test: /\.less$/, loaders: ['raw-loader', 'less-loader'] },
        { test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader'] },
        { test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000' },
      ],
    },

    resolve: {
      modules: [
        path.join(wallaby.projectCacheDir, 'client/app'),
        path.join(wallaby.projectCacheDir, 'client'),
      ],
    },
  });

  return {
    files: [
      { pattern: 'client/**/*.ts', load: false },
      { pattern: 'client/**/*.d.ts', ignore: true },
      { pattern: 'client/**/*.css', load: false },
      { pattern: 'client/**/*.less', load: false },
      { pattern: 'client/**/*.scss', load: false },
      { pattern: 'client/**/*.sass', load: false },
      { pattern: 'client/**/*.styl', load: false },
      { pattern: 'client/**/*.html', load: false },
      { pattern: 'client/**/*.json', load: false },
      { pattern: 'client/**/*spec.ts', ignore: true },
    ],

    tests: [{ pattern: 'client/**/*spec.ts', load: false }],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions),
    },

    middleware: function(app, express) {
      var path = require('path');
      app.use(
        '/favicon.ico',
        express.static(path.join(__dirname, 'client/favicon.ico'))
      );
      app.use('/assets', express.static(path.join(__dirname, 'client/assets')));
    },

    env: {
      kind: 'electron',
    },

    postprocessor: webpackPostprocessor,

    setup: function() {
      window.__moduleBundler.loadTests();
    },

    debug: false,
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.14

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment] 2017-07-28 04:18
This is by design. Wallaby.js TypeScript compiler doesn't check types at all to make the compilation as fast as possible, to run tests as fast as possible. So if TypeScript compiler can produce a working output, then wallaby.js just runs it. 

Implementing proper type checking and reporting of compile time errors (as opposed to runtime errors) is out of scope for the tool. Wallaby is a test runner and your tests are passing, because TypeScript is able to produce runnable output, despite the fact that there are some compilation errors/warnings. 

It's not that it is extremely hard to implement, however we would be duplicating (UI to report things, CPU time for the type checking) of what your code editor is already doing for you. VS Code (as well as other editors that we support) is perfectly capable of reporting the compilation errors (inline + the clickable error list + summary in the status bar):

<img width="458" alt="screen shot 2017-07-28 at 2 05 00 pm" src="https://user-images.githubusercontent.com/979966/28702129-459f3838-739e-11e7-9d4b-85154365336c.png">

Hope it makes sense.

**Comment by craigsmitham** [comment] 2017-07-28 18:24
Thanks for the quick response. This makes sense in part - during development time I will most likely use VS Code/TypeScript tooling to help notify me of these errors. However, it introduces the overhead of an additional test runner required for teams using TypeScript w/strict compilation. **Devs can no longer assume that if Wallaby.js tests pass that they all _should_ pass, nor that it won't break their CI build.** If I use TypeScript strict compilation, then I have to use another test runner as part of my workflow in addition to Wallaby.js to ensure my tests pass. 

Some things that would make wallaby.js more usable for this scenario, which will become increasingly prevalent as more users adopt TypeScript and strict type checking - as both produce safer code:

1. Continue to set defaults as currently designed
2. Output which version of tsconfig.json is being used by Wallaby.js
3. Output warnings if the defaults differ from project's tsconfig.json
4. Honor any TypeScript compiler options set explicitly via the wallaby.js config, most notably the "strict" compiler option. If devs want the extra cost of the strict type checking, let us make that call. 

Right now the product documentation indicates/implies #4 is feasible, which is not the case for the "strict" compiler option.

**Comment by ArtemGovorov** [comment] 2017-07-29 00:08
> it introduces the overhead of an additional test runner required for teams using TypeScript w/strict compilation. If I use TypeScript strict compilation, then I have to use another test runner as part of my workflow in addition to Wallaby.js to ensure my tests pass.

You don't have to use another test runner - wallaby can tell if your tests are passing or not (regardless of whether your TypeScript build is failing or not). Editor plugin or CI/app build can catch any compilation errors, but another test runner is not something that one must use.

> Honor any TypeScript compiler options set explicitly via the wallaby.js config, most notably the "strict" compiler option. If devs want the extra cost of the strict type checking, let us make that call.

Fair enough. We'll make it possible to fail the test run if there are any compilation errors.

**Comment by ArtemGovorov** [comment] 2017-07-29 06:37
> more users adopt TypeScript and strict type checking - as both produce safer code

Well, fixing type errors doesn't affect test results, it's just a dev time experience - the runtime result (produced JavaScript code) is the same.

From wallaby perspective as a test runner, it's the same as linting. Yes, I'd like to see linting errors and fix them, but is it a job of continuous test runner to report those? We think that it is not.

Whether you have some type errors or not, as well as whether you have some linting errors or not, the JavaScript code output is exactly the same. None of the type errors change the output (if TypeScript compiler can still compile the code). For example, the `noImplicitAny` flag errors fixing doesn't change the output (and test results for that matter) - it'll be exactly the same no matter whether you have the errors/the flag set or not.

**Comment by ArtemGovorov** [comment] 2017-07-31 08:10
> Honor any TypeScript compiler options set explicitly via the wallaby.js config, most notably the "strict" compiler option. If devs want the extra cost of the strict type checking, let us make that call.

With [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), wallaby is now honoring strict compilation settings (and stops running  tests on any compilation errors), if `noEmitOnError` standard TypeScript option is set to `true`.

So you may change your wallaby config like this:
```javascript
...
compilerOptions.noEmitOnError = true;
```
and wallaby will stops running tests if there're any compilation errors.

The [docs had been updated](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings) as well.

**Closed by ArtemGovorov** 2017-07-31 08:10 UTC
Labels: enhancement

**Comment by ArtemGovorov** [comment] 2017-08-02 00:25
Update: we added a separate option (`useStandardDefaults`) that better describes the behavior than overloading the `noEmitOnError` setting. I have also updated the sample above.

**Comment by craigsmitham** [comment] 2017-08-03 17:07
@ArtemGovorov thanks for supporting this scenario. I agree that it is not a test runner's responsibility to perform compilation/linting, etc. However, I do think it is problematic if the test runner overrides the compilation settings. So, I think the right decision was made here to honor (if desired) the compiler settings. I'll give this a try and let you know how the experience is. Thanks for a quick response and a great product.
