### ISSUE TITLE
IntelliJ 2020.3 Update

### ISSUE THREAD

**Issue by ryandegruyter** [wallabyjs/public#2579] opened 2020-12-02 14:47 UTC
### Issue description or question
Running my WallabyJS autoconfigured configuration for an Angular 10 project results in:

<img width="454" alt="Screenshot 2020-12-02 at 15 42 31" src="https://user-images.githubusercontent.com/12190633/100887748-9d6fb200-34b5-11eb-90b6-9d30e5c4ce86.png">
<img width="1104" alt="Screenshot 2020-12-02 at 15 42 37" src="https://user-images.githubusercontent.com/12190633/100887757-9f397580-34b5-11eb-9f4e-f2870e55812c.png">

'void com.intellij.platform.templates.github.ZipUtil.unzipWithProgressSynchronously(com.intellij.openapi.project.Project, java.lang.String, java.io.File, java.io.File, boolean)'

**Comment by smcenlly** [comment] 2020-12-02 23:01
This is a duplicate of https://github.com/wallabyjs/public/issues/2527. This issue was fixed in Wallaby for IntelliJ, v1.0.198+. Please uninstall the Wallaby extension from your editor and then download and install the latest version from [our website](https://download.wallabyjs.com/intellij).

**Closed by smcenlly** 2020-12-02 23:01 UTC
