### ISSUE TITLE
Project developed w/ Claudia.js and claudia-api-builder (serverless). Code coverage doesn't work.

### ISSUE THREAD

**Issue by lstone** [wallabyjs/public#1593] opened 2018-03-29 15:37 UTC
### Issue description or question
Backend API codebase developed w/ Claudia.js (https://claudiajs.com/) and Claudia-api-builder (https://github.com/claudiajs/claudia-api-builder) lack code coverage. Code coverage runs, but returns no coverage for any file. Is there a way to help Wallaby.js reconcile this? Everything else works as expected.

### Wallaby.js configuration file
```javascript
module.exports = function (wallaby) {
  return {
    name: 'my-api',
    files: [
      'controllers/**/*.js',
      'helpers/**/*.js',
      'models/**/*.js',
      'mailers/**/*.*',
      'index.js',
      'spec/**/*-helpers.js',
      '!spec/**/*-spec.js'
    ],
    tests: [
      'spec/**/*-spec.js'
    ],
    testFramework: "jasmine",
    filesWithNoCoverageCalculated: ['**/*.*'],
    reportConsoleErrorAsError: true,
    env: {
      type: 'node',
      runner: 'node'
    },
    // force tests run in order to prevent PG errors
    workers: {
      initial: 1,
      regular: 1,
      recycle: true
    }
  };
};
```

### Code coverage
<img width="406" alt="2018-03-29 11 35 15 am" src="https://user-images.githubusercontent.com/972730/38098176-5232b798-3345-11e8-8632-688811a1da2f.png">

### Code editor or IDE name and version
WebStorm v2017.3.4

### OS name and version
OSX

**Comment by ArtemGovorov** [comment] 2018-03-29 23:03
It doesn't calculate code coverage because you are excluding *all* files from code coverage calculation [with the setting](https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-a-file):

```
filesWithNoCoverageCalculated: ['**/*.*'],
```

If you adjust the pattern, or remove the setting if you don't need it, then it should work for you.

**Comment by lstone** [comment] 2018-03-30 01:19
Hi @ArtemGovorov - thanks, I actually had that setting there to speed up test running. Even with `filesWithNoCoverageCalculated: ['**/*.*'],` commented out, I get no code coverage report.

### No code coverage
<img width="537" alt="2018-03-29 09 19 04 pm" src="https://user-images.githubusercontent.com/972730/38120436-d5d72f88-3396-11e8-9c4d-673603b945fb.png">

**Comment by ArtemGovorov** [comment] 2018-03-30 01:34
>  I actually had that setting there to speed up test running

The setting doesn't affect test running, only affect reporting.

> I get no code coverage report.

You are actually getting coverage report now. Note how it was reporting `n/a` for all of your folders, but now it's reporting `0%`.

**Comment by lstone** [comment] 2018-03-30 01:51
Correct, it's now reporting `0%` even though I've got 100's of tests and should have almost complete code coverage. Is there a way for me to determine why I'm getting 0% coverage, even though I surely have far more?

**Comment by ArtemGovorov** [comment] 2018-03-30 01:56
If you open any file from the `controllers/**/*.js` in WebStorm, do you see some green indicators in it? If so, what indicators do you see if you locate and open the file in the code coverage tree in Wallaby App?

Also try stopping wallaby, closing all instances of WebStorm and wallaby app in browser, killing all `node` processes on the machine, starting WebStorm and wallaby on the project, then opening wallaby in browser to see if it helps.

**Comment by lstone** [comment] 2018-04-02 20:09
All good suggestions. I only see green test coverage indicators in the "spec" files themselves. All the regular app files show a transparent indicator and 0% coverage as shown in image.
<img width="469" alt="2018-04-02 04 09 03 pm" src="https://user-images.githubusercontent.com/972730/38213703-3c43e3d2-3690-11e8-9c9a-9b66838151fd.png">

**Comment by ArtemGovorov** [comment] 2018-04-03 00:55
Thanks for checking. This means that your tests are somehow running on your local project files, as opposed to be running on their instrumented versions (to collect the code coverage). I can't see any issues with your config, so we will need a sample repo where the issue can be reproduced. Could you please create a share one with a simple test and a source file that is covered from the test, but displays zero coverage in your IDE and wallaby app?

**Comment by smcenlly** [comment] 2019-03-12 22:56
Closing this issue as we need more information to reproduce the problem. We will re-open the issue if more detail is provided.

**Closed by smcenlly** 2019-03-12 22:56 UTC
Labels: configuration question, more info is required, reproducible example is required, solution suggested
