### ISSUE TITLE
Wallaby + Browserify (Postprocessor run failure: Unexpected token)

### ISSUE THREAD

**Issue by davegomez** [wallabyjs/public#1047] opened 2017-02-24 20:17 UTC
### Issue description or question
Wallaby keep throwing the same error without any other information. `Postprocessor run failure: Unexpected token`

### Wallaby.js configuration file
```javascript
// Wallaby.js configuration

const wallabifyPath = '/Users/davidg/.nvm/versions/node/v7.6.0/lib/node_modules/wallabify'; // eslint-disable-line
const wallabify = require(wallabifyPath);

const wallabyPostprocessor = wallabify({
    entryPatterns: [
        'version.json',
        'app/locale/en-US/messages.json',
        'test/**/*.js'
    ]
});

module.exports = function(wallaby) {
    return {
        files: [
            {
                pattern: 'node_modules/babel-polyfill/dist/polyfill.js',
                instrument: false
            },
            { pattern: 'app/src/**/*.js', load: false },
            { pattern: 'version.json', load: false },
            { pattern: 'app/locale/en-US/messages.json', load: false },
            { pattern: 'test/fixtures.js', load: false },
            { pattern: 'test/spec_util.js', load: false },
            { pattern: 'app/templates/**/*.hbs', load: false }
        ],

        tests: [
            { pattern: 'test/**/*.test.js', load: false }
        ],

        env: {
            kind: 'electron',
            runner: '/Users/davidg/.nvm/versions/node/v7.6.0/lib/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron' // eslint-disable-line
        },

        compilers: {
            '**/*.js': wallaby.compilers.babel()
        },

        postprocessor: wallabyPostprocessor,

        debug: true,

        setup() {
            window.__moduleBundler.loadTests(); // eslint-disable-line
        }
    };
};
```

### Debug log
Pastebin: [http://pastebin.com/bKK2MRL3](http://pastebin.com/bKK2MRL3)

### Code editor or IDE name and version
WebStorm 2016.3.3

### OS name and version
OSX

**Comment by ArtemGovorov** [comment] 2017-02-24 23:39
Try removing json files from your entry patterns, you may actually remove the whole `entryPatterns` section as there are only tests that's left and they are included by default:

```javascript
const wallabyPostprocessor = wallabify({

});
```

**Comment by davegomez** [comment] 2017-02-25 02:26
Hi Artem, thanks for your quick response.

I already removed the entryPatterns as you suggested and Wallaby asked for `messages.json` file so I added it in the files array. After that start asking me about each one of the `.hbs` templates inside `app/templates/` and once I finished to add all the patterns the error message came back.

This is not a problem of one particular `.hbs` file, since if I remove any of those files pattern Wallaby will ask for the file to launch the error after adding it.

This is how my config looks now:

```javascript
// Wallaby.js configuration

const wallabifyPath = '/Users/davidg/.nvm/versions/node/v7.6.0/lib/node_modules/wallabify'; // eslint-disable-line
const wallabify = require(wallabifyPath);

const wallabyPostprocessor = wallabify({});

module.exports = function(wallaby) {
    return {
        files: [
            { pattern: 'app/src/**/*.js', load: false },
            { pattern: 'test/fixtures.js', load: false },
            { pattern: 'test/spec_util.js', load: false },
            { pattern: 'app/locale/en-US/messages.json', load: false },
            { pattern: 'app/templates/partials/glyph.hbs', load: false },
            { pattern: 'app/templates/app-view.hbs', load: false },
            { pattern: 'app/templates/subscribers-page.hbs', load: false },
            { pattern: 'app/templates/subscriber-activity.hbs', load: false },
            { pattern: 'app/templates/subscriber-list.hbs', load: false },
            { pattern: 'app/templates/delivery-failures.hbs', load: false },
            { pattern: 'app/templates/message-picker.hbs', load: false },
            { pattern: 'app/templates/message-picker-field.hbs', load: false },
            { pattern: 'app/templates/message-picker-modal.hbs', load: false },
            { pattern: 'app/templates/message-picker-tab.hbs', load: false },
            { pattern: 'app/templates/bulk-action.hbs', load: false },
            { pattern: 'app/templates/export-segment-button.hbs', load: false },
            { pattern: 'app/templates/segment-manager.hbs', load: false },
            { pattern: 'app/templates/segment-details.hbs', load: false },
            { pattern: 'app/templates/date-field.hbs', load: false },
            { pattern: 'app/templates/query-builder.hbs', load: false },
            { pattern: 'app/templates/confirm-modal.hbs', load: false },
            { pattern: 'app/templates/bulk-edit-modal.hbs', load: false },
            { pattern: 'app/templates/subscriber-details-tab.hbs', load: false },
            { pattern: 'app/templates/create-segment-modal.hbs', load: false },
            { pattern: 'app/templates/subscriber-details.hbs', load: false },
            { pattern: 'app/templates/subscriber-overview.hbs', load: false },
            { pattern: 'app/templates/subscriber-details-modal.hbs', load: false },
            { pattern: 'app/templates/relative-date-field.hbs', load: false }
        ],

        tests: [
            { pattern: 'test/**/*.test.js', load: false }
        ],

        env: {
            kind: 'electron',
            runner: '/Users/davidg/.nvm/versions/node/v7.6.0/lib/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron' // eslint-disable-line
        },

        compilers: {
            '**/*.js': wallaby.compilers.babel()
        },

        debug: true,

        postprocessor: wallabyPostprocessor,

        setup() {
            window.__moduleBundler.loadTests(); // eslint-disable-line
        }
    };
};
```

And this is the debug log:

Pastebin: [http://pastebin.com/uWSxRSJP](http://pastebin.com/uWSxRSJP)

**Comment by ArtemGovorov** [comment] 2017-02-25 02:57
Looks like you're missing browserify transform in your wallaby config, ie. how's browserify supposed to load `.hbs` files? I think you need to install
```
npm i hbsfy --save-dev
```
and add it to the [wallabify configuration as described in the sample code comments](https://wallabyjs.com/docs/integration/browserify.html#usage):

```javascript
const wallabifyPath = '/Users/davidg/.nvm/versions/node/v7.6.0/lib/node_modules/wallabify'; // eslint-disable-line
const wallabify = require(wallabifyPath);

const hbsfy = require('hbsfy').configure({
  extensions: ['hbs']
});

const wallabyPostprocessor = wallabify({}, b => b.transform(hbsfy));

module.exports = function(wallaby) {
    return {
        files: [
            { pattern: 'app/src/**/*.js', load: false },
            { pattern: 'test/fixtures.js', load: false },
            { pattern: 'test/spec_util.js', load: false },
            { pattern: 'app/locale/en-US/messages.json', load: false },
            { pattern: 'app/**/*.hbs', load: false }
        ],

        tests: [
            { pattern: 'test/**/*.test.js', load: false }
        ],

        env: {
            kind: 'electron',
            runner: '/Users/davidg/.nvm/versions/node/v7.6.0/lib/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron' // eslint-disable-line
        },

        compilers: {
            '**/*.js': wallaby.compilers.babel()
        },

        debug: true,

        postprocessor: wallabyPostprocessor,

        setup() {
            window.__moduleBundler.loadTests(); // eslint-disable-line
        }
    };
};
```

**Comment by davegomez** [comment] 2017-02-25 03:32
I tried to use the transforms I'm using in Karma but didn't know how to write them for the Wallaby config to be honest (and I'm still don't) but I forgot about them.

This is the config I have for the transforms in Karma:

```javascript
browserify: {
   debug: true,
   transform: ['babelify', ['hbsfy', { global: true }]]
}
```

I'm trying to add Babelify also, but is not working, I'm still getting the same error, I assume I'm doing wrong.

```javascript
const hbsfy = require('/Users/davidg/.nvm/versions/node/v7.6.0/lib/node_modules/hbsfy').configure({
    extensions: ['hbs'],
    global: true
});

const babelify = require('/Users/davidg/.nvm/versions/node/v7.6.0/lib/node_modules/babelify');

const wallabyPostprocessor = wallabify({}, b => b.transform(babelify).transform(hbsfy));
```

**Comment by ArtemGovorov** [comment] 2017-02-25 03:42
Try removing the `babelify` transform, it's not required because you're using wallaby babel compiler.

Just created [the branch in the wallaby-browserify sample](https://github.com/wallabyjs/wallaby-browserify-sample/tree/1047) with an `.hbs` file and the transform, and it's working for me. Take a look if you stop what's different in your config/project.

**Comment by ArtemGovorov** [comment] 2017-02-25 03:54
I have also juts published wallabify@0.0.15 that has an improved error reporting (should point out the file and some more error info), Please update to the latest wallabify@0.0.15 to see what file is causing the issue.

**Comment by davegomez** [comment] 2017-02-25 03:58
Seems to be a node package:

```js
Postprocessor run failure: 
/Users/davidg/git/subscriber-management/node_modules/backbone-editable-field/templates/index.hbs:1
<div class="editable-field">
^
ParseError: Unexpected token
```

This is my config file now:

```js
// Wallaby.js configuration

const wallabify = require('/Users/davidg/.nvm/versions/node/v7.6.0/lib/node_modules/wallabify');
const hbsfy = require('/Users/davidg/.nvm/versions/node/v7.6.0/lib/node_modules/hbsfy').configure({
    extensions: ['hbs'],
    global: true
});

const wallabyPostprocessor = wallabify({}, b => b.transform(hbsfy));

module.exports = function(wallaby) {
    return {
        files: [
            { pattern: 'app/**/*.js', load: false },
            { pattern: 'app/**/*.hbs', load: false },
            { pattern: 'test/fixtures.js', load: false },
            { pattern: 'test/spec_util.js', load: false },
            { pattern: 'app/locale/en-US/messages.json', load: false }
        ],

        tests: [
            { pattern: 'test/**/*.test.js', load: false }
        ],

        env: {
            kind: 'electron',
            runner: '/Users/davidg/.nvm/versions/node/v7.6.0/lib/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron' // eslint-disable-line
        },

        compilers: {
            '**/*.js': wallaby.compilers.babel()
        },

        postprocessor: wallabyPostprocessor,

        setup() {
            window.__moduleBundler.loadTests();
        }
    };
};
```

**Comment by davegomez** [comment] 2017-02-25 04:08
I'm trying to ignore the node_modules files but it doesn't work either:

```js
{ pattern: '!node_modules/**/*.hbs', load: false },
```

or 

```js
{ pattern: 'node_modules/**/*.hbs', load: false, ignore: true },
```

**Comment by ArtemGovorov** [comment] 2017-02-25 04:11
I can't find the `backbone-editable-field` module in the npm registry: https://www.npmjs.com/package/backbone-editable-field. How can I reproduce the issue?

Ignoring it will not help, because something in your app is importing/requiring it. You may try including it, but I doubt it'll help:
```
{ pattern: 'node_modules/backbone-editable-field/**/*.hbs', load: false },
```

**Comment by davegomez** [comment] 2017-02-25 04:19
Yes, it is an internal package and indeed one file is importing it. I just remove it from the code the wallaby started to work on some tests.

I can't connect to the company registry right now so I'm gonna call it a night.

I'll let you know if I can resolve it.

Thanks for your help =)

**Comment by ArtemGovorov** [comment] 2017-02-25 04:19
It's really hard to troubleshoot without a sample repo, but try this:

```javascript
const hbsfy = require('/Users/davidg/.nvm/versions/node/v7.6.0/lib/node_modules/hbsfy').configure({
    extensions: ['hbs']
});

const wallabyPostprocessor = wallabify({}, b => b.transform(hbsfy, {global: true})); //<---
```
and remove any `{ pattern: 'node_modules/...hbs` from your files list.

**Comment by ArtemGovorov** [comment] 2017-02-26 02:47
Closing, as we've addressed the rest of the issues via email.

**Closed by ArtemGovorov** 2017-02-26 02:47 UTC
