### ISSUE TITLE
Wallaby continously spinning and no tests loaded

### ISSUE THREAD

**Issue by investor-analytics** [wallabyjs/public#854] opened 2016-11-03 09:18 UTC
I loaded the web pack starter example from the samples on your website

https://github.com/wallabyjs/angular2-webpack-starter
I followed the instructions, and installed wallaby.js into Visual Studio Code
However, when I use the command palette to start Wallaby all I receive is a spinner and I don't see any of the icons in my tests. 

Just to test this I have included a very simple starter test so that I could learn how wallaby works.
The configuration file is below as is the very simple test file I have used to start with.

So the problems are when I run Wallaby.js:Start I see the spinner running continuously and there are no icons on my tests. I'm unsure what I'm doing wrong.

### Wallaby.js configuration file

```
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'config/spec-bundle.js',
    'src/**/*spec.js'
  ],

  module: {
    loaders: [
      {test: /\.css$/, loader: 'raw-loader'},
      {test: /\.html$/, loader: 'raw-loader'},
      {test: /karma-require/, loader: 'null'}
    ]
  }
});

module.exports = function () {

  return {
    files: [
      {pattern: 'config/spec-bundle.js', load: false},
      {pattern: 'config/karma-require.js', load: false},
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true},
      {pattern: 'src/**/*.d.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'test/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    env: {
      runner: require('phantomjs-prebuilt').path,
      params: { runner: '--web-security=false' }
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    }
  };
};

```

```test
describe('1st tests', function () {
    it('true is true', function () { return expect(true).toBe(true); });
});
```

### Code editor or IDE name and version
Visual Studio Code v1.6.1

### OS name and version
Windows

**Comment by ArtemGovorov** [comment] 2016-11-03 09:29
Please have a look if there's anything interesting, such as some errors, reported [in the Wallaby.js Console](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting).

**Comment by ArtemGovorov** [comment] 2016-11-03 10:20
BTW, I have just renewed the https://github.com/wallabyjs/angular2-webpack-starter sample repo (synced it with the original repo). Try taking it again from the scratch, doing `npm install` and running wallaby.js.

**Comment by investor-analytics** [comment] 2016-11-03 11:13
Hi. so I got the new sample repo and included my very simple test using Jasmine.

1. I went to the command palette and did Wallaby.js:Start
2. I got the licence warning which I accepted (if I can get this working I want to buy it!)
3. The spinner started up and I cannot see any icons in the visual studio code editor.
4. In the debug console there are no errors just info..

I'm not sure why 

a.) Wallaby doesn't seem to be picking up the test - I looked at the configuration and it seems to cater for

```
return {
    files: [
      {pattern: 'config/spec-bundle.js', load: false},
      {pattern: 'config/karma-require.js', load: false},
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.html', load: false},
      {**pattern: 'src/**/*spec.ts', ignore: true**},
      {pattern: 'src/**/*.d.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {**pattern: 'test/**/*spec.ts', load: false**}
    ],
```
which matches the pattern of my test simple.spec.ts.

Could it be a problem with VS Code?

![image](https://cloud.githubusercontent.com/assets/22916653/19963567/ecffca0a-a1b4-11e6-88cf-11f5510bfd67.png)

**Comment by ArtemGovorov** [comment] 2016-11-03 11:44
Could you please set the `debug: true` option as [described in the docs](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting) and paste the full output from the Wallaby.js Console after it stops outputting anything?

**Comment by investor-analytics** [comment] 2016-11-03 11:58
Hi there . the configuration was set as debug:true as shown here

![image](https://cloud.githubusercontent.com/assets/22916653/19964959/86464192-a1bc-11e6-8cbf-275217c593ff.png)

and the full output of the log is here:

```
[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:project Wallaby config: c:\web-pack-starter\wallaby.js
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: config/spec-bundle.js
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: config/karma-require.js
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.313
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/index.html
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/main.browser.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/polyfills.browser.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/vendor.browser.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/app.component.css
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/app.component.spec.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/app.component.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/app.e2e.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/app.module.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/app.resolver.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/app.service.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/app.routes.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/environment.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/index.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/assets/data.json
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/assets/manifest.json
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/tests/simple.spec.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/+detail/detail.component.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/+detail/index.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/about/about.component.spec.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/about/about.component.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/about/index.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/home/home.component.css
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/home/home.component.html
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/home/home.component.spec.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/home/home.component.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/home/home.e2e.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/home/index.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/no-content/index.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/app/no-content/no-content.component.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:06 GMT wallaby:fs File added: src/assets/mock-data/mock-data.json
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:07 GMT wallaby:fs File added: src/app/home/title/index.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:07 GMT wallaby:fs File added: src/app/home/title/title.service.spec.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:07 GMT wallaby:fs File added: src/app/home/title/title.service.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:07 GMT wallaby:fs File added: src/app/home/x-large/index.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:07 GMT wallaby:fs File added: src/app/home/x-large/x-large.directive.spec.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:07 GMT wallaby:fs File added: src/app/home/x-large/x-large.directive.ts
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:fs File system scan has finished by timeout
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:project File cache: C:\Users\ScanlonJ\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.29\projects\cba32decc2d1eb0e
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:uiService Listening port 51235
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Parallelism for initial run: 38, for regular run: 19
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #0
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #1
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #2
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #3
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #4
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #5
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #6
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #7
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #8
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #9
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #10
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #11
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #12
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #13
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #14
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #15
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #16
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #17
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #18
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #19
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #20
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #21
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #22
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #23
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #24
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #25
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #26
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #27
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #28
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #29
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #30
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #31
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #32
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #33
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #34
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #35
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #36
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Starting run worker instance #37
​​​​​[Info]​​​​​ Thu, 03 Nov 2016 11:57:08 GMT wallaby:workers Web server is listening at 31756
```

Many thanks for your assistance..

**Comment by ArtemGovorov** [comment] 2016-11-03 12:05
Hmm, interesting, not sure what's going on, I can't reproduce the issue. Let's try something,  reduce the number of workers by setting:

```javascript
 module.exports = function () {
   return {
     ...
     workers: {
       initial: 6,
       regular: 2
     }
   };
 };
```

in your wallaby config, and run wallaby to see if it changes anything. 

Also, just to check if the issue is project or environment specific, please try cloning this simple sample and running wallaby https://github.com/wallabyjs/calculator-sample (no npm install is required).

**Comment by investor-analytics** [comment] 2016-11-03 13:45
Hi there.. Thanks for the sample..

So the changing of the workers did not have any effect but the simple sample did work. See screenshot

![image](https://cloud.githubusercontent.com/assets/22916653/19968250/baa64090-a1cb-11e6-9ce2-66f6f9dd3127.png)

However, I noticed that your tests were .spec.js files rather than my .spec.ts files.

Could the problem we that the test files are not being transpiled properly by wallaby.js?

**Comment by investor-analytics** [comment] 2016-11-03 14:02
and this little change in the wallaby.js fixed it..

entryPatterns: [
    'config/spec-bundle.js',
    'src/**/*spec.js',
    _**'src/**/*spec.ts'**_
  ],

in short adding the last line *spec.ts' fixed the problem and now everything is working including my tests.
Does that make sense? i would expect that the entry patterns would be reading in the transpiled **.js rather than .ts but obviously that is not correct..


Many thanks for your help...

**Comment by ArtemGovorov** [comment] 2016-11-03 23:00
> i would expect that the entry patterns would be reading in the transpiled *.js rather than .ts but obviously that is not correct

You are correct, the entry patterns should be reading in the transpiled *.js. Changing it to *.ts will make wallaby to load your .ts tests (that may work for your simple test because it's basically JavaScript without using any TS features). Do all other sample tests (like `src/app/about/about.component.spec.ts`) work for you?

I'll close this for now as long as it works, but happy to investigate more if it doesn't fully work for you.

**Closed by ArtemGovorov** 2016-11-03 23:00 UTC
