### ISSUE TITLE
Tests not re-running on save, no coverage (atom-wallaby, node, babel)

### ISSUE THREAD

**Issue by thgaskell** [wallabyjs/public#484] opened 2016-02-29 06:58 UTC
I am using babel on a node project, and am running into issues with code coverage not showing up in Atom, and tests are not rerunning on save. I think they both might be related?

I'm not quite sure if there is a problem with my config file since the tests do run, but they don't rerun when I make file changes. I was going off of the example repo at wallabyjs/wallaby-node-babel@2fe00a4.

Opening up the inspector in Atom, Wallaby appears to detect the file change, but it also mentions that there's no metadata found? What does this mean?

```
Wallaby Console: Mon, 29 Feb 2016 06:15:57 GMT wallaby:fs File changed:
Wallaby Console: Mon, 29 Feb 2016 06:15:57 GMT wallaby:fs No metadata for changed file found:
```

Example repo: thgaskell/cobble@8244f80
### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    compilers: {
      '**/*.js': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: ['airbnb'],
      }),
    },
    debug: true,
    env: {
      type: 'node',
      runner: 'node',
      params: {
        env: 'NODE_ENV=test',
        runner: '--harmony',
      },
    },
    files: [
      '!src/**/*.spec.js',
      'src/**/*.js',
    ],
    setup: function() {
      require('babel-polyfill');
    },
    testFramework: 'mocha',
    tests: [
      'src/**/*.spec.js',
    ],
  };
};
```

Atom v1.5.3
OSX v10.10.5

**Comment by ArtemGovorov** [comment] 2016-02-29 07:17
Thanks for the repo. 
It works for me
![a](https://cloud.githubusercontent.com/assets/979966/13387909/22acbd14-df07-11e5-89bc-1eea8ea02c03.gif)

What's your node.js version?

Is there a `File added: ...` entry in the console for the file that you're changing?
Is there anything special about your project file path (where you cloned the repo to)? Are you using symlinks?
Could you try copying the project to another place on your file system and trying again?

**Comment by thgaskell** [comment] 2016-02-29 08:06
> Is there a File added: ... entry in the console for the file that you're changing?
```
Wallaby Console: Mon, 29 Feb 2016 07:37:03 GMT wallaby:fs Symlink resolution for: /path/to/symlink/cobble/src/lib/compile/compile.spec.js
Wallaby Console: Mon, 29 Feb 2016 07:37:03 GMT wallaby:fs File added: src/lib/compile/compile.spec.js
```

> Is there anything special about your project file path (where you cloned the repo to)? Are you using symlinks?
> Could you try copying the project to another place on your file system and trying again?

Thank you, this seems to be the issue. My project does happen to be in a symlinked directory, and it seems that moving it out of there fixes the issues I was running into.

It looks like the symlink path is throwing off wallaby off since the file change is seeing `absolute/path/git/cobble/src/lib/compile/compile.spec.js` but it's loading the file under the symlinked path.

Is there a way to have wallaby work with the symlinked path? Or is this more of an Atom issue?
I can get around this by opening the absolute path instead of the symlinked path, so it's not really a real big deal.

**Comment by ArtemGovorov** [comment] 2016-02-29 09:39
@thgaskell  Awesome, thanks for the update. Will have a look if it's an Atom issue or something we could fix in wallaby.

**Comment by ArtemGovorov** [comment] 2016-03-01 03:20
@thgaskell The issue is fixed in the latest wallaby plugin for Atom (will be updated automatically within few minutes after your next wallaby start/restart).

**Closed by ArtemGovorov** 2016-03-01 03:20 UTC

**Comment by thgaskell** [comment] 2016-03-01 07:10
Works great! Thanks for the quick fix. :beers:
