### ISSUE TITLE
Cache not cleaned up?

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#81] opened 2015-04-23 09:24 UTC
Wallaby usually throws exceptions when I switch branches (so a lot of files are changing) or when I run the Wallaby config for another subproject. I have multiple wallaby.conf.js files.

Sometimes I get this error in the Wallaby Console:

> Runtime error: TypeError: 'undefined' is not an object (evaluating 'a.$_$coverage[c][d][this._spec]=b++')

Sometimes I get exceptions for code that is not included in my files list, but are in the files list of the config from the previous run.

Restarting Wallaby or IntelliJ does not help.

I looks like the cache is not cleaned up very well after (before?) each run.

**Comment by ArtemGovorov** [comment] 2015-04-23 09:56
It sounds like wallaby cache issue, it's not supposed to be cleaned between runs (to speed up wallaby restarts). I'm planning to add a button to wallaby tool window to clear the cache. 

For now, as you probably know, the only way to clear the cache is to make any change (even just a space) to wallaby config and restart it.

**Comment by fvanwijk** [comment] 2015-04-23 10:05
Ok that's good to know. I hope you manage to clean the cache automatically whenever possible, without affecting the performance. It should happing in any case when switching config files.

**Comment by ArtemGovorov** [comment] 2015-04-24 04:38
Fixed some caching issues that might have been causing the symptoms that you have described. Please try the new version (1.0.8, should prompt to update) to see if the issue is fixed.

**Comment by Almenit** [comment] 2016-03-12 15:42
We still se the issue. Didn't you change the logging, as you talked about in #464 ?

**Comment by ArtemGovorov** [comment] 2016-03-13 01:38
@Almenit I thought I did, but as you mentioned you're still seeing it without changes in logging, I have looked into it again and discovered one scenario where it may not have been properly logged. Have covered the scenario in core v1.0.197. Please try the new core version and let me know how it goes. If it's still logging `TypeError: undefined is not an object (evaluating 'e.$_$coverage[i][n]`, please attach a screenshot of your Failing Tests tab with the error, so I could better understand if I missed any other scenarios.

**Comment by ArtemGovorov** [comment] 2016-03-13 02:04
@Almenit Regarding the issue itself, apparently one of the [possible](https://github.com/wallabyjs/public/issues/495) reasons is when your `tests` list contains some files that are not tests. As [stated in the docs](http://wallabyjs.com/docs/config/files.html), wallaby `tests` should only contain actual test files (with `describe`/`it` in them). Please try checking your `tests` list, perhaps you're getting the error for the same reason.

**Comment by Almenit** [comment] 2016-03-15 10:48
Ok now I get the new error. Checked the test list and it looks ok. If I switch the instrumentation off for files it works.
Our config for files and tests look lite this: 

```
files: [
            "Capish.Applications.Reflect.Web/Content/Scripts/**/*.ts*",
            "!Capish.Applications.Reflect.Web/Content/Scripts/cql/*.js",
            "!Capish.Applications.Reflect.Web/Content/Scripts/tests/**/test.*.ts*",
            "!Capish.Applications.Reflect.Web/Content/Scripts/tests/index.ts*",
            { pattern: "Capish.Applications.Reflect.Web/Content/Scripts/tests/polyfills.ts", instrument: false },
            { pattern: "Capish.Applications.Reflect.Web/Content/Scripts/tests/jsnlogTestConfigure.ts", instrument: false },
            "Capish.Applications.Reflect.ConfigurationTools/ConfigurationBuilders/**/*.ts*",
            "!Capish.Applications.Reflect.ConfigurationTools/ConfigurationBuilders/tests/**/test.*.ts*"
        ],

        tests: [
            "Capish.Applications.Reflect.Web/Content/Scripts/tests/**/test.*.ts*",
            "Capish.Applications.Reflect.ConfigurationTools/ConfigurationBuilders/tests/**/test.*.ts*"
        ],
```

**Comment by ArtemGovorov** [comment] 2016-03-15 10:54
Ok, thanks for checking.

> If I switch the instrumentation off for files it works.

It makes sense, because the error is raised from the instrumentation code. 

Please let me know if you manage to isolate the issue somehow.

**Comment by smcenlly** [comment] 2020-10-08 23:50
Closing this issue out as it is very old and likely fixed by a number of improvements we have made to Wallaby caching and file watching in the last 18 months.

**Closed by smcenlly** 2020-10-08 23:50 UTC
Labels: bug
