### ISSUE TITLE
Files loaded via require.js text plugin are cached until wallaby.js restart

### ISSUE THREAD

**Issue by cResults** [wallabyjs/public#183] opened 2015-07-08 15:22 UTC
We use jasmine-jquery for testing logical outcomes within the dom.  Wallaby runs these tests just fine, however, if any changes are made to the html file, Wallaby requires a restart to update any affected tests.  I've tried "Run Project Tests" but it doesn't work.  The issue seems to happen all the time no matter what change is made.

We currently use knockout and durandal (moving toward aurelia) for model binding. We follow a pattern where a view and viewmodel are in the same folder with the same name. For example widget.js would be bound to widget.html in the DOM.

We require the view into the test file to insert it into the dom.  Therefore, the file with our test suite has the relevant html files listed as dependencies.

It would be extremely helpful and time-saving if Wallaby could be made aware of the changes in associated html files and update testes results.  Please let me know if you have any questions or need more information.

Respectfully,

cResults

**Comment by cResults** [comment] 2015-07-08 18:32
I'm running Visual Studio 2013.

**Comment by RainerAtSpirit** [comment] 2015-07-08 20:10
This would be a great enhancement. We are using knockout components with a webpack build step and I also noticed that updating .html files do not trigger test re-runs. Typically we do not test the DOM at this point, but I see how this could be useful in the future. If it's helpful I could create a small repo that demonstrates the behavior.

**Comment by ArtemGovorov** [comment] 2015-07-09 01:32
Wallaby.js dependency tracking mechanism currently doesn't take into account HTML files. As you know, wallaby runs tests incrementally, based on the code changes. There's no reliable way to tell what tests or test files are affected if some html files changes. In future we plan to introduce an option to run all tests if wallaby can't determine what tests to run.

Having said that, we have some **heuristics in place that are doing exactly what you're asking**. When wallaby.js can't determine what tests to run on a file change, it currently tries to run last edited test file. So you have a test file that loads HTML file(s) and actively editing it and HTML file(s), it should just work for you: 

![h](https://cloud.githubusercontent.com/assets/979966/8586001/260d9610-262d-11e5-8696-71ea8da78b81.gif)

It's the same in Visual Studio, except that there you also have to save (Ctrl + S) HTML file to trigger the run. JavaScript files don't require the save, but HTML files do require it at the moment. This may be the reason why `Run Project Tests` didn't work for you.

Let me know if it works for you. If it doesn't please share a repo where I can reproduce the issue.

**Comment by RainerAtSpirit** [comment] 2015-07-09 09:53
I created an isolated test repo https://github.com/RainerAtSpirit/koComponentsWallaby and indeed, when updating the .html fragment a test run is triggered. Excellent.

![image](https://cloud.githubusercontent.com/assets/581644/8592426/7d346822-262f-11e5-8af2-d90709be8ef7.png)

However this might be due the fact that in this case html files are explicitly required via the raw-loader `var template = require('raw!./like-widget.html');` https://github.com/RainerAtSpirit/koComponentsWallaby/blob/master/src/components/like-widget/like-widget.js

Durandal/Aurelia use case might be different.

**Comment by cResults** [comment] 2015-07-09 17:38
I'm working in VS2013.  [our basic solution configuration can be found here](https://github.com/wallabyjs/wallaby-requirejs-middleware).  We're using Require.js.  

The test file requires the html file in the describe.  It uses Jasmine-Jquery setFixture to add the html to the dom. then binds a viewmodel to the html view using knockout.

Saving all files runs karma tests and it reflects the change. Running all project tests after saving files doesn't do anything in wallaby on my machine. The only thing that updates wallaby in this case is a restart

I'll make a repro if need be, but it may take me a while to get to this.  For now, I'm just using karma for these tests and moving on.

**Comment by ArtemGovorov** [comment] 2015-07-10 05:33
Have reproduced the issue by adding files that you have described to [this sample](https://github.com/wallabyjs/wallaby-requirejs-middleware). I had to make a couple of assumptions to cover the missing bits, correct me if I'm wrong - you are using require.js 'text' plugin to load HTML files? If that's the case, the issue is fixed now in core v1.0.78.

So now if you first edit the spec that requests an HTML file and then start editing and saving the HTML file, it should work for you:

![rec](https://cloud.githubusercontent.com/assets/979966/8612699/3c57175c-2718-11e5-91ee-7c066903f8b6.gif)

**Closed by ArtemGovorov** 2015-07-10 05:33 UTC
Labels: bug

**Comment by cResults** [comment] 2015-07-13 16:47
I see in the Wallaby.js - Console that I've been updated to v1.0.78.  I'll be working in code that will test this today.

Does wallaby use a file dependencies to figure out what to run?  for example the dependencies listed by an AMD or CommonJS require or define, or an ES6 import?

**Comment by ArtemGovorov** [comment] 2015-07-14 00:25
@cResults Wallaby is using code instrumentation to figure out the dependencies. Before executing your code, it changes it to insert some instructions to collect the code coverage and track dependencies. So when a test executes, wallaby gets the information from all JavaScript files it uses during its execution, no matter what mechanism is used to load them: AMD/CommonJs/native ES6 import.

This however means that wallaby has no idea about an HTML file dependencies and when you change the HTML file, wallaby generally doesn't know what tests to execute. But, as I have said, it also has some built-in heuristic rules to help in such cases:  if you first edit the spec that requests an HTML file and then start editing and saving the HTML file, then wallaby will run the last edited spec.

There's a plan to improve the mechanism that determines dependencies to better work with non-JavaScript files.
