### ISSUE TITLE
Error Message in Wallaby Console: "timeout - async callback was not invoked within timeout specified by jasmine.default_timeout_interval"

### ISSUE THREAD

**Issue by pahund** [wallabyjs/public#64] opened 2015-04-09 15:08 UTC
First off, I'm quite excited about Wallaby and really like using it!

When I work on my JavaScript code in IntelliJ IDEA, after some time, Wallaby stops executing the tests immediately and I get these error messages in the error console: 

`timeout - async callback was not invoked within timeout specified by jasmine.default_timeout_interval`

The tests results then do pop up, but now there is a noticeable delay.

I tried to set the `Jasmine.DEFAULT_TIMEOUT_INTERVAL` constant up to a higher value, but that just increases the delay by the amount of milliseconds I specify.

When I restart my Wallaby run configuration, all is well once more, until after spending some time working on my instrumented code, the problem starts again.

I use Wallaby version 1.0.5 with IntelliJ IDEA Ultimate 14.1.1. I'm running a Jasmine test suite with about 40 test cases. I use RequireJS as module loader.

**Comment by ArtemGovorov** [comment] 2015-04-10 00:32
Thanks!

The issue is most likely caused by one of your async tests or wallaby bug related to async tests execution. From the symptoms, it looks like in one of the async tests `done` callback is not invoked under some certain circumstances.

It'd be awesome if I could get some simple code where the issue could be reproduced.
From those 40 tests that you have, how many are async? Could you please have a brief look to make sure that all of them always call `done` callback under all circumstances, especially the test that is marked as failed with `timeout - async callback was not invoked` error? It's possible that some test depends on some data set up in some other test or in `beforeEach` setup of some other test file, so when launched all together then tests work fine, but when wallaby launches them separately then they fail.
If there's nothing obvious, could you try commenting async test(s) out (or renaming corresponding `it` functions to `xit`) and then try reproducing the issue? If the issue goes away, could you try uncommenting your async tests by chunks (or one by one if there're not many of them) to determine what test is causing the issue?

**Comment by pahund** [comment] 2015-04-10 07:26
Well, that's the thing I was puzzled about: actually, none of the tests are async, it's testing a simple jQuery plugin that opens and closes popup menus and such, no mocked Ajax calls or anything like that. I do use [jquery-jasmine](https://github.com/velesin/jasmine-jquery) to load an HTML page as a fixture, perhaps that has something to do with it. I'll see if I can find the time to set up a sandbox example where you can reproduce the problem.

**Comment by ArtemGovorov** [comment] 2015-04-10 07:31
Does wallaby.js always reports one particular test with `timeout - async callback was not invoked` error, or it reports different tests with this error?

I'll try to create a few simple tests using jquery-jasmine to see if I can reproduce the issue.

**Comment by pahund** [comment] 2015-04-11 12:02
Here's a code example that should let you reproduce the issue: https://github.com/pahund/wallaby-demo
When I change stuff in the instrumented code ([navigation.js](https://github.com/pahund/wallaby-demo/blob/master/js/navigation.js)), Wallaby works as expected, but when I change code in the spec ([navigation-spec.js](https://github.com/pahund/wallaby-demo/blob/master/test/specs/navigation-spec.js)), especially in one of the deeply nested {{it}}-sections, the issue starts occurring after 2-3 attempts.
Try changing the argument of {{toHaveLength}} in [line 257](https://github.com/pahund/wallaby-demo/blob/master/test/specs/navigation-spec.js#L257), for example

**Closed** 2015-04-12 02:55 UTC

**Comment by ArtemGovorov** [comment] 2015-04-12 03:05
Thanks for the sample and detailed steps how to reproduce the issue. It's fixed now.

**Comment by pahund** [comment] 2015-04-12 05:40
Awesome, thanks! :-)

**Comment by tanzeelrana** [comment] 2018-10-04 22:00
@ArtemGovorov  what did you do to fix this bug ?

**Comment by pahund** [comment] 2018-10-05 06:05
@tanzeelrana you did notice that this conversation is from more than three years ago, right? 😀
