### ISSUE TITLE
react-native and jest - Cannot find module 'ReactNativeDefaultInjection'

### ISSUE THREAD

**Issue by DanielZlotin** [wallabyjs/public#879] opened 2016-11-21 09:33 UTC
### Issue description or question

When running wallaby with jest and react-native, using the `jest-react-native` preset (required by jest to play nicely with react-native components) I get this error:

```
Runtime error: Error: Cannot find module 'ReactNativeDefaultInjection' from 'setup.js'
```

Running from node works (with the `jest` command).

jest configuration:
```
{
    "preset": "jest-react-native",
    "resetMocks": true,
    "resetModules": true,
    "verbose": true
  }
```

babelrc:
```
{
  "presets": [
    "react-native"
  ]
}

```

build dependencies:
```
├── babel-cli@6.18.0
├── babel-core@6.18.2
├── babel-jest@17.0.2
├── babel-polyfill@6.16.0
├── babel-preset-react-native@1.9.0
├── babel-register@6.18.0
├── eslint@3.10.2
├── eslint-plugin-babel@3.3.0
├── eslint-plugin-react@6.7.1
├── eslint-plugin-react-native@2.1.0
├── jest@17.0.3
├── jest-cli@17.0.3
├── jest-react-native@17.0.3
├── lodash@4.17.2
├── node-pre-gyp@0.6.31 extraneous
├── react@15.3.2
├── react-native@0.37.0
├── react-test-renderer@15.3.2
```

### Wallaby.js configuration file

```javascript
/*eslint-disable*/
'use strict';
const babelOptions = JSON.parse(require('fs').readFileSync(`${__dirname}/.babelrc`));
module.exports = function(wallaby) {
  return {
    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    files: [
      'package.json',
      'node_modules/react/**/*.js',
      'node_modules/*jest*/**/*.js',
      'src2/**/*.js',
      '!src2/**/*.test.js'
    ],

    tests: [
      'src2/**/*.test.js'
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel(babelOptions)
    },

    setup: function(w) {
      require('babel-polyfill');
      w.testFramework.configure(require('./package.json').jest);
    }
  };
};

```

### Code editor or IDE name and version

WebStorm 2016.3

### OS name and version

OSX El Capitan 10.11.6

**Comment by ArtemGovorov** [comment] 2016-11-21 10:58
I was able able to reproduce the issue, however I must be missing something, because when I run `jest` command, I'm getting the same error:

<img width="594" alt="screen shot 2016-11-21 at 8 55 49 pm" src="https://cloud.githubusercontent.com/assets/979966/20480175/29343fca-b02d-11e6-9854-9b8b979449be.png">

Could you please share a small project where `jest` command works for you (but running wallaby fails)?

**Comment by ArtemGovorov** [comment] 2016-11-21 11:02
Here's the [sample I'm using](https://github.com/wallabyjs/wallaby-879), both wallaby and `npm test` (that runs `jest`) fail with the same error.

**Comment by DanielZlotin** [comment] 2016-11-21 12:30
@ArtemGovorov Thanks a lot for the quick response!
I fixed the project to reproduce the problem:
You were missing the react and react-native dependencies.

Now it runs from node but not through wallaby.

My guess is that `setup` script of `jest-react-native` preset tries to mock `ReactNativeDefaultInjection` [and a bunch of other stuff](https://github.com/facebook/jest/blob/master/packages/jest-react-native/src/setup.js#L14) but can't find this module. 
This module is provided by `react`, [using their weird `@providesModule` mechanism](https://github.com/facebook/react/blob/bdf263625db59f54368d39e8ef077e7f0e9313db/src/renderers/native/ReactNativeDefaultInjection.js).

Keep in most of those dependencies' version are coupled. Meaning, you must use react@15.3.2 together with react-test-renderer@15.3.2 for example.

**Comment by ArtemGovorov** [comment] 2016-11-22 04:23
Thanks for providing the sample. It was an issue with wallaby setting jest `rootDir` to be wallaby cache folder instead of setting it to be the local project root. The issue is fixed in the latest core (you [may restart your IDE](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) to get the update ASAP). I have also cleaned up the config a bit to [remove `node_modules` from the `files` list](https://github.com/wallabyjs/wallaby-879/blob/master/wallaby.js#L13) as they are not required there.

**Closed by ArtemGovorov** 2016-11-22 04:23 UTC
Labels: bug

**Comment by DanielZlotin** [comment] 2016-11-22 09:48
@ArtemGovorov works! thnx!
Not a big issue, but now test cases which import 'react' / 'react-native' take 17 seconds to run, while in node they run under a second

**Comment by ArtemGovorov** [comment] 2016-11-22 10:26
@DanielZlotin Awesome, thanks or checking

> Not a big issue, but now test cases which import 'react' / 'react-native' take 17 seconds to run, while in node they run under a second

Hmm, could you please share a simple test (may just update the sample repo) so I could reproduce and have a look into why does it take that long?

**Comment by ArtemGovorov** [comment] 2016-11-22 10:37
I have added `import 'react'` to the [sample test](https://github.com/wallabyjs/wallaby-879/blob/master/src2/a.test.js#L1), but everything is still fast for me.

**Comment by DanielZlotin** [comment] 2016-11-22 17:25
I can't reproduce it, I figured out that those 17 seconds are the time it takes for a test suite to run (with 5 tests, each calls react-native mocked components), so I guess it just takes time to load all the mocks. I'll PR some "stress test" code

**Comment by DanielZlotin** [comment] 2016-11-22 17:32
https://github.com/wallabyjs/wallaby-879/pull/2

**Comment by ArtemGovorov** [comment] 2016-11-23 06:01
Thanks for the PR! 

Please try the latest core v1.0.327 (you [may restart your IDE](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) to get the update ASAP), and let me know if it fixes the issue for you.

**Comment by DanielZlotin** [comment] 2016-11-23 09:35
Much faster now, thanks!
