### ISSUE TITLE
Angular 1.5 - All Tests Fail

### ISSUE THREAD

**Issue by jefhauschild** [wallabyjs/public#457] opened 2016-02-11 17:35 UTC
I just tried to update an app to use Angular 1.5 and Wallaby doesn't seem to like it at all.  All my tests fail.  The first issue is it appears that 1.5 makes use of Function.prototype.bind.apply, so I polyfilled that, but now I'm getting for every test:

Error: [$injector:modulerr] Failed to instantiate module ng due to:
TypeError: 'null' is not an object (evaluating 'this')

Normally, that would make me think I've got some Angular module problems, but literally all I'm doing is switching between passing tests with 1.4.9 and failing tests with 1.5.0.  The app seems to work fine with 1.5 in the browser.  Anyone else seeing this?

**Comment by fvanwijk** [comment] 2016-02-11 19:46
I have the same, but it is not a Wallaby issue. Still investigating why this happens. Did you already checked the 1.5 changelog?

**Comment by chrisns** [comment] 2016-02-11 22:03
this may help
`env: {
      type: 'browser',
      runner: require("phantomjs2-ext").path,
      params: {
        runner: "--web-security=false"
      }
    },`

**Comment by chrisns** [comment] 2016-02-11 22:03
(npm install phantomjs-ext too)

**Comment by ArtemGovorov** [comment] 2016-02-12 02:14
The only issue I was getting is `Function.prototype.bind.apply` and it can be fixed by polyfilling it as @jefhauschild mentioned or [upgrading to PhantomJs2](http://wallabyjs.com/docs/integration/phantomjs2.html) as @chrisns mentioned. I have updated the [docs page](http://wallabyjs.com/docs/integration/angular.html#angular-15) to mention it.

I have also updated [angular sample to use 1.5](https://github.com/wallabyjs/wallaby-angular-todomvc-sample) and tests are running fine.

I didn't get this error:
```
Error: [$injector:modulerr] Failed to instantiate module ng due to:
TypeError: 'null' is not an object (evaluating 'this')
```

@fvanwijk Happens in karma as well?

Does anyone have a repo where it's reproducible so I could have a look?

**Comment by fvanwijk** [comment] 2016-02-12 07:20
Yes I was so stupid to trust on semver backwards compatibility by depending on `angular: 1`. So Angular 1.5 was fetched instead of 1.4.

https://travis-ci.org/xebia/angular-form-messages/builds/108594952

**Comment by ArtemGovorov** [comment] 2016-02-12 07:57
@fvanwijk 
> You could check out the specific commit of this repo to reproduce it.

I can only reproduce this one: `Function.prototype.bind.apply`. Which as I have mentioned can be fixed by installing phantom polyfill:
```
npm i phantomjs-polyfill --save-dev
```
and referencing it in your `files` list:
```
n('node_modules/phantomjs-polyfill/bind-polyfill.js'),
```
(similar will work for your karma config).

I was wondering if anyone has this issue and can share a way to reproduce it.
```
Error: [$injector:modulerr] Failed to instantiate module ng due to:
TypeError: 'null' is not an object (evaluating 'this')
```

**Comment by fvanwijk** [comment] 2016-02-12 08:01
Oh sorry, I misread your request. I'm not yet able to reproduce the TypeError in my repo.

**Comment by jefhauschild** [comment] 2016-02-12 14:14
I'll try updating PhantomJS and see if that helps further.  After that I'll have to look through my dependencies and see who's causing the problems.  If that doesn't work I'll see about making a repo to replicate the problem.

Thanks everyone for the help.

**Comment by ArtemGovorov** [comment] 2016-02-20 01:30
@jefhauschild I have reproduced the 
```
Error: [$injector:modulerr] Failed to instantiate module ng due to:
TypeError: 'null' is not an object (evaluating 'this')
```
error and it looks like it's because of some bad `Function.prototype.bind` polyfill. When I switched to `phantomjs-polyfill`, everything worked. So just try to

```
npm i phantomjs-polyfill --save-dev
```
and add 
```
{pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false}
```
as the very first entry in your `files` list.

**Closed by ArtemGovorov** 2016-02-20 01:30 UTC

**Comment by jefhauschild** [comment] 2016-02-22 14:54
@ArtemGovorov  Switching to that polyfill worked like a charm.  Thanks.

**Comment by ValentinH** [comment] 2016-02-25 09:39
@ArtemGovorov :+1: I'm not using this library but came through google when searching for this error, you saved me quite much time!

**Comment by raymer** [comment] 2016-10-25 13:41
I had this issue after upgrading to Angular 1.5.8 and the polyfill worked great. Thank you!

**Comment by roopkt** [comment] 2017-01-10 14:33
Hey guys 
I am also getting this error I am using chutzpah.json and jasmine. 
I do not use Node js my project is in vs 2013 with nuget packages installed. 

I am trying to upgrade from angular 1.4 to 1.5.8 and all of my test cases are breaking with below error:


> Error: [$injector:modulerr] Failed to instantiate module ng due to:
> TypeError: 'null' is not an object (evaluating 'this')

Is it because of phantom pollyfill ? How can I use phantomjs-polyfill in my project, please advice ?

**Comment by roopkt** [comment] 2017-01-10 15:15
I figure it out that I already have polyfill for phantomjs  in my javascript file. Still the error is coming.

**Comment by ArtemGovorov** [comment] 2017-01-10 23:45
@roopkt Wallaby.js includes the correct polyfill by default now. If you're experiencing the issue with wallaby.js, please share your wallaby config file. 

From what you've mentioned, you seem to be using chutzpah to run your tests, I'm not much familiar with it, so perhaps try asking them about it (or try manually replacing your polyfill [with this](https://github.com/tom-james-watson/phantomjs-polyfill/blob/master/bind-polyfill.js)).

**Comment by roopkt** [comment] 2017-01-11 02:05
Hi thanks for your reply.
We do not use wallaby.js. We also have included polyfill manually in our javascript file. 
Probably I will ask in chutzpah team. We use Jasmine and Sinon test framework.
