### ISSUE TITLE
Solved: Quokka license expiration causes valid wallaby license to fail

### ISSUE THREAD

**Issue by samjcombs** [wallabyjs/public#3177] opened 2023-02-28 14:19 UTC
### Issue description or question
if Quokka trial runs out but you have a valid Wallaby license, you cant run wallaby until you uninstall (or likely valid license Quokka)
You get these errors:
```
Error starting wallaby.js server, Cannot run program "node" (in directory "[redacted -- my project directory]"): error=2, No such file or directory
```

```
Cannot invoke "com.intellij.execution.process.ProcessHandler.putUserData(com.intellij.openapi.util.Key, Object)" because "this.p" is null
```

**Comment by ArtemGovorov** [comment] 2023-03-01 01:01
Hi, we have reviewed the code and it looks unlikely that the Wallaby starting issue is related to Quokka or Quokka license. It looks like the issue is that Wallaby can't find your system default node.js executable. Please try opening the Wallaby Run Configuration in your IDE and specifying the path to your node executable in the `Node.js` config field.

**Comment by samjcombs** [comment] 2023-03-01 11:17
It wasn’t a node issue.  I certainly have node installed and configured correctly.   The only solve for this issue which I had for a few weeks was to uninstall quokka.  Not sure why but that solved it.  I tried multiple different ways of pointing it to node to no avail On Feb 28, 2023, at 8:02 PM, Artem Govorov ***@***.***> wrote:﻿
Hi, we have reviewed the code and it looks unlikely that the Wallaby starting issue is related to Quokka or Quokka license. It looks like the issue is that Wallaby can't find your system default node.js executable. Please try opening the Wallaby Run Configuration in your IDE and specifying the path to your node executable in the Node.js config field.

**Comment by ArtemGovorov** [comment] 2023-03-02 00:54
Hi, thanks for providing the details.

We have tried a few scenarios of running Wallaby with expired and trial Quokka licenses, but can not reproduce the issue.

Can you please try reproducing the issue in your environment and, when the problem is reproduced please:
- share a screenshot of the error,
- share a screenshot of your Wallaby Run Configuration that is failing to start,
- attach the `idea.log` file (available via `Help - Show Log ...` menu in your IDE),
- archive and attach `~/.quokka` and `~/.wallaby` folders,
- share the steps to reproduce the issue.

**Comment by smcenlly** [comment] 2023-03-04 00:22
I'm closing this issue as there's no further action required from us at this stage. If you can provide the details requested, we will re-open the issue at that point in time.

**Closed by smcenlly** 2023-03-04 00:22 UTC
Labels: more info is required
