### ISSUE TITLE
Support for Gitpod

### ISSUE THREAD

**Issue by jwrunner** [wallabyjs/public#2691] opened 2021-04-29 01:30 UTC
### Issue description or question

Similar to #2675 I would like to use Wallaby (and Quokka while you're at it) in an online dev environment, [Gitpod](https://gitpod.io/), which is very similar to what GitHub Codespaces is going to be except that it's already available! Since they are not a Microsoft product, they cannot use extensions from the marketplace that VS Code pulls from however. Would you be able to also publish your extension to the [Open VSX Registry](https://open-vsx.org/) via `npx ovsx publish` as documented in https://www.gitpod.io/blog/open-vsx-in-gitpod/ and https://www.gitpod.io/blog/open-vsx/, see also https://www.gitpod.io/docs/vscode-extensions/

**Comment by smcenlly** [comment] 2021-04-29 01:47
Closing as a duplicate of https://github.com/wallabyjs/public/issues/2436.

We don't have any immediate plans to publish to open-vsx.org registry. For now, it looks like a work-around is available:

> ... you can also install it by drag-and-dropping a *.vsix file into the IDE’s Extensions view. Gitpod will automatically install and activate the new extension, and add an entry to your .gitpod.yml file.

You may download Quokka VSIX from [here](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode), and the Wallaby VSIX from [here](https://marketplace.visualstudio.com/items?itemName=WallabyJs.wallaby-vscode)

**Closed by smcenlly** 2021-04-29 01:47 UTC
