### ISSUE TITLE
VSCode Exception: “The ‘data’ argument must be of type string.”

### ISSUE THREAD

**Issue by phyllisstein** [wallabyjs/public#2247] opened 2019-10-24 04:26 UTC
### Issue description or question
Hey folks! I’m getting an odd error from Wallaby every time I start VSCode:

```
The "data" argument must be one of type string, Buffer, TypedArray, or DataView. Received type undefined
```

I just tried installing the extension in an otherwise brand-new VSCode instance; it installed core v1.0.769, then threw the same error.

### Wallaby diagnostics report

<details>
<summary>Diagnostics report</summary>

```
{
  editorVersion: '1.40.0-insider',
  pluginVersion: '1.0.152',
  editorType: 'VSCode',
  osVersion: 'darwin 19.0.0',
  nodeVersion: 'v12.12.0',
  coreVersion: '1.0.766',
  config: {},
  packageJSON: {
    dependencies: {
      '@apollo/react-hooks': '^3.1.3',
      '@apollo/react-ssr': '^3.1.3',
      '@babel/polyfill': '^7.6.0',
      '@babel/runtime-corejs3': '^7.6.3',
      '@fortawesome/fontawesome-svg-core': '^1.2.25',
      '@fortawesome/pro-duotone-svg-icons': '^5.11.2',
      '@fortawesome/pro-solid-svg-icons': '^5.11.2',
      '@mdi/js': '^4.5.95',
      '@mdi/react': '^1.2.1',
      '@reach/router': '^1.2.1',
      'apollo-boost': '^0.4.4',
      'apollo-client': '^2.6.4',
      'apollo-utilities': '^1.3.2',
      'babel-plugin-styled-components': '^1.10.6',
      'chroma-js': '^2.0.6',
      'core-js': '^3.3.2',
      'cross-fetch': '^3.0.4',
      exenv: '^1.2.2',
      'fast-async': '>=7',
      graphql: '^14.5.8',
      'graphql-tag': '^2.10.1',
      gsap: '^2.1.3',
      history: '^4.10.1',
      immutable: '^4.0.0-rc.12',
      jss: '^10.0.0',
      'jss-plugin-cache': '^10.0.0',
      'jss-plugin-camel-case': '^10.0.0',
      'jss-plugin-compose': '^10.0.0',
      'jss-plugin-default-unit': '^10.0.0',
      'jss-plugin-expand': '^10.0.0',
      'jss-plugin-extend': '^10.0.0',
      'jss-plugin-global': '^10.0.0',
      'jss-plugin-isolate': '^10.0.0',
      'jss-plugin-nested': '^10.0.0',
      'jss-plugin-props-sort': '^10.0.0',
      'jss-plugin-rule-value-function': '^10.0.0',
      'jss-plugin-rule-value-observable': '^10.0.0',
      'jss-plugin-template': '^10.0.0',
      'jss-plugin-vendor-prefixer': '^10.0.0',
      'jss-preset-default': '^10.0.0',
      koa: '^2.10.0',
      'koa-router': '^8.0.0-alpha.1',
      'koa-static': '^5.0.0',
      lodash: '^4.17.15',
      moment: '^2.24.0',
      'open-color': '^1.7.0',
      polished: '^3.4.1',
      raf: '^3.4.1',
      ramda: '^0.26.1',
      react: '^16.10.2',
      'react-dom': '^16.10.2',
      'react-helmet': '^5.2.1',
      'react-hot-loader': '^4.12.15',
      'react-jss': '^10.0.0',
      'react-loadable': '^5.5.0',
      'react-loadable-visibility': '^3.0.1',
      'react-spring': '^8.0.27',
      'react-transition-group': '^4.3.0',
      recompose: '^0.30.0',
      'regenerator-runtime': '^0.13.3',
      slate: '^0.47.8',
      'slate-plain-serializer': '^0.7.10',
      'slate-react': '^0.22.9',
      'styled-components': '^4.4.0',
      'webpack-node-externals': '^1.7.2'
    },
    devDependencies: {
      '@babel/cli': '^7.6.4',
      '@babel/core': '^7.6.4',
      '@babel/plugin-proposal-class-properties': '^7.5.5',
      '@babel/plugin-proposal-decorators': '^7.6.0',
      '@babel/plugin-proposal-do-expressions': '^7.6.0',
      '@babel/plugin-proposal-export-default-from': '^7.5.2',
      '@babel/plugin-proposal-export-namespace-from': '^7.5.2',
      '@babel/plugin-proposal-function-bind': '^7.2.0',
      '@babel/plugin-proposal-logical-assignment-operators': '^7.2.0',
      '@babel/plugin-proposal-nullish-coalescing-operator': '^7.4.4',
      '@babel/plugin-proposal-numeric-separator': '^7.2.0',
      '@babel/plugin-proposal-optional-catch-binding': '^7.2.0',
      '@babel/plugin-proposal-optional-chaining': '^7.6.0',
      '@babel/plugin-proposal-pipeline-operator': '^7.5.0',
      '@babel/plugin-proposal-throw-expressions': '^7.2.0',
      '@babel/plugin-syntax-dynamic-import': '^7.2.0',
      '@babel/plugin-transform-modules-commonjs': '^7.6.0',
      '@babel/plugin-transform-regenerator': '^7.4.5',
      '@babel/plugin-transform-runtime': '^7.6.2',
      '@babel/preset-env': '^7.6.3',
      '@babel/preset-react': '^7.6.3',
      '@hot-loader/react-dom': '^16.10.2',
      'babel-eslint': '^10.0.3',
      'babel-loader': '^8.0.6',
      'babel-plugin-graphql-tag': '^2.5.0',
      'babel-plugin-inline-react-svg': '^1.1.0',
      'babel-plugin-lodash': '^3.3.4',
      'babel-plugin-ramda': '^2.0.0',
      'babel-plugin-react-local': '^0.6.2',
      'copy-webpack-plugin': '^5.0.4',
      'css-loader': '^3.2.0',
      'directory-named-webpack-plugin': '^4.0.1',
      eslint: '^6.5.1',
      'eslint-config-standard': '^14.1.0',
      'eslint-config-standard-jsx': '^8.1.0',
      'eslint-plugin-babel': '^5.3.0',
      'eslint-plugin-import': '^2.18.2',
      'eslint-plugin-lodash-fp': '^2.2.0-a1',
      'eslint-plugin-node': '^10.0.0',
      'eslint-plugin-promise': '^4.2.1',
      'eslint-plugin-ramda': '^3.0.0-beta.1',
      'eslint-plugin-react': '^7.16.0',
      'eslint-plugin-react-hooks': '^2.1.2',
      'eslint-plugin-standard': '^4.0.1',
      'file-loader': '^4.2.0',
      'html-webpack-plugin': '^4.0.0-beta.8',
      'imports-loader': '^0.8.0',
      'merge-deep': '^3.0.2',
      rimraf: '^3.0.0',
      'style-loader': '^1.0.0',
      stylelint: '^11.1.1',
      'stylelint-config-standard': '^19.0.0',
      'stylelint-config-styled-components': '^0.1.1',
      'stylelint-order': '^3.1.1',
      'stylelint-processor-styled-components': '^1.8.0',
      'url-loader': '^2.2.0',
      webpack: '^4.41.2',
      'webpack-chain': '^6.0.0',
      'webpack-cli': '^3.3.9',
      'webpack-common-shake': '^2.1.0',
      'webpack-dev-server': '^3.8.2',
      'webpack-merge': '^4.2.2'
    }
  },
  fs: { numberOfFiles: 0 },
  debug: []
}
```
</details>

**Comment by ArtemGovorov** [comment] 2019-10-24 05:48
Thanks for the report! The issue is fixed and the fixed in published in the latest extension version v1.0.153.

**Closed by ArtemGovorov** 2019-10-24 05:48 UTC
Labels: bug
