### ISSUE TITLE
Error installing on Webstorm 2019.2.3: javax.swing.Icon com.intellij.util.ui.EmptyIcon.create(int)

### ISSUE THREAD

**Issue by clarkeym** [wallabyjs/public#2229] opened 2019-10-02 19:03 UTC
### Error running 'Wallaby': 'javax.swing.Icon com.intellij.util.ui.EmptyIcon.create(int)'

Trying to install the plugin from disk on mac. Webstorm version 2019.2.3 (dated 24 September 2019). Get the above error

**Comment by smcenlly** [comment] 2019-10-02 23:36
We've seen a [similar error](https://github.com/wallabyjs/public/issues/1817) in the past because of a breaking change in the IntelliJ API. This was fixed in Wallaby v1.0.118+. If you have recently upgraded Webstorm and have an older version of Wallaby, it's possible that this is the cause of your problem.

The [latest version of Wallaby for IntelliJ](https://download.wallabyjs.com/intellij) is working for us with the latest version of Webstorm (2019.2.3).

If you are using the latest version Wallaby and are still having issues:

1) Are you using the JetBrains Runtime or a custom runtime? 
2) Can you please provide us with the details/screenshot from WebStorm Help->About? (we're interested to know `Runtime version` and `VM`.

**Comment by clarkeym** [comment] 2019-10-03 11:39
thanks, it’s working now

**Closed** 2019-10-03 23:33 UTC
