### ISSUE TITLE
Runtime error: TypeError: Cannot read property '_jasmineAdapter' of undefined

### ISSUE THREAD

**Issue by JonathanYates** [wallabyjs/public#2053] opened 2019-04-09 10:58 UTC
### Issue description or question

I get the following Error running Latest Wallaby in VSCode with latest enzyme and jest

[Error] Runtime error: TypeError: Cannot read property '_jasmineAdapter' of undefined 
[Error]     at Runtime._execModule (I:\playground\wallaby-test\node_modules\jest-runtime\build\index.js:858:13) 
[Error]     at Runtime._loadModule (I:\playground\wallaby-test\node_modules\jest-runtime\build\index.js:551:12) 
[Error]     at Runtime.requireModule (I:\playground\wallaby-test\node_modules\jest-runtime\build\index.js:415:10) 
[Error]     at config.setupFilesAfterEnv.forEach.path (I:\playground\wallaby-test\node_modules\jest-jasmine2\build\index.js:186:55) 
[Error]     at Array.forEach (<anonymous>) 
[Error]     at I:\playground\wallaby-test\node_modules\jest-jasmine2\build\index.js:186:31 
[Error]     at Generator.next (<anonymous>) 
[Error]     at asyncGeneratorStep (I:\playground\wallaby-test\node_modules\jest-jasmine2\build\index.js:27:24) 
[Error]     at _next (I:\playground\wallaby-test\node_modules\jest-jasmine2\build\index.js:47:9) 
[Error]     at I:\playground\wallaby-test\node_modules\jest-jasmine2\build\index.js:52:7 
[Error]     at new Promise (<anonymous>) 
[Error]     at I:\playground\wallaby-test\node_modules\jest-jasmine2\build\index.js:44:12 
[Error]     at _jasmine (I:\playground\wallaby-test\node_modules\jest-jasmine2\build\index.js:206:19) 
[Error]     at jasmine2 (I:\playground\wallaby-test\node_modules\jest-jasmine2\build\index.js:60:19) 
[Error]     at I:\playground\wallaby-test\node_modules\jest-runner\build\runTest.js:384:24 
[Error]     at Generator.next (<anonymous>) 
[Error]     at asyncGeneratorStep (I:\playground\wallaby-test\node_modules\jest-runner\build\runTest.js:161:24) 
[Error]     at _next (I:\playground\wallaby-test\node_modules\jest-runner\build\runTest.js:181:9) 
[Error]     at <anonymous> 
[Error]     at process._tickCallback (internal/process/next_tick.js:188:7)
[Info]  console.log: FAIL src/foo.spec.js
[Info]  console.log:   ● Test suite failed to run
[Info]      TypeError: Cannot read property '_jasmineAdapter' of undefined
[Info]        at Object._jasmineAdapter (I:/software/VSCode-win32-x64-1.32.3/data/extensions/wallabyjs.wallaby-vscode-1.0.122/wallaby/runners/node/jest@0.4.3/jasmine2Initializer.js:14:2524)
[Info]        at Runtime.d._wallabyReplaced.c.requireModule (I:/software/VSCode-win32-x64-1.32.3/data/extensions/wallabyjs.wallaby-vscode-1.0.122/wallaby/runners/node/jest@0.4.3/initializer.js:14:25212)
[Info]            at Array.forEach (<anonymous>) 

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: [
      "src/**/*.js",
      "src/**/*.jsx",
      "!src/**/*.spec.js",
      "!src/**/*.spec.jsx"
    ],
    tests: ["src/**/*.spec.js", "src/**/*.spec.jsx"],
    env: {
      type: "node",
      runner: "node"
    },
    testFramework: "jest"
  };
};
```

### Package.json

```json
{
  "name": "wallaby-test",
  "version": "0.0.0",
  "description": "wallaby-test",
  "scripts": {
    "test": "jest",
    "test:watch": "npm run test -- --watch"
  },
  "dependencies": {},
  "devDependencies": {
    "enzyme": "^3.9.0",
    "enzyme-adapter-react-16": "^1.12.1",
    "jest": "^24.7.1"
  },
  "jest": {
    "verbose": true,
    "moduleDirectories": [
      "node_modules",
      "src"
    ],
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "setupFilesAfterEnv": [
      "<rootDir>/src/test-setup.js"
    ],
    "testMatch": [
      "<rootDir>/src/**/*spec.(ts|tsx|js)"
    ],
    "testPathIgnorePatterns": [
      "<rootDir>/node_modules/"
    ]
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.32.3

### OS name and version

Windows 7

**Comment by ArtemGovorov** [comment] 2019-04-09 11:42
What is your Wallaby core version? (it is [printed in Wallaby Console](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting))

**Comment by JonathanYates** [comment] 2019-04-09 12:15
Wallaby.js Core v1.0.675

**Comment by JonathanYates** [comment] 2019-04-09 12:16
and latest Wallaby 1.0.122

**Comment by JonathanYates** [comment] 2019-04-09 12:26
I have also reduced the package.json and wallaby.js files down to the following but still get the same error.

### wallaby.js
```javascript
module.exports = function(wallaby) {
  return {
    files: ["src/**/*.js", "!src/**/*.spec.js"],
    tests: ["src/**/*.spec.js"],
    env: {
      type: "node",
      runner: "node"
    },
    testFramework: "jest"
  };
};
```

### package.json
```json
{
  "name": "wallaby-test",
  "version": "0.0.0",
  "description": "wallaby-test",
  "scripts": {
    "test": "jest"
  },
  "dependencies": {},
  "devDependencies": {
    "jest": "24.7.1"
  },
  "jest": {
    "verbose": true
  }
}
```

**Comment by smcenlly** [comment] 2019-04-09 23:38
We've tried the same configuration and everything is working for us. I've created a [sample repo with everything working](https://github.com/wallabyjs/issue-2053). Could you please try cloning our sample repo and seeing if that works for you?

If that doesn't work, it's possible that there's an older version of `jest` installed that is being resolved by `node` based off where wallaby's project cache is located. It looks like you're using windows, by default, the project cache is located C:\Users\%USERNAME%\.vscode\extensions\wallabyjs.wallaby-vscode-%VERSION%\projects. Please check all directories above this for a `node_modules` directory containing `jest`.

**Comment by JonathanYates** [comment] 2019-04-10 09:50
Thanks for the sample repo. I have discovered something interesting with regards to where I put the source code. Normally all my source code is located on a separate drive (I:/) to C:/. If I place the source code on my C: drive it works without the error. However if I put the exact same code (node_modules included) on the I: drive I get the error. I don't have jest installed globally on C drive or anywhere else. I am also running VSCode from I: drive as well which has been installed from the zip distributable and all the extensions (including Wallaby) are in the data\extensions folder of my VSCode folder. But it works absolutely fine if I open the this sample from C: drive. If I run npm test to run Jest that works fine from I: drive, so I can only think it's something to do with Wallaby running from the I: drive. 

Please can you test this with the source code on another drive other than C: ?

**Comment by smcenlly** [comment] 2019-04-10 23:28
@JonathanYates - thanks for letting us know, we'll take a look at this today and get back to you.

**Comment by ArtemGovorov** [comment] 2019-04-11 00:14
@JonathanYates We have checked that the sample repo is working for us on other drives too.

Could you please double check that following folders do not exist on your `I:` drive:

```
I:\Users\%USERNAME%\.vscode\extensions\node_modules
I:\Users\%USERNAME%\.vscode\node_modules
I:\Users\%USERNAME%\node_modules
I:\Users\node_modules
I:\node_modules
I:\playground\node_modules
```

**Comment by JonathanYates** [comment] 2019-04-11 08:05
I confirm that I do not have any of the above folders on I: drive.

I don't have any issues with anything else on I: drive requiring npm packages and I am able to run Jest without any issues. The only issue is this issue with Wallaby, therefore I can only assume Wallaby is the issue and is incorrectly resolving Jest which exists in the node_modules of this sample repo.

**Comment by smcenlly** [comment] 2019-04-11 23:28
Sorry it's taking a while for us to help find the cause of this error. Can you please provide us with the results of when you run the following command in `cmd.exe` from your `I:\` root directory?

```
dir *jest /s /b
```

Just to double-check/confirm, you get the same problem when you run our repo (issue-2053) on your `I:\`?

**Comment by smcenlly** [comment] 2019-04-15 23:23
@JonathanYates - following up to see if you still have the same problem and if so, if you're able to provide us with the information we requested. If we don't hear from you in the next few days, we'll close out the issue and re-open when you provide additional information.

**Comment by JonathanYates** [comment] 2019-04-17 09:37
@smcenlly - Sorry for the late reply. Here is the results of running the command above from the root of I:\ 

I:\dev\xap-prod-svc-web\xap-prod-svc-web-web\node_modules\babel-jest
I:\dev\xap-prod-svc-web\xap-prod-svc-web-web\node_modules\babel-preset-jest
I:\dev\xap-prod-svc-web\xap-prod-svc-web-web\node_modules\jest
I:\dev\xap-prod-svc-web\xap-prod-svc-web-web\node_modules\ts-jest
I:\dev\xap-prod-svc-web\xap-prod-svc-web-web\node_modules\.bin\jest
I:\dev\xap-prod-svc-web\xap-prod-svc-web-web\node_modules\.bin\ts-jest
I:\dev\xap-prod-svc-web\xap-prod-svc-web-web\node_modules\@types\jest
I:\dev\xap-prod-svc-web\xap-prod-svc-web-web\node_modules\apollo-client\config\jest
I:\dev\xap-prod-svc-web\xap-prod-svc-web-web\node_modules\jest\node_modules\.bin\jest
I:\playground\issue-2053-master\node_modules\@jest
I:\playground\issue-2053-master\node_modules\babel-jest
I:\playground\issue-2053-master\node_modules\babel-preset-jest
I:\playground\issue-2053-master\node_modules\jest
I:\playground\issue-2053-master\node_modules\.bin\jest
I:\playground\issue-2053-master\node_modules\jest\node_modules\.bin\jest

xap-prod-svc-web is the project I am working on. issue-2053-master is your sample.

**Comment by JonathanYates** [comment] 2019-04-17 09:56
I've also run the same on c:\ with the following results

C:\Users\E853065\AppData\Local\Microsoft\TypeScript\3.3\node_modules\@types\jest
C:\Users\E853065\AppData\Local\Microsoft\TypeScript\3.4\node_modules\@types\jest

**Comment by ArtemGovorov** [comment] 2019-04-17 23:46
Thanks for providing the details.

Could you please add the `debug` flag to your [sample project Wallaby config](https://github.com/wallabyjs/issue-2053/blob/master/wallaby.js):

```diff
module.exports = function(wallaby) {
  return {
    files: [
      "src/**/*.js",
      "src/**/*.jsx",
      "!src/**/*.spec.js",
      "!src/**/*.spec.jsx"
    ],
    tests: ["src/**/*.spec.js", "src/**/*.spec.jsx"],
    env: {
      type: "node",
      runner: "node"
    },
    testFramework: "jest",
+   debug: true
  };
};
```

then run Wallaby and attach the full output from Wallaby Console output channel in VS Code?

**Comment by JonathanYates** [comment] 2019-04-18 07:44
With debug: true the output is:

[Info]  Thu, 18 Apr 2019 07:42:20 GMT wallaby:project Wallaby config: I:\playground\issue-2053-master\wallaby.js
[Info]  Thu, 18 Apr 2019 07:42:20 GMT wallaby:fs File added: package.json
[Info]  Started Wallaby.js Core v1.0.677
[Info]  Thu, 18 Apr 2019 07:42:20 GMT wallaby:fs File added: src/source.spec.js
[Info]  Thu, 18 Apr 2019 07:42:20 GMT wallaby:fs File added: src/source.js
[Info]  Thu, 18 Apr 2019 07:42:20 GMT wallaby:project File cache: I:\software\VSCode-win32-x64-1.33.1\data\extensions\wallabyjs.wallaby-vscode-1.0.123\projects\03a6a491315b8890
[Info]  Thu, 18 Apr 2019 07:42:21 GMT wallaby:uiService Listening port 51235
[Info]  Thu, 18 Apr 2019 07:42:21 GMT wallaby:project Config file change detected, invalidating local cache
[Info]  Wallaby App (realtime reports) is available at: http://localhost:51245
[Info]  Thu, 18 Apr 2019 07:42:21 GMT wallaby:workers Parallelism for initial run: 6, for regular run: 3
[Info]  Thu, 18 Apr 2019 07:42:21 GMT wallaby:workers Starting run worker instance #0
[Info]  Thu, 18 Apr 2019 07:42:21 GMT wallaby:workers Starting run worker instance #1
[Info]  Thu, 18 Apr 2019 07:42:21 GMT wallaby:workers Starting run worker instance #2
[Info]  Thu, 18 Apr 2019 07:42:21 GMT wallaby:workers Starting run worker instance #3
[Info]  Thu, 18 Apr 2019 07:42:21 GMT wallaby:workers Starting run worker instance #4
[Info]  Thu, 18 Apr 2019 07:42:21 GMT wallaby:workers Starting run worker instance #5
[Info]  Thu, 18 Apr 2019 07:42:21 GMT wallaby:workers Web server is listening at 58307
[Info]  Thu, 18 Apr 2019 07:42:21 GMT wallaby:project File cache requires some updates, waiting required files from IDE
[Info]  Thu, 18 Apr 2019 07:42:24 GMT wallaby:project File package.json changes are patches only: false
[Info]  Thu, 18 Apr 2019 07:42:24 GMT wallaby:project File src/source.js changes are patches only: false
[Info]  Thu, 18 Apr 2019 07:42:24 GMT wallaby:project Preparing to process package.json
[Info]  Thu, 18 Apr 2019 07:42:24 GMT wallaby:project Starting processor pool (if not yet started)
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project File package.json is not instrumented by core
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project Preparing to process src/source.js
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project Starting processor pool (if not yet started)
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:workers Started run worker instance (delayed) #0
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:workers Started run worker instance (delayed) #2
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:workers Started run worker instance (delayed) #1
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:workers Started run worker instance (delayed) #3
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:workers Started run worker instance (delayed) #4
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:workers Started run worker instance (delayed) #5
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:processor No compilers found for src/source.js
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:processor Running 1 processor(s) for package.json
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project Instrumenting src/source.js, via process pool: true
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:processor Finished running one processor for package.json
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project Writing to disk and caching processed file package.json
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project File package.json changes saved, store ts: 1554852302000, change ts: 1555573344842
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:processor No preprocessors found for src/source.js
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project Writing to disk and caching processed file src/source.js
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project File src/source.js changes saved, store ts: 1554852302000, change ts: 1555573344843
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project File src/source.spec.js changes are patches only: false
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project Preparing to process src/source.spec.js
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project Starting processor pool (if not yet started)
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:processor No compilers found for src/source.spec.js
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project Instrumenting src/source.spec.js, via process pool: true
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:processor No preprocessors found for src/source.spec.js
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project Writing to disk and caching processed file src/source.spec.js
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project File src/source.spec.js changes saved, store ts: 1554852302000, change ts: 1555573349640
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project Stopping process pool
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project Running postprocessor
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:postprocessor New TypeScript language service is required
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:postprocessor TypeScript postprocessor will be removed because in 3 project files none were found by patterns: **/*.ts?(x)
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project Postprocessor execution finished
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project Postprocessor is removed as requested by itself
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project Test run started; run priority: 3
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:project Running all tests
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:workers Starting test run, priority: 3
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #lfxm1]
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #lfxm1]
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #lfxm1]
[Info]  Thu, 18 Apr 2019 07:42:29 GMT wallaby:workers [worker #0, session #lfxm1] Running tests in sandbox
[Info]  Thu, 18 Apr 2019 07:42:38 GMT wallaby:workers Sandbox (active) [lfxm1] error: TypeError: Cannot read property '_jasmineAdapter' of undefined
[Error] Runtime error: TypeError: Cannot read property '_jasmineAdapter' of undefined 
[Error]     at Runtime._execModule (I:\playground\issue-2053-master\node_modules\jest-runtime\build\index.js:858:13) 
[Error]     at Runtime._loadModule (I:\playground\issue-2053-master\node_modules\jest-runtime\build\index.js:551:12) 
[Error]     at Runtime.requireModule (I:\playground\issue-2053-master\node_modules\jest-runtime\build\index.js:415:10) 
[Error]     at config.setupFilesAfterEnv.forEach.path (I:\playground\issue-2053-master\node_modules\jest-jasmine2\build\index.js:186:55) 
[Error]     at Array.forEach (<anonymous>) 
[Error]     at I:\playground\issue-2053-master\node_modules\jest-jasmine2\build\index.js:186:31 
[Error]     at Generator.next (<anonymous>) 
[Error]     at asyncGeneratorStep (I:\playground\issue-2053-master\node_modules\jest-jasmine2\build\index.js:27:24) 
[Error]     at _next (I:\playground\issue-2053-master\node_modules\jest-jasmine2\build\index.js:47:9) 
[Error]     at I:\playground\issue-2053-master\node_modules\jest-jasmine2\build\index.js:52:7 
[Error]     at new Promise (<anonymous>) 
[Error]     at I:\playground\issue-2053-master\node_modules\jest-jasmine2\build\index.js:44:12 
[Error]     at _jasmine (I:\playground\issue-2053-master\node_modules\jest-jasmine2\build\index.js:206:19) 
[Error]     at jasmine2 (I:\playground\issue-2053-master\node_modules\jest-jasmine2\build\index.js:60:19) 
[Error]     at I:\playground\issue-2053-master\node_modules\jest-runner\build\runTest.js:384:24 
[Error]     at Generator.next (<anonymous>) 
[Error]     at asyncGeneratorStep (I:\playground\issue-2053-master\node_modules\jest-runner\build\runTest.js:161:24) 
[Error]     at _next (I:\playground\issue-2053-master\node_modules\jest-runner\build\runTest.js:181:9) 
[Error]     at <anonymous> 
[Error]     at process._tickCallback (internal/process/next_tick.js:188:7) 
[Info]  Thu, 18 Apr 2019 07:42:38 GMT wallaby:workers Failed to map the stack to user code, entry message: TypeError: Cannot read property '_jasmineAdapter' of undefined, stack: TypeError: Cannot read property '_jasmineAdapter' of undefined
[Info]      at Object._jasmineAdapter (I:\software\VSCode-win32-x64-1.33.1\data\extensions\wallabyjs.wallaby-vscode-1.0.123\wallaby\runners\node\jest@0.4.3\jasmine2Initializer.js:14:2524)
[Info]      at Runtime._execModule (I:\playground\issue-2053-master\node_modules\jest-runtime\build\index.js:858:13)
[Info]      at Runtime._loadModule (I:\playground\issue-2053-master\node_modules\jest-runtime\build\index.js:551:12)
[Info]      at Runtime.requireModule (I:\playground\issue-2053-master\node_modules\jest-runtime\build\index.js:415:10)
[Info]      at Runtime.d._wallabyReplaced.c.requireModule (I:\software\VSCode-win32-x64-1.33.1\data\extensions\wallabyjs.wallaby-vscode-1.0.123\wallaby\runners\node\jest@0.4.3\initializer.js:14:25212)
[Info]      at config.setupFilesAfterEnv.forEach.path (I:\playground\issue-2053-master\node_modules\jest-jasmine2\build\index.js:186:55)
[Info]      at Array.forEach (<anonymous>)
[Info]      at I:\playground\issue-2053-master\node_modules\jest-jasmine2\build\index.js:186:31
[Info]      at 
[Info]  console.log: FAIL src/source.spec.js
[Info]  console.log:   ● Test suite failed to run
[Info]      TypeError: Cannot read property '_jasmineAdapter' of undefined
[Info]        at Object._jasmineAdapter (I:/software/VSCode-win32-x64-1.33.1/data/extensions/wallabyjs.wallaby-vscode-1.0.123/wallaby/runners/node/jest@0.4.3/jasmine2Initializer.js:14:2524)
[Info]        at Runtime.d._wallabyReplaced.c.requireModule (I:/software/VSCode-win32-x64-1.33.1/data/extensions/wallabyjs.wallaby-vscode-1.0.123/wallaby/runners/node/jest@0.4.3/initializer.js:14:25212)
[Info]            at Array.forEach (<anonymous>)
[Info]  Thu, 18 Apr 2019 07:42:38 GMT wallaby:workers [lfxm1] Run 0 test(s), skipped 0 test(s)
[Info]  Thu, 18 Apr 2019 07:42:38 GMT wallaby:workers [lfxm1] Sandbox is responsive, closing it
[Info]  Thu, 18 Apr 2019 07:42:38 GMT wallaby:project Test run finished
[Info]  Thu, 18 Apr 2019 07:42:38 GMT wallaby:project Processed console.log entries
[Info]  Thu, 18 Apr 2019 07:42:38 GMT wallaby:project Processed loading sequences
[Info]  Thu, 18 Apr 2019 07:42:38 GMT wallaby:project Processed executed tests
[Info]  Thu, 18 Apr 2019 07:42:38 GMT wallaby:project Processed code coverage
[Info]  Thu, 18 Apr 2019 07:42:38 GMT wallaby:project Test run result processed and sent to IDE

**Comment by ArtemGovorov** [comment] 2019-04-19 00:21
Thanks for providing the log. Unfortunately we can't see anything in the log that could be the reason for the issue. 

Could you please try the same sample project on some other disk/computer (outside of your C: and I: drives)?

**Comment by JonathanYates** [comment] 2019-04-24 15:12
Unfortunately I don't have another drive or pc at my workpace to try this on. I can only think this must be something unique to the setup there. I will clone my repo on my C: drive and try it from there.

**Comment by JonathanYates** [comment] 2019-04-25 08:14
The sample project works on c: as reported above. However I am now trying to run Wallaby against my real project. I'm not getting the above error but I am now getting other errors.

[Error] Some long running code has been detected: one of your files is taking more than 5000ms to execute. 
[Error] Execution of the following files has started but has not finished: 
[Error] - src/test/test-setup.js 

test-setup.js looks like this:

import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });

and also it is trying to run tests in files that are not part of my project that are part of jedt-cli.

[Error] Runtime error: Error: Your test suite must contain at least one test. 
[Error]     at C:\Users\E853065\dev\xap-prod-svc-web\xap-prod-svc-web-web\node_modules\jest-cli\build\TestScheduler.js:225:24

**Comment by smcenlly** [comment] 2019-04-25 22:58
Am I correct in assuming that your project is a mono-repo? You will need to exclude nested `node_modules` folders from both your wallaby `files` and `tests`. You will also need to update your `process.env.NODE_PATH` in your wallaby configuration file to include the nested `node_modules` paths. See an example below:

```javascript
module.exports = function (wallaby) {
  process.env.NODE_PATH = require('path').join(__dirname, 'xap-prod-svc-web-web', 'node_modules')
...
  return {
...
}
```

When using wallaby to run in a mono-repo, if all of your package versions aren't aligned then you can experience conflicts. The original error that you reported `Runtime error: TypeError: Cannot read property '_jasmineAdapter' of undefined #2` is an example of such a conflict.

If you're still having problems please send us a sample repo, we'd be happy to take a look.

**Comment by smcenlly** [comment] 2019-06-11 23:29
Closing this issue due to lack of activity.

**Closed** 2019-07-11 06:45 UTC
Labels: more info is required
