### ISSUE TITLE
Real Browser Support

### ISSUE THREAD

**Issue by mdoleh** [wallabyjs/public#213] opened 2015-07-25 00:10 UTC
My project typically runs our tests against Chrome, IE, and PhantomJS. It would be great if Wallaby.js supported running unit tests in actual browsers such as Chrome and IE. It would be even better if the feedback from the runner could specify which test runner failed a test. Perhaps a plugin system so developers can pick which browsers they would prefer to run against to better suit their needs.

**Comment by ArtemGovorov** [comment] 2015-07-25 00:40
Thanks for the suggestion. Closing this one as a duplicate of https://github.com/wallabyjs/public/issues/29

**Closed by ArtemGovorov** 2015-07-25 00:40 UTC
Labels: duplicate
