### ISSUE TITLE
`Failed to load configuration file` not informative enough

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#1427] opened 2017-12-09 17:07 UTC
**Failing tests**

```
elsee is not defined
```

**Wallaby console**

```
wallaby.js started
core v1.0.528
Failed to load configuration file:  elsee is not defined
```

---

The only way I could find the error was to search my codebase for `elsee`. Turns out it was a type in a file that was required at the top of `wallaby.js`.

Can we print a stack trace?

**Comment by ArtemGovorov** [comment] 2017-12-10 03:52
We are printing the stack trace when it's possible. Just tried to reproduce the case as you have described using the calculator sample and requiring `other.js` file with an error in it, the stack is displayed:

<img width="743" alt="screen shot 2017-12-10 at 1 48 27 pm" src="https://user-images.githubusercontent.com/979966/33801758-e04013c2-ddb0-11e7-81c6-2a32ddba74b6.png">

Could you please share a repro (wallaby config file and a failing dependency should be enough), and share your node.js version (if you are overriding the wallaby default one in your Wallaby Run configuration).

**Comment by vjpr** [comment] 2017-12-10 09:44
I should have mentioned that its a plugin in the babel compiler.

```
compilers: {
  '*.js': wallaby.compilers.babel({babel: require('babel-core'), babelrc: false, plugins: [require('a-plugin-with-syntax-error')]})
}
```

**Comment by ArtemGovorov** [comment] 2017-12-11 02:33
Still can't reproduce it with the exact module depenency:

<img width="732" alt="screen shot 2017-12-11 at 12 19 24 pm" src="https://user-images.githubusercontent.com/979966/33813405-4f87309e-de6f-11e7-8371-bbddd3b434bc.png">

Could you please share a repro?

**Comment by vjpr** [comment] 2018-05-28 11:52
I'm getting a similar error now:

```
Failed to load configuration file:  undefined
```

Seems like it happens when I am using `require('@babel/register')` in my wallaby.js file.

**Comment by ArtemGovorov** [comment] 2018-05-28 22:35
> Seems like it happens when I am using `require('@babel/register')` in my wallaby.js file.
> It used to work when I was running `babel@7.0.0-beta.46`, but now with 49 it doesn't.


@vjpr Here's what I've tried:

- installed `babel@7.0.0-beta.49`,
- created wallaby config that just loads `@babel/register` and throws an error.

and it seems to be working as expected (printing the stack trace):

<img width="716" alt="screen shot 2018-05-29 at 8 26 54 am" src="https://user-images.githubusercontent.com/979966/40630973-f356f4cc-631a-11e8-8c27-f0f874e6615d.png">

I'm clearly missing something, any ideas on what you may be doing differently?

**Comment by vjpr** [comment] 2018-05-28 22:43
@ArtemGovorov Sorry, added info to my previous comment as I debugged it more.

The error occurs if your babel preset throws an error.

_wallaby.js_

```
require('@babel/register')({preset: [require.resolve('./my-preset')]})

require('./bar')
```

_my-preset.js_

```
boom;

// or

throw new Error('foo')
```

_my-wallaby-config.js_

```
console.log('bar')
```

In my case, my preset was symlinked in a lerna monorepo, but I'm pretty sure `require.resolve()` would cause it too.

It's rare, because not many people would use a custom js preset I guess.

**Comment by ArtemGovorov** [comment] 2018-05-28 23:08
@vjpr Tried this:

```js
require('@babel/register')({presets: [require.resolve('./my-preset')]})
require('./bar')
```

still getting a good stack trace:

```
ReferenceError: boom is not defined
    at Object.<anonymous> (/Users/artemgovorov/WebstormProjects/wallaby-1674/my-preset.js:1:1)
    at Module._compile (module.js:624:30)
    ... babel/wallaby/node stack ...
    at Object.<anonymous> (/Users/artemgovorov/WebstormProjects/wallaby-1674/wallaby.js:2:1)
```

**Comment by smcenlly** [comment] 2020-10-08 23:47
Closing this issue out as the original issue was resolved.

**Closed by smcenlly** 2020-10-08 23:47 UTC
Labels: more info is required, reproducible example is required
