### ISSUE TITLE
Support browserify

### ISSUE THREAD

**Issue by aulizko** [wallabyjs/public#27] opened 2015-03-01 08:47 UTC
Hi!
So far, wallaby looks awesome to me. Nice work!
Still, I have some problems with browserified tests. It looks like wallaby cannot detect what source files are involved in test, although source maps are created and provided. 
I'm not sure did I wrote wrong configuration file for wallaby, or what. 

#### Here are dummy project configuration.

Project structure: 

```
.
├── package.json
├── src
│   └── string-utils.js
├── test
│   └── string-utils-test.js
└── wallaby.js
```

Wallaby configuration file (./wallaby.js) content: 

```javascript
var path = require('path');
var browserify = require('browserify');
var convert = require('convert-source-map');

module.exports = function (wallaby) {
    return {
        files: [
            {pattern: 'src/**/*.js', load: false}
        ],

        tests: [
            'test/**/*-test.js'
        ],

        preprocessors: {
            'test/**/*-test.js': (file, done) => {
                var resultFile = {
                    code: ''
                };

                browserify(
                    path.resolve('./', file.path),
                    {
                        commondir: wallaby.localProjectDir,
                        basedir: wallaby.localProjectDir,
                        debug: true // enable sourcemaps
                    })
                    .bundle()
                    .on('data', buf => {
                        resultFile.code += buf.toString();
                    })
                    .on('error', err => done(err))
                    .on('end', () => {
                        var sourceMapConverter = convert.fromSource(resultFile.code);
                        if (sourceMapConverter) {
                            sourceMapConverter.setProperty('sourceRoot', wallaby.localProjectDir);
                            resultFile.map = sourceMapConverter.toJSON();
                        }

                        done(resultFile);
                    });
            }
        },

        testFramework: 'mocha@2.0.1',

        bootstrap: function (innerScopeWallaby) {
            innerScopeWallaby.testFramework.setup('bdd');
        },

        debug: true
    };
};
```

Test file (./test/string-utils-test.js) content: 

```javascript
var StringUtils = require('../src/string-utils.js');
var chai = require('chai');
var expect = chai.expect;

describe('StringUtils', function () {
    describe('#truncate()', function () {
        it('should left too short string untouched', function () {
            expect(StringUtils.truncate('short string', 100)).to.equal('short string');
        });
    });
});
```

Source file (./src/string-utils.js) content: 

```javascript
module.exports = {
    truncate: function (inputString, limit, useWordBoundary) {
        return inputString;
    }
};
```

Wallaby console output: 

```
wallaby.js started
Sun, 01 Mar 2015 07:13:08 GMT project File cache: /Users/aulizko/Library/Caches/WebStorm9/wallaby/projects/wallaby-test_wallaby
Sun, 01 Mar 2015 07:13:10 GMT project Parallelism for initial run: 2, for regular run: 2
Sun, 01 Mar 2015 07:13:10 GMT project Starting run worker instance #0
Sun, 01 Mar 2015 07:13:10 GMT project Starting run worker instance #1
Sun, 01 Mar 2015 07:13:10 GMT project Web server is listening at 29740
Sun, 01 Mar 2015 07:13:10 GMT project File cache requires some updates, waiting required files from IDE
Sun, 01 Mar 2015 07:13:10 GMT project File test/string-utils-test.js changes are patches only: false
Sun, 01 Mar 2015 07:13:10 GMT project Starting processor pool (if not yet started)
Sun, 01 Mar 2015 07:13:10 GMT project Instrumenting test/string-utils-test.js, via process pool: true
Sun, 01 Mar 2015 07:13:13 GMT project Running 1 preprocessor(s) for test/string-utils-test.js
Sun, 01 Mar 2015 07:13:17 GMT project File test/string-utils-test.js changes saved
Sun, 01 Mar 2015 07:13:17 GMT project Stopping process pool
Sun, 01 Mar 2015 07:13:17 GMT project Test run started; run priority: 3, tests (may have duplicates): 0
Sun, 01 Mar 2015 07:13:17 GMT project Running all tests
Sun, 01 Mar 2015 07:13:17 GMT project Starting test run, priority: 3
Sun, 01 Mar 2015 07:13:17 GMT project Starting sandbox [worker #0, session #ra94k]
Sun, 01 Mar 2015 07:13:17 GMT project Preparing sandbox [worker #0, session #ra94k]
Sun, 01 Mar 2015 07:13:17 GMT project Total files to load in sandbox: 2
Sun, 01 Mar 2015 07:13:17 GMT project Sandbox is generated [worker #0, session #ra94k]
Sun, 01 Mar 2015 07:13:17 GMT project Started run worker instance (immediate) #0
Sun, 01 Mar 2015 07:13:17 GMT project Creating page for worker #0
Sun, 01 Mar 2015 07:13:17 GMT project Started run worker instance (immediate) #1
Sun, 01 Mar 2015 07:13:17 GMT project Phantom page created
Sun, 01 Mar 2015 07:13:17 GMT project Prepared sandbox [worker #0, session #ra94k]
Sun, 01 Mar 2015 07:13:17 GMT project Running tests in sandbox [worker #0, session #ra94k]
Sun, 01 Mar 2015 07:13:17 GMT project Preparing to serve /Users/aulizko/Library/Caches/WebStorm9/wallaby/wallaby/tracer.js
Sun, 01 Mar 2015 07:13:17 GMT project Serving /Users/aulizko/Library/Caches/WebStorm9/wallaby/wallaby/tracer.js from disk
Sun, 01 Mar 2015 07:13:17 GMT project Preparing to serve /mocha@2.0.1/framework.js
Sun, 01 Mar 2015 07:13:17 GMT project Serving /mocha@2.0.1/framework.js from disk
Sun, 01 Mar 2015 07:13:17 GMT project Preparing to serve /mocha@2.0.1/configurator.js
Sun, 01 Mar 2015 07:13:17 GMT project Serving /mocha@2.0.1/configurator.js from disk
Sun, 01 Mar 2015 07:13:17 GMT project Preparing to serve /mocha@2.0.1/starter.js
Sun, 01 Mar 2015 07:13:17 GMT project Serving /mocha@2.0.1/starter.js from disk
Sun, 01 Mar 2015 07:13:17 GMT project Preparing to serve /mocha@2.0.1/reporter.js
Sun, 01 Mar 2015 07:13:17 GMT project Serving /mocha@2.0.1/reporter.js from disk
Sun, 01 Mar 2015 07:13:17 GMT project Preparing to serve /test/string-utils-test.js
Sun, 01 Mar 2015 07:13:17 GMT project Serving /test/string-utils-test.js from cache
Sun, 01 Mar 2015 07:13:17 GMT project Loaded 1 test(s)
Sun, 01 Mar 2015 07:13:17 GMT project Test executed: should left too short string untouched
Sun, 01 Mar 2015 07:13:17 GMT project Run 1 test(s), skipped 0 test(s)
Sun, 01 Mar 2015 07:13:18 GMT project Sandbox [ra94k] is responsive, closing it
Sun, 01 Mar 2015 07:13:18 GMT project Test run finished
Test without test file id, most likely the test did not run { testFileIdCanNotBeDetermined: 'should left too short string untouched',
  id: 100001,
  log: undefined,
  filesInvolved: [] }
Sun, 01 Mar 2015 07:13:18 GMT project Test run result processed and sent to IDE
```

And here is what browserify transformation outputs: [http://pastebin.ru/Q7T93MpU](http://pastebin.ru/Q7T93MpU).

It does have "code" and "map" properties, so it should work. I hope ;)

Any advices?

**Comment by ArtemGovorov** [comment] 2015-03-01 10:08
Hi, 

Thanks for your kind words and for the provided detailed sample!

Bundlers like browserify (and webpack https://github.com/wallabyjs/public/issues/9) are not yet supported. I have updated our roadmap on our [website](http://wallabyjs.com/#plans) to indicate that the support is planned.

The source map in your sample is generated correctly, but the issue is that when in the preprocessor browserify is invoked, it reads original source files, not instrumented content of the files, so coverage and other essential wallaby services don't work. There're a few more other issues we need to solve before making it work.

We are looking into implementing the support of browserify (and webpack). I'll post some update in the issue once we make the support available.

Quick question - are you using both browserified tests and non browserified tests in your application?

**Comment by jeffling** [comment] 2015-03-01 10:17
^ that's exactly the problem I'm having with wallaby-webpack. Does this mean it's blocked by wallaby and I can relax now? 

Also: for your future plans, are you planning to have support baked-in or available as third party plugins?

**Comment by ArtemGovorov** [comment] 2015-03-01 10:23
@jeffling from what I can see now, some issues can already be solved from preprocessor/config, but not all of them unfortunately, so wallaby core changes are required. 

The plan is to solve core issues, preventing working with module bundlers, perhaps expose some additional API as well, and let (and help by committing to) third party plugins (such as the one you have started) and config writers to do the rest.

**Comment by aulizko** [comment] 2015-03-01 10:29
> Quick question - are you using both browserified tests and non browserified tests in your application?

In fact, I do. 
Code that will run on the client side are browserified (so are tests for that code, too). 
And  code for server-side (node.js environment) are not browserified.

Actually, that is the question I want to ask: is there a way to implement more than one environment for tests?

Btw, there are another problem with browserify and es6-to-es5 transforms: 
When I wrote both test and source files in es6, wallaby's parser throws syntax errors on source files (test files are preprocessed with browserify+babelify), so I need to introduce another preprocessor for source files (tried it with babelify, but I plan to use some transformations for templating etc.). 
But it looks quite strange for me: when I transform es6 source files with babel, it generates it's own source map and result of that transformation is not envolved at browserify transform of the test file. 
I mean, wallaby should at first run preprocessor on the source file, and then browserify should use that result of preprocessor, not the original file, in order to utilize souce maps correctly. 

As far as I can see, most likely, you should provide your own version of the require() method, which will replace the one that comes with browserify. If you need any help with that - I'll be glad to help.

**Comment by ArtemGovorov** [comment] 2015-03-01 10:48
@aulizko Yep, you can use 2 (or more) configuration files and have 2 wallaby Run Configurations running at the same time in WebStorm (or IDE you're using). If there's a common part between those two config files, you can put it the third files, and require(...) it from both config files.

You have exactly described one of the issues we are having - browserify is not using wallaby generated content, but reads not yet modified content from disk.

If I get your idea correctly, you are probably right that we can try just changing require() method implementation (and module.exports as well) with simple mocks (remembering and returning remembered stuff). In this case we won't need browserify at all for tests! And everything should perfectly work, even without any wallaby changes, unless I missed something. That's one of the approaches we can try to evaluate and your help is appreciated.

**Comment by ArtemGovorov** [comment] 2015-03-01 10:59
@jeffling @aulizko  As a matter of fact, we could try something like that for webpack as well. Instead of trying to use the bundler where it's awesomeness is not really required (in tests), we can just support the syntax it supports: commonJs, AMD (etc flavours) and write simple mocks for the syntax. The mocks will be included in the list of files and will provide the simple infrastructure to export and load everything when require is called.

It can even be one project, supporting both browserify and webpack. I may be missing some details, as I haven't worked much neither with browserify nor with webpack. Such as details how browserify handles special cases like __dir/__filename, node globals etc., or webpack specific APIs like require.ensure etc. But it still seems feasible. 

Your thoughts guys?

**Comment by ArtemGovorov** [comment] 2015-03-01 11:05
More I think about it, more I like it. No bundler specific hacks, clean and simple, one test/source file per files, efficient existing wallaby caching without involving a bundler middleware/stateful instances. Unless I'm missing something fundamental.

**Comment by aulizko** [comment] 2015-03-01 11:22
@ArtemGovorov I think that's great idea. 
And it would work smoothly at most scenarios. 
Yet, still, there are fundamental problems with "transforms" that games with bundlers. 

Just as an example: 
With browserify, I can write some widget that (somewhere in the `render` function) does `var template = require('template.hbs')` and expects to receive valid js function, that allows to do something like `template(data);`. 

I think, it's far from wallaby's field of responsibility to mock all that transformations that come with bundlers. In the end, it's easier to somehow intercept the inner `require` work of the bundlers, than to endlessly mock their plugins. 
I propose do some instrumentation/patching for a few named bundlers, like browserify. 
In fact, with browserify, I see an opportunity to use it's internal pipeline and intervene into the process of the building of the result file: [https://github.com/substack/node-browserify#bpipeline](https://github.com/substack/node-browserify#bpipeline)

And yet, that kind of things still needs to be tested in browser environment.

**Comment by jeffling** [comment] 2015-03-01 11:31
I don't know if it would work with all those loaders and transforms that are webpack/browserify specific. There are many features like lazy-loaded code splits and so on that might be hard to mock.

**Comment by ArtemGovorov** [comment] 2015-03-01 12:18
Got it, thanks, will keep thinking about other approaches.
Patching a bundler may get us there, but some core changes will still be required if several files end up in one bundle because a few wallaby parts, such as caching, stack processing, line mapping, etc. currently assume one to one file transformations and may break on many to one (bundle) type of transformations.

**Comment by ArtemGovorov** [comment] 2015-03-14 05:50
Just sharing some progress:

I'm working on the solution for browserify and webpack. Agreeing with both of you that wallaby should try to interfere as less as possible with a bundler work, as @aulizko suggested, I'm extending bundler internal pipeline to allow a bundler and all of its transformers/loaders/plugins to do their work.

Apart from integrating to get the required data, pipeline extension will have to change one aspect of a bundler work - it will prevent bundler from actual concatenation of files. Wallaby.js will get the order of files from the bundler, and will generate a correct sequence of script tags instead. 

As PhantomJs (and other browsers that we'll add a support for in future) cache on the file basis, this will be more performant solution than in Karma integrations, because browser will only have to fetch changed files from the wallaby server and not the whole bundle. In Karma it's not that critical, as it runs all tests and time savings of not loading the whole bundle may not be too significant comparing to the full test run time. In wallaby.js world however, we'd like to save every single millisecond, as we run only minimal set of tests on each code change.

Like in Karma integrations of browserify and webpack, wallaby integrations will cache the bundler instance to leverage its caching for fast re-bundles.

So basically the idea is to allow a bundler do everything it is configured to, except files concatenation. Files wrapping way and implementation of 'require' will also be taken from the module bundler (with some patching). It's essentially going to be something similar to what https://www.npmjs.com/package/factor-bundle in browserify and CommonsChunkPlugin in webpack do, but with a bit deeper integration with a bundler.

How does the plan sound? Are there any drawbacks of the plan that you can see? Partial prototype for browserify seems to be working ok, but I'm yet to test lots more things.

As I have said before, wallaby.js core changes are required to expose the API for integrations. The integration projects will be open sourced. I have started this project https://github.com/wallabyjs/wallabify for browserify integration and will start committing to the https://github.com/jeffling/wallaby-webpack project for webpack once I have stuff to commit.

**Comment by ArtemGovorov** [comment] 2015-03-20 02:35
I think I have got something working for browserify, could you please recommend an OSS project or projects using browserify with significant number tests so that I could test my solution?

**Comment by ArtemGovorov** [comment] 2015-03-26 07:49
Everyone is welcome to try the first version of browserify support: https://github.com/wallabyjs/wallabify

**Closed by ArtemGovorov** 2015-03-26 07:49 UTC
Labels: enhancement, in progress
