### ISSUE TITLE
Wallaby doesn't output anything in "Failing Tests"

### ISSUE THREAD

**Issue by DenisGorbachev** [wallabyjs/public#203] opened 2015-07-15 13:43 UTC
https://github.com/fixin-platform/backend-freshdesk/commit/afbba65b172d94eb3a7684e8281be4ab049761f8

The tests fail, obviously — but Wallaby doesn't output anything in "Failing Tests", and doesn't display code coverage:

![no-nothing](https://cloud.githubusercontent.com/assets/829578/8699770/87e7a596-2b10-11e5-8643-3b01d64b0445.png)

**Comment by ArtemGovorov** [comment] 2015-07-16 00:29
Can't reproduce the issue. I'm getting this when running tests for the commit:

<img width="822" alt="screen shot 2015-07-16 at 10 24 43 am" src="https://cloud.githubusercontent.com/assets/979966/8712901/47239566-2ba5-11e5-8496-e59dab7d3418.png">

Though I had to exclude DB tests that are also failing (because I don't have the DB deployed). Is the issue reproducible without the DB tests?

What is displayed in the Wallaby Console in this case?

**Comment by DenisGorbachev** [comment] 2015-07-16 16:52
Here's Wallaby console output: https://gist.github.com/DenisGorbachev/b0cc8764fb1bcd4e97d7

Without DB tests I'm getting the same error, so the issue doesn't reproduce without them. Do you need any assistance with setting up PostgreSQL?

**Comment by ArtemGovorov** [comment] 2015-07-16 22:52
> Do you need any assistance with setting up PostgreSQL?

That'd be awesome, thanks. I have installed PostgreSQL on OSX, but stuck trying to create the required environment. Do you have a script that creates everything required for the application/tests (db, user with correct credentials and permissions, etc.) that I could run?

**Comment by DenisGorbachev** [comment] 2015-07-17 15:37
Actually, I just did it by hand... Would you like to hop on a Skype call (ID: faster-than-wind), so that I could guide you through the process? (the commands may be different on OSX, plus who knows what else may be required to reproduce the issue)

**Comment by ArtemGovorov** [comment] 2015-07-18 00:46
I'll try again over the weekend and if I fail I'll try to reach you next week on Skype. I'm at GMT +10, are you somewhere around GMT +3?

**Comment by DenisGorbachev** [comment] 2015-07-18 06:25
That's right, GMT +3. Looking forward!

**Comment by DenisGorbachev** [comment] 2015-07-18 11:05
https://github.com/fixin-platform/backend-core/commit/61292538ddb8044ed2533f9d5886798415ddac3b

No DB tests, same issue. This time, Wallaby doesn't report any errors in console, but keeps the spinning indicator in the bottom-right corner of WebStorm. To reproduce, put https://gist.github.com/DenisGorbachev/4bbf3537b8e2dff43791 in test/config/dependencies.json.

**Comment by DenisGorbachev** [comment] 2015-07-18 11:17
https://github.com/fixin-platform/backend-core/commit/7301fa482e2f47e644abfd3edbcd7d8fef2a0b3f "fixed" it — Wallaby outputs an error for another test.

To recap:
https://github.com/fixin-platform/backend-core/commit/61292538ddb8044ed2533f9d5886798415ddac3b — Wallaby outputs nothing.
https://github.com/fixin-platform/backend-core/commit/4de24cec0c99ef5a0d0b91f42b435e1aa955e023 — Wallaby outputs nothing.
https://github.com/fixin-platform/backend-core/commit/7301fa482e2f47e644abfd3edbcd7d8fef2a0b3f — Wallaby outputs an error (that's expected).

**Comment by ArtemGovorov** [comment] 2015-07-20 03:12
Awesome, thanks! The issue should be fixed now in core v1.0.81 and IntelliJ plugin v1.0.25. It was a combination of CoffeeScript compiler generated source maps and the way wallaby maps console.log messages.

**Closed by ArtemGovorov** 2015-07-20 03:12 UTC

**Comment by DenisGorbachev** [comment] 2015-07-20 19:58
Thank you, Artem!
