### ISSUE TITLE
Is it possible to use Wallaby with `shelfio/jest-mongodb`?

### ISSUE THREAD

**Issue by smeijer** [wallabyjs/public#2291] opened 2019-12-10 09:39 UTC
### Question; using Wallaby with `jest` + `jest-mongodb`

I'm using `Jest >= v24`, and thereby switched to Automatic configuration. One thing that I cannot get working though, (also not with manual config), is support for `jest-mongodb`.

The initial run works fine. All lights turn up green, but after coding a bit, they all turn grey because an error is thrown:

```
MongoDB instance already in status startup/running/error. 
Use opts.debug = true for more info.
```

Jest watch mode works fine, so it looks like something in Wallaby that triggers this.

A basic test to confirm the behavior:

```js
let connection;
let collection;

beforeAll(async () => {
  connection = await mongo.connect(process.env.MONGO_URL || '', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });

  const db = await connection.db();
  collection = db.collection('users');
});

afterEach(async () => {
  await collection.removeMany({});
});

afterAll(async () => {
  await connection.close();
});

test('insert', async () => {
  const { result } = await collection.insertOne({ foo: 'bar' });
  expect(result.ok).toEqual(1);
});
```

The lights are easily turned off, by adding a second test. Anything, the change of the test file itself throws the error I've pasted above.

Using the latest wallaby, `jest: 24.9.0`, `@shelf/jest-mongodb: 1.1.3` and `mongodb: 3.3.5`. Configured and installed conform official docs: https://jestjs.io/docs/en/mongodb

**Comment by smcenlly** [comment] 2019-12-10 23:02
By default, Wallaby runs your tests in parallel and re-uses node processes between test runs. It looks like this is causing some problems when using mongodb. You may want to try setting your [Wallaby workers properties](https://wallabyjs.com/docs/config/workers.html) to:

```
"workers": {
       "initial": 1,
       "regular": 1,
       "restart": true
     }
```

The **initial** numeric property specifies the number of parallel processes to use to run your tests when your start/restart wallaby.js.

The **regular** numeric property specifies the number of parallel processes to use to run your tests every time your code changes.

The **restart** boolean property determines whether wallaby.js should restart workers. (When set to true, wallaby.js will restart processes for each run; When set to false, wallaby.js will forever keep using processes that were started once, relying on your test cleanup code). The property is only applicable in a node.js environment, as in the browser environment wallaby.js reloads the page anyway.

--

Since you are using automatic configuration you may either create a wallaby.js configuration file:

**Wallaby.js**
```javascript
module.exports = () => ({
   autoDetect: true,
   workers: {
      initial: 1,
      regular: 1,
      restart: true
   }
});
```

or you may use wallaby section in your package.json file to configure Wallaby.js:

**package.json**
```
{
  "name": "...",
  ...
  
  "dependencies": {
    ...
  },
  
  "devDependencies": {
    ...
  },
  
  ...
  
  "wallaby": {
    "workers": {
      "initial": 1,
      "regular": 1,
      "restart": true
    }
  }
}
```

**Comment by smcenlly** [comment] 2019-12-15 22:16
Closing this issue, assuming that our response solved the problem. If not, let us know.

**Closed by smcenlly** 2019-12-15 22:16 UTC

**Comment by smeijer** [comment] 2019-12-17 13:42
Not really solved, as `restart` makes it uncomfortably slow. But I understand your point, and believe it then must be fixed in `jest-mongodb` instead of in wallaby. I'll report it there.

**Comment by smcenlly** [comment] 2019-12-18 00:24
@smeijer - we took at look at the source code for `@shelf/jest-mongodb` and can see where the problem lies. We also have a work around for you. `@shelf/jest-mongodb` expects processes to be terminated after running jest tests (which is not always going to be the case if using Jest's API, and certainly is not for Wallaby.js). Basically, their [teardown logic](https://github.com/shelfio/jest-mongodb/blob/master/teardown.js#L5) also needs to be included in their [setup logic](https://github.com/shelfio/jest-mongodb/blob/master/setup.js#L11) (as teardown is not guaranteed to run).

You may workaround the issue by configuring a `globalSetup` file in your jest configuration:

**globalSetup.js**
```javascript
const setup = require('@shelf/jest-mongodb/setup');

module.exports = async () => {
  if (global.__MONGOD__) {
    try {
      await global.__MONGOD__.stop();
    } catch (err) {}
  }
  return setup();
};
```

**jest.config.js**
```javascript
module.exports = {
  globalSetup: '<rootDir>/globalSetup.js',
  preset: '@shelf/jest-mongodb',
};
```

If you'd like to suggest a fix to the `@shelf/jest-mongodb` repo, the lines of code preceding the `setup()` function in `globalSetup.js` need to be added to `https://github.com/shelfio/jest-mongodb/blob/master/setup.js`.

**Comment by smeijer** [comment] 2019-12-18 11:38
Thanks, that's definitely useful and a good start. 

However to keep the instant feedback experience that wallaby usually offers, I think we should somehow try to keep the Mongo instance running (/reuse the current instance) , as restarting it is time consuming.

Database restore can be done in an `afterEach`, and is way faster than restarting Mongo.

**Comment by smcenlly** [comment] 2019-12-18 22:54
@smeijer - the time to run changes was very fast when running with the code that I sent you. Is it not fast for you? You should be able to use a similar approach to what we provided and set up a `global` variable (similar to `if (global.__MONGOD__) {`) and not run the restart logic. If you update to only start once, please share your code in this issue to help others in the future.

**Comment by kaminskypavel** [comment] 2021-10-20 22:54
Hi @smcenlly thanks for the suggestions, I've tried it and _almost_ got it working,

Integrated **[globalSetup.js](globalSetup.js)** and even tried to limit the [workers to 1](https://github.com/kaminskypavel/mongo-doc-versioning/blob/d57f0a40411cf053910f534fe16b086ce75374ae/package.json#L24) as you suggested

here's what im getting in the console :

```
‍​[Info]​ Started Wallaby.js Core v1.0.1168
​[Info]​ console.warn: Possibly incompatible/unsupported Jest version (D:\devl\mongo-doc-versioning\node_modules\jest-resolve\build\defaultResolver.js)
​[Info]​ console.info: check if mongo runing ⚡⚡⚡
​[Info]​ console.warn: Possibly incompatible/unsupported Jest version (D:\devl\mongo-doc-versioning\node_modules\jest-resolve\build\defaultResolver.js)
​[Info]​ console.log: Jest: PASS src/index.spec.ts
​[Info]​ Finished executing 1 affected test(s) in 4.15 second(s)
​[Info]​ console.warn: Possibly incompatible/unsupported Jest version (D:\devl\mongo-doc-versioning\node_modules\jest-resolve\build\defaultResolver.js)
​[Info]​ console.info: check if mongo runing ⚡⚡⚡
​[Info]​ [2h3z6] Global Setup and Teardown is not complete, waiting for 5000ms before recycling worker
​[Info]​ console.warn: Possibly incompatible/unsupported Jest version (D:\devl\mongo-doc-versioning\node_modules\jest-resolve\build\defaultResolver.js)
​[Info]​ console.warn: Possibly incompatible/unsupported Jest version (D:\devl\mongo-doc-versioning\node_modules\jest-resolve\build\defaultResolver.js)
​[Info]​ console.info: check if mongo runing ⚡⚡⚡
​[Info]​ [jz726] Global Setup and Teardown is not complete, waiting for 5000ms before recycling worker
​[Info]​ console.warn: Possibly incompatible/unsupported Jest version (D:\devl\mongo-doc-versioning\node_modules\jest-resolve\build\defaultResolver.js)
​[Info]​ console.warn: Possibly incompatible/unsupported Jest version (D:\devl\mongo-doc-versioning\node_modules\jest-resolve\build\defaultResolver.js)
​[Info]​ console.info: check if mongo runing ⚡⚡⚡
​[Info]​ [kgfvh] Global Setup and Teardown is not complete, waiting for 5000ms before recycling worker
.............
.............

and it keeps on looping the same message
```

it looks like this particular if is skipepd 
```
    if (global.__MONGOD__) {
``` in **globalSetup.js**.


any idea what might cause this?
here's a [branch](https://github.com/kaminskypavel/mongo-doc-versioning/tree/wallaby-support) to reproduce this! 🤷‍♂️

**Comment by smcenlly** [comment] 2021-10-21 22:15
> do you think there's a way to speed up wallaby by removing

Yes - but based on the project that you provided, you're going to have to make a few code changes.

By default, Wallaby re-uses the processes that runs your tests. This is what makes subsequent test executions really fast. What you'll need to do is make your tests tolerant of the mongo db instance living forever, and across multiple processes using it at the same time.

When Wallaby runs your project, your configuration file is executed multiple times:
1. First the configuration file is loaded on first startup, and Wallaby determines from that, how many worker processes to use when your tests are executed
2. Wallaby also executes your configuration file within each worker process (that runs your tests).

So what you can do, in the context of (1): load mongo db, and in the context of (2): wait for mongo db to be loaded and then start tests.

The side effect of this is that mongo db will never be recycled so you would need to make sure that your tests are tolerant of:
a. Different spec files using the same mongo db instance at the same time
b. The same spec file executing twice against the same mongo db instance
c. "Cleanup" logic being tolerant of sometimes not being executed (e.g. if a test hangs or errors, Wallaby/Jest may not execute your cleanup logic).

Your project has issues with (b), and doesn't have any cleanup logic (c), but you could configure by creating a Wallaby.js configuration file:

**wallaby.js configuration file**
```javascript
const setup = require('@shelf/jest-mongodb/setup');
const fs = require('fs');

// Function to setup mongo db
async function setupMongo() {
  // Since this is asynchronous, we need to somehow tell worker
  // processes when the database has been started; use a marker
  // file to do this. 
  if (fs.existsSync('./wallabyMongo.json')) {
    fs.unlinkSync('./wallabyMongo.json');
  }
  await setup();

  // Write marker file once database is ready
  fs.writeFileSync('./wallabyMongo.json', JSON.stringify({}));
}

// On initial Wallaby start, check for environment variable
// and set it to true for subsequent worker processes to know
// not to start the database again.
if (!process.env.WALLABY_MONGO_INITIALIZED) {
  process.env.WALLABY_MONGO_INITIALIZED = true;
  setupMongo();
}

module.exports = function () {
  return {
    autoDetect: true,
    setup: async function () {
      // For worker processes, check for the existance of the
      // marker file so that they know it's safe to start.

      // If the marker file doesn't exist, wait for it to be
      // created
      const fs = require('fs');
      while (!fs.existsSync('./wallabyMongo.json')) {
        await new Promise(resolve => setTimeout(resolve, 100));
      }
    }
  };
};
```

**globalSetup.js**
```javascript
const setup = require('@shelf/jest-mongodb/setup');

module.exports = async () => {
    if (!process.env.WALLABY_MONGO_INITIALIZED) {
        console.info('check if mongo runing ⚡⚡⚡');

        if (global.__MONGOD__) {
            console.info('yes! MongoDB is running 🏃🏃🏃');
            try {
                console.info('stopping mongo 🛑🛑🛑');
                await global.__MONGOD__.stop();
            } catch (err) {
                console.info('ooooooooops error 😔😔', err);
            }
        }

        return setup();
    }
};
```

**jest.config.js**
```javascript
/** @type {import('ts-jest/dist/types').InitialOptionsTsJest} */
const { defaults: tsjPreset } = require('ts-jest/presets')

module.exports = {

  // https://github.com/wallabyjs/public/issues/2291
  globalSetup: '<rootDir>/globalSetup.js',

  // for ts-jest , since jest is not supporting multiple preset we do it manually 
  transform: tsjPreset.transform,
  // rootDir: './lib',
  // roots: ['<rootDir>'],
  moduleFileExtensions: ['ts', 'js', 'json', 'node'],

  // 
  preset: "@shelf/jest-mongodb",
  watchPathIgnorePatterns: [
    '<rootDir>/globalConfig.json',
    '<rootDir>/wallabyMongo.json',
  ]
};
```
