### ISSUE TITLE
wallabyjs stoppped running after java upgrade

### ISSUE THREAD

**Issue by lgandecki** [wallabyjs/public#2158] opened 2019-07-29 11:46 UTC
### Issue description or question

First click to run wallabyjs

13:43	Error running 'Unnamed': com.intellij.util.ui.EmptyIcon.create(I)Ljavax/swing/Icon;

Second click:

13:44	Error running 'Unnamed': Could not initialize class com.wallaby.javascript.j$a

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: [
      "src/**/*.js",
      "src/views/*.html",
      "config/config.json",
      "models/**.js",
      "models/**.ts",
      "src/**/*.ts",
      "src/**/*.json",
      { pattern: "src/**/*.spec.js", ignore: true },
      { pattern: "src/**/*.spec.ts", ignore: true }
    ],

    tests: ["src/**/*.spec.js", "src/**/*.spec.ts"],

    compilers: {
      "**/*.js": wallaby.compilers.babel(),
      "**/*.ts": wallaby.compilers.babel()
    },

    env: {
      type: "node"
    },
    testFramework: "jest"
  };
};

```

### Code editor or IDE name and version

Webstorm  2019.2

### OS name and version

OSX

**Comment by smcenlly** [comment] 2019-07-29 22:51
We've seen a [similar error](https://github.com/wallabyjs/public/issues/1817) in the past because of a breaking change in the IntelliJ API. This was fixed in Wallaby v1.0.118+. If you have recently upgraded Webstorm and have an older version of Wallaby, it's possible that this is the cause of your problem.

The [latest version of Wallaby for IntelliJ](https://download.wallabyjs.com/intellij) is working for us with the latest version of Webstorm (2019.2)

If you are using the latest version Wallaby and are still having issues:

1) Are you using the JetBrains Runtime or a custom runtime? 
2) Can you please provide us with the details/screenshot from WebStorm Help->About? (we're interested to know `Runtime version` and `VM`.

**Closed** 2019-07-30 09:02 UTC

**Comment by lgandecki** [comment] 2019-07-30 09:38
Shouldn't wallabyjs update automatically though? :) Maybe the issue should be "wallabyjs" didn't update itself. I tried to change the wallaby.js config hoping that would force the update, but it didn't.
Downloading the plugin and reinstalling it kickstarted the "updating wallaby.js core" which helped.  Thanks.

Btw,

<img width="560" alt="Screen Shot 2019-07-30 at 11 32 06 AM" src="https://user-images.githubusercontent.com/4002543/62118420-ee6a0780-b2bd-11e9-8ad0-85d54a04db39.png">

**Comment by ArtemGovorov** [comment] 2019-07-30 09:43
> Shouldn't wallabyjs update automatically though? :) 

You are right, it absolutely should have. However, that breaking change in the IntelliJ API wasn't allowing Wallaby to even get to the self-update step, so unfortunately manual update was required.
