### ISSUE TITLE
Intellij: `Error running 'Wallaby': Cannot find runner for Wallaby`

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#1751] opened 2018-07-05 17:14 UTC
### Issue description or question

In Intellij: `Error running 'Wallaby': Cannot find runner for Wallaby`.

Works on another project.

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

```
IntelliJ IDEA 2018.2 EAP (Ultimate Edition)
Build #IU-182.3208.16, built on June 14, 2018
IntelliJ IDEA EAP User
Expiration date: July 14, 2018
JRE: 1.8.0_152-release-1226-b7 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6
```

### OS name and version

Windows
**OSX**
Linux

**Comment by vjpr** [comment] 2018-07-05 17:16
I had the launch config named `Wallaby`. Changing it to `wallaby` worked strangely...

**Comment by ArtemGovorov** [comment] 2018-07-05 23:28
Hmm, I have just tried various names, including `Wallaby`, but can't reproduce the issue. Could you please share the stack trace of the error from from your `idea.log` files?

**Comment by myuanz** [comment] 2018-07-17 10:51
The same as yours.
`错误运行test: Cannot find runner for test`
```
IntelliJ IDEA 2018.1.5 (Ultimate Edition)
构建, 建立在 June 12, 2018

JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by vjpr** [comment] 2018-07-17 15:36
Installed on fresh IntelliJ version, and got the error again. Restarting resolved it.

**Comment by myuanz** [comment] 2018-07-18 03:09
I tried to install  `2018.2` and then run successfully.
But `2018.1.5` still can't be used normally, even if it is reinstalled
```
IntelliJ IDEA 2018.2 (Ultimate Edition)
Build #IU-182.3684.40, built on July 17, 2018

JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by justinbarry** [comment] 2018-07-26 22:14
I had to remove the 'cache' folder outlined here: https://github.com/wallabyjs/public/issues/571#issuecomment-224515332.

Once I did that it worked.

**Comment by ArtemGovorov** [comment] 2018-07-27 00:20
@justinbarry Thanks for the update. Could you please specify your IDE version?

**Comment by justinbarry** [comment] 2018-07-27 21:06
WebStorm 2018.2
Build #WS-182.3684.70, built on July 20, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by smcenlly** [comment] 2019-09-02 04:25
We rewrote our JetBrains Plugin earlier in the year ([read more here](https://medium.com/@wallabyjs/new-wallaby-js-for-jetbrains-editors-496da2c30d34)). Closing this issue as we haven't had any report of this issue since July 2018.

**Closed by smcenlly** 2019-09-02 04:25 UTC
Labels: more info is required
