### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by taeyangoh** [wallabyjs/public#204] opened 2015-07-17 00:54 UTC
Good morning Artem!

I have purchased company seat license, but I have received attached license error message since yesterday. 

How could we sort this issue out?   

Thank you so much for your support & enjoy!

Taeyang. 

![license warning message](https://cloud.githubusercontent.com/assets/5927824/8738377/52032f2c-2c69-11e5-9d13-af8fb6a3ef66.jpg)

**Comment by ArtemGovorov** [comment] 2015-07-17 01:04
Hello,

This normally means that someone else is using the same wallaby.js license on some other machine at the same time as you are. Please contact me via wallabyjs@gmail.com and we'll sort it out.

**Comment by fvanwijk** [comment] 2015-07-17 06:17
I had the same when Wallaby was still running while moving from the office to home. IP switch is detected while Wallaby was still running. If you could prevent the License warning from begin displayed in this case, the false positive is eliminated.

**Comment by ArtemGovorov** [comment] 2015-07-17 06:24
> IP switch is detected while Wallaby was still running.

@fvanwijk Hmm, this is a different issue - will try to reproduce this one. So in your case you had the message when switching networks/IP address and while having wallaby.js running, is it correct?

**Comment by fvanwijk** [comment] 2015-07-17 07:18
Yes
1. Be connected to network
2. Start Wallaby
3. Drive home
4. Connect to home network
5. Continue developing
6. Message appears

**Comment by DinisCruz** [comment] 2015-07-29 14:32
I just had the same issue when I swapped wifi networks

![image](https://cloud.githubusercontent.com/assets/656739/8960267/fde1415c-3606-11e5-9794-25f66bbf4204.png)

**Comment by okonet** [comment] 2015-08-17 08:28
Also just got it by moving from home to the office network. It still work after restart though.

**Comment by ArtemGovorov** [comment] 2015-08-17 08:32
I have made some fixes a couple of weeks ago that should have improved the check, but apparently, there're still some issues. Will get back to it to see how else I can try to fix it. Can't reproduce it when switching Wi-Fi network to my phone hot spot.

**Comment by fvanwijk** [comment] 2015-08-17 09:50
Your IP may not change when switching between those two networks?

**Comment by ArtemGovorov** [comment] 2015-08-18 00:51
@fvanwijk Just doubled checked - the IP address is switching.

**Comment by okonet** [comment] 2015-08-18 06:10
It's different in my case as well but it's not guaranteed. Still don't get why is the IP address related to the issue.

**Comment by okonet** [comment] 2015-10-05 09:25
Please reopen this one since this is still happening very often.

**Comment by ArtemGovorov** [comment] 2015-10-05 14:09
@okonet I have added a fix that should remove the issue in 1.0.34, so closing it again. Please let me know if it's still reproduced in the new version.

**Closed by ArtemGovorov** 2015-10-05 14:09 UTC
