### ISSUE TITLE
Wallaby complains EADDRINUSE

### ISSUE THREAD

**Issue by IPWright** [wallabyjs/public#933] opened 2017-01-06 09:42 UTC
### Issue description or question

I've got a single editor running, and I'm finding that stopping and starting wallaby it often doesn't shut down properly as I get a port in use error:

```
[Info]: wallaby.js started​​​​​
​​[Error]: Error: listen EADDRINUSE :::51245​​
​​[Error]:   at Object.exports._errnoException (util.js:893:11)​​
​​[Error]:   at exports._exceptionWithHostPort (util.js:916:20)​​
​​[Error]:   at Server.__dirname.Server.Server._listen2 (net.js:1246:14)​​
​​[Error]:   at listen (net.js:1282:10)​​
​​[Error]:   at Server.__dirname.Server.Server.listen (net.js:1378:5)​​
​​[Error]:   at C:\Users\ian.wright\AppData\Roaming\Sublime Text 3\Packages\Wallaby\wallaby\node_modules\phantom\receiver.js:3:8543​​
​​[Error]:   at _fulfilled (C:\Users\ian.wright\AppData\Roaming\Sublime Text 3\Packages\Wallaby\wallaby\node_modules\q\q.js:787:54)​​
​​[Error]:   at self.promiseDispatch.done (C:\Users\ian.wright\AppData\Roaming\Sublime Text 3\Packages\Wallaby\wallaby\node_modules\q\q.js:816:30)​​
​​[Error]:   at Promise.promise.promiseDispatch (C:\Users\ian.wright\AppData\Roaming\Sublime Text 3\Packages\Wallaby\wallaby\node_modules\q\q.js:749:13)​​
​​[Error]:   at C:\Users\ian.wright\AppData\Roaming\Sublime Text 3\Packages\Wallaby\wallaby\node_modules\q\q.js:557:44​​
​​[Error]:   at flush (C:\Users\ian.wright\AppData\Roaming\Sublime Text 3\Packages\Wallaby\wallaby\node_modules\q\q.js:108:17)​​
​​[Error]:   at _combinedTickCallback (internal/process/next_tick.js:67:7)​​
​​[Error]:   at process._tickCallback (internal/process/next_tick.js:98:9)​​
```

### Wallaby.js configuration file

```
module.exports = function (wallaby) {
    process.env.NODE_ENV = 'wallaby';
    return {
        files: [
            { pattern: "./tests/**/*.snap", load: false, instrument: false },
            { pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false },
            { pattern: 'src/**/*.css', load: false },
            { pattern: 'src/**/*.js', load: false },
        ],
        tests: [
            // Exclude specific tests, that won't run in Jest (since they require a browserr object)
            // Load all other tests
            { pattern: './tests/**/*.test.js' }
        ],
        hints: {
            ignoreCoverage: /ignore coverage/
        },
        env: {
            type: "node",
            runner: "node",
        },
        testFramework: 'jest',
        compilers: {
            '**/*.js': wallaby.compilers.babel({ babel: require('babel-core') })
        },
    };
};
```

### Code editor or IDE name and version

Sublime Text v3

### OS name and version

Windows 10 x64

**Comment by ArtemGovorov** [comment] 2017-01-06 10:23
Thanks for the report. The issue is fixed in [core v1.0.338](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Closed by ArtemGovorov** 2017-01-06 10:23 UTC
Labels: bug
