### ISSUE TITLE
filtered tests are not refreshed

### ISSUE THREAD

**Issue by pixsrv** [wallabyjs/public#3021] opened 2022-06-24 12:35 UTC
seq:
- add some failing test
- filter test view by failing and by name (upto now it's fine)
- add new failing tests

now filter view is not refreshed until user changes failing checkbox or name filter
(even if test matches the filter)

**Comment by smcenlly** [comment] 2022-06-27 01:40
I assume that you're talking about Wallaby App and not the editor?

It appears to be working for us.

Could you please provide us with screenshots so we understand exacltly where the problem is occurring, and also provide us with your Wallaby Diagnostics report?

**Comment by smcenlly** [comment] 2023-03-01 06:09
Closing this issue as we didn't hear back.

**Closed by smcenlly** 2023-03-01 06:09 UTC
Labels: more info is required
