### ISSUE TITLE
isomorphic node / react

### ISSUE THREAD

**Issue by yanivefraim** [wallabyjs/public#713] opened 2016-07-28 12:54 UTC
I'm developing an isomorphic application, something similar to [this](https://github.com/kriasoft/react-starter-kit) project. This means that I have both client and server (Javascript) in the same project, side by side (we share same components and tests).

We use webpack for bundling client code and client tests (two different bundles) + we have all code in `dist` so server code is not bundled (on dist).

I was wondering if we can use both client and server using same wallabyjs configuration. 
I'm trying two options:
1. Run tests as 'node' env. I wonder if this is possible (for now I'm getting the following error: `Error: It looks like you called`mount()`without a global document being loaded.`. I tried adding JSDOM/JSDOM-global to 'files', with no success so far. Another issue that I might have in this setup is using css imports inside my components. We solved this issue on our server code by using this module: `css-modules-require-hook`. 
2. Bundle both server and client using webpack. This is something that we did not do in our build. I think it might work (although I prefer option 1) .

I would love to hear what you have to say about it + I promise to contribute an example of an isomorphic react app to the examples page (:

BTW: https://github.com/kriasoft/react-starter-kit/issues/744

**Comment by ArtemGovorov** [comment] 2016-07-29 05:17
Option 1 should be possible if your client side tests can run in node.js.

With `env.type = node`, you [don't need to add any of your node modules in the `files` list](https://wallabyjs.com/docs/config/files.html). With css imports, you should probably be able to use the `css-modules-require-hook` as well.

Your config may look like:
```javascript
module.exports = function (wallaby) {
  return {
    files: [...],

    tests: [...],

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    env: {
      type: 'node'
    },

    setup: function () {
      require('babel-polyfill'); // if you need it
      
      // minimal jsdom setup taken from 
      // http://hellote.com/testing-react-components-with-mocha-and-jsdom/
      var jsdom = require('jsdom');
      global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
      global.window = document.defaultView;
      global.navigator = global.window.navigator;
    }
  };
};
```

Depending on your project, you may need a more complex setup, but it's not a wallaby specific thing though, you'd still need it for mocha or other runners. 

You may have a look into [this example](https://github.com/wallabyjs/public/issues/684#issue-165139502) and [this one](https://github.com/wallabyjs/public/issues/642#issuecomment-225144327) to see how others are doing it. Some are using separate files for their setup to reuse it across mocha and wallaby; one example is using [ignore-styles](https://www.npmjs.com/package/ignore-styles) module for loading CSS, another one just adds a custom css loader.

**Comment by ArtemGovorov** [comment] 2016-07-29 05:19
Perhaps it's a good idea if you could start creating a sample of an isomorphic react app with your project specific setup. If something doesn't work there and you get stuck, I could easily have a look into it and contribute. Will be much easier than trying to suggest something without the code, as there are many ways to accomplish it.

**Comment by yanivefraim** [comment] 2016-07-31 10:02
Thanks. I will try to work on a simplified version. It is kind of complicated because all of our projects and examples are too complex for this. I will make an effort (in order to contribute the example to 'examples' and maybe add wallaby.js file to react starter kit later (:

**Comment by vanjaoljaca** [comment] 2019-01-18 13:19
mern.io is an isomorphic starter kit that fails on css import in wallabyjs.

**Comment by ArtemGovorov** [comment] 2019-01-18 23:15
@vanjaoljaca Could you try this in your Wallaby config?

```diff
      ...
      setup: function () {
        // source: package.json ava require
        require("./server/util/setup-test-env.js");
+       require.extensions['.css'] = () => {};
      },
```

**Comment by vanjaoljaca** [comment] 2019-01-19 02:15
Sorry that was a terrible edit, I got mere-starter pack working with that commit. Thanks for your help.

**Comment by vjpr** [comment] 2019-01-25 00:21
@ArtemGovorov I tried your solution but it didn't work. I am working with Ava. Is there anything in the worker that would override the `require.extensions`? None of the packages that override there are working for me.

**Comment by vjpr** [comment] 2019-01-25 02:13
Thanks, I'm thinking it was caused by not including the .css files in the files config. Will double-check soon.

**Comment by smcenlly** [comment] 2020-10-08 23:48
Closing this issue out as it is very old and we know Wallaby now works well with mono-repos.

**Closed by smcenlly** 2020-10-08 23:48 UTC
