### ISSUE TITLE
Wallaby app navigation issue - webstorm 2019.2

### ISSUE THREAD

**Issue by NikkiJ19** [wallabyjs/public#2173] opened 2019-08-10 12:20 UTC
### Issue description or question
I cannot use alt + right / left arrow to navigate the wallaby app tabs after updating to 2019.2. The navigation seems to work fine in other plugins. 

![image](https://user-images.githubusercontent.com/31554476/62821715-2c70f200-bb2e-11e9-9b80-1e71a55ea42f.png)

### Code editor or IDE name and version

WebStorm 2019.2
Build #WS-192.5728.87, built on July 22, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 733M
Cores: 2
Registry: ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, com.wakatime.intellij.plugin, com.intellij.database, BashSupport, com.intellij.lang.jsgraphql, quokka.js, ru.adelf.idea.dotenv, wallaby.js

### OS name and version

![image](https://user-images.githubusercontent.com/31554476/62821738-7fe34000-bb2e-11e9-85bb-65089f0915f1.png)

Windows

**Comment by smcenlly** [comment] 2019-08-12 00:28
Thanks for reporting the problem. We've duplicated the issue and identified that it's not caused by Wallaby. The issue affects any run configuration that contains tabs. We have created an issue in the JetBrains youtrack repository ([WEB-40650](https://youtrack.jetbrains.com/issue/WEB-40650)) so that the JetBrains team may investigate and address. 

If you want to, you may follow the link above and upvote or watch.

Because the issue is not caused by Wallaby and is being tracked in the JetBrains issue repository, we will close this issue.

**Closed by smcenlly** 2019-08-12 00:28 UTC
