### ISSUE TITLE
Test with missing file causes a different test to indicate an error

### ISSUE THREAD

**Issue by mindjuice** [wallabyjs/public#1209] opened 2017-06-28 18:55 UTC
### Issue description or question
When one test file contains an import of a non-existent file,  Wallaby app reports that a different test file has an error.

See attached zip file for a project to repro this.  Specifically, the test in `src/folder2/__tests__/utils_tests.ts` attempts to import a missing file, but wallaby app reports an error in `src/folder1/Add/__tests__/Add_tests.ts` in the TESTS tab.

### Wallaby.js configuration file

```javascript
module.exports = () => {
  return {
    testFramework: 'jest',
    env: {
      type: 'node',
      runner: 'node'
    },

    files: [
      'src/folder1/Add/index.ts',
      'src/folder1/Sub/index.ts',

      'src/folder2/utils.ts',
    ],
    tests: [
      'src/folder1/Add/__tests__/Add_tests.ts',
      'src/folder1/Sub/__tests__/Sub_tests.ts',

      'src/folder2/__tests__/utils_tests.ts',
    ],
    debug: true,
  }
}
```

### Code editor or IDE name and version
Visual Studio v1.13.1

### OS name and version
OSX 10.12.3 Sierra

[wallaby-bug.zip](https://github.com/wallabyjs/public/files/1109895/wallaby-bug.zip)

![screen shot 2017-06-28 at 2 54 21 pm](https://user-images.githubusercontent.com/934638/27654997-c57e5d8a-5c11-11e7-83dc-2adcd0db27a4.png)

**Comment by ArtemGovorov** [comment] 2017-06-29 09:03
Thanks for the report, the issue is fixed in the [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Closed by ArtemGovorov** 2017-06-29 09:03 UTC
Labels: bug

**Comment by mindjuice** [comment] 2017-06-29 20:17
Thanks...works for me nicely now.

Just bought a license.

**Comment by ArtemGovorov** [comment] 2017-06-30 00:04
Awesome, thanks for the update and for your order!
