### ISSUE TITLE
`module.export` in node modules breaks wallaby typescript es6 imports

### ISSUE THREAD

**Issue by raix** [wallabyjs/public#485] opened 2016-02-29 14:00 UTC
### Issue description or question
I've cloned the `wallaby-typescript-browserify` example and wanted to use regular es6 import syntax importing `expect` in the spec file:
```js
import expect from 'expect';
```

Reproduction:
* cloned https://github.com/wallabyjs/wallaby-typescript-browserify
* Then installed `npm i expect --save-dev`
* Comment out the `spec.setup.ts` *(setting the global expect from chai)*
* Add `import expect from 'expect';` in `person.spec.ts`
* This compiles fine via regular typescript / tsc
* When I startup wallabyjs the test breaks

![image](https://cloud.githubusercontent.com/assets/1136718/13396337/49ea5f52-def4-11e5-9da4-c02dcced1037.png)
*[Error]: 'undefined' is not a function (evaluating 'expect_1.default(new person_1.default('John').name')*

When I comment out one line in `node_modules/expect/index.js`:
```js
// module.exports = exports['default'];
```
Then restart wallaby tests work again.

![image](https://cloud.githubusercontent.com/assets/1136718/13396398/9cd1e320-def4-11e5-9b88-453a770ecf21.png)

-

### Wallaby.js configuration file

```javascript
module.exports = function (w) {
  var wallabify = require('wallabify');

  var wallabyPostprocessor = wallabify({
      entryPatterns: [
        'src/**/*.spec.js'
      ]
    }
  );

  return {
    files: [
      {pattern: 'node_modules/expect/node_modules/expect/lib/index.js', instrument: false},
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*.spec.ts', load: false}
    ],

    testFramework: 'mocha',

    postprocessor: wallabyPostprocessor,

    compilers: {
      '**/*.ts': w.compilers.typeScript()
    },

    env: {
      type: 'browser'
    },

    bootstrap: function (w) {
      window.__moduleBundler.loadTests();
    }
  };
};
```

### Typescript configuration file *(tsconfig.json)*

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5"
  },
  "exclude": [
      "node_modules",
      "dist"
  ]
}
```

### Code editor or IDE name and version

Mac os X
Sublime Text v3 + wallaby and the typescript plugin

### OS name and version

OSX

**Comment by ArtemGovorov** [comment] 2016-03-01 02:11
I have tried running plain mocha without wallaby and I'm getting the same issue. It looks like `expect` module that you are using is incorrectly exporting it's functionality. 

When they do (I'm assuming they've been compiling their source code with some old version of `babel`):
```javascript
exports['default'] = expect;
module.exports = exports['default'];
```
the `exports`/`module.exports` ends up having no `default` property so the code generated by TypeScript compiler, that tries to access it, fails.

Before the issue is fixed in `expect.js`, you may import it like this:
```javascript
import * as expect from 'expect';
```

BTW, you don't need this line in your config, including it this way will add it via `script` tag into the sandbox page.
```
{pattern: 'node_modules/expect/node_modules/expect/lib/index.js', instrument: false},
```
In your case wallabify will find the file when building your project.

**Comment by ArtemGovorov** [comment] 2016-03-01 02:12
Here is how I tried to run it with plain `mocha`:
```
```

**Closed by ArtemGovorov** 2016-03-01 02:11 UTC

**Comment by ArtemGovorov** [comment] 2016-03-01 02:15
```
npm install mocha ts-node
```
and then run
```
./node_modules/.bin/mocha --require ts-node/register app/src/**/*.spec.ts
```
and in the `person.spec.ts` file I just have 
```javascript
import expect from 'expect';
console.log(expect);
```
it prints `undefined`.

**Comment by raix** [comment] 2016-03-01 03:28
> the exports/module.exports ends up having no default property

Only module.exports have no default

**Comment by raix** [comment] 2016-03-01 03:32
The sublime text typescript plugin seems to resolve the import correctly

**Comment by ArtemGovorov** [comment] 2016-03-01 03:43
`module.exports` is the same as `exports`. Here what `browserify` passes  - https://github.com/substack/browser-pack/blob/master/prelude.js#L36 (`m` is `module`).

Typescript plugin resolves it because it uses static analysis, perhaps is just checking the module existence. The error however is thrown in runtime, and is is out of reach for the TypeScript compiler/plugin.

**Comment by ArtemGovorov** [comment] 2016-03-01 03:56
You may easily test it by creating 2 files:
`a.ts`:
```
import b from './b';
console.log(b);
```
`b.js`:
```
exports['default'] = {test: 1};
module.exports = exports['default'];
```

`a.ts` gets compiled to JavaScript:
```javascript
var b_1 = require('./b');
console.log(b_1.default);
```

When you run the code in node or browserify (with or without wallaby), you'll be getting `undefned`.

**Comment by raix** [comment] 2016-03-01 08:02
Using `import * as expect from 'expect'` works,

Thank you for your time @ArtemGovorov
