### ISSUE TITLE
Module parse failed: The keyword 'interface' is reserved

### ISSUE THREAD

**Issue by pauleustice** [wallabyjs/public#2146] opened 2019-07-23 14:03 UTC
### First setup in Angular 8 CLI repo fails

I've set up Wallaby for another project in the past, but this is a first attempt in this repository. It's an Angular CLI that we just updated to ng 8. It uses Typescript, SCSS and has some TS path aliases configured.

When I run Wallaby, I get this error repeated twice in the Wallaby Console:

```
Runtime error: Uncaught Error: Module parse failed: The keyword 'interface' is reserved (10:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { WindowService } from '../window/window.service';
| 
> interface AnalyticsConfig {
|   cms: any;
|   page: {
at http://localhost:57113/____wallaby-bundle.js?1563890294527&wallabyFileId=bundle:167418
```

In the Failing Tests tab, this is also displayed below the error from above:

```
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import 'settings';
       ^
      Can't find stylesheet to import.
```

### Wallaby.js configuration file

I copied the example from here: https://wallabyjs.com/docs/tutorial/angular-cli.html?editor=jb

It is identical, with the exception that I've added some TS path aliases to the `postprocessor.resolve.alias` object, and removed the reducer for library public apis that was there before.

```javascript
module.exports = function(wallaby) {
  const wallabyWebpack = require('wallaby-webpack');
  const path = require('path');
  const fs = require('fs');

  const specPattern = '/**/*spec.ts';
  const angularConfig = require('./angular.json');


  const projects = Object.keys(angularConfig.projects).map(key => {
    return { name: key, ...angularConfig.projects[key] };
  }).filter(project => project.sourceRoot)
    .filter(project => project.projectType !== 'application' ||
      (project.architect &&
        project.architect.test &&
        project.architect.test.builder === '@angular-devkit/build-angular:karma'));

  const applications = projects.filter(project => project.projectType === 'application');
  const libraries = projects.filter(project => project.projectType === 'library');

  const tsConfigFile = projects
    .map(project => path.join(__dirname, project.root, 'tsconfig.spec.json'))
    .find(tsConfig => fs.existsSync(tsConfig));

  const tsConfigSpec = tsConfigFile ? JSON.parse(fs.readFileSync(tsConfigFile)) : {};

  const compilerOptions = Object.assign(require('./tsconfig.json').compilerOptions, tsConfigSpec.compilerOptions);
  compilerOptions.emitDecoratorMetadata = true;

  return {
    files: [
      { pattern: path.basename(__filename), load: false, instrument: false },
      ...projects.map(project => ({
        pattern: project.sourceRoot + '/**/*.+(ts|js|css|less|scss|sass|styl|html|json|svg)',
        load: false
      })),
      ...projects.map(project => ({
        pattern: project.sourceRoot + specPattern,
        ignore: true
      })),
      ...projects.map(project => ({
        pattern: project.sourceRoot + '/**/*.d.ts',
        ignore: true
      }))
    ],

    tests: [
      ...applications.map(project => ({
        pattern: project.sourceRoot + specPattern,
        load: false
      }))
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript({
        ...compilerOptions,
        getCustomTransformers: program => {
          return {
            before: [
              require('@ngtools/webpack/src/transformers/replace_resources').replaceResources(
                path => true,
                () => program.getTypeChecker(),
                false
              )
            ]
          };
        }
      })
    },

    preprocessors: {
      /* Initialize Test Environment for Wallaby */
      [path.basename(__filename)]: file => `
 import '@angular-devkit/build-angular/src/angular-cli-files/models/jit-polyfills';
 import 'zone.js/dist/zone-testing';
 import { getTestBed } from '@angular/core/testing';
 import { BrowserDynamicTestingModule,  platformBrowserDynamicTesting} from '@angular/platform-browser-dynamic/testing';

 getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());`
    },

    middleware: function(app, express) {
      const path = require('path');

      applications.forEach(application => {
        if (
          !application.architect ||
          !application.architect.test ||
          !application.architect.test.options ||
          !application.architect.test.options.assets
        ) {
          return;
        }

        application.architect.test.options.assets.forEach(asset => {
          app.use(asset.slice(application.sourceRoot.length), express.static(path.join(__dirname, asset)));
        });
      });
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: wallabyWebpack({
      entryPatterns: [
        ...applications
          .map(project => project.sourceRoot + '/polyfills.js')
          .filter(polyfills => fs.existsSync(path.join(__dirname, polyfills.replace(/js$/, 'ts')))),
        path.basename(__filename),
        ...projects.map(project => project.sourceRoot + specPattern.replace(/ts$/, 'js'))
      ],

      module: {
        rules: [
          { test: /\.css$/, loader: ['raw-loader'] },
          { test: /\.html$/, loader: 'raw-loader' },
          {
            test: /\.ts$/,
            loader: '@ngtools/webpack',
            include: /node_modules/,
            query: { tsConfigPath: 'tsconfig.json' }
          },
          { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
          { test: /\.less$/, loaders: ['raw-loader', { loader: 'less-loader' }] },
          {
            test: /\.scss$|\.sass$/,
            loaders: [{ loader: 'raw-loader' }, { loader: 'sass-loader', options: { implementation: require('sass') } }]
          },
          { test: /\.(jpg|png|svg)$/, loader: 'raw-loader' }
        ]
      },

      resolve: {
        extensions: ['.js', '.ts'],
        modules: [
          __dirname,
          'node_modules',
          ...(projects.length ? projects.filter(project => project.root).map(project => project.root) : []),
          ...(projects.length ? projects.filter(project => project.sourceRoot).map(project => project.sourceRoot) : [])
        ],
        alias: {
          '@environments': path.join(wallaby.projectCacheDir, 'src/environments'),
          '@core': path.join(wallaby.projectCacheDir, 'src/app/core'),
          '@graphql': path.join(wallaby.projectCacheDir, 'src/app/graphql'),
          '@product': path.join(wallaby.projectCacheDir, 'src/app/product'),
          '@shared': path.join(wallaby.projectCacheDir, 'src/app/shared'),
          '@mocks': path.join(wallaby.projectCacheDir, 'src/app/mocks'),
          '@models': path.join(wallaby.projectCacheDir, 'src/app/models'),
          '@directives': path.join(wallaby.projectCacheDir, 'src/app/shared/directives'),
          '@guards': path.join(wallaby.projectCacheDir, 'src/app/shared/guards'),
          '@pipes': path.join(wallaby.projectCacheDir, 'src/app/shared/pipes'),
          '@services': path.join(wallaby.projectCacheDir, 'src/app/shared/services')
        }
      }
    }),

    setup: function() {
      window.__moduleBundler.loadTests();
    }
  };
};

```

### Code editor or IDE name and version

WebStorm v2019.2

### OS name and version

OSX 10.13.6

**Comment by smcenlly** [comment] 2019-07-23 21:37
It looks like when you're using Wallaby, the `sass-loader` is trying to process one of your TypeScript files for some reason. Can you please confirm that your tests are running when you use the CLI?

Could you please try changing the `sass` test pattern in your wallaby configuration from:

```
{
  test: /\.scss$|\.sass$/,
  loaders: [{ loader: 'raw-loader' }, { loader: 'sass-loader', options: { implementation: require('sass') } }]
},
```

to:

```
{
  test: /\.(scss|sass)$/,
  loaders: [{ loader: 'raw-loader' }, { loader: 'sass-loader', options: { implementation: require('sass') } }]
},
```

I am pretty sure that this will not fix your problem, but I'd like to try just in case.

If that doesn't work, can you please provide us with a sample repo that has the same problem? I'm guessing there's something with your project structure that's causing the problem and we'll need to see it in order to work out what's going wrong. You should be able to remove all files/components/etc (and all code except a sample import) to duplicate the problem.

**Comment by smcenlly** [comment] 2019-07-24 04:18
We thought of another thing to check re: the first error that you received. How are you importing your TypeScript files? Do you specify the `.ts` extension in your import?

**Comment by pauleustice** [comment] 2019-07-24 08:10
@smcenlly Thanks for getting back to me. Changing the pattern didn't make a difference. We heavily use TS path aliases and barrel files, so our imports are usually something like:

`import { WindowService } from '../window/window.service';`

or

`import { SplitPipe } from '@pipes';`

We don't specify the `.ts` extension anywhere

**Comment by pauleustice** [comment] 2019-07-24 14:57
@smcenlly I've spent some time reducing down our repo into non-confidential parts in order to a barebones reproduction. During the course of that, the "The keyword 'interface' is reserved" error has disappeared and I'm not sure at what point it did. I'll have to come back to that.

I don't think the other issue is a case of the sass loader importing TS files, just that it can't resolve the "@import 'settings';" line. This refers to a scss partial which exists in the 'styles' directory which I think is (in Angular world) resolved by the angular.json `test.stylePreprocessorOptions.includePaths` setting.

How do I add that 'scope' in Wallaby?

**Comment by pauleustice** [comment] 2019-07-25 08:28
@ArtemGovorov @smcenlly I have established the cause of the issues and am not sure if this is expected behaviour from Wallaby? It certainly isn't from a user's perspective :)

If any of our files (I found this problem in spec and component files) within `src/app/**` import a TS file like so:

`import { bar } from 'src/app/foo/bar';`

Wallaby will throw the error about needing an appropriate loader. The key is paths not being relative - if I use a path alias or a relative path then Wallaby seems OK with it.

The thing is, this resolves correctly and the tests run fine when using `karma run`. I'm not sure how or why it resolves correctly (and I'll be updating them), but they do...

Any ideas why?

**Comment by ArtemGovorov** [comment] 2019-07-25 08:51
Thanks for the update. Looks like our recent Angular CLI config changes were not quite correct. The issue is fixed in the docs and the sample repo. Please update the following config section: https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js#L137-L141 and it should work for you.

**Closed by ArtemGovorov** 2019-07-25 08:51 UTC
