### ISSUE TITLE
Sublime Footer Icons

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#1126] opened 2017-04-19 08:16 UTC
### Issue description or question

Sublime Footer Icons no longer work.

![image](https://cloud.githubusercontent.com/assets/1374775/25169908/988c4570-24e0-11e7-9e9a-11bf9c1e2079.png)

### Wallaby.js configuration file

n/a

### Code editor or IDE name and version

Sublime Text v3 Build 3129

### OS name and version

Windows 10 x64

**Comment by ArtemGovorov** [comment] 2017-04-19 08:27
> Sublime Text v3 Build 3129

Where did you get the 3129 build from? I can only see 3126 in the official downloads.

**Comment by IPWright83** [comment] 2017-04-19 08:29
I use the Dev builds - https://www.sublimetext.com/3dev

I've reported the odd issue with Sublime and the response was always (try the latest build). So I just run with that now.

**Comment by IPWright83** [comment] 2017-04-19 08:31
I would guess that it was build *3127* that broke the icons by the way. The two immediately after seemed like bug fixes to bits that broke in 3127.

**Comment by ArtemGovorov** [comment] 2017-04-19 08:35
Did you you report the issue to Sublime guys? If so, could you paste the issue link? I'm guessing it's not much we can do in wallaby. These are not even icons that we use - just two Unicode chars: `✗` and `✔`.

**Comment by IPWright83** [comment] 2017-04-19 08:41
@ArtemGovorov I haven't done so yet, but I will do and see what they say. I'll also link it for you.

Cheers

**Comment by ArtemGovorov** [comment] 2017-04-19 08:52
Thanks, the issue also seems to be Windows specific, it's working ok on Mac:
<img width="298" alt="screen shot 2017-04-19 at 6 41 53 pm" src="https://cloud.githubusercontent.com/assets/979966/25171454/3d45643e-2531-11e7-9af5-1b85e7bf9655.png">

**Comment by IPWright83** [comment] 2017-04-19 08:57
Useful to know. Thanks :)

**Comment by ArtemGovorov** [comment] 2017-04-19 09:29
Just that it looks good before the issue is fixed in Sublime, I have replaced the icons on Windows for the dev build:
![sub copy](https://cloud.githubusercontent.com/assets/979966/25173141/72310266-2536-11e7-936a-83d1b9eb701d.png)

The update is published and should be available in an hour or so.

**Closed by ArtemGovorov** 2017-04-19 09:29 UTC

**Comment by IPWright83** [comment] 2017-04-19 09:34
Linked to Sublime forum issue https://forum.sublimetext.com/t/footer-icons-broken-for-some-plugins/27672?u=ipwright83

**Comment by IPWright83** [comment] 2017-04-19 09:52
Been linked to a GitHub issue https://github.com/SublimeTextIssues/Core/issues/1654
