### ISSUE TITLE
wallabjs vscode fail to detect in source testing code

### ISSUE THREAD

**Issue by sweetim** [wallabyjs/public#3150] opened 2023-01-18 11:04 UTC
### Issue description or question

wallabjs vscode fail to detect in source testing code when using vitest
- https://vitest.dev/guide/in-source.html

is this feature not supported yet?

the dependencies version used in the repo

```
{
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.9",
    "@vitejs/plugin-react-swc": "^3.0.0",
    "@vitest/coverage-c8": "^0.27.1",
    "typescript": "^4.9.3",
    "vite": "^4.0.0",
    "vitest": "^0.27.1"
  }
```

**Comment by smcenlly** [comment] 2023-01-18 21:59
> is this feature not supported yet?

No, Wallaby does not support inline tests at the moment. Closing this issue as a duplicate of https://github.com/wallabyjs/public/issues/3108.

**Closed by smcenlly** 2023-01-18 21:59 UTC
