### ISSUE TITLE
Error installing into Visual Studio Code

### ISSUE THREAD

**Issue by selangley-wa** [wallabyjs/public#2191] opened 2019-08-26 14:14 UTC
### Issue description or question
Attempting to install the extension into Visual Studio Code displays the following error:

c:\Users\scott.langley@ofm.wa.gov\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.141\dist\wallaby.json: Unexpected token < in JSON at position 0

where the contents of the referenced wallaby.json file  onsists of:

`<html><title>Authentication Required</title><body>Error: Authentication Failure</body></html>`

### Code editor or IDE name and version
![image](https://user-images.githubusercontent.com/43478262/63696709-2aff2500-c7d0-11e9-925d-cd588ab83da7.png)

![image](https://user-images.githubusercontent.com/43478262/63696894-9cd76e80-c7d0-11e9-9280-e801803b125e.png)

**Comment by smcenlly** [comment] 2019-08-26 22:48
Looks like a duplicate of https://github.com/wallabyjs/public/issues/1123

> It looks like you are behind a corporate proxy. Please try this:
> - uninstall the extension,
> - add these settings to VS Code settings.json:

```
{
  ...
  "http.proxy": "your corporate proxy address",
  "https.proxy": "your corporate proxy address",
  "wallaby.useHttpForDownload": true
}
```

> - install the extension.

If that doesn't work for you, you may perform an [offline installation](https://wallabyjs.com/docs/intro/offline.html).

**Closed by smcenlly** 2019-08-26 22:48 UTC
