### ISSUE TITLE
Error in IntellijIDEA Ultimate 2019.2

### ISSUE THREAD

**Issue by masputih** [wallabyjs/public#2212] opened 2019-09-19 10:58 UTC
### Issue description or question

Error loading the plugin in IntellijIDEA.

IntelliJ IDEA 2019.2.2 (Ultimate Edition)
Build #IU-192.6603.28, built on September 6, 2019
Runtime version: 11.0.3+12-b304.56 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

### Wallaby diagnostics report

![image](https://user-images.githubusercontent.com/194357/65238502-fd737600-db06-11e9-890d-691d24c607b1.png)

There's no menu item called "Copy diagnostics report", so I thought I'd just paste the error message here:

```
com.intellij.diagnostic.PluginException: com.wallaby.javascript.actions.CopyDiagnosticsReportAction PluginClassLoader[wallaby.js, 1.0.137] com.intellij.ide.plugins.cl.PluginClassLoader@31c175cc [Plugin: wallaby.js]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:163)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:139)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:501)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:489)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1327)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:18)
	at com.intellij.openapi.application.Preloader.lambda$null$1(Preloader.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.application.Preloader.lambda$componentsInitialized$2(Preloader.java:71)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.lambda$run$0(BoundedTaskExecutor.java:185)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:181)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.wallaby.javascript.actions.CopyDiagnosticsReportAction PluginClassLoader[wallaby.js, 1.0.137] com.intellij.ide.plugins.cl.PluginClassLoader@31c175cc
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:151)
	... 20 more
```

**Comment by smcenlly** [comment] 2019-09-19 21:36
This appears to be a duplicate of #2205.

Please update your Wallaby for IntelliJ plugin to the [latest version](https://download.wallabyjs.com/intellij) to fix the issue.

**Closed by smcenlly** 2019-09-19 21:36 UTC
