### ISSUE TITLE
async setup syntax error

### ISSUE THREAD

**Issue by BraunreutherA** [wallabyjs/public#1029] opened 2017-02-20 22:59 UTC
Hi I have to spin up my express api for integration tests. Therefore I need a async bootstrap script. But wallaby doesn't like to import my bootstrap script (it's written in es6). 

That's the error: 
SyntaxError: Unexpected token }
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at afterWrite (_stream_writable.js:388:3)
    at onwrite (_stream_writable.js:379:7)
    at WritableState.onwrite (_stream_writable.js:90:5)
    at afterTransform (_stream_transform.js:79:3)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:639:5)

Additionally there aren't any logs in the wallaby panel if I place console logs in the setup function.

I also found the smallest possible error config for this. 
The funny thing is if I delete the commented line wallaby starts.

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.js',
      '!src/**/*.spec.js',
      'test/helpers.js',
      'test/bootstrap.js',
    ],

    tests: [
      'src/**/*.spec.js',
    ],

    env: {
      type: 'node',
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
    },

    testFramework: 'mocha',
    debug: true,
    workers: {
      recycle: true,
    },

    setup(wallaby) {
      function x(cb) {
        cb();
      }
      // const x = cb => cb(); <--- if I delete this line it works

      wallaby.delayStart();
      x(wallaby.start);
    },
  };
};
```

instead of the function `x` I would normally required the bootstrap script which returns a promise and then call wallaby.start() in the then function, but this weir error appears.

Atom v1.13 x64
OSX

**Comment by ArtemGovorov** [comment] 2017-02-21 01:36
I don't think there's any issue with the async setup. Looks like the `setup` function is not correctly serialised (to be passed to a test worker). I suspect it's happening because the `setup` function is defined as ES6 method. Try this:

```javascript
module.exports = function (wallaby) {
  return {
    ..

    setup: (wallaby) => {
      ...
    },
  };
};
```

**Comment by ArtemGovorov** [comment] 2017-02-21 01:43
I think I found the bug. This `setup` should work for yuo before it's fixed:

```javascript
module.exports = function (wallaby) {
  return {
    ..

    setup: function (wallaby) {
      ...
    },
  };
};
```

**Comment by BraunreutherA** [comment] 2017-02-21 08:16
That fixed it. Thanks a lot!

**Comment by ArtemGovorov** [comment] 2017-02-21 08:53
Awesome, thanks for the update!
The issue is fixed in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), so after the update you may use the ES6 method syntax that you had originally:

```javascript
...
setup(wallaby) {
  ...
}
...
```

**Closed by ArtemGovorov** 2017-02-21 08:53 UTC
Labels: bug
