### ISSUE TITLE
Unexpected SyntaxError

### ISSUE THREAD

**Issue by epsitec** [wallabyjs/public#515] opened 2016-03-14 06:30 UTC
Here is a project where the tests just pass fine by running `npm test`:

https://github.com/epsitec-sa/electrum-field

however, when running Wallaby.js inside of atom, I get this output:

![wallaby-5](https://cloud.githubusercontent.com/assets/3872435/13736609/3115eaa6-e9b6-11e5-93aa-9297e71f4416.png)

Any idea of what might be going on? I don't see anything suspect in the source code:

![wallaby-5](https://cloud.githubusercontent.com/assets/3872435/13736649/a7aadeec-e9b6-11e5-9518-fea17d9b417d.png)

**Comment by ArtemGovorov** [comment] 2016-03-14 06:48
Looks like a bug in our parser/generator, will be looking into to shortly.

In a meantime, the workaround is to replace
```javascript
for (const state of states)
```
with
```javascript
for (let state of states)
```

**Comment by epsitec** [comment] 2016-03-14 07:11
Thanks.

**Comment by ArtemGovorov** [comment] 2016-03-14 08:02
The issue is fixed in core v1.0.198. The core will be updated automatically in a few minutes, to get the update ASAP, you may [force the core update](https://github.com/wallabyjs/public/issues/413#issuecomment-173174486).

**Closed by ArtemGovorov** 2016-03-14 08:02 UTC
Labels: bug
