### ISSUE TITLE
wallaby.js creating multiple versions of the same test case (with #1, #2 ...etc appended)

### ISSUE THREAD

**Issue by breathe** [wallabyjs/public#1284] opened 2017-09-01 20:16 UTC
### Issue description or question

Wallaby is reporting results for duplicate versions of the same test case with #1, #2, #3 appended.  If I restart wallaby the extra tests initially disappear but then return after awhile of normal usage I get things like this:

<img width="563" alt="screen shot 2017-09-01 at 1 53 38 pm" src="https://user-images.githubusercontent.com/434034/29985635-0570a9c8-8f1d-11e7-9e9c-48946783cb4e.png">

Here are wallaby console output from startup until reaching the state shown in wallaby app ...

[wallabylogs.txt](https://github.com/wallabyjs/public/files/1271367/wallabylogs.txt)

### Wallaby.js configuration file

```javascript
module.exports = function() {

  return {
    files: [
      "package.json",
      "tsconfig.json",
      ".secrets/*",
      "resources/**/*",
      "src/**/*.yml",
      "src/**/*",
      "serverless-services/*",
      "serverless-services/**/*.yml",
      "!src/**/*.test.ts",
      "!lib/**"
    ],

    tests: ["src/**/*.test.ts", "!src/service-tests/**/*"],

    env: {
      type: "node",
      runner: "node"
    },

    debug: false,
    testFramework: "jest"
  };
};
```

I'm not sure if I'm using the files[] and tests[] properties properly -- documentation suggests that the first matching pattern determines the behavior -- but then the example shown for projects with tests in the same directory seems to contradict that?

<img width="1092" alt="screen shot 2017-09-01 at 1 57 05 pm" src="https://user-images.githubusercontent.com/434034/29985791-b73d07d2-8f1d-11e7-90c7-82ec319e9665.png">

According to the documentation won't the first file pattern match all the .js files making the "!src/**/*Spec.js" pattern meaningless?  I might be a little confused about the semantics of the '!' symbol -- is it both a part of the regular expression _and_ flipping the value of the wallaby {ignore: } property or is it stripped from the glob pattern and used to exclude matching files?

I've tried both orderings of patterns and it doesn't seem to make a difference.

Also -- here is my jest config from package.json -- its a bit of a mystery to me how ts-jest interacts with wallaby ... 

```
  "jest": {
    "globals": {
      "ts-jest": {
        "skipBabel": true
      }
    },
    "testEnvironment": "node",
    "transform": {
      "^.+\\.tsx?$": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
    "modulePaths": ["<rootDir>/.serverless_plugins"],
    "testRegex": "(test.tsx?|test.jsx?)$",
    "moduleFileExtensions": ["ts", "tsx", "js", "json", "jsx"],
    "modulePathIgnorePatterns": ["./lib/", ".serverless"]
  }
````
### Code editor or IDE name and version

Visual Studio v 1.15.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment] 2017-09-02 00:35
Thanks for providing the logs and the config, will try to reproduce the issue.

> I'm not sure if I'm using the files[] and tests[] properties properly

Your `files`/`tests` patterns look ok to me.

> I might be a little confused about the semantics of the '!' symbol -- is it both a part of the regular expression and flipping the value of the wallaby {ignore: } property or is it stripped from the glob pattern and used to exclude matching files?

The `!` symbol in front of a pattern is just a shortcut for setting the `ignore` flag,  so `"!src/**/*Spec.js"` and `{pattern: 'src/**/*Spec.js', ignore: true}` are the same thing to wallaby.

> According to the documentation won't the first file pattern match all the .js files making the "!src/**/*Spec.js" pattern meaningless?

Good catch. The "top to bottom" rule applies to all file configuration properties, except the `ignore` property. So if a file pattern is marked as ignored, it will be ignored (excluded) regardless of its position in the `files`/`tests` list. I have updated our docs to mention it.

**Comment by ArtemGovorov** [comment] 2017-09-02 00:36
> its a bit of a mystery to me how ts-jest interacts with wallaby

Wallaby is not using `ts-jest` at all (wallaby has its own [TypeScript compiler](https://wallabyjs.com/docs/integration/typescript.html)), so there' so interaction at all.

**Comment by breathe** [comment] 2017-09-02 00:45
Beautiful -- that makes me happy to know and removes a huge "how can this possibly work" question mark that's been in my head

**Comment by ArtemGovorov** [comment] 2017-09-04 04:14
We've analysed the attached log and it looks like certain tests from the `src/AarpStack/aarp-user-info.test.ts` file are sometimes reported more than once per run. Even though I couldn't reproduce the issue locally, I have found some code in our Jest integration that could potentially be causing it. So we've fixed the suspect and released the fix in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version. Please update the core to 1.0.478 (if it hasn't yet updated automatically), and try the same scenario of editing the `src/AarpStack/aarp-user-info.ts` file and inspecting the wallaby app output.

**Comment by breathe** [comment] 2017-09-06 15:50
> We've analysed the attached log and it looks like certain tests from the src/AarpStack/aarp-user-info.test.ts file are sometimes reported more than once per run. Even though I couldn't reproduce the issue locally, I have found some code in our Jest integration that could potentially be causing it. So we've fixed the suspect and released the fix in the latest core version. Please update the core to 1.0.478 (if it hasn't yet updated automatically), and try the same scenario of editing the src/AarpStack/aarp-user-info.ts file and inspecting the wallaby app output

Amazing!!  Sorry for the delayed reply -- I was only able to get back into this today.

I've upgraded to the latest Wallaby:

```
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.480
```

and so far the issue appears to be gone!

**Closed** 2017-09-06 15:50 UTC
Labels: solution suggested
