### ISSUE TITLE
Wallaby doesn't work with require.main.require

### ISSUE THREAD

**Issue by ludydoo** [wallabyjs/public#147] opened 2015-06-07 21:34 UTC
Hi,

Requiring a module with require.main.require("/module/path") does not work

**Comment by ArtemGovorov** [comment] 2015-06-08 00:21
Hello,

Does `require.main.require("/module/path")` work for you when you're not using wallaby.js and running mocha directly?

**Comment by ludydoo** [comment] 2015-06-08 02:24
Hi. It works in mocha without wallaby when there is no leading ‘/' like require.main.require('module/path’);

**Comment by ArtemGovorov** [comment] 2015-06-08 02:45
Could you please share your wallaby.js config and `module/path` that doesn't work in wallaby but works in mocha?

**Comment by ludydoo** [comment] 2015-06-08 02:51
Sure. 

```
{
  "files": [
    "**/*.js",
    { "pattern": "node_modules/**/*", "ignore": true },
    { "pattern": "public/**/*", "ignore": true },
    { "pattern": "tests/**/*", "ignore": true },
    { "pattern": "views/**/*", "ignore": true }
  ],

  "tests": [
    "tests/*.js"
  ],

  "env" : {
    "type" : "node"
  }
}
```

Wallaby output 
```
Error: Cannot find module 'easymage/application/services/person.js'
	at tests/easymage/application/services/person.js:1

Error: Cannot find module 'easymage/domain/aggregate/person'
	at tests/easymage/ddd/repository/event-sourced.js:3

Error: Cannot find module 'easymage/domain/aggregate/person.js'
	at tests/easymage/domain/aggregate/person.js:2

Error: Cannot find module 'easymage/domain/aggregate/person.js'
	at tests/easymage/domain/repository/person.js:3

Error: Cannot find module 'easymage/infrastructure/event-store/redis.js'
	at tests/easymage/infrastructure/event-store/redis.js:2
```
All mocha test do pass.


```
Requires in person module
var EventFactory = require.main.require("easymage/ddd/factory/event.js"),
    Aggregate    = require.main.require("easymage/ddd/aggregate/core.js"),
    Locator = require.main.require("easymage/domain/model/locator.js"),
    Address = require.main.require("easymage/domain/value-objects/address.js");
```

**Comment by ludydoo** [comment] 2015-06-08 02:55
This is my directory structure for now
```
easymage
├── application
│   ├── commands
│   │   ├── addAddress.js
│   │   ├── changeAddress.js
│   │   ├── createOrganisation.js
│   │   ├── createPerson.js
│   │   ├── deleteOrganisation.js
│   │   ├── deletePerson.js
│   │   ├── removeAddress.js
│   │   ├── renameOrganisation.js
│   │   └── renamePerson.js
│   ├── events
│   ├── models
│   │   └── errors.js
│   ├── routes
│   └── services
│       ├── event-store.js
│       ├── logger.js
│       └── person.js
├── ddd
│   ├── aggregate
│   │   └── core.js
│   ├── event
│   │   └── base.js
│   ├── factory
│   │   └── event.js
│   └── repository
│       ├── core.js
│       └── event-sourced.js
├── domain
│   ├── aggregate
│   │   ├── index.js
│   │   ├── organisation.js
│   │   └── person.js
│   ├── event
│   │   ├── index.js
│   │   ├── organisation
│   │   │   ├── created.js
│   │   │   └── renamed.js
│   │   └── person
│   │       ├── activated.js
│   │       ├── address-locator-added.js
│   │       ├── address-locator-address-changed.js
│   │       ├── address-locator-deactivated.js
│   │       ├── address-locator-function-changed.js
│   │       ├── created.js
│   │       ├── deactivated.js
│   │       └── renamed.js
│   ├── factory
│   │   └── addressFactory.js
│   ├── model
│   │   ├── address-locator.js
│   │   ├── errors.js
│   │   └── locator.js
│   ├── repository
│   │   └── person.js
│   └── value-objects
│       ├── address.js
│       ├── currency.js
│       ├── email.js
│       ├── employee_budget.js
│       ├── fax.js
│       ├── mandate_budget.js
│       ├── telephone.js
│       └── website.js
└── infrastructure
    ├── db
    │   └── client
    │       └── redis.js
    └── event-store
        └── redis.js

```

**Comment by ArtemGovorov** [comment] 2015-06-08 03:01
In this directory structure, where is wallaby.js file and tests folder are located? One level up?

**Comment by ArtemGovorov** [comment] 2015-06-08 04:56
Ok, thanks, I reproduced it. The issue is fixed in wallaby.js core version 1.0.61 (will update itself automatically).
Please let me know if it works for you now.

**Closed by ArtemGovorov** 2015-06-08 04:56 UTC
Labels: bug
