### ISSUE TITLE
Regex for isolatedModules on mono repo ?

### ISSUE THREAD

**Issue by appsolutegeek** [wallabyjs/public#2085] opened 2019-05-27 10:46 UTC
Hi, 

i was checking the documentation and it states to use isolatedModules to speed up things..

It gives the following

```
    compilers: {
      '**/*.ts?(x)': w.compilers.typeScript({ isolatedModules: true })
    },
```

Problem is that I am in a mono repo AND there are potentially node_modules and "dist" folders further down the tree

I am currently getting this

```
Failed to run compilers on libs/nest-logger/dist/common/libs/stdlib-string/src/index.d.ts, Error: Debug Failure. Output generation failed
    at Object.transpileModule (/Users/ian/Development/test/projects/nest-common/node_modules/typescript/lib/typescript.js:105174:29)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

### Wallaby.js configuration file

```javascript
module.exports = function (w) {
  return {
    files: [
      'libs/**/src/**/*.ts',
      '!libs/**/src/**/*.spec.ts',
      '!**/node_modules/**/*',
      '!**/dist/*'
    ],

    tests: [
      'libs/**/src/**/*.spec.ts',
      '!**/node_modules/**/*',
      '!**/dist/*'
    ],

    compilers: {
      '**/*.ts?(x)': w.compilers.typeScript({ isolatedModules: true })
    },

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',
    debug: true
  };
};

```

### Code editor or IDE name and version

WebStorm v2019.1

### OS name and version

OSX

**Comment by appsolutegeek** [comment] 2019-05-27 12:03
I also got a strange error inside the DEBUG of wallaby.. I have no JS files - although I presume just is compiling behind the scenes ? 

I am unsure if this error is correct or not ?

```
console.error: ts-jest[jest-transformer] (WARN) Got a `.js` file to compile while `allowJs` option is not set to `true` (file: /Users/ian/Library/Caches/WebStorm2019.1/wallaby/projects/5f38c0e7951e57f7/instrumented/libs/nest-correlation/src/lib/correlation.service.spec.js). To fix this:
  - if you want TypeScript to process JS files, set `allowJs` to `true` in your TypeScript config (usually tsconfig.json)
  - if you do not want TypeScript to process your `.js` files, in your Jest config change the `transform` key which value is `ts-jest` so that it does not match `.js` files anymore
```

**Comment by appsolutegeek** [comment] 2019-05-27 12:36
And seemed to have this too 

```
console.error: ts-jest[jest-transformer] (WARN) Got a `.js` file to compile while `allowJs` option is not set to `true` (file: /Users/ian/Library/Caches/WebStorm2019.1/wallaby/wallaby/runners/node/jest@0.4.3/jasmine2Initializer.js). To fix this:
  - if you want TypeScript to process JS files, set `allowJs` to `true` in your TypeScript config (usually tsconfig.json)
  - if you do not want TypeScript to process your `.js` files, in your Jest config change the `transform` key which value is `ts-jest` so that it does not match `.js` files anymore
```

**Comment by smcenlly** [comment] 2019-05-27 21:48
I'm going to close this issue as a duplicate of #2084 as the same problems apply to this issue. Once we get everything up in running in the other issue, if `isolatedModules` isn't working, this can be re-opened or else a new issue created.

**Closed by smcenlly** 2019-05-27 21:48 UTC
