### ISSUE TITLE
PureScript support

### ISSUE THREAD

**Issue by kevinbarabash** [wallabyjs/public#2364] opened 2020-03-07 20:52 UTC
I'd like to use Wallaby with PureScript.  My understanding is that Wallaby supports compile-to-JS languages as long as the compiler for the language can generate source maps (which PureScript supports).  The thing I'm less clear is how testing frameworks affect things.  I'm using [purescript-spec](https://purescript-spec.github.io/purescript-spec/).  There is also a wrapper for jest [purescript-jest](https://github.com/nonbili/purescript-jest).  Will either of these test frameworks work with Wallaby?

**Comment by smcenlly** [comment] 2020-03-09 00:17
We took a look at [purescript](https://github.com/purescript/purescript), [purescript-spec](https://github.com/purescript-spec/purescript-spec) and [purescript-jest](https://github.com/nonbili/purescript-jest).

We can see that the purescript compiler supports sourcemaps but were unable to determine how to enable these for a project build using [pulp](https://github.com/purescript-contrib/pulp). This would need to be confirmed as sourcemaps are a pre-requisite for Wallaby to work.

Forgetting about the test framework question for a moment, the first step in supporting PureScript is to add support for compiling PureScript files for Wallaby projects. Wallaby supports compiling/transpiling single file changes as well as compiling at the project level. For example, TypeScript with `isolatedModules: true` compiles at the file level, but with `isolatedModules: false` it compiles at the project level (because of type dependencies, etc.). We're not entirely sure how PureScript works with incremental/file-by-file compilation and its type checking but expect that a post-processor will be compiled required to compile the PureScript files (**and generate source maps**). If you wanted to add support for PureScript files yourself, you could do this by creating your own PureScript post-processor; you can [read about how to do this in our docs](https://wallabyjs.com/docs/config/postprocessor.html). There are a few open-source examples of post-processors that you may refer to: [webpack](https://github.com/jeffling/wallaby-webpack), [browserify](https://github.com/wallabyjs/wallabify), and [wallaby-angular-filesort](https://github.com/ryanwischkaemper/wallaby-angular-filesort).

Once language support is added for PureScript, we would be able to determine how to add support for purescript-spec. It's possible that this could be achieved with the same post-processor mentioned above, or we may need to make a product change.

We also looked at the [purescript-jest](https://github.com/nonbili/purescript-jest) wrapper and encountered a couple of problems with its default configuration:
1) There is no sourcemap support.
2) The way jest is loading the tests means that the test file is always reported as a dummy test entry point file (`test/main.test.js`).
3) The project needs to be re-built after any changes are made.

Once the [purescript-jest](https://github.com/nonbili/purescript-jest) project is built, Wallaby runs the jest configuration successfully on the last compiled file, but doesn't show any coverage information on `.purs` files. If you were to get `npx jest --watch` working for your project with PureScript (and fix the source mapping to report `.purs` files), then Wallaby should work also.

---

We don't have any immediate plans to add a compiler/post-processor to support PureScript but are happy to work with you/support you in your efforts to do is (if you want to undertake that work). If you do want to work on this, either let us know via this issue or else email us (hello@wallabyjs.com). 

In the meantime we'll mark this issue as a feature request. Please have your team/colleagues/other PureScript users +1 your initial post so we can gauge interest in the feature.

**Comment by kevinbarabash** [comment] 2020-03-09 00:53
@smcenlly thanks for looking into this.  I'll try setting up webpack and creating a post-processor.

**Comment by kevinbarabash** [comment] 2020-03-11 04:25
I've put together an example project to try and get this working.  PureScript compiles each Foo.Bar.purs to an output folder `./output/Foo.Bar` that contains: index.js and sometimes a foreign.js which index.js imports to get access to native JS functions.  In the example project I've added `build` and `watch` scripts to the package.json which will also add `index.js.map` files to each of the folders.  The output folder also contains the compiled versions of any test modules declared in the `test` folder. 

https://github.com/kevinbarabash/wallaby-ps

It looks like my next step will be trying write a wallaby post-processor that watches the output folder and then generate calls to `createFile` with the source map data.  Is that right?  In my wallaby config should I set the `files` and `tests` properties to match .purs files in `src` and `test` respectively?

**Comment by smcenlly** [comment] 2020-03-11 23:57
@kevinbarabash - wallaby takes responsibility for watching file changes and will call into your post-processor when the files change. This means that the generation of the code and source map will need to done in the post-processor. The post-processor assumes you to return a promise, so your code may be asynchronous.

Please also note that I tried your project but was unable to build, it failed with an error: `Invalid argument `sourcemaps''`

**Comment by kevinbarabash** [comment] 2020-03-12 02:54
> Please also note that I tried your project but was unable to build, it failed with an error: Invalid argument sourcemaps''`

I thought that `spago` (one PureScript's many build tools) would use `node_modules/.bin/purs` instead of the global one.  It doesn't appear to have an option to do so at first glance.  I've updated the `build` script to call `node_modules/.bin/purs` directly if you want to give it another try.

I think I know what I need to do with post-processor now.  Thank you.

**Comment by kevinbarabash** [comment] 2020-03-12 04:09
I've updated the repo again.  I have files loading and showing up in the test explorer.  No tests are running yet.  It looks like I might need to add another call to `createFile` which creates a file that imports the `main` function from `output/Test.Main/index.js` and runs it.  I created a `run-tests.js` file on disk that does this for manual test.

**Comment by kevinbarabash** [comment] 2020-03-12 04:16
I tried doing
```
                wallaby.createFile({
                    order: Infinity,
                    path: 'run-tests.js',
                    content: 'const {main} = require("./output/Test.Main/index.js");\nmain();',
                }),
```
but I got the following error:
```
Uncaught ReferenceError: require is not defined 
```
Looking at the https://github.com/jeffling/wallaby-webpack/blob/master/index.js it looks like I need to provide an implementation of `require` that works in the browser and ensure that all .js have access to it.

**Comment by smcenlly** [comment] 2020-03-12 04:45
The reason that you're getting the error `Uncaught ReferenceError: require is not defined` is that by default Wallaby runs your test in the browser unless you override your [runner setting](https://wallabyjs.com/docs/config/runner.html). Because you've provided a transformed javascript file content that using `require()` (which is not supported in the browser), you're getting the error.

```javascript
const {main} = require("./output/Test.Main/index.js");\nmain();
```

Did you intend on running your tests in the browser? If not, you may switch to node using by changing your wallaby.js file:

```javascript
module.exports = function () {
...
    env: {
      type: 'node'
    }
...
  };
};
```

---

We also tried to take a look at your project and post-processor for you but unfortunately your project is not working for us.  When using `yarn build`, we get the following error (it looks like the problem is that we don't have a `.spago` folder):

```
C:\temp\wallaby-ps>yarn build
yarn run v1.22.0
$ yarn purs compile -g sourcemaps ".spago/*/*/src/**/*.purs" "src/**/*.purs" "test/**/*.purs"
$ C:\temp\wallaby-ps\node_modules\.bin\purs compile -g sourcemaps .spago/*/*/src/**/*.purs src/**/*.purs test/**/*.purs
purs compile: No files found using pattern: .spago/*/*/src/**/*.purs
Error 1 of 11:

  in module Main
  at src\Main.purs:3:1 - 3:15 (line 3, column 1 - line 3, column 15)

    Module Prelude was not found.
    Make sure the source file exists, and that it has been provided as an input to the compiler.


  See https://github.com/purescript/documentation/blob/master/errors/ModuleNotFound.md for more information,
  or to contribute content related to this error.

Error 2 of 11:

  in module Main
  at src\Main.purs:5:1 - 5:23 (line 5, column 1 - line 5, column 23)

    Module Effect was not found.
    Make sure the source file exists, and that it has been provided as an input to the compiler.


  See https://github.com/purescript/documentation/blob/master/errors/ModuleNotFound.md for more information,
  or to contribute content related to this error.

Error 3 of 11:

  in module Main
  at src\Main.purs:6:1 - 6:28 (line 6, column 1 - line 6, column 28)

    Module Effect.Console was not found.
    Make sure the source file exists, and that it has been provided as an input to the compiler.


  See https://github.com/purescript/documentation/blob/master/errors/ModuleNotFound.md for more information,
  or to contribute content related to this error.

Error 4 of 11:

  in module Test.Main
  at test\Main.purs:3:1 - 3:15 (line 3, column 1 - line 3, column 15)

    Module Prelude was not found.
    Make sure the source file exists, and that it has been provided as an input to the compiler.


  See https://github.com/purescript/documentation/blob/master/errors/ModuleNotFound.md for more information,
  or to contribute content related to this error.

Error 5 of 11:

  in module Test.Main
  at test\Main.purs:5:1 - 5:45 (line 5, column 1 - line 5, column 45)

    Module Data.Time.Duration was not found.
    Make sure the source file exists, and that it has been provided as an input to the compiler.


  See https://github.com/purescript/documentation/blob/master/errors/ModuleNotFound.md for more information,
  or to contribute content related to this error.

Error 6 of 11:

  in module Test.Main
  at test\Main.purs:6:1 - 6:23 (line 6, column 1 - line 6, column 23)

    Module Effect was not found.
    Make sure the source file exists, and that it has been provided as an input to the compiler.


  See https://github.com/purescript/documentation/blob/master/errors/ModuleNotFound.md for more information,
  or to contribute content related to this error.

Error 7 of 11:

  in module Test.Main
  at test\Main.purs:7:1 - 7:38 (line 7, column 1 - line 7, column 38)

    Module Effect.Aff was not found.
    Make sure the source file exists, and that it has been provided as an input to the compiler.


  See https://github.com/purescript/documentation/blob/master/errors/ModuleNotFound.md for more information,
  or to contribute content related to this error.

Error 8 of 11:

  in module Test.Main
  at test\Main.purs:8:1 - 8:41 (line 8, column 1 - line 8, column 41)

    Module Test.Spec was not found.
    Make sure the source file exists, and that it has been provided as an input to the compiler.


  See https://github.com/purescript/documentation/blob/master/errors/ModuleNotFound.md for more information,
  or to contribute content related to this error.

Error 9 of 11:

  in module Test.Main
  at test\Main.purs:9:1 - 9:42 (line 9, column 1 - line 9, column 42)

    Module Test.Spec.Assertions was not found.
    Make sure the source file exists, and that it has been provided as an input to the compiler.


  See https://github.com/purescript/documentation/blob/master/errors/ModuleNotFound.md for more information,
  or to contribute content related to this error.

Error 10 of 11:

  in module Test.Main
  at test\Main.purs:10:1 - 10:52 (line 10, column 1 - line 10, column 52)

    Module Test.Spec.Reporter.Console was not found.
    Make sure the source file exists, and that it has been provided as an input to the compiler.


  See https://github.com/purescript/documentation/blob/master/errors/ModuleNotFound.md for more information,
  or to contribute content related to this error.

Error 11 of 11:

  in module Test.Main
  at test\Main.purs:11:1 - 11:34 (line 11, column 1 - line 11, column 34)

    Module Test.Spec.Runner was not found.
    Make sure the source file exists, and that it has been provided as an input to the compiler.


  See https://github.com/purescript/documentation/blob/master/errors/ModuleNotFound.md for more information,
  or to contribute content related to this error.


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

When using `yarn watch` as per `README.md`, we get:

```
C:\temp\wallaby-ps>yarn watch
yarn run v1.22.0
$ yarn spago build --watch --purs-args '-g sourcemaps'
$ C:\temp\wallaby-ps\node_modules\.bin\spago build --watch --purs-args '-g sourcemaps'
Invalid argument `sourcemaps''
```

**Comment by kevinbarabash** [comment] 2020-03-12 12:27
I am so sorry that the installation instructions are still not right.  I've updated them to fix the missing `.spago` directory issue.  Unfortunately I don't know how to fix the issue with `watch` so please use `build` for now. 

I update wallaby.js to use `env: { type: "node" }` as you suggested it's loading the test file but runs into the following error:
```
0 failing tests, 0 passing  ​Launch Coverage & Test Explorer​ | ​Search Tests​

Cannot find module '../Control.Applicative/index.js' 
  at Object.<anonymous> ​test/Main.purs:3​
```

I changed the path from `file.path` which was reusing the original path of the to file to:
```
path: path.join("output", name, "index.js"),
```
and that fixed that issue.  The next thing I ran into was:
```
Cannot find module './foreign.js' 
  at Object.<anonymous> ​.spago/prelude/v4.1.1/src/Control/Applicative.purs:1​
  at Object.<anonymous> ​test/Main.purs:1​
```
which I should be able to fix by calling `createFile` for each of the `foreign.js` files.  Some of those `foreign.js` files will loading files from `node_modules`.  I assume that I'll have to call `createFiles` for those as well.  Should I include these files in the array of `files` in wallaby.js?

I feel like I'm making real progress on this.  I'm going to continue working on this this evening.  Thanks for your help so far.

**Comment by kevinbarabash** [comment] 2020-03-12 13:26
I solved the `foreign.js` file issue, but now wallaby appears to be trying to load/compile the .purs files even though I've set the `path` for each `createFile` call to be the associated .js file in the output folder.
```
./test/Main.purs:1 
module Test.Main where 
       ^^^^ 
 
SyntaxError: Unexpected identifier 
    at Module._compile (internal/modules/cjs/loader.js:723:23) 
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) 
    at Module.load (internal/modules/cjs/loader.js:653:32) 
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12) 
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) 
    at Module.require (internal/modules/cjs/loader.js:692:17) 
    at require (internal/modules/cjs/helpers.js:25:18) 
    at Array.forEach (<anonymous>) 
    at WebSocket.emit (events.js:198:13) 
    at afterWrite (_stream_writable.js:485:3) 
    at onwrite (_stream_writable.js:476:7) 
    at InflateRaw.afterTransform (_stream_transform.js:94:3) 
    at Zlib.processCallback (zlib.js:557:8) 
```
I'm not sure what to do about this.

**Comment by kevinbarabash** [comment] 2020-03-13 03:35
I tried setting up a custom compiler and that fixed the error in my previous message, but wallaby can't seem to find any of the files that the entry point loads.
```
[Error] Runtime error: Error: Cannot find module '../Control.Applicative/index.js' 
[Error]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:562:25) 
[Error]     at Module.require (internal/modules/cjs/loader.js:692:17) 
[Error]     at require (internal/modules/cjs/helpers.js:25:18) 
[Error]     at Object.<anonymous> (./test/Main.purs:3:46) 
[Error]     at Module._compile (internal/modules/cjs/loader.js:778:30) 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) 
[Error]     at Module.load (internal/modules/cjs/loader.js:653:32) 
[Error]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:585:3) 
[Error]     at Module.require (internal/modules/cjs/loader.js:692:17) 
[Error]     at require (internal/modules/cjs/helpers.js:25:18) 
[Error]     at Array.forEach (<anonymous>) 
[Error]     at WebSocket.emit (events.js:198:13) 
[Error]     at afterWrite (_stream_writable.js:485:3) 
[Error]     at onwrite (_stream_writable.js:476:7) 
[Error]     at InflateRaw.afterTransform (_stream_transform.js:94:3) 
[Error]     at Zlib.processCallback (zlib.js:557:8) 
```
The problem is that the *.purs files live in
```
.spago/<pkg>/<version>/src/*.purs
src/*.purs
test/*.purs
```
while the compiled .js files all end up as `/output/*/index.js` and the `require` paths are all with respect to the module's location in the `output` directory.  I tried setting up a preprocessor since I saw that there was a `rename()` method on the `file` that gets passed to the preprocessor.  I couldn't get it to work though.

**Comment by smcenlly** [comment] 2020-03-13 03:37
@kevinbarabash - nice work on making some progress. Our team spent most of today working on this for you and unfortunately were unable to get any further. There is some preliminary work that needs to be done first (in the compilation) that we couldn't work through properly (mostly because we're not familiar with PureScript). Now that we've spent a bit more time working with PureScript and seeing how it works, our advice is a little different to what it was before (but if you still want to try get this working, I don't think anything you have done to date has been a waste).

We suggest that you get everything working in Jest first instead of Wallaby. There are a few reasons for this:
1) Jest has more extension points available to you that you can take advantage of (we think you might need them).
2) The feedback loop for developing and testing PureScript integration is faster with Jest.
3) Wallaby fully supports Jest, so if you get everything working in Jest, Wallaby will just work.
4) Members of the PureScript community outside who want to use Jest and don't use Wallaby will be able to re-use what you create.
5) If you need to debug/see what is going on inside Jest, you have the full source code available to you.

**Comment by kevinbarabash** [comment] 2020-03-13 04:02
@smcenlly thanks digging into this with your team.  I really appreciated it.  I think I've figured out the path issue.  Since the files in `src` and `test` are trying to reference paths like `../Control.Applicative/index.js` that means the file would be located a `Control.Applicative/index.js` relative to the project root.  I added the following:
```
promises.push(
    wallaby.createFile({	
        path: 'Control.Applicative/index.js',	
        content: 'console.log("hello, world!")',	
    }),
)
```
to my [compiler](https://github.com/kevinbarabash/wallaby-ps/commit/f57a34095b273dbf4d8b2dd064a3435ad520c2c8) branch and sure enough that file loaded and the new error is for the next file.
```
[Error] Runtime error: Error: Cannot find module '../Control.Bind/index.js' 
[Error]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:562:25) 
[Error]     at Module.require (internal/modules/cjs/loader.js:692:17) 
...
```
It's getting a little late here.  I'll pick this up again tomorrow and put together something more polished.  I like that this is using the files in the `test` folder as entry points.

Question about the `jest` approach: would the test have to be written in JavaScript while the code under test is written in PureScript?

**Comment by smcenlly** [comment] 2020-03-13 04:11
> I think I've figured out the path issue. Since the files in src and test are trying to reference paths like ../Control.Applicative/index.js that means the file would be located a Control.Applicative/index.js relative to the project root. I added the following:

We saw the same thing, you may us `fs` to read all the files in our output folder to generate this content. You may need to be careful to exclude the files that are compiled from your project source vs. doing this for imported libraries.

> Question about the `jest` approach: would the test have to be written in JavaScript while the code under test is written in PureScript?

You could implement either way (i.e. tests written in jest, or tests written in purescript). You **would** need to switch your testing framework to use the jest library instead of of purescript-spec.

---

Please be sure to let us know how you progress. If you get this working we'd love to take a look. We'll continue to assist as/when we can.

**Comment by kevinbarabash** [comment] 2020-03-15 21:57
@smcenlly I got the tests running, but no reporting, see https://github.com/kevinbarabash/wallaby-ps/pull/1.  

After looking at the code for the mocha integraation in the wallaby plugin I see that there's a private `tracer` API that's used by a custom mocha runner to report test results to wallaby.  In order to use `purescript-spec` I'd need to write a custom runner for `purescript-spec` that makes the appropriate calls to the `tracer` API.

In the PureScript community, `purescript-spec` is much more mature and more popular so it would be awesome to get it working eventually.  Is there any chance that the `tracer` API would ever be made public?  If it were, it would allow users to add support for more niche testing frameworks.

For now though I'm going to switch gears and work on getting `purescript-jest` working.

**Comment by smcenlly** [comment] 2020-03-16 05:19
Hi @kevinbarabash - As per my previous post:

> There is some preliminary work that needs to be done first (in the compilation) that we couldn't work through properly (mostly because we're not familiar with PureScript). 

This is probably what you need to focus on first, both for jest and wallaby. We saw there is a [PureScript loader for webpack](https://github.com/ethul/purs-loader) that might be good reference material for you (at least for how to spawn and run the compiler).

To answer your question re: tracer

>  I see that there's a private tracer API that's used by a custom mocha runner to report test results to wallaby. In order to use purescript-spec I'd need to write a custom runner for purescript-spec that makes the appropriate calls to the tracer API.

Yes - in order to use `purescript-spec`, you would need to create a runner for it. We **do not** have any plans on making the tracer API public. If we get enough demand from the community, we're be happy to reconsider that position.

---

I'm going to close this issue as we don't plan to spend any more time investigating this, but as per our last, please let us know how you go with jest.

**Closed by smcenlly** 2020-03-16 05:19 UTC
Labels: feature request
