### ISSUE TITLE
TypeError: Object(...) is not a function IntelliJ Angular CLI

### ISSUE THREAD

**Issue by ed-squared** [wallabyjs/public#2206] opened 2019-09-13 15:10 UTC
### Issue description or question

After installing the plugin and setting up Wallaby.js via the tutorial for Jetbrains IDEs and Angular CLI
I run into an issue where 301 tests fail (419 pass) due to the spread operator error 
`TypeError: Object(...) is not a function`

I have setup intelliJ to use ECMAScript 6, node 11, and Typescript 3.5.2.

I've attempted to change the environment set workers to 1, and all to no avail.

It works fine on vs code.

Not sure why I am seeing this error intellij...

### Wallaby diagnostics report

```
{ editorVersion: 'IntelliJ IDEA 2019.2.1',
  pluginVersion: '1.0.138',
  editorType: 'IntelliJ',
  osVersion: 'darwin 18.7.0',
  nodeVersion: 'v11.13.0',
  coreVersion: '1.0.740',
  config:
   { trace: true,
     files:
      [ { pattern: 'wallaby.js',
          load: false,
          instrument: false,
          ignore: false,
          trigger: true,
          order: 1 },
        { pattern: 'src/**/*.+(ts|js|css|less|scss|sass|styl|html|json|svg)',
          load: false,
          ignore: false,
          trigger: true,
          instrument: true,
          order: 2 },
        { pattern: 'wallaby.js',
          load: false,
          instrument: false,
          ignore: false,
          trigger: true,
          order: 3 },
        { pattern:
           'e2e-testcafe/**/*.+(ts|js|css|less|scss|sass|styl|html|json|svg)',
          load: false,
          ignore: false,
          trigger: true,
          instrument: true,
          order: 4 },
        { pattern: 'node_modules/jquery/dist/jquery.js',
          instrument: false,
          ignore: false,
          trigger: true,
          load: true,
          order: 5 },
        { pattern:
           'node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.js',
          instrument: false,
          ignore: false,
          trigger: true,
          load: true,
          order: 6 },
        { pattern: 'node_modules/bootstrap/js/dist/util.js',
          instrument: false,
          ignore: false,
          trigger: true,
          load: true,
          order: 7 },
        { pattern: 'node_modules/bootstrap/js/dist/modal.js',
          instrument: false,
          ignore: false,
          trigger: true,
          load: true,
          order: 8 },
        { pattern: 'src/**/*spec.ts',
          ignore: true,
          trigger: true,
          load: true,
          instrument: true },
        { pattern: 'src/**/*.d.ts',
          ignore: true,
          trigger: true,
          load: true,
          instrument: true } ],
     tests:
      [ { pattern: 'src/**/*spec.ts',
          load: false,
          ignore: false,
          trigger: true,
          test: true,
          order: 9 } ],
     testFramework:
      { version: 'jasmine@3.4.0',
        configurator: 'jasmine@2.1.3',
        reporter: 'jasmine@2.1.3',
        starter: 'jasmine@2.1.3' },
     compilers: { '**/*.?(lit)coffee?(.md)': [Function] },
     preprocessors: { 'wallaby.js': [Function: wallaby.js] },
     env:
      { kind: 'chrome',
        type: 'browser',
        params: {},
        viewportSize: { width: 800, height: 600 },
        options: { width: 800, height: 600 },
        bundle: true },
     postprocessor: [Function],
     externals: { jQuery: 'jQuery' },
     filesWithNoCoverageCalculated: [],
     runAllTestsInAffectedTestFile: false,
     maxConsoleMessagesPerTest: 100,
     autoConsoleLog: true,
     delays: { run: 0, edit: 100, update: 0 },
     workers: { initial: 0, regular: 0, recycle: false },
     teardown: undefined,
     hints:
      { ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
        ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
        commentAutoLog: '?',
        testFileSelection:
         { include: '__REGEXP /file\\.only/',
           exclude: '__REGEXP /file\\.skip/' } },
     automaticTestFileSelection: true,
     runSelectedTestsOnly: false,
     extensions: {},
     reportUnhandledPromises: false,
     throwOnBeforeUnload: true,
     slowTestThreshold: 75,
     lowCoverageThreshold: 80,
     loose: undefined,
     configCode:
      'module.exports = function(wallaby) {\n    const wallabyWebpack = require(\'wallaby-webpack\');\n    const path = require(\'path\');\n    const fs = require(\'fs\');\n  \n    const specPattern = \'/**/*spec.ts\';\n    const angularConfig = require(\'./angular.json\');\n  \n    const projects = Object.keys(angularConfig.projects).map(key => {\n      return { name: key, ...angularConfig.projects[key] };\n    }).filter(project => project.sourceRoot)\n      .filter(project => project.projectType !== \'application\' || \n                         (project.architect &&\n                          project.architect.test &&\n                          project.architect.test.builder === \'@angular-devkit/build-angular:karma\'));\n  \n    const applications = projects.filter(project => project.projectType === \'application\');\n    const libraries = projects.filter(project => project.projectType === \'library\');\n  \n    const tsConfigFile = projects\n      .map(project => path.join(__dirname, project.root, \'tsconfig.spec.json\'))\n      .find(tsConfig => fs.existsSync(tsConfig));\n  \n    const tsConfigSpec = tsConfigFile ? JSON.parse(fs.readFileSync(tsConfigFile)) : {};\n  \n    const compilerOptions = Object.assign(require(\'./tsconfig.json\').compilerOptions, tsConfigSpec.compilerOptions);\n    compilerOptions.emitDecoratorMetadata = true;\n  \n    return {\n      trace: true,\n      files: [\n        { pattern: path.basename(__filename), load: false, instrument: false },\n        ...projects.map(project => ({\n          pattern: project.sourceRoot + \'/**/*.+(ts|js|css|less|scss|sass|styl|html|json|svg)\',\n          load: false\n        })),\n        { pattern: path.basename(__filename), load: false, instrument: false },\n        ...projects.map(project => ({\n          pattern: \'e2e-testcafe/**/*.+(ts|js|css|less|scss|sass|styl|html|json|svg)\',\n          load: false\n        })),\n        {pattern: "node_modules/jquery/dist/jquery.js", instrument: false},\n        {pattern: "node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.js", instrument: false},\n        {pattern: "node_modules/bootstrap/js/dist/util.js", instrument: false},\n        {pattern: "node_modules/bootstrap/js/dist/modal.js", instrument: false},\n        ...projects.map(project => ({\n          pattern: project.sourceRoot + specPattern,\n          ignore: true\n        })),\n        ...projects.map(project => ({\n          pattern: project.sourceRoot + \'/**/*.d.ts\',\n          ignore: true\n        }))\n      ],\n  \n      tests: [\n        ...projects.map(project => ({\n          pattern: project.sourceRoot + specPattern,\n          load: false\n        }))\n      ],\n  \n      testFramework: \'jasmine\',\n  \n      compilers: {\n        \'**/*.ts\': wallaby.compilers.typeScript({\n          ...compilerOptions,\n          getCustomTransformers: program => {\n            return {\n              before: [\n                require(\'@ngtools/webpack/src/transformers/replace_resources\').replaceResources(\n                  path => true,\n                  () => program.getTypeChecker(),\n                  false\n                )\n              ]\n            };\n          }\n        })\n      },\n  \n      preprocessors: {\n        /* Initialize Test Environment for Wallaby */\n        [path.basename(__filename)]: file => `\n   import \'zone.js/dist/zone-testing\';\n   import { getTestBed } from \'@angular/core/testing\';\n   import { BrowserDynamicTestingModule,  platformBrowserDynamicTesting} from \'@angular/platform-browser-dynamic/testing\';\n  \n   getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());`\n      },\n  \n      middleware: function(app, express) {\n        const path = require(\'path\');\n  \n        applications.forEach(application => {\n          if (\n            !application.architect ||\n            !application.architect.test ||\n            !application.architect.test.options ||\n            !application.architect.test.options.assets\n          ) {\n            return;\n          }\n  \n          application.architect.test.options.assets.forEach(asset => {\n            if (asset && !asset.glob) {\n              // Only works for file assets (not globs)\n              // (https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/asset-configuration.md#project-assets)\n              app.use(asset.slice(application.sourceRoot.length), express.static(path.join(__dirname, asset)));\n            }\n          });\n        });\n      },\n  \n      env: {\n        kind: \'chrome\'\n      },\n  \n      postprocessor: wallabyWebpack({\n        entryPatterns: [\n          ...applications\n            .map(project => project.sourceRoot + \'/polyfills.js\')\n            .filter(polyfills => fs.existsSync(path.join(__dirname, polyfills.replace(/js$/, \'ts\')))),\n          path.basename(__filename),\n          ...projects.map(project => project.sourceRoot + specPattern.replace(/ts$/, \'js\'))\n        ],\n  \n        module: {\n          rules: [\n            { test: /\\.css$/, loader: [\'raw-loader\'] },\n            { test: /\\.html$/, loader: \'raw-loader\' },\n            {\n              test: /\\.ts$/,\n              loader: \'@ngtools/webpack\',\n              include: /node_modules/,\n              query: { tsConfigPath: \'tsconfig.json\' }\n            },\n            { test: /\\.styl$/, loaders: [\'raw-loader\', \'stylus-loader\'] },\n            { test: /\\.less$/, loaders: [\'raw-loader\', { loader: \'less-loader\' }] },\n            {\n              test: /\\.scss$|\\.sass$/,\n              loaders: [{ loader: \'raw-loader\' }, { loader: \'sass-loader\' }]\n            },\n            { test: /\\.(jpg|png|svg)$/, loader: \'raw-loader\' }\n          ]\n        },\n  \n        resolve: {\n          extensions: [\'.js\', \'.ts\'],\n          modules: [\n            wallaby.projectCacheDir,\n            ...(projects.length ? projects.filter(project => project.root)\n              .map(project => path.join(wallaby.projectCacheDir, project.root)) : []),\n            ...(projects.length ? projects.filter(project => project.sourceRoot)\n              .map(project => path.join(wallaby.projectCacheDir,project.sourceRoot)) : []),\n            \'node_modules\'\n          ],\n          alias: libraries.reduce((result, project) => {\n            result[project.name] = path.join(wallaby.projectCacheDir, project.sourceRoot, \'public-api\');\n            return result;\n          }, {})\n        }\n      }),\n  \n      setup: function() {\n        window.__moduleBundler.loadTests();\n      },\n      externals: { jQuery: "jQuery" }\n    };\n  };\n' },
  packageJSON:
   { dependencies:
      { '@angular/animations': '^6.1.0',
        '@angular/common': '^6.1.0',
        '@angular/compiler': '^6.1.0',
        '@angular/core': '^6.1.0',
        '@angular/forms': '^6.1.0',
        '@angular/http': '^6.1.0',
        '@angular/platform-browser': '^6.1.0',
        '@angular/platform-browser-dynamic': '^6.1.0',
        '@angular/router': '^6.1.0',
        'angular2-draggable': '^2.1.4',
        'angular2-multiselect-dropdown': '^4.0.0',
        'angular2-text-mask': '^8.0.5',
        bootstrap: '4.1.1',
        'bootstrap-datepicker': '^1.8.0',
        'core-js': '^2.5.4',
        intl: '^1.2.5',
        jquery: '^3.3.1',
        lodash: '^4.17.10',
        moment: '^2.22.2',
        'ng5-slider': '^1.1.14',
        'ngx-quill': '^3.6.0',
        'ngx-webstorage': '^2.0.1',
        'popper.js': '1.14.3',
        qtip2: '^3.0.3',
        quill: '^1.3.6',
        rxjs: '^6.0.0',
        'zone.js': '~0.8.26' },
     devDependencies:
      { '@angular-devkit/build-angular': '~0.7.0',
        '@angular/cli': '~6.1.5',
        '@angular/compiler-cli': '^6.1.0',
        '@angular/language-service': '^6.1.0',
        '@types/bootstrap': '^4.1.0',
        '@types/bootstrap-datepicker': '0.0.10',
        '@types/core-js': '^0.9.46',
        '@types/jasmine': '~2.8.6',
        '@types/jasminewd2': '~2.0.3',
        '@types/jquery': '^3.3.2',
        '@types/lodash': '^4.14.109',
        '@types/node': '~8.9.4',
        '@types/qtip2': '^2.2.29',
        codelyzer: '~4.2.1',
        immer: '^1.8.0',
        'jasmine-core': '^2.99.1',
        'jasmine-spec-reporter': '~4.2.1',
        karma: '~1.7.1',
        'karma-chrome-launcher': '~2.2.0',
        'karma-coverage-istanbul-reporter': '~2.0.0',
        'karma-jasmine': '~1.1.1',
        'karma-jasmine-html-reporter': '^0.2.2',
        'ng-mocks': '^6.2.3',
        'ng2-mock-component': '^0.1.1',
        protractor: '~5.4.0',
        testcafe: '^0.22.0',
        'testcafe-live': '^0.1.3',
        'ts-node': '~5.0.1',
        tslint: '~5.11.0',
        typescript: '^2.8.4',
        'wallaby-webpack': '^3.9.15' } },
  fs: { numberOfFiles: 3035 },
  debug: [] }
```

**Comment by smcenlly** [comment] 2019-09-14 23:50
Wallaby uses the version of TypeScript found in your `node_modules`. The version of TypeScript specified in your `devDependencies` is TypeScript `^2.8.4`, which means at most, your TypeScript version will be `2.9.2", possibly a version between `2.8.4` and `2.9.2` if you have a `package-lock.json` file.

Could you please update your `node_modules` to use the same version of TypeScript that you've specified in your IntelliJ settings (`3.5.2`) and see if that solves the problem?

If your problem persists, can you please provide us with your TypeScript configuration file(s)?

**Comment by ed-squared** [comment] 2019-09-16 14:54
That didn't work... :(  I guess I don't understand why it would matter whether we are using 2.8.4 or 3.5.2. The spread operator was available in Typescript by version 2.1 .
Here is the tsconfig file for the app:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

**Comment by smcenlly** [comment] 2019-09-16 22:08
> That didn't work... :( I guess I don't understand why it would matter whether we are using 2.8.4 or 3.5.2. The spread operator was available in Typescript by version 2.1.

Yep - I wasn't sure it would work either, but was the only issue I could spot with your project.

> It works fine on vs code.

Can you confirm that you're trying VS Code on the same directory, on the same PC? If not, could you please try cloning to a new directory and confirming you have the same problem using IntelliJ on the new directory?

---

In terms of next steps, can you please provide us with a sample repo that has the same problem? We don't need any of your actual application code, just the minimal set of dependencies/code to reproduce the issue.

**Comment by smcenlly** [comment] 2019-09-19 22:23
@ed-squared - are you able to provide us with a sample repo that has the same problem, or were you able to fix this another way?

**Comment by edmo-jpg** [comment] 2019-09-25 21:03
Hi @smcenlly I'm an associate of @ed-squared 
I have tried to recreate the issue with a sample repo using angular-cli, and a minimal amount of code involving a spread operator to try and recreate the issue. The sample repo used the same `package.json` and `wallaby.js` config as the failing project for consistency, as well as the same version of Node and typescript.

Oddly, I was unable to reproduce the issue in the sample repo, and my test involving the spread operator worked. We are continuing to investigate and attempting to replicate the issue.

**Comment by smcenlly** [comment] 2019-09-25 21:58
@edmo-jpg - thanks for the update. We'll keep the issue open for now and will wait to hear back from you. Hopefully you will be able to spot the difference between the sample repo and your main repo to identify the cause of the problem.

**Comment by smcenlly** [comment] 2019-10-02 05:44
@edmo-jpg - we're going to close this issue for now. If you haven't found a solution, let us know and provide us with a sample to reproduce the problem and we will re-open the issue.

**Closed by smcenlly** 2019-10-02 05:44 UTC
