### ISSUE TITLE
Wallaby erroneously reports "​​​Possibly incompatible/unsupported Jest version"

### ISSUE THREAD

**Issue by Peeja** [wallabyjs/public#3197] opened 2023-04-05 16:51 UTC
### Issue description or question

Steps to reproduce:
* Create a Next.js/SWC project with Jest.
* Run Wallaby.
* Look at Wallaby.js Console output.

Wallaby attempts to patch `next/dist/build/swc/jest-transformer.js`. It applies two patches, one which matches `return((0, _index).transformSync(src, {`, and one which matches `return (0, _index).transformSync(src, {`. I assume these correspond to different versions of SWC. Only one should be expected to match. However, the patching logic emits `​​​Possibly incompatible/unsupported Jest version` if *any* patch fails to match. In this case, we should never expect both patches to match; they're only there to cover for different versions of SWC.

I'm guessing this was just a mistake, and the best solution is to have the patcher report only if applying *all* the patches has no effect, rather than if any one has no effect.

### Wallaby diagnostics report

<details>
<summary>Report</summary>

```
{
  editorVersion: '1.76.2',
  pluginVersion: '1.0.351',
  editorType: 'VSCode',
  osVersion: 'darwin 20.6.0',
  nodeVersion: 'v16.14.2',
  coreVersion: '1.0.1404',
  checksum: 'N2RjMTEwMTAwMDIyNmY0YjU1MDc5NGZkODYzZjBlYzAsMTcwNjU3MjgwMDAwMCww',
  config: {
    env: {
      type: 'node',
      runner: '<homeDir>/.nvm/versions/node/v18.15.0/bin/node',
      params: { runner: '--experimental-vm-modules' },
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/private/var/folders/86/909pcqwd7pg1t7xf5z_4h4f40000gn/T/jest_dx',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/clients/m-ld/m-ld-react-demo',
              dependencyExtractor: undefined,
              detectLeaks: false,
              detectOpenHandles: false,
              displayName: undefined,
              errorOnDeprecated: false,
              extensionsToTreatAsEsm: [],
              fakeTimers: { enableGlobally: false },
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, enableSymlinks: false, forceNodeFilesystemAPI: true, throwOnModuleCollision: false },
              id: '5122a8c86d0c1f75c63c3e11a91c7ff6',
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [
                'js',   'mjs',
                'cjs',  'jsx',
                'ts',   'tsx',
                'json', 'node'
              ],
              moduleNameMapper: [
                [
                  '^.+\\.module\\.(css|sass|scss)$',
                  '<homeDir>/clients/m-ld/m-ld-react-demo/node_modules/.pnpm/next@13.2.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/jest/object-proxy.js'
                ],
                [
                  '^.+\\.(css|sass|scss)$',
                  '<homeDir>/clients/m-ld/m-ld-react-demo/node_modules/.pnpm/next@13.2.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/jest/__mocks__/styleMock.js'
                ],
                [
                  '^.+\\.(png|jpg|jpeg|gif|webp|avif|ico|bmp)$',
                  '<homeDir>/clients/m-ld/m-ld-react-demo/node_modules/.pnpm/next@13.2.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/jest/__mocks__/fileMock.js'
                ],
                [
                  '^.+\\.(svg)$',
                  '<homeDir>/clients/m-ld/m-ld-react-demo/node_modules/.pnpm/next@13.2.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/jest/__mocks__/fileMock.js'
                ],
                [
                  '@next/font/(.*)',
                  '<homeDir>/clients/m-ld/m-ld-react-demo/node_modules/.pnpm/next@13.2.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/jest/__mocks__/nextFontMock.js'
                ],
                [
                  'next/font/(.*)',
                  '<homeDir>/clients/m-ld/m-ld-react-demo/node_modules/.pnpm/next@13.2.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/jest/__mocks__/nextFontMock.js'
                ]
              ],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<homeDir>/clients/m-ld/m-ld-react-demo',
              roots: [ '<homeDir>/clients/m-ld/m-ld-react-demo' ],
              runner: '<homeDir>/clients/m-ld/m-ld-react-demo/node_modules/.pnpm/jest-runner@29.4.3/node_modules/jest-runner/build/index.js',
              runtime: undefined,
              sandboxInjectedGlobals: [],
              setupFiles: [],
              setupFilesAfterEnv: [],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotFormat: { escapeString: false, printBasicPrototype: false },
              snapshotResolver: undefined,
              snapshotSerializers: [],
              testEnvironment: '<homeDir>/clients/m-ld/m-ld-react-demo/node_modules/.pnpm/jest-environment-node@29.4.3/node_modules/jest-environment-node/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
              testPathIgnorePatterns: [ '/node_modules/', '/.next/' ],
              testRegex: [],
              testRunner: '<homeDir>/clients/m-ld/m-ld-react-demo/node_modules/.pnpm/jest-circus@29.4.3/node_modules/jest-circus/runner.js',
              transform: [
                [
                  '^.+\\.(js|jsx|ts|tsx|mjs)$',
                  '<homeDir>/clients/m-ld/m-ld-react-demo/node_modules/.pnpm/next@13.2.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/swc/jest-transformer.js',
                  {
                    nextConfig: {
                      env: {},
                      webpack: null,
                      webpackDevMiddleware: null,
                      eslint: { ignoreDuringBuilds: false },
                      typescript: { ignoreBuildErrors: false, tsconfigPath: 'tsconfig.json' },
                      distDir: '.next',
                      cleanDistDir: true,
                      assetPrefix: '',
                      configOrigin: 'next.config.js',
                      useFileSystemPublicRoutes: true,
                      generateBuildId: [Function: generateBuildId],
                      generateEtags: true,
                      pageExtensions: [ 'tsx', 'ts', 'jsx', 'js' ],
                      target: 'server',
                      poweredByHeader: true,
                      compress: true,
                      analyticsId: '',
                      images: {
                        deviceSizes: [
                           640,  750,  828,
                          1080, 1200, 1920,
                          2048, 3840
                        ],
                        imageSizes: [
                          16,  32,  48,  64,
                          96, 128, 256, 384
                        ],
                        path: '/_next/image',
                        loader: 'default',
                        loaderFile: '',
                        domains: [],
                        disableStaticImages: false,
                        minimumCacheTTL: 60,
                        formats: [ 'image/webp' ],
                        dangerouslyAllowSVG: false,
                        contentSecurityPolicy: "script-src 'none'; frame-src 'none'; sandbox;",
                        contentDispositionType: 'inline',
                        remotePatterns: [],
                        unoptimized: false
                      },
                      devIndicators: { buildActivity: true, buildActivityPosition: 'bottom-right' },
                      onDemandEntries: { maxInactiveAge: 15000, pagesBufferLength: 2 },
                      amp: { canonicalBase: '' },
                      basePath: '',
                      sassOptions: {},
                      trailingSlash: false,
                      i18n: null,
                      productionBrowserSourceMaps: false,
                      optimizeFonts: true,
                      excludeDefaultMomentLocales: true,
                      serverRuntimeConfig: {},
                      publicRuntimeConfig: {},
                      reactStrictMode: true,
                      httpAgentOptions: { keepAlive: true },
                      outputFileTracing: true,
                      staticPageGenerationTimeout: 60,
                      swcMinify: true,
                      output: undefined,
                      modularizeImports: undefined,
                      experimental: {
                        clientRouterFilter: false,
                        preCompiledNextServer: false,
                        fetchCacheKeyPrefix: '',
                        middlewarePrefetch: 'flexible',
                        optimisticClientCache: true,
                        runtime: undefined,
                        manualClientBasePath: false,
                        legacyBrowsers: false,
                        newNextLinkBehavior: true,
                        cpus: 15,
                        sharedPool: true,
                        isrFlushToDisk: true,
                        workerThreads: false,
                        pageEnv: false,
                        proxyTimeout: undefined,
                        optimizeCss: false,
                        nextScriptWorkers: false,
                        scrollRestoration: false,
                        externalDir: false,
                        disableOptimizedLoading: false,
                        gzipSize: true,
                        swcFileReading: true,
                        craCompat: false,
                        esmExternals: true,
                        appDir: false,
                        isrMemoryCacheSize: 52428800,
                        incrementalCacheHandlerPath: undefined,
                        fullySpecified: false,
                        outputFileTracingRoot: '<homeDir>/clients/m-ld/m-ld-react-demo',
                        swcTraceProfiling: false,
                        forceSwcTransforms: false,
                        swcPlugins: undefined,
                        largePageDataBytes: 128000,
                        disablePostcssPresetEnv: undefined,
                        amp: undefined,
                        urlImports: undefined,
                        enableUndici: false,
                        adjustFontFallbacks: false,
                        adjustFontFallbacksWithSizeAdjust: false,
                        turbo: undefined,
                        turbotrace: undefined,
                        typedRoutes: false,
                        instrumentationHook: false
                      },
                      configFile: '<homeDir>/clients/m-ld/m-ld-react-demo/next.config.js',
                      configFileName: 'next.config.js'
                    },
                    jsConfig: {
                      compilerOptions: {
                        target: 2,
                        lib: [ 'lib.dom.d.ts', 'lib.dom.iterable.d.ts', 'lib.esnext.d.ts' ],
                        allowJs: true,
                        skipLibCheck: true,
                        strict: true,
                        forceConsistentCasingInFileNames: true,
                        noEmit: true,
                        esModuleInterop: true,
                        module: 99,
                        moduleResolution: 2,
                        resolveJsonModule: true,
                        isolatedModules: true,
                        jsx: 1,
                        incremental: true,
                        baseUrl: '<homeDir>/clients/m-ld/m-ld-react-demo',
                        paths: { '@/*': [ './src/*' ] },
                        pathsBasePath: '<homeDir>/clients/m-ld/m-ld-react-demo',
                        configFilePath: undefined
                      }
                    },
                    resolvedBaseUrl: '<homeDir>/clients/m-ld/m-ld-react-demo',
                    hasServerComponents: false,
                    isEsmProject: false,
                    pagesDir: '<homeDir>/clients/m-ld/m-ld-react-demo/src/pages'
                  }
                ]
              ],
              transformIgnorePatterns: [ '/node_modules/', '^.+\\.module\\.(css|sass|scss)$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: [ '/.next/' ]
            }
          ],
          globalConfig: {
            bail: 0,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            ci: false,
            collectCoverage: false,
            collectCoverageFrom: [],
            coverageDirectory: '<homeDir>/clients/m-ld/m-ld-react-demo/coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: undefined,
            detectLeaks: false,
            detectOpenHandles: false,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: false,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 15,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: false,
            projects: [],
            replname: undefined,
            reporters: undefined,
            rootDir: '<homeDir>/clients/m-ld/m-ld-react-demo',
            runTestsByPath: false,
            seed: -1553492621,
            shard: undefined,
            showSeed: undefined,
            silent: undefined,
            skipFilter: false,
            snapshotFormat: { escapeString: false, printBasicPrototype: false },
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/clients/m-ld/m-ld-react-demo/node_modules/.pnpm/@jest+test-sequencer@29.4.3/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true,
            workerIdleMemoryLimit: undefined
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/private/var/folders/86/909pcqwd7pg1t7xf5z_4h4f40000gn/T/jest_dx', '/.next/', '\\./coverage' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/', '/private/var/folders/86/909pcqwd7pg1t7xf5z_4h4f40000gn/T/jest_dx', '/.next/', '\\./coverage' ],
            testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
            testRegex: []
          }
        }
      }
    },
    filesWithCoverageCalculated: [],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    dot: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, file: true, test: true },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        file: true,
        test: true
      },
      {
        pattern: '/private/var/folders/86/909pcqwd7pg1t7xf5z_4h4f40000gn/T/jest_dx',
        regexp: /\/private\/var\/folders\/86\/909pcqwd7pg1t7xf5z_4h4f40000gn\/T\/jest_dx/,
        ignore: true,
        trigger: true,
        load: true,
        file: true,
        test: true
      },
      { pattern: '/.next/', regexp: /\/.next\//, ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true, file: true }
    ],
    captureConsoleLog: true,
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true, file: false },
      {
        pattern: '\\./dist/|\\./build/|\\./coverage/|\\./git/|/\\..+/',
        regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\.\/git\/|\/\..+\//,
        ignore: true,
        trigger: true,
        load: true,
        test: true,
        file: false
      },
      {
        pattern: '/private/var/folders/86/909pcqwd7pg1t7xf5z_4h4f40000gn/T/jest_dx',
        regexp: /\/private\/var\/folders\/86\/909pcqwd7pg1t7xf5z_4h4f40000gn\/T\/jest_dx/,
        ignore: true,
        trigger: true,
        load: true,
        test: true,
        file: false
      },
      { pattern: '/.next/', regexp: /\/.next\//, ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '\\./coverage', regexp: /\.\/coverage/, ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
      { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: false,
    configCode: 'module.exports = function () {\n' +
      '  process.env.NO_WATCHMAN = true;\n' +
      '\n' +
      '  return {\n' +
      '    env: {\n' +
      '      type: "node",\n' +
      '      runner: "<homeDir>/.nvm/versions/node/v18.15.0/bin/node",\n' +
      '      params: {\n' +
      '        runner: "--experimental-vm-modules",\n' +
      '      },\n' +
      '    },\n' +
      '  };\n' +
      '};\n'
  },
  packageJSON: {
    dependencies: {
      '@m-ld/m-ld': '^0.9.1',
      '@types/node': '18.14.1',
      '@types/react': '18.0.28',
      '@types/react-dom': '18.0.11',
      classnames: '2.3.2',
      'into-stream': '7.0.0',
      jsonld: '8.1.1',
      'memory-level': '^1.0.0',
      n3: '^1.16.3',
      next: '13.2.1',
      react: '18.2.0',
      'react-dom': '18.2.0',
      'readable-stream': '4.3.0',
      rxjs: '^7.8.0',
      sparqlalgebrajs: '4.0.5',
      'todomvc-app-css': '2.4.2',
      'todomvc-common': '1.0.5',
      typescript: '4.9.5'
    },
    devDependencies: {
      '@comunica/query-sparql-rdfjs': '2.6.10',
      '@graphy/memory.dataset.fast': '4.3.6',
      '@rdfjs/types': '^1.1.0',
      '@types/jest': '^29.4.0',
      '@types/n3': '^1.10.4',
      '@types/readable-stream': '^2.3.15',
      eslint: '8.34.0',
      'eslint-config-next': '13.2.1',
      jest: '^29.4.3',
      'rxjs-for-await': '^1.0.0',
      'ts-node': '^10.9.1'
    }
  },
  fs: { numberOfFiles: 32 },
  debug: [
    '2023-04-05T16:48:39.785Z config Attempting automatic configuration for angular\n',
    '2023-04-05T16:48:39.788Z angular/cli config Angular CLI not found.\n',
    '2023-04-05T16:48:39.788Z config Finished attempting automatic configuration for angular (4ms)\n',
    '2023-04-05T16:48:39.788Z config Attempting automatic configuration for jest\n',
    '2023-04-05T16:48:56.014Z jest/config Detected Jest.\n',
    '2023-04-05T16:48:56.014Z jest/config Configured Jest.\n',
    '2023-04-05T16:48:56.014Z config Finished attempting automatic configuration for jest (16226ms)\n',
    '2023-04-05T16:48:56.018Z project Wallaby Node version: v16.14.2\n',
    '2023-04-05T16:48:56.018Z project Wallaby config: <homeDir>/clients/m-ld/m-ld-react-demo/wallaby.js\n',
    '2023-04-05T16:48:56.036Z fs File system starting\n',
    '2023-04-05T16:48:56.067Z fs File system scan completed\n',
    '2023-04-05T16:48:56.076Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.351/projects/cd6143835f2d63ce\n',
    '2023-04-05T16:48:56.194Z uiService Listening port 51235\n',
    '2023-04-05T16:48:56.208Z workers Parallelism for initial run: 14, for regular run: 7\n',
    '2023-04-05T16:48:56.208Z workers Starting run worker instance #0\n',
    '2023-04-05T16:48:56.208Z workers Starting run worker instance #1\n',
    '2023-04-05T16:48:56.208Z workers Starting run worker instance #2\n',
    '2023-04-05T16:48:56.208Z workers Starting run worker instance #3\n',
    '2023-04-05T16:48:56.208Z workers Starting run worker instance #4\n',
    '2023-04-05T16:48:56.208Z workers Starting run worker instance #5\n',
    '2023-04-05T16:48:56.208Z workers Starting run worker instance #6\n',
    '2023-04-05T16:48:56.208Z workers Starting run worker instance #7\n',
    '2023-04-05T16:48:56.208Z workers Starting run worker instance #8\n',
    '2023-04-05T16:48:56.208Z workers Starting run worker instance #9\n',
    '2023-04-05T16:48:56.209Z workers Starting run worker instance #10\n',
    '2023-04-05T16:48:56.209Z workers Starting run worker instance #11\n',
    '2023-04-05T16:48:56.209Z workers Starting run worker instance #12\n',
    '2023-04-05T16:48:56.209Z workers Starting run worker instance #13\n',
    '2023-04-05T16:48:56.209Z workers Web server is listening at 60618\n',
    '2023-04-05T16:48:56.620Z project Stopping process pool\n',
    '2023-04-05T16:48:56.620Z project File cache is up-to-date, starting full test run\n',
    '2023-04-05T16:48:56.646Z project Test run started; run priority: 3\n',
    '2023-04-05T16:48:56.654Z project Running all tests\n',
    '2023-04-05T16:48:56.673Z workers Starting test run, priority: 3\n',
    '2023-04-05T16:48:56.673Z workers Distributing tests between 14 workers\n',
    '2023-04-05T16:48:56.674Z workers Running tests in parallel\n',
    '2023-04-05T16:48:56.674Z nodeRunner Starting sandbox [worker #0, session #5sawk]\n',
    '2023-04-05T16:48:56.719Z nodeRunner Starting sandbox [worker #1, session #efdiv]\n',
    '2023-04-05T16:48:56.719Z nodeRunner Starting sandbox [worker #2, session #pgk5r]\n',
    '2023-04-05T16:48:56.720Z nodeRunner Preparing sandbox [worker #0, session #5sawk]\n',
    '2023-04-05T16:48:56.720Z nodeRunner Preparing sandbox [worker #1, session #efdiv]\n',
    '2023-04-05T16:48:56.720Z nodeRunner Preparing sandbox [worker #2, session #pgk5r]\n',
    '2023-04-05T16:48:56.743Z workers Started run worker instance (delayed) #0\n',
    '2023-04-05T16:48:56.743Z nodeRunner Prepared sandbox [worker #0, session #5sawk]\n',
    '2023-04-05T16:48:56.744Z workers [worker #0, session #5sawk] Running tests in sandbox\n',
    '2023-04-05T16:48:56.745Z workers Started run worker instance (delayed) #1\n',
    '2023-04-05T16:48:56.745Z nodeRunner Prepared sandbox [worker #1, session #efdiv]\n',
    '2023-04-05T16:48:56.745Z workers [worker #1, session #efdiv] Running tests in sandbox\n',
    '2023-04-05T16:48:56.745Z workers Started run worker instance (delayed) #2\n',
    '2023-04-05T16:48:56.746Z nodeRunner Prepared sandbox [worker #2, session #pgk5r]\n',
    '2023-04-05T16:48:56.746Z workers [worker #2, session #pgk5r] Running tests in sandbox\n',
    '2023-04-05T16:48:56.747Z workers Started run worker instance (delayed) #3\n',
    '2023-04-05T16:48:56.749Z workers Started run worker instance (delayed) #4\n',
    '2023-04-05T16:48:56.750Z workers Started run worker instance (delayed) #5\n',
    '2023-04-05T16:48:56.753Z workers Started run worker instance (delayed) #6\n',
    '2023-04-05T16:48:56.754Z workers Started run worker instance (delayed) #7\n',
    '2023-04-05T16:48:56.755Z workers Started run worker instance (delayed) #8\n',
    '2023-04-05T16:48:56.756Z workers Started run worker instance (delayed) #9\n',
    '2023-04-05T16:48:56.756Z workers Started run worker instance (delayed) #11\n',
    '2023-04-05T16:48:56.756Z workers Started run worker instance (delayed) #10\n',
    '2023-04-05T16:48:56.759Z workers Started run worker instance (delayed) #12\n',
    '2023-04-05T16:48:56.784Z workers Started run worker instance (delayed) #13\n',
    '2023-04-05T16:49:13.802Z workers Scheduling Jest Test Run (efdiv): 2023-04-05T16:49:13.370Z\n',
    '2023-04-05T16:49:13.804Z workers [efdiv] Loaded unknown number of test(s)\n',
    '2023-04-05T16:49:13.804Z workers [efdiv] Test executed: \n',
    '2023-04-05T16:49:13.806Z workers [efdiv] Run 1 test(s), skipped 0 test(s)\n',
    '2023-04-05T16:49:13.806Z workers Jest Test Run Complete (efdiv): 2023-04-05T16:49:13.799Z\n',
    '2023-04-05T16:49:13.808Z workers [efdiv] Sandbox is responsive, closing it\n',
    '2023-04-05T16:49:14.390Z workers Scheduling Jest Test Run (5sawk): 2023-04-05T16:49:13.355Z\n',
    '2023-04-05T16:49:14.420Z workers [5sawk] Loaded unknown number of test(s)\n',
    '2023-04-05T16:49:14.431Z workers [5sawk] Test executed: can be cloned\n',
    '2023-04-05T16:49:14.466Z workers [5sawk] Test executed: can deliver updates\n',
    '2023-04-05T16:49:14.472Z workers [5sawk] Run 2 test(s), skipped 0 test(s)\n',
    '2023-04-05T16:49:14.473Z workers Jest Test Run Complete (5sawk): 2023-04-05T16:49:14.465Z\n',
    '2023-04-05T16:49:14.475Z workers [5sawk] Sandbox is responsive, closing it\n',
    '2023-04-05T16:49:16.057Z workers Scheduling Jest Test Run (pgk5r): 2023-04-05T16:49:13.354Z\n',
    '2023-04-05T16:49:16.058Z workers [pgk5r] Loaded unknown number of test(s)\n',
    '2023-04-05T16:49:16.059Z workers [pgk5r] Test executed: should fetch and frame a single property by @id\n',
    '2023-04-05T16:49:16.063Z workers [pgk5r] Test executed: should fetch and frame multiple properties by @id\n',
    '2023-04-05T16:49:16.066Z workers [pgk5r] Test executed: should fetch and frame by other properties\n',
    '2023-04-05T16:49:16.066Z workers [pgk5r] Test executed: should fetch and frame child objects\n',
    '2023-04-05T16:49:16.067Z workers [pgk5r] Test executed: should fetch and frame within nested objects\n',
    '2023-04-05T16:49:16.069Z workers [pgk5r] Run 5 test(s), skipped 0 test(s)\n',
    '2023-04-05T16:49:16.069Z workers Jest Test Run Complete (pgk5r): 2023-04-05T16:49:16.054Z\n',
    '2023-04-05T16:49:16.072Z workers [pgk5r] Sandbox is responsive, closing it\n',
    '2023-04-05T16:49:16.072Z workers Merging parallel test run results\n',
    '2023-04-05T16:49:16.073Z project Test run finished\n',
    '2023-04-05T16:49:16.073Z project Processed console.log entries\n',
    '2023-04-05T16:49:16.073Z project Processed loading sequences\n',
    '2023-04-05T16:49:16.074Z project Processed executed tests\n',
    '2023-04-05T16:49:16.075Z project Processed code coverage\n',
    '2023-04-05T16:49:16.089Z project Test run result processed and sent to IDE\n'
  ]
}
```
</details>

**Comment by ArtemGovorov** [comment] 2023-04-06 00:11
Thanks for the report! The issue is now fixed and the fix is published in [the latest core v1.0.1405](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update)

**Closed by ArtemGovorov** 2023-04-06 00:11 UTC

**Comment by heysanyam** [comment] 2023-05-25 04:10
@ArtemGovorov still facing the issue
<img width="941" alt="image" src="https://github.com/wallabyjs/public/assets/126690801/8f555751-963f-45a1-89d8-9b49efc04805">

**Comment by smcenlly** [comment] 2023-05-25 04:19
Thanks for reporting the problem. This was actually a regression based on a change we made today. This has been fixed in the latest version of Wallaby core, `v1.0.1426`. Please update to the latest version, it will fix your problem.
