### ISSUE TITLE
Wallaby not check coverage, when return object with spread

### ISSUE THREAD

**Issue by ipostol** [wallabyjs/public#963] opened 2017-01-20 17:20 UTC
### Wallaby not check return object with spread;

Hello, have some problem with code coverage in switch/case http://prntscr.com/dy5lew

```js
switch (action.type) {

    case CHANGE_DETAIL:
      return {
        ...state,
        detail: action.id,
      };

}
```

If you have spread operator in you returned object, wallaby not check this;

When remove spread wallaby start check code coverage http://prntscr.com/dy5ltg

```js
switch (action.type) {

    case CHANGE_DETAIL:
      return {
        detail: action.id,
      };

}
```

### Wallaby.js configuration file

```javascript
process.env.BABEL_ENV = 'wallaby';
process.env.TZ = 'utc';

module.exports = wallaby => {
  return {
    files: [
      {pattern: 'src/**/*.js', load: true, instrument: true},
      {pattern: 'src/**/*.scss', load: false, instrument: true},
      {pattern: 'src/**/*.css', load: false, instrument: true},
      {pattern: 'src/**/*.json', load: false, instrument: true},
      {pattern: 'src/**/*.png', load: false, instrument: true},
      {pattern: 'src/**/*.svg', load: false, instrument: true},

      '!src/**/*test.js',
      '!src/**/*docs.js'
    ],

    filesWithNoCoverageCalculated: [
      'src/*.js',
      'src/analytics/**/*.js',
      'src/redux/create.js',
      'src/containers/**/*.js',
      'src/consts/**/*.js',
      'src/helpers/**/*.js',
      'src/theme/**/*.js',
      'src/utils/localStorage/**/*.js',
      'src/utils/*.js',
      'src/utils/scroll/**/*.js',
      'src/utils/dom/**/*.js',
      'src/utils/fontName/**/*.js',
    ],

    tests: [
      {pattern: 'src/**/*.test.js', load: true},
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
    },
    testFramework: 'mocha',
    setup() {
      require('./src/tests/jsdom.js');
      require('babel-polyfill');

      /* eslint-disable */
      navigator = {
        userAgent: 'test'
      };
      process.env.TZ = 'utc';
      /* eslint-enable */

    },
    debug: false,
    env: {
      type: 'node',
      params: {
        runner: ''
      }
    },
    workers: {
      initial: 4,
      regular: 2,
    },
    // delays: {
    //   run: 500
    // },
    hints: {
      ignoreCoverage: /ignore coverage/ /* ignore coverage: use for disable code coverage */
    },
  };
};

```

### Code editor or IDE name and version
Sublime Text v3

### OS name and version
OSX

**Comment by ArtemGovorov** [comment] 2017-01-23 01:25
Thanks for the detailed report. The issue is fixed in the [latest core v1.0.354](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Closed by ArtemGovorov** 2017-01-23 01:25 UTC
Labels: bug

**Comment by ipostol** [comment] 2017-03-02 16:52
@ArtemGovorov, Hello, can you check this problem now?, i have her still :(

**Comment by ArtemGovorov** [comment] 2017-03-03 01:35
@ipostol Just checked using the exact code that you've provided and it's working for me:

<img width="385" alt="screen shot 2017-03-03 at 11 33 56 am" src="https://cloud.githubusercontent.com/assets/979966/23534711/77cae698-0005-11e7-867c-76f46fee54c7.png">


Please create a sample repo where I could reproduce the issue.

**Comment by ipostol** [comment] 2017-03-05 19:59
@ArtemGovorov, hello again, i am find problem:

If i remove transform-runtime plugin from .babelrc, and all work ok, when i am add them, coverage on spread don`t working correctly. Now i not need this plugin, i am remove them and all ok, i think is not problem for now.

.babelrc
```
{
  "plugins": ["transform-runtime"]
}
```

I'm sorry to trouble you.
