### ISSUE TITLE
Support for ava v4

### ISSUE THREAD

**Issue by jsbrain** [wallabyjs/public#2780] opened 2021-08-24 13:48 UTC
### Issue description or question

Newest version of `ava` seems to not be supported. Probably due to changes to the lib exports?

```
ava node module is not found or the version is not supported, missing `npm install ava --save-dev`? 
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/assert' is not defined by "exports" in ./node_modules/ava/package.json 
    at new NodeError (node:internal/errors:363:5) 
    at throwExportsNotFound (node:internal/modules/esm/resolve:335:9) 
    at packageExportsResolve (node:internal/modules/esm/resolve:560:3) 
    at resolveExports (node:internal/modules/cjs/loader:476:36) 
    at Function.Module._findPath (node:internal/modules/cjs/loader:516:31) 
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:913:27) 
    at Function.Module._load (node:internal/modules/cjs/loader:772:27) 
    at Module.require (node:internal/modules/cjs/loader:999:19) 
    at require (node:internal/modules/cjs/helpers:93:18) 
    at Module._compile (node:internal/modules/cjs/loader:1095:14) 
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10) 
    at Module.load (node:internal/modules/cjs/loader:975:32) 
    at Function.Module._load (node:internal/modules/cjs/loader:816:12) 
    at Module.require (node:internal/modules/cjs/loader:999:19) 
    at require (node:internal/modules/cjs/helpers:93:18) 
    at Module._compile (node:internal/modules/cjs/loader:1095:14) 
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10) 
    at Module.load (node:internal/modules/cjs/loader:975:32) 
    at Function.Module._load (node:internal/modules/cjs/loader:816:12) 
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) 
    at node:internal/main/run_main_module:17:47 
```

**Comment by smcenlly** [comment] 2021-08-24 22:27
Thanks for reporting the problem. The issue is because of this change: https://github.com/avajs/ava/commit/5e0844452fb919bbd5253fe7435fe1d69f5751d5

The change updates `package.json` to use the `exports` which encapsulates internal modules that have not been publicly exposed. Unfortunately Wallaby needs access to these.

We're considering the best way of fixing this.

Do you have any idea when version 4 will be released?

**Comment by smcenlly** [comment] 2021-08-25 01:51
We've added support for Ava v4 from Wallaby core `v1.0.1134`. Please update to the latest version and it will work for you.

**Closed by smcenlly** 2021-08-25 01:51 UTC

**Comment by jsbrain** [comment] 2021-08-25 08:28
Amazing! Thanks do the quick fix!
Not sure when they release v4 but it's been in alpha since the beginning of the year so I expect pretty soon.
