### ISSUE TITLE
Node Jasmine Tests

### ISSUE THREAD

**Issue by daw451-duplicate** [wallabyjs/public#305] opened 2015-10-26 14:28 UTC
Trying out the product... all of our existing tests for node are done in jasmine.

You do not support jasmine tests for node????? Just want to make sure that i am not doing something wrong....

Of course i am getting the following:

ReferenceError: beforeAll is not defined

module.exports = function (wallaby) {
    return {
        files: [
            { pattern: 'lib/logger.js', instrument: false, load: true, ignore: false },
            { pattern: 'lib/http_constants.js', instrument: false, load: true, ignore: false },
            { pattern: 'config/config.json', instrument: false, load: true, ignore: false },
            { pattern: 'config/default.json', instrument: false, load: true, ignore: false },
            { pattern: 'config/development.json', instrument: false, load: true, ignore: false },
            'routes/v1.0/*.js'
        ],

        tests: [
            'test/api/*.spec.js'
        ],

        // for node.js tests you need to set env property as well
        // http://wallabyjs.com/docs/integration/node.html
        env: {
            // use 'node' type to use node.js
            type: 'node'
}
        }
    };
};

**Comment by ArtemGovorov** [comment] 2015-10-26 22:57
Hello,

You are not doing anything wrong, we [don't yet support jasmine for node](http://wallabyjs.com/docs/integration/overview.html#supported-testing-frameworks) (only mocha and jest). There's a plan to support it pretty soon.
Closing as a duplicate of https://github.com/wallabyjs/public/issues/21

**Closed by ArtemGovorov** 2015-10-26 22:57 UTC
Labels: duplicate

**Comment by daw451-duplicate** [comment] 2015-10-28 13:48
when you say soon... can you estimate?

also i wrote in to get an extended license... cause we have a complex existing application and i am having a lot of issues getting wallaby to work. I never heard back is that possible?

**Comment by ArtemGovorov** [comment] 2015-10-28 22:58
@daw451-duplicate ETA: today or tomorrow. I have actually sent you the extended license key yesterday (assuming your email looks like `a....@da.......s.com`). If you haven' received it, please send me an email to artem.govorov@gmail.com and I'll send it to you again.

**Comment by ArtemGovorov** [comment] 2015-10-29 01:12
@daw451-duplicate Jasmine for node support is implemented now - https://github.com/wallabyjs/public/issues/21
