### ISSUE TITLE
Sublime Text 3 Error

### ISSUE THREAD

**Issue by seantimm** [wallabyjs/public#748] opened 2016-08-19 00:00 UTC
I just setup a trial of Wallaby w/ Sublime Text 3.  It was working fine up until the first time that Wallaby timed out.  I closed the editor and reopened, and now I get the following stack trace in the console:

Exception in thread Thread-1567:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "<string>", line 860, in documentUpdatesNotification
  File "<string>", line 866, in drawIndicators
RuntimeError: dictionary changed size during iteration

The tests themselves appear to still be running, but I can't open the Wallaby Console to see the friendly error anymore (just get a white panel).
### Wallaby.js configuration file

`````` javascript
module.exports = function (wallaby) {
    return {
        files: [
            'src/portal.web/app/**/*.js',
            { pattern: 'src/portal.web/app/**/*.test.js', ignore: true }
        ],

        tests: [
            'src/portal.web/app/**/*.test.js'
        ], 

        env: {
            type: 'node',
        },

        testFramework: 'jest',

        setup: function (wallaby) {
            wallaby.testFramework.configure({
                "automock": false,
                "rootDir": "src/portal.web/app",
                "testRegex": ".*\\.test\\.js$",
                "verbose": true
            })
        },

        compilers: {
            'src/portal.web/app/**/*.js': wallaby.compilers.babel({
                babel: require('babel-core'),
                presets: ['es2015', 'react'],
                plugins: ['transform-object-rest-spread']
            })
        }
    }
};```

### Code editor or IDE name and version
Sublime Text v3 Dev Channel Build 3120

### OS name and version
OSX 10.11.6
``````

**Comment by ArtemGovorov** [comment] 2016-08-19 04:28
Thanks for the error message.
Can't reproduced it locally, but hopefully found the piece of code that could be causing it. I have published the 1.0.23 version (should be available within an hour or so). Please try updating to the latest and try again. Before you try, please close all Sublime Text instances and after you start the editor but before running wallaby, try closing all opened files.

**Comment by seantimm** [comment] 2016-08-19 17:15
The error appears to have cleared up, but I was still able to get it where the Output: Wallabyjs panel was just white with nothing showing.  A bit of monkeying around turning Wallabyjs off and on and opening the right .js files seemed to kick start it.

It seems like I can repro it by making sure Sublime has no files open when I first open it (with my previous project still opened), start Wallaby, and then open the Wallabyjs panel.  It'll be all white, and I can't get it to go black and show any details without hiding the panel, opening some files, and turning Wallaby back on.

**Comment by ArtemGovorov** [comment] 2016-08-22 05:57
Can't reproduce it yet. Here's what I'm doing:
- open a project, start wallaby, open any file with reported coverage
- open another project in a second window (no files opened), start wallaby, open wallaby panel

If I do so, wallaby panel open normally for me. I also tried a few variations, like having more than 2 projects, having files opened/closed in the first project, opening/closing wallaby panel on all opened projects.

![s](https://cloud.githubusercontent.com/assets/979966/17844871/174a4a0a-6881-11e6-8cbc-e2f7264ec79f.gif)

Perhaps you can spot what am I missing or doing differently?

**Comment by ArtemGovorov** [comment] 2016-12-13 09:21
Closing the issue for now, please let me know if it's still valid and you can share a sample project so I may have a look.

**Closed by ArtemGovorov** 2016-12-13 09:21 UTC
Labels: Sublime Text
