### ISSUE TITLE
Wallaby Webpack with partially modular project

### ISSUE THREAD

**Issue by eranshabi** [wallabyjs/public#968] opened 2017-01-23 10:18 UTC
### Issue description or question
We want to convert a large project to ES6 modules but want Wallaby to work while the conversion is in progress.
We are using TypeScript, Angular and Webpack.

So in my config all files with `.notModule` in their name are old not modular style files, and I have two files which are modular: `productPageApp.ts` and `productPageAppWrapper.ts` (the entry).

The error I get is `Error: [$injector:nomod] Module 'productPageApp' is not available! ` which to my understanding means that the files from the Webpack entry weren't really loaded.

My karma and webpack configuration works, so I think It's something about wallaby-webpack.
Thanks.

### Wallaby.js configuration file

```javascript
const wallabyWebpack = require('wallaby-webpack');
const webpack = require('webpack');
const angularTemplatePreprocessor = require('wallaby-ng-html2js-preprocessor');

const webpackPostprocessor = wallabyWebpack({
	entryPatterns: [
		'app/modules/productPageAppWrapper.js'
	],
	module: {
		plugins: [
			new webpack.IgnorePlugin(/externals/)
		],
		loaders: [
			{
				test: /\.html$/,
				loader: 'html-loader'
			}, {
				test: /\.scss$/,
				loader: 'null-loader'
			}
		]
	},
	externals: {
		"angular": "angular",
		"jquery": "jQuery",
		"lodash": "_",
	}
});

module.exports = () => {
	return {
		files: [
			// deleted all third parties from here as not related to the issue
			'app/test/mock/**/*.ts',
			'app/test/mock/**/*.js',
			'app/**/*.html',
			{
				pattern: 		'app/modules/productPageAppWrapper.ts',
				load: false
			},
			{
				pattern: 		'app/modules/productPageApp.ts',
				load: false
			},
			'app/modules/**/*.notModule.ts',
			'!app/modules/**/*.spec.notModule.ts',
		],
		tests: [
			{
				pattern: 'app/modules/**/*.spec.notModule.ts',
				load: false
			},
		],
		debug: true,
		testFramework: 'jasmine',
		postprocessor: webpackPostprocessor,
		bootstrap: function () {
			window.__moduleBundler.loadTests();
		},
		preprocessors: {
			'app/**/*.html': function (file) {
				return angularTemplatePreprocessor.transform(file, {
					stripPrefix: 'app/',
					moduleName: 'productPageTemplates'
				})
			}
		}
	}
};
```

### Code editor or IDE name and version

WebStorm 2016.3.2
### OS name and version

OSX

**Comment by ArtemGovorov** [comment] 2017-01-23 10:29
I'm not sure if it's related to the issue, but your [`entryPatterns` should contain your test patterns](https://wallabyjs.com/docs/integration/webpack.html#entry-patterns) as well:
```javascript
const webpackPostprocessor = wallabyWebpack({
	entryPatterns: [
		'app/modules/productPageAppWrapper.js', 'app/modules/**/*.spec.notModule.js'
	],
...
```

If fixing it doesn't resolve the issue, could you please tell, and in which file the `productPageApp` module is registered? Is it the `app/modules/productPageApp.ts` and it is imported from the `app/modules/productPageAppWrapper.js` file? What else is done in the `app/modules/productPageAppWrapper.js` file?

**Comment by eranshabi** [comment] 2017-01-23 10:41
Thanks for the quick answer!
Adding the tests didn't solve the issue.
`productPageApp` module is registered in `app/modules/productPageApp.ts` and imported from `productPageAppWrapper.ts` which looks like this:

```
 import productPageApp from './productPageApp';

export default angular
	.module('productPageAppWrapper', [
		..dependencies...
		productPageApp,
		...more dependencies...
                ]).name;
```

**Comment by ArtemGovorov** [comment] 2017-01-23 10:46
Given that the error is raised for missing **`'productPageApp'`** module, and you are registering 

```
        ...
	.module('productPageAppWrapper', [ // <-- not productPageApp
```

perhaps it is the issue?

**Comment by eranshabi** [comment] 2017-01-23 10:53
No, the error is raised from some other file which loads afterward. I load this module on some of my tests like this:`module('productPageApp')`

**Comment by ArtemGovorov** [comment] 2017-01-23 11:05
Where the `productPageApp` module is registered, in the `app/modules/productPageApp.ts`?

> error is raised from some other file which loads afterward

What file is it? If it is one of your `app/modules/**/*.notModule.ts` files? Because your `app/modules/**/*.notModule.ts` files are loaded **before** the `app/modules/productPageAppWrapper.js` file. These file are just included as scripts into the HTML sandbox and the `app/modules/productPageAppWrapper.js` is loaded as an entry point afterwards (but before tests) .

**Comment by ArtemGovorov** [comment] 2017-01-23 11:35
I waht I suggested in the previous comment is true, try this:
- add your `*.notModule` file to the entry patterns, but after your proper modules:
```javascript
const webpackPostprocessor = wallabyWebpack({
	entryPatterns: [
		'app/modules/productPageAppWrapper.js', 
                'app/modules/**/!(*.spec).notModule.js'
                'app/modules/**/*.spec.notModule.js'
	],
```
- set `load: false` for them:
```javascript
...
files: [
  ...
  { pattern: 'app/modules/**/*.notModule.ts', load: false },
  '!app/modules/**/*.spec.notModule.ts',
],
...
```
This way the `app/modules/**/*.notModule.ts` files be loaded **after** the `app/modules/productPageAppWrapper.js` (and after the `productPageApp` is registered).

**Comment by eranshabi** [comment] 2017-01-24 07:52
Now I get `a dependency to an entry point is not allowed`

**Comment by ArtemGovorov** [comment] 2017-01-24 07:56
Is any of the `app/modules/**/!(*.spec).notModule.ts` files required/imported as a dependency in `app/modules/productPageAppWrapper.ts` or any of the tests `app/modules/**/*.spec.notModule.ts`?

**Comment by eranshabi** [comment] 2017-01-24 08:15
Yes. Is there a workaround?

**Comment by ArtemGovorov** [comment] 2017-01-24 08:22
Trying to think of some workarounds. 
Just to clarify something: why some of the `app/modules/**/!(*.spec).notModule.ts` are required/imported as a dependency is they are not modules? Perhaps you can exclude those files from the `entryPatterns` pattern and include them as script with `load: true` (just those files that are imported from entry points)?

**Comment by eranshabi** [comment] 2017-01-24 09:16
It's this way because I have both modular and non modular files that use the files you asked about.
What you suggested resulted the same error.

**Comment by ArtemGovorov** [comment] 2017-01-24 09:24
I'm a bit lost trying to understand your scenario. 
You confirmed that something imports your non modular files, correct? They are non modular, so why something imports any of the non modular files?

Perhaps you could put together a small repo demonstrating the issue and reflecting your dependencies structure? Once I have it and fully understand what's going on, I may be able to suggest a workaround or even implement something in the `wallaby-webpack` module to support your scenario. Without some sample I don't know where to start and how to verify any of my workarounds.

**Comment by felixmosh** [comment] 2017-01-25 22:12
@ArtemGovorov, i`v created a demo repo with the bug.
https://github.com/felixmosh/wallaby-bug

**Comment by ArtemGovorov** [comment] 2017-01-25 23:55
@felixmosh Thanks for the repo. I have [sent the PR](https://github.com/felixmosh/wallaby-bug/pull/1) with [the idea I suggested earlier](https://github.com/wallabyjs/public/issues/968#issuecomment-274465140) and it's working. 

As I understand, in your real project you are getting the `dependency to an entry point is not allowed` when you try this approach, correct? If it's correct, please update the repo to reproduce the `dependency to an entry point is not allowed`, I'm happy to investigate it further.

**Comment by felixmosh** [comment] 2017-01-26 07:10
First of all, thank you for your quick reply!

I`ve updated the example to be more accurate...

**Comment by ArtemGovorov** [comment] 2017-01-26 07:32
@felixmosh Have sent you [another PR](https://github.com/felixmosh/wallaby-bug/pull/2): added the `app` file to the `entryPatterns` list. The test are failing in the repo currently, but the failure is not wallaby.js specific: the `src/wellcome/welcome.spec.notModule.ts` file is using global `WellcomeDriver`, but the `src/wellcome/welcome.notModule.ts` file doesn't expose the class globally.

**Comment by felixmosh** [comment] 2017-01-26 09:12
Why do you added the app.js to the entry?
appWrapper is importing it...

**Comment by ArtemGovorov** [comment] 2017-01-26 09:42
@felixmosh `appWrapper` in the repo [only contains one line](https://github.com/felixmosh/wallaby-bug/blob/master/src/appWrapper.ts#L2) and is not importing anything. Am I missing something?

**Comment by felixmosh** [comment] 2017-01-26 10:29
Yeah, i forgot to revert the code...
so appWrapper should import the app...

**Comment by ArtemGovorov** [comment] 2017-01-26 12:36
@felixmosh I fully see the issue, thanks. As promised, I have added a new setting to `wallaby-webpack` (so please update it to v0.0.32 in the sample and your real app), that allows to respect the position of the entry patterns in the `files` list.

By default, all files with `load: true` are loaded as scripts before any webpack-ed files. And now I have added a new setting that allows to preserve webpack-ed entry files order in the `files` list. So in your sample with the `preserveEntryFileLoadOrder : true` set, and the following order of the files:
```javascript
...
{pattern: 'src/appWrapper.ts', load: false},
'src/**/*.notModule.ts',
...
```
the `src/appWrapper.ts` used as the entry pattern, will be loaded before any of the `src/**/*.notModule.ts` files.

Please try it and let me know if it works for you.

**Comment by felixmosh** [comment] 2017-01-26 17:38
Thanx!

I will try it on the real project. 
thank you again.

**Comment by felixmosh** [comment] 2017-01-26 18:13
It did`nt solved the issue, basically, how it works in karma, (with that partially approach in mind), is the webpack bundles whatever he can reach through the entry point, and that bundle is loaded as karma`s files.
So the webpack knows files only files without `.notNodule` suffix.
Whenever you  suggested to put `.notNodule` files as an entry for webpack we introduce other problems (like, previously files exposed some vars on global but whenever they bundled with webpack those globals wont be available in the global...)

The basic solution in my opinion would be to load the bundles before the files, @ArtemGovorov  WDYT?

**Comment by ArtemGovorov** [comment] 2017-01-27 03:22
> Whenever you suggested to put .notNodule files as an entry for webpack we introduce other problems

I understand, but we are [not doing it in the sample anymore](https://github.com/felixmosh/wallaby-bug/blob/master/wallaby.conf.js#L4).

> The basic solution in my opinion would be to load the bundles before the files, @ArtemGovorov WDYT?

This is **exactly what I have implemented with the `preserveEntryFileLoadOrder` setting**. With the setting, wallaby respects the order in the `files` list, and like karma loads the bundle with entry files before `.notNodule`, if the entry files appear higher than `.notNodule` in the `files` list.

Your sample works for me now with my last PR that you have merged. As I have mentioned you also need to update `wallaby-webpack` module to the latest version.

The sample works, because 
- the `preserveEntryFileLoadOrder: true,` is set (in the wallabyWebpack settings),
- [`src/**/*.spec.notModule.ts` are below the `src/appWrapper.ts` in the `files` list](https://github.com/felixmosh/wallaby-bug/blob/master/wallaby.conf.js#L35).

So the `src/appWrapper.ts` (and the imported `src/app.ts`) load before `src/**/*.spec.notModule.ts` and everything is working.

> Now i'm getting Angular's unknown module... cause some file (.notModule one) tries to register on on the module that webpack bundles, and probably it not available there.

Please make sure you've done everything like in the sample. If it's still the case, please update the sample to demonstrate the issue.

**Comment by felixmosh** [comment] 2017-01-27 11:30
Ok, silly me, i`ve forgot to update the npm before :]
So i needed to order some include and positioning but eventually `preserveEntryFileLoadOrder: true` did it`s magic.

Thank you so much @ArtemGovorov

**Comment by ArtemGovorov** [comment] 2017-01-27 11:31
Awesome, thanks for the update!

**Closed by ArtemGovorov** 2017-01-27 11:31 UTC
