### ISSUE TITLE
Inconsistent jest snapshot

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1154] opened 2017-05-09 21:47 UTC
### Issue description or question

I am seeing a snapshot pass using Jest command line, but fails with Wallaby. Any ideas what I am doing wrong here?

Thank you!

```
git:(develop) ✗ jest
   ...
Test Suites: 44 passed, 44 total
Tests:       293 passed, 293 total
Snapshots:   17 passed, 17 total
Time:        3.789s, estimated 5s
Ran all test suites.
```

```js
// wallaby.js result: 
	expect(value).toMatchSnapshot()
	
	Received value does not match stored snapshot 1.
	
	- Snapshot
	+ Received
	
	@@ -13,11 +13,11 @@
	     }
	   />
	   <Connect(Component)
	     action="tag"
	   />
	-  <Connect(Thanks)
	+  <Connect(Component)
	     config={
	       Object {
	         "pageTitle": "Thank You!",
	       }
	
```

### Wallaby.js configuration file

``wallaby.js``
```javascript
/* eslint strict:off, global-require:off */

'use strict';

module.exports = (wallaby) => {
    return ({
        files: [
            'src/**/*.js',
            'src/**/*.snap',

            'src/**/*.scss',

            'jest.config.js',
            'setup_jest.js',
            '.env',

            '!src/**/*.test.js',
        ],

        tests: [
            'src/**/*.test.js',
        ],

        compilers: {
            '**/*.js': wallaby.compilers.babel(),
        },

        env: {
            type: 'node',
            runner: 'node',
        },

        testFramework: 'jest',

        delays: {
            // run: 500,
        },

        // https://github.com/wallabyjs/public/issues/465
        workers: { initial: 1, regular: 1 },
        setup: (w) => {
            const jestConfig = require('./jest.config');
            w.testFramework.configure(jestConfig);
        },
    });
};
```

``jest.config.js``
```js
/* eslint strict:off, global-require:off */

'use strict';

module.exports = {
    roots: [
        '<rootDir>/src/',
    ],
    moduleNameMapper: {
        '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$': '<rootDir>/__mocks__/file_mock.js',
        '\\.(css|scss)$': 'identity-obj-proxy',
    },
    moduleFileExtensions: [
        'js',
        'jsx',
    ],
    moduleDirectories: [
        'node_modules',
        'src',
    ],
    setupFiles: [
        '<rootDir>/setup_jest.js',
    ],
    testEnvironment: 'jsdom',
    verbose: false,
};
```

``.babelrc``
```js
{
    "env": {
        "test": {
            "passPerPreset": false,
            "presets": [
                [
                    "env",
                    {
                        "targets": {
                            "node": 6.9
                        },
                        "exclude": ["transform-regenerator"],
                        // "modules": false,
                        "useBuiltIns": true,
                        "debug": false
                    }
                ],
                "react"
            ],
            "plugins": [
                "rewire",
                "transform-object-rest-spread"
            ]
        }
    }
}
```

``setup_jest.js``
```js
/* eslint strict:off, global-require:off */

'use strict';

require('babel-polyfill');
const noop = require('node-noop').noop;

process.env.MOCK_REQUESTS = 'false';
process.env.NODE_ENV = 'test';
process.env.HOST = 'https://localhost';
process.env.PORT = '443';

global.__CLIENT__ = false;
global.__SERVER__ = true;
global.__DEVELOPMENT__ = false;
global.__TESTING__ = true;
global.__PRODUCTION_RELEASE__ = true;

global.__GIT_REVISION__ = JSON.stringify('');
global.__DEVTOOLS__ = false;
global.__SENTRY_DISABLE__ = true;

global.Raven = {
    captureException: noop,
    captureMessage: noop,
};
```
### Code editor or IDE name and version

```
WebStorm 2017.1.3 EAP
Build #WS-171.4424.20, built on May 3, 2017
Licensed to Discover Media, Inc / Chris Blossom
You have a perpetual fallback license for this version
Subscription is active until December 29, 2018
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4
```
### OS name and version

``OSX 10.12.4``

**Comment by ArtemGovorov** [comment] 2017-05-10 01:40
It's hard to tell without a sample where we could reproduce it. 

I have created this sample branch: https://github.com/wallabyjs/wallaby-jest-snapshots/tree/1154 with your setup/config files and a simple component, and it's working as expected. Please try the repo to see if it's working for you, and if so, try adding the missing bits from your project to break it. I'll then jump in to see what's going on.

**Comment by chrisblossom** [comment] 2017-05-22 22:13
@ArtemGovorov sorry it took me so long to get back to you. Here is an example repo:

https://github.com/chrisblossom/wallaby-issue-1154

**Comment by ArtemGovorov** [comment] 2017-05-23 06:15
@chrisblossom Thanks for the repo! 
The issue is fixed in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). After the update, make sure to clean wallaby cache by changing your wallaby config file (adding a space anywhere it it is enough) and restarting wallaby.

**Closed by ArtemGovorov** 2017-05-23 06:15 UTC
Labels: bug, reproducible example is required
