### ISSUE TITLE
Issues with typescript + react + webpack postprocessor

### ISSUE THREAD

**Issue by rokoroku** [wallabyjs/public#1138] opened 2017-05-03 04:07 UTC
### Issue description or question
Typescript React + Wallaby-webpack postprocess emit wrong output.
I can think this issue is related with `wallaby.compilers.typescript()`, so I post the issue here.

The problem is that `import`ed (or `require`ed) components in `*.ts` and `*.tsx` files have been disappeared after processing from wallaby compiler. 

for example, given **index.tsx**
```typescript
import * as React from 'react';
import { Provider } from 'mobx-react';
import { useStrict } from 'mobx';
import { Redirect, Route, Router, Switch } from 'react-router-dom';
import { Root } from './containers/Root';
import { RootStores } from './stores';
import { ProviderUtils, assert } from './utils';
import { LazyRoute, NotFound } from './components';
import { DISABLE_SIGNUP, PATH_APP, PATH_LOGIN } from './constants';

// enable MobX strict mode
useStrict(true);

// prepare root DOM object
export function createDOM(stores: RootStores) {
  const uiStore = ProviderUtils.getUIStore(stores);
  assert(uiStore, 'UIStore should be provided.');

  return (
    <Provider {...stores} >
      <Root>
        <Router history={uiStore.getHistory()}>
          <Switch>
            {/* Use System.import() to implement lazy route */}
            <LazyRoute path={PATH_APP} imports={System.import('app/containers/App')} />
            <LazyRoute path={PATH_LOGIN} imports={System.import('app/containers/Login')} />
            {!DISABLE_SIGNUP && (
              <LazyRoute path={PATH_SIGNUP} imports={System.import('app/containers/Signup')} />
            )}
            <Redirect from="/" to={PATH_LOGIN} />
            <Route component={NotFound} />
          </Switch>
        </Router>
      </Root>
    </Provider >
  );
}
```

will be transpiled to **index.js**
```javascript
'use strict';
$_$wp(8);
$_$w(8, 0), Object.defineProperty(exports, '__esModule', { value: true });
var tslib_1 = ($_$w(8, 1), require('tslib'));
var React = ($_$w(8, 2), require('react'));
var mobx_react_1 = ($_$w(8, 3), require('mobx-react'));
var mobx_1 = ($_$w(8, 4), require('mobx'));
var utils_1 = ($_$w(8, 5), require('./utils'));
$_$w(8, 6), mobx_1.useStrict(true);
function createDOM(stores) {
    $_$wf(8);
    var uiStore = ($_$w(8, 7), utils_1.ProviderUtils.getUIStore(stores));
    $_$w(8, 8), utils_1.assert(uiStore, 'UIStore should be provided.');
    return $_$w(8, 9), React.createElement(mobx_react_1.Provider, tslib_1.__assign({}, stores), React.createElement(Root_1.Root, null, React.createElement(react_router_dom_1.Router, { history: uiStore.getHistory() }, React.createElement(react_router_dom_1.Switch, null, React.createElement(components_1.LazyRoute, {
        path: constants_1.PATH_APP,
        imports: System.import('app/containers/App')
    }), React.createElement(components_1.LazyRoute, {
        path: constants_1.PATH_LOGIN,
        imports: System.import('app/containers/Login')
    }), ($_$w(8, 10), !constants_1.DISABLE_SIGNUP) && ($_$w(8, 11), React.createElement(components_1.LazyRoute, {
        path: constants_1.PATH_SIGNUP,
        imports: System.import('app/containers/Signup')
    }), React.createElement(react_router_dom_1.Redirect, {
        from: '/',
        to: constants_1.PATH_LOGIN
    }), React.createElement(react_router_dom_1.Route, { component: components_1.NotFound })))));
}
$_$w(8, 12), exports.createDOM = createDOM;
$_$wpe(8);
```

As you can see, `import { Root } from './containers/Root';` and `import { LazyRoute, NotFound } from './components';` has been disappeared from output and eventually test also failed with these errors:
```
Can't find variable: Root​
      at createDOM ​src/app/index.tsx:22:2​
      at ​test/main.spec.tsx:42:2​

Can't find variable: LazyRoute
      ...

```

It worked well in the past, but someday only wallabyjs started spewing errors.  
(My another testing framework `karma` still works with same webpack configurations.)

 
### Webpack configuration file
```javascript
var webpack = require('webpack');

module.exports = {
  target: 'web',
  resolve: {
    extensions: ['.js', '.ts', '.tsx'],
    modules: ['src', 'node_modules'],
    mainFields: [/* 'module', */ 'browser', 'main']
  },
  module: {
    loaders: [
      { test: /\.tsx?$/, loader: 'awesome-typescript-loader' },
      { test: /\.json$/, loader: 'json-loader' },
      { test: /\.css$/, loader: 'noop-loader' },
      { test: /\.(png|svg|jpg)$/, loader: 'file-loader?emitFile=false' },
    ],
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('test'),
      'process.env.API_HOST': JSON.stringify(process.env.API_HOST || 'http://localhost:8000'),
      'process.env.DISABLE_SIGNUP': Boolean(process.env.DISABLE_SIGNUP),
      'process.env.DISABLE_CREATE_BOT': Boolean(process.env.DISABLE_CREATE_BOT),
      'process.env.DISABLE_INCOMPLETE': Boolean(process.env.DISABLE_INCOMPLETE),
      'process.env.DISABLE_EXPERIMENTAL': Boolean(process.env.DISABLE_EXPERIMENTAL),
    }),
    new webpack.ProvidePlugin({
      chai: 'chai',
      react: 'react/dist/react-with-addons',
      React: 'react/dist/react-with-addons',
    }),
    new webpack.NormalModuleReplacementPlugin(/\.(css)$/, 'node-noop'),

    // Conditional requires workaround
    // https://github.com/airbnb/enzyme/issues/47
    // https://github.com/airbnb/enzyme/blob/master/docs/guides/webpack.md
    new webpack.IgnorePlugin(/react\/addons/),
    new webpack.IgnorePlugin(/react\/lib\/ReactContext/),
    new webpack.IgnorePlugin(/react\/lib\/ExecutionEnvironment/)
  ],
  externals: {
    // Do not bundle React to the test bundle
    'react': 'React',
    'react-dom': 'ReactDOM',
    // Conditional requires workaround
    // https://github.com/airbnb/enzyme/issues/47
    // https://github.com/airbnb/enzyme/blob/master/docs/guides/webpack.md
    'react/addons': 'react',
    'react/lib/ReactContext': true,
    'react/lib/ExecutionEnvironment': true,
    'fs': true,
    'net': true,
    'jsdom': 'window',
    'cheerio': 'window',
    'expect': 'chai/expect'
  },

  // stats configuration since webpack 2.1, seems not work yet.
  // https://webpack.js.org/configuration/stats/#stats
  stats: 'none',
  devServer: {
    stats: 'errors-only',
  }
};

```
### Wallaby.js configuration file

```javascript
var path = require('path');
var webpack = require('webpack');
var wallabyWebpack = require('wallaby-webpack');
var webpackConfig = require('./webpack.test.config');

module.exports = function (wallaby) {

  webpackConfig.context = path.join(wallaby.projectCacheDir, 'src');
  var webpackPostprocessor = wallabyWebpack(webpackConfig);

  return {
    files: [
      { pattern: 'node_modules/babel-polyfill/browser.js', instrument: false },
      { pattern: 'node_modules/chai/chai.js', instrument: false },
      { pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false },
      { pattern: 'node_modules/react-dom/dist/react-dom.js', instrument: false },
      { pattern: 'src/mixins/**/*', instrument: false },
      { pattern: 'src/assets/**/*', load: false },
      { pattern: 'src/**/*.{ts,tsx}', load: false },
      { pattern: 'src/**/*.d.ts', ignore: true },
      { pattern: 'test/**/*.spec.{ts,tsx}', ignore: true },
    ],
    tests: [
      { pattern: 'test/**/*.spec.{ts,tsx}', load: false },
    ],
    compilers: {
      '**/*.{ts,tsx}': wallaby.compilers.typeScript({
        jsx: 'react',
        module: 'commonjs'
      }),
    },
    postprocessor: webpackPostprocessor,
    testFramework: 'mocha',
    setup: function (wallaby) {
      window.expect = chai.expect;

      // required to trigger test loading
      window.__moduleBundler.loadTests();
    }
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.11
Typescript 2.3.1
Wallaby.js Core 1.0.419

### OS name and version

OSX 10.12.4

**Comment by ArtemGovorov** [comment] 2017-05-03 04:27
Could you please also share your `tsconfig.json` and `package.json` files?

**Comment by ArtemGovorov** [comment] 2017-05-03 05:05
I have [created this repo](https://github.com/ArtemGovorov/wallaby-1138) with your setup reproduced as much as I could. Everything is working for me:

![screen shot 2017-05-03 at 2 57 35 pm](https://cloud.githubusercontent.com/assets/979966/25648642/7766a76e-3011-11e7-9bc7-115bfcab8a29.png)

and the produced js contains required types:

```javascript
...
var React = ($_$w(8, 14), require('react'));
var mobx_react_1 = ($_$w(8, 15), require('mobx-react'));
var mobx_1 = ($_$w(8, 16), require('mobx'));
var react_router_dom_1 = ($_$w(8, 17), require('react-router-dom'));
var Root_1 = ($_$w(8, 18), require('./containers/Root'));
var utils_1 = ($_$w(8, 19), require('./utils'));
var components_1 = ($_$w(8, 20), require('./components'));
var constants_1 = ($_$w(8, 21), require('./constants'));
...
``` 

The `tsconfig.json` that I have used is very simple. Please take a look into the repo and try your `tsconfig.json` with it to see if it's working or not.

**Comment by rokoroku** [comment] 2017-05-03 07:02
my **tsconfig.json** is below
```javascript
{
  "compilerOptions": {
    "sourceMap": true,
    "target": "es5",
    "jsx": "react",
    "module": "es6",
    "moduleResolution": "node",
    "emitDecoratorMetadata": false,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "pretty": true,
    "declaration": false,
    "noImplicitAny": false,
    "noImplicitReturns": false,
    "removeComments": true,
    "strictNullChecks": false,
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
      "*": [
        "src/*",
        "*"
      ]
    },
    "lib": [
      "es6",
      "es7",
      "dom"
    ]
  },
  "exclude": [
    "dist",
    "node_modules"
  ]
}
```

and **package.json**
```javascript
{
  "scripts": {
    "test": "karma start --single-run",
    "prelint": "tsc --noEmit",
    "lint": "tslint --project tsconfig.json",
    "start": "webpack-dashboard -- webpack-dev-server -d --port 3000",
    "build": "webpack -p --progress",
    "predeploy": "npm run build",
    "deploy": "node ./bin/deploy.js",
    "prepush": "npm run test",
    "precommit": "npm run lint",
    "commit": "git-cz -a"
  },
  "devDependencies": {
    "@types/chai": "^3.5.0",
    "@types/classnames": "^0.0.32",
    "@types/core-decorators": "^0.10.32",
    "@types/dotenv": "^2.0.20",
    "@types/enzyme": "^2.7.8",
    "@types/history": "^4.5.0",
    "@types/invariant": "^2.2.28",
    "@types/joi": "^10.0.1",
    "@types/lodash": "^4.14.62",
    "@types/lodash-decorators": "^1.0.30",
    "@types/mocha": "^2.2.40",
    "@types/react": "^15.0.21",
    "@types/react-dom": "^0.14.23",
    "@types/react-ga": "^2.1.0",
    "@types/react-helmet": "^5.0.0",
    "@types/react-intl": "^2.2.5",
    "@types/react-motion": "^0.0.21",
    "@types/react-router": "^4.0.4",
    "@types/react-sidebar": "^2.2.0",
    "@types/react-sortable-hoc": "0.0.4",
    "@types/webpack": "^2.2.14",
    "awesome-typescript-loader": "^3.1.2",
    "aws-sdk": "^2.41.0",
    "babel-polyfill": "^6.23.0",
    "chai": "^3.5.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "cz-conventional-changelog": "^2.0.0",
    "dotenv": "^4.0.0",
    "enzyme": "^2.8.2",
    "extract-text-webpack-plugin": "^2.1.0",
    "file-loader": "^0.11.1",
    "html-loader": "^0.4.5",
    "html-webpack-include-assets-plugin": "^0.0.5",
    "html-webpack-plugin": "^2.28.0",
    "husky": "^0.13.3",
    "intl": "^1.2.5",
    "json-loader": "^0.5.4",
    "karma": "^1.6.0",
    "karma-chai": "^0.1.0",
    "karma-mocha": "^1.3.0",
    "karma-mocha-reporter": "^2.2.3",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-typescript-preprocessor2": "^1.2.1",
    "karma-webpack": "^2.0.3",
    "mobx-react-devtools": "^4.2.11",
    "mocha": "^3.2.0",
    "mocha-webpack": "^0.7.0",
    "node-noop": "^1.0.0",
    "noop-loader": "^1.0.0",
    "null-loader": "^0.1.1",
    "postcss": "^5.2.17",
    "postcss-browser-reporter": "^0.5.0",
    "postcss-cssnext": "^2.10.0",
    "postcss-import": "^9.1.0",
    "postcss-loader": "^1.3.3",
    "postcss-reporter": "^3.0.0",
    "postcss-url": "^6.0.4",
    "react-addons-test-utils": "15.4.2",
    "react-hot-loader": "^3.0.0-beta.6",
    "smoothscroll-polyfill": "^0.3.4",
    "style-loader": "^0.16.1",
    "tslint": "^4.5.1",
    "tslint-microsoft-contrib": "^4.0.1",
    "typescript": "^2.3.0",
    "url-loader": "^0.5.8",
    "wallaby-webpack": "^0.0.38",
    "webpack": "^2.4.1",
    "webpack-cleanup-plugin": "^0.5.1",
    "webpack-dashboard": "^0.3.0",
    "webpack-dev-server": "^2.4.2",
    "webpack-hot-middleware": "^2.18.0"
  },
  "dependencies": {
    "axios": "^0.16.1",
    "chart.js": "^2.5.0",
    "classnames": "^2.2.5",
    "history": "^4.6.1",
    "invariant": "^2.2.2",
    "joi-browser": "^10.0.6",
    "lodash": "^4.17.4",
    "lodash-decorators": "^3.0.2",
    "lodash-es": "^4.17.4",
    "mobx": "^3.1.9",
    "mobx-react": "^4.1.8",
    "mobx-utils": "^2.0.1",
    "moment": "^2.18.1",
    "moxios": "^0.4.0",
    "react": "15.4.2",
    "react-chartjs-2": "^2.0.5",
    "react-dom": "15.4.2",
    "react-ga": "^2.2.0",
    "react-grid-layout": "^0.14.4",
    "react-helmet": "^5.0.3",
    "react-intl": "^2.2.3",
    "react-motion": "^0.4.7",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "react-sidebar": "^2.3.1",
    "react-sizeme": "^2.3.1",
    "react-sortable-hoc": "^0.6.3",
    "semantic-ui-css": "^2.2.10",
    "semantic-ui-react": "^0.67.2",
    "store": "^2.0.4",
    "tslib": "^1.6.1"
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  }
}

```

**Comment by ArtemGovorov** [comment] 2017-05-03 07:13
I have updated the repo https://github.com/ArtemGovorov/wallaby-1138 with your config files, but still unable to reproduce the issue. 

Please try cloning the repo to see if it's working for you. If so, please try to find out and let me know what is different between it and your project.

**Comment by rokoroku** [comment] 2017-05-03 07:16
The repo is also working for me.
I'm gonna trying to reproduce the issue on top of your repo.

**Comment by rokoroku** [comment] 2017-05-03 11:44
I just found the cause.

I use some `Record` type in `app/store` like below:
```ts
export type RootStores =
  { [key: string]: any }
  & Record<typeof PROVIDER_UI, UIStore>
  & Record<typeof PROVIDER_USER, UserStore>
  & Record<typeof PROVIDER_AUTH, AuthStore>;
```

It was transpiled well in regular typescript compiler, and webpack plugins (such as awesome-typescript-loader) well so it also passed in karma-runner (which can be test via `npm run test`), however, not in wallaby's intermediate compiler.

For more information, see below pull request
https://github.com/ArtemGovorov/wallaby-1138/pull/1

**Comment by ArtemGovorov** [comment] 2017-05-03 13:51
Thanks for the analysis and for updating the repo. It was the `Record` type indeed. Because wallaby's TypeScript compiler couldn't find it, it would produce an incorrect compilation result.

Wallaby's TypeScript compiler is exactly the same as karma's/awesome loader's, it's just karma and webpack are running in the local project folder, while wallaby is running in its own file cache, so in this particular case there was a missing definition file.

The issue can be fixed by adding the `.d.ts` file where the type is defined to the `files` list.
https://github.com/ArtemGovorov/wallaby-1138/blob/master/wallaby.js#L17

**Closed by ArtemGovorov** 2017-05-03 13:51 UTC
Labels: more info is required, reproducible example is required
