### ISSUE TITLE
Encountering some random errors

### ISSUE THREAD

**Issue by unional** [wallabyjs/public#1480] opened 2018-01-23 21:45 UTC
Visual Studio Code v1.19.2
Wallaby core: latest (today, how to get the core version?)

Encountering some random errors on some tests that are not in the current active file.

e.g.:

```sh
​​​​exportDevieState reject if no key specified​​​​ ​​​[1516 ms]​​​​
    ​​​​
    ​​TypeError: Cannot read property '11' of undefined​​
  
  ​​​​GET missing key returns invalid credentials.​​​​ ​​​[5002 ms]​​​​
    ​​​​
    ​​Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.​​
  
  ​​​​ omitting user and password will use default (admin/admin)​​​​ ​​​[5003 ms]​​​​
    ​​​​
    ​​Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.​​
```

Will be posting others when they occur. Start the issue early to see if someone has experienced this before.

When I run the tests again, (Stop and restart Wallaby), they all pass.

Using `jest` + `TypeScript` in this project.

**Comment by ArtemGovorov** [comment] 2018-01-24 05:43
Could you try resetting wallaby cache? Touching wallaby config file (like adding a space anywhere) and restarting it will do. Also, perhaps your tests somehow depend on each other (maybe share some state)?

Let me know if it fixes the issues. If not, could you please share a sample repo where we could reproduce it?

**Comment by unional** [comment] 2018-01-24 06:38
The tests don't depend on each other.
It's an internal project so I do need to create a repro for it outside.
But I guess it would be hard to reproduce.

Haven't seen it in other projects.

**Comment by ArtemGovorov** [comment] 2018-01-24 07:28
Did wallaby cache reset help?

> It's an internal project so I do need to create a repro for it outside.

Hopefully you can do it, because other than `​​TypeError: Cannot read property '11' of undefined​​` (that may mean a corrupted wallaby cache), error messages don't seem to point any wallaby specific issues, so I have no idea what else to suggest to troubleshoot (except for maybe adding some logging to tests to see exactly why there are failing when running from wallaby).

**Comment by unional** [comment] 2018-01-25 23:15
Seeing some more error today on another project:

This happens on a VSCode multi-root workspace.

```sh
​​Error: Cannot find module 'perf_hooks' from 'StateMachine.js'​​
  at Object.<anonymous> ​src/authenticate.spec.ts:1​
​​Error: Cannot find module 'perf_hooks' from 'StateMachine.js'​​
  at Object.<anonymous> ​src/config/device/deviceState.spec.ts:1​
​​Error: Cannot find module 'perf_hooks' from 'StateMachine.js'​​
  at Object.<anonymous> ​src/config/objects/addresses.spec.ts:1​
​​TypeError: util.promisify is not a function​​
  at Object.<anonymous> ​src/util.ts:5:0​
```

**Comment by unional** [comment] 2018-02-03 23:58
I encounter this on one OOS project. You can check it out here:
https://github.com/unional/komondor/blob/env/src/ws/ws.spec.ts
When I run wallaby, this file reported with errors.
If I make any edit in it, it will change to pass.

If I stop wallaby and start again, the errors reoccur.

**Comment by unional** [comment] 2018-02-04 00:02
Tried reset cache, the errors persist.

**Comment by ArtemGovorov** [comment] 2018-02-04 01:23
Just tried cloning the repo, switching to the wallaby branch, running `npm i`, starting wallaby, and everything seems to work:

<img width="914" alt="screen shot 2018-02-04 at 11 18 04 am" src="https://user-images.githubusercontent.com/979966/35773411-336e7b70-099d-11e8-80f2-bc36b15c0f64.png">

Am I missing something?

Try adding `debug: true` to your wallaby config,

```javascript
module.exports = function (wallaby) {
  return {
    ...
    debug: true
  }
}
```
start wallaby, open Wallaby Console output channel in VS Code, in the output please search for the
```
wallaby:project File cache:
```
string, open the found cache path, archive the `instrumented` subfolder and attach the archive to the issue please.

**Comment by unional** [comment] 2018-02-04 02:19
after adding `debug: true` to the config, the problem goes away.
Maybe it is some caching issue. Maybe just adding spaces in the config does not actually make changes to the file thus not triggering the clearing of cache.

**Comment by unional** [comment] 2018-02-04 05:12
um......after a while it comes back again.

**Comment by unional** [comment] 2018-02-04 05:14
[instrumented.zip](https://github.com/wallabyjs/public/files/1692481/instrumented.zip)

Here is the archieve

**Comment by ArtemGovorov** [comment] 2018-02-04 07:53
> Maybe just adding spaces in the config does not actually make changes

Adding a space should do the trick, but the file needs to be saved. Try adding a line break.

> Here is the archieve

Thanks.

The wallaby cache is the attached archive doesn't seem to have any issues. 

The instrumented `src/ws/ws.spec.js` file loads `../index` which in its turn exports `spec` function from `src/spec.js`. To double check, I have modified wallaby locally to just use the your instrumented folder as is as its cache, and run tests - all tests are passing.

It looks like the copy of the attached `instrumented` folder was made when there wasn't any issues (probably after a cache reset?) Could you please copy/attach the `instrumented` folder archive when the issue is showing up (before resetting the cache)?

**Comment by unional** [comment] 2018-02-04 08:49
I'm suspecting the issue I encountered in `komondor` is actually TypeScript related, not wallaby:
https://github.com/Microsoft/TypeScript/issues/21612

The original issue is not thou, so don't close this issue just yet. 😛

**Comment by unional** [comment] 2018-02-20 21:31
Does wallaby run tsc with `allowJS: true`? If so, this could be related to: https://github.com/Microsoft/TypeScript/issues/21928

**Comment by ArtemGovorov** [comment] 2018-02-20 23:24
> Does wallaby run tsc with `allowJS: true`?

Wallaby itself doesn't set it and respects the setting's value in your `tsconfig.json` file.

**Comment by smcenlly** [comment] 2019-03-12 22:57
Closing this issue as we need more information to reproduce the problem. We will re-open the issue if more detail is provided.

**Closed by smcenlly** 2019-03-12 22:57 UTC
Labels: more info is required, reproducible example is required
