### ISSUE TITLE
Issue with React Native URI paths

### ISSUE THREAD

**Issue by blackxored** [wallabyjs/public#1436] opened 2017-12-15 17:07 UTC
When run through Wallaby here's a snippet of my snapshot diff:
```
  <Image
    source={
	        Object {
	          "testUri": "../../../": "../../../../../../../../Library/Caches/IntelliJIdea2017.3/wallaby/projects/e6babc92b675f180/instrumented/core/images/healthcare-notice.png",
	        }
	      }
	      style={
```

React Native recently added `testUri` (they used to be numbers), but now they're different depending on whether the test ran on Wallaby or manually through the command line. Anything we can do to fix?

Just the diff part:

```diff
- "testUri": "../../../core/images/healthcare-notice.png",
+ "testUri": "../../../../../../../../Library/Caches/IntelliJIdea2017.3/wallaby/projects/e6babc92b675f180/instrumented/core/images/healthcare-notice.png",
```

EDIT: these files are marked with 
```javascript 
{ instrument: false }
``` 
in my config

**Comment by ArtemGovorov** [comment] 2017-12-16 00:58
Could you please create a sample repo demonstrating the issue? I'm sure we can figure something out to fix it for you.

**Comment by blackxored** [comment] 2018-01-17 06:54
Please take a look at [blackxored/WallabyRNAssets](https://github.com/blackxored/WallabyRNAssets).  As you can see, the commited snapshot (ran within Wallaby) doesn't match the snapshot if ran via the command-line (`yarn test`).

**Comment by ArtemGovorov** [comment] 2018-01-17 08:47
@blackxored Thanks for providing the repo. The issue is fixed in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version.

**Closed by ArtemGovorov** 2018-01-17 08:47 UTC
Labels: configuration question, reproducible example is required

**Comment by sunnylqm** [comment] 2018-07-27 06:30
@ArtemGovorov Still met this issue
[Wallaby Console] VS Code extension v1.0.91
[Wallaby Console] Core v1.0.608

**Comment by bj97301** [comment] 2019-04-17 23:53
> @ArtemGovorov Still met this issue
> [Wallaby Console] VS Code extension v1.0.91
> [Wallaby Console] Core v1.0.608
> 
> UPDATE: This is because I forgot to add assets folder to `files`

Yep this was my issue too.  Thanks for sharing.
