### ISSUE TITLE
[Jest] Removing a test while Wallaby is executing it blows its head off

### ISSUE THREAD

**Issue by endragor** [wallabyjs/public#142] opened 2015-06-03 10:23 UTC
Steps to reproduce:

1. Run Wallaby on the project from the [sample repo](https://github.com/endragor/wallaby-jest-sample).
2. Wait until it executes the single test.
3. Copy-paste the test and after ~1-2 seconds press Undo (Cmd+Z) to remove it. Make sure to do this before Wallaby had enough time to run the test.
4. Observe lots of weird stuff happening after that:

* The following error in the log:
```
Test without test file id, most likely the test did not run { testFileIdCanNotBeDetermined: 'adds 1 + 2 to equal 3',
  id: 100001,
  log: undefined,
  filesInvolved: [] }
```
The error occurs even if you add new tests that should run without problems.
* When you change something in the test file, the number of executed tests shown is two times more than the actual number of tests.
* Sometimes errors like `Cannot set property '100002' of undefined` occur.

The only cure to this is to relaunch Wallaby.

A couple of screenshots:
![errors_and_bad_number_of_tests](https://cloud.githubusercontent.com/assets/2417849/7957916/490f4afe-0a04-11e5-9923-11a5adb21945.png)
![cannot_set_property](https://cloud.githubusercontent.com/assets/2417849/7957917/4d631f40-0a04-11e5-96d3-ff2278868bf5.png)

**Comment by ArtemGovorov** [comment] 2015-06-03 10:30
Looks like Jest integration specific, will have a look into it.

**Comment by ArtemGovorov** [comment] 2015-06-04 07:37
Thanks for the detailed steps to reproduce and screenshots, very helpful. Fixed in core 1.0.59, let me know whether it works for you now.

**Closed by ArtemGovorov** 2015-06-04 07:37 UTC
Labels: bug

**Comment by endragor** [comment] 2015-06-04 11:04
Works good now, thanks!

**Comment by endragor** [comment] 2015-06-04 12:10
Just got `Test without test file id, most likely the test did not run` again and same symptoms in 1.0.59. Not sure if it has the same cause as in this issue. Steps to reproduce are different (can be done in the same sample project):

This time just leave single test and open the source file (sum.js)
1. Make a syntax error, like add `}` somewhere. See Wallaby complains about syntax error in "Failing Tests" tab.
2. Quickly replace the `}` with `console.log` call (you may paste it from clipboard).
3. Observe the same symptoms as originally described in the issue.

These steps make the issue occur 1 out of 3 times for me, so you might have to try multiple times to get this.

Screenshot:
![wallaby_error](https://cloud.githubusercontent.com/assets/2417849/7983703/7fa7a420-0adc-11e5-966e-c760d661e4d8.png)

**Comment by ArtemGovorov** [comment] 2015-06-04 13:09
Can't reproduce it, what am I doing wrong? Is there anything changed in wallaby.js?
![noid](https://cloud.githubusercontent.com/assets/979966/7984738/742b63c0-0b0e-11e5-87fc-d7c63a953842.gif)

**Comment by endragor** [comment] 2015-06-04 13:51
Ah, right, I had babel preprocessor configured locally. It seems to be an important part in reproducing this. Pushed the updated config now.

**Comment by ArtemGovorov** [comment] 2015-06-05 00:09
Cool, reproduced on a slightly different scenario. Will be looking into it now.

**Comment by ArtemGovorov** [comment] 2015-06-05 00:55
Ok, please try 1.0.60. 
Can't believe how many dark corners does Jest have, thanks for your help again!

**Comment by hellboy81** [comment] 2015-07-10 11:59
[I have the same problem](http://pasteboard.co/1QXen7Mb.png)

**Comment by ArtemGovorov** [comment] 2015-07-11 02:28
@hellboy81 Are you using Jest? Could you create a small repository where I could reproduce the issue please?
