### ISSUE TITLE
Line doesn't recover from "red" state even if the test passes

### ISSUE THREAD

**Issue by VasilySizov** [wallabyjs/public#1530] opened 2018-02-25 00:41 UTC
### Issue description or question
For some methods Wallaby is not refreshing previous error results till the line is commented/uncommented or modified in some way.

Example to reproduce:
1) We have the following method (at left), and a test (at right), which works (both method and test are "green"):
![state-1](https://user-images.githubusercontent.com/3389718/36636811-8dfade36-1982-11e8-9676-a14268f46168.png)

2) Imagine, that we passed wrong object into the tested method, and it throws an error, and the test fails (both method and test are red):
![state-2](https://user-images.githubusercontent.com/3389718/36636812-8e11ea04-1982-11e8-8fcd-cd80c4ad7fd1.png)

3) We noticed that and fixed the test: we pass the correct object to the method, and test becomes green, but method is still confusingly red(!) and shows us an error, which doesn't make sense anymore:
![state-3](https://user-images.githubusercontent.com/3389718/36636813-8e279c0a-1982-11e8-8928-e2d230fa32e9.png)

4) The possible way to revert Wallaby into the correct state is to comment the "red" line in the method:
![state-4](https://user-images.githubusercontent.com/3389718/36636814-8e3bc658-1982-11e8-9259-8b8bc4685dc0.png)

5) ...and uncomment it back:
![state-5](https://user-images.githubusercontent.com/3389718/36636815-8e515d9c-1982-11e8-9fe9-e32dbcaf000c.png)

### Wallaby.js configuration file

```javascript
module.exports = function () {
    return {
        files: [
            'src/**/*.coffee'
        ],

        tests: [
            'test/**/test-*.coffee'
        ],
        env: {
            type: 'node'
        }
    };
};
```

### Code editor or IDE name and version
WebStorm v2017.3.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment] 2018-02-25 01:43
It's hard to tell why it's happening (there may be few possible reasons - all fixed by configuration), could you please isolate/create a sample repo where we could reproduce it? We're happy to have a look and sort it out for you.

**Comment by VasilySizov** [comment] 2018-02-25 03:21
No problem. Please find the file attached.
[issue.zip](https://github.com/wallabyjs/public/files/1755699/issue.zip)

I've managed to shorten the example to one single test file consisted of 4 lines.
The project itself has no dependencies, but I have globally installed latest coffeescript (2.2.2) and latest Mocha (5.0.1).

The steps to have it reproduced are as follows:
![issue-1](https://user-images.githubusercontent.com/3389718/36637736-ccf28408-1997-11e8-9aab-98700b09e31f.png)

![issue-2](https://user-images.githubusercontent.com/3389718/36637737-cd0d2970-1997-11e8-9e29-a54af3181fad.png)

![issue-3](https://user-images.githubusercontent.com/3389718/36637738-cd2396d8-1997-11e8-867e-82c947bc656c.png)

**Comment by VasilySizov** [comment] 2018-02-25 03:27
Please note, that in case of no branching in the methodToTest it works just fine:

![no-issue-1](https://user-images.githubusercontent.com/3389718/36637786-9c861220-1998-11e8-9e8e-c355c482d242.png)
![no-issue-2](https://user-images.githubusercontent.com/3389718/36637787-9c9f9b64-1998-11e8-97f8-fa25095b14b4.png)
![no-issue-3](https://user-images.githubusercontent.com/3389718/36637788-9cb65944-1998-11e8-8144-a5382c371949.png)

**Comment by ArtemGovorov** [comment] 2018-02-25 09:05
Thanks for sample repo. The issue was with the way we used to map CoffeeScript ranges. The issue is now fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), as well as the latest Webstorm plugin v1.0.107 (it'll prompt for the update automatically)

**Closed by ArtemGovorov** 2018-02-25 09:05 UTC
Labels: configuration question, reproducible example is required

**Comment by VasilySizov** [comment] 2018-02-25 09:26
That was quick. Thank you for the great support!
