### ISSUE TITLE
Couldn't find preset "es2015" relative to directory 

### ISSUE THREAD

**Issue by sangyum** [wallabyjs/public#452] opened 2016-02-11 06:31 UTC
Hi,

I have a Babel 6 project with es2016 and stage-0 presets. My test is configured to run mocha. I am having difficulty creating a working Wallaby configuration under Atom editor. It would be a shame if I couldn't make this work after purchasing three licenses for the team. Any help would be greatly appreciated.

Error:
```
Failed to run compilers on app/router/index.js, Error: Couldn't find preset "es2015" relative to directory "app/router"
  at /Users/sangyum/Documents/GitHub/video-services/src/clip-service/node_modules/babel-core/lib/transformation/file/options/option-manager.js:393:17
  at Array.map (native)
  at OptionManager.resolvePresets (/Users/sangyum/Documents/GitHub/video-services/src/clip-service/node_modules/babel-core/lib/transformation/file/options/option-manager.js:385:20)
  at OptionManager.mergePresets (/Users/sangyum/Documents/GitHub/video-services/src/clip-service/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:10)
```

wallaby.js

```js
module.exports = function (wallaby) {
  return {
    files: [
      {pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false},
      'app/**/*.js',
      '!app/**/*.spec.js'
    ],

    tests: [
      'app/**/*.spec.js'
    ],

    env: {
      type: 'node',
      runner: 'node',
      params: {
        env: 'NODE_ENV=test',
        runner: '--harmony'
      }
    },

    testFramework: 'mocha',

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: ['es2015', 'stage-0']
      })
    },

    debug: true
  };
};
```
.babelrc:
```json
{
   "presets": ["es2015", "stage-0"]
}
```

`npm run test` command:
```
    "test": "NODE_ENV=test node --stack_trace_limit=200 --harmony ./node_modules/mocha/bin/_mocha \"./{app,bin}/**/*.spec.js\" --compilers js:babel-register,js:babel-polyfill",
```

**Comment by ArtemGovorov** [comment] 2016-02-11 07:10
Hi,

I have created [this simple repo](https://github.com/wallabyjs/wallaby-node-babel) with your file structure and your config, but can't reproduce the issue. 

One thing I have changed is the way to load `babel-polyfill` (in node.js you need to `require` it from your [`setup` function](http://wallabyjs.com/docs/config/bootstrap.html) as opposed to just adding the file to the `files` list like for browser):

```javascript
    compilers: {
      ...
    },

    setup: function () {
      require("babel-polyfill");
    },
```
but it shouldn't be not related to the issue as far as I can tell (but you will need it in future).

Another thing you may try (but I doubt it's going to help) is to pass `babelrc: false` in your compiler settings (to prevent babel from loading `.babelrc` file because you have all the options configured in your wallaby config anyway):
```javascript
compilers: {
      '**/*.js': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: ['es2015', 'stage-0'],
        babelrc: false
      })
    },
```

Could you please have a look into the sample, see if it works for you and if it does try to reproduce the error by adding your project specific bits if I'm missing some?

**Comment by ArtemGovorov** [comment] 2016-02-11 10:35
If nothing above helps and you can't reproduce the issue on the sample repo, there's one thing we may check.
I have been reading babel source code and the issue is caused when babel can't resolve node modules of a relative dir path. To better understand why, please open
`/Users/sangyum/Documents/GitHub/video-services/src/clip-service/node_modules/babel-core/lib/helpers/resolve.js` and replaced the exported function as follows:

```javascript
exports["default"] = function (loc /*: string*/) /*: ?string*/ {
  var relative /*: string*/ = arguments.length <= 1 || arguments[1] === undefined ? process.cwd() : arguments[1];

  // we're in the browser, probably
  if (typeof _module3["default"] === "object") {
    console.log('This should never happen');
    return null;
  }

  var relativeMod = relativeModules[relative];

  if (!relativeMod) {
    relativeMod = new _module3["default"]();
    relativeMod.paths = _module3["default"]._nodeModulePaths(relative);
    relativeModules[relative] = relativeMod;
  }

  try {
    return _module3["default"]._resolveFilename(loc, relativeMod);
  } catch (err) {
    console.log('File resolution failed', loc, relative, relativeMod, e.message);
    return null;
  }
};
```
This function in your case must be returning null/undefined for `babel-preset-es2015` and `app/router` args. Additional logging that I have added may shed some light on why does it happen.
Then set the setting `debug: false` to remove the noise from wallaby console, run wallab, open Atom Developer Tools and copy/paste Wallaby console output, [like described here](http://wallabyjs.com/docs/intro/get-started-atom.html#troubleshooting).

**Comment by fvanwijk** [comment] 2016-02-15 20:52
@ArtemGovorov If the polyfill should be loaded on setup instead of via the file patterns, please update the sample project: https://github.com/wallabyjs/wallaby-babel-es7-sample/blob/master/wallaby.js

**Comment by ArtemGovorov** [comment] 2016-02-15 23:28
@fvanwijk The polyfill is the sample you have referenced is loaded correctly, because the sample is for browser environment. The original issue config on the other hand is for node environment, and in node land things have to be `require`-ed.

**Comment by ArtemGovorov** [comment] 2016-02-15 23:29
@sangyum Did you have a chance to try what I was suggesting? If so, how did it go?

**Comment by ArtemGovorov** [comment] 2016-03-09 05:00
@sangyum Closing the issue for now, let me know if it still doesn't work for you, and if so please try my suggestions.

**Closed by ArtemGovorov** 2016-03-09 05:00 UTC

**Comment by szarouski** [comment] 2017-06-10 03:30
Had similar issue because part of my plugins were in a different node_module folder. Specifying full path helped:
```js
babelOptions.plugins =
    babelOptions.plugins.map(x =>
      x.includes('react-hot-loader/babel') ?
      require.resolve(path.join(process.env.NODE_PATH, x)) :
      require.resolve(`babel-plugin-${x}`)
    );
```
