### ISSUE TITLE
TypeScript - ReferenceError: Can't find variable when using a declared enum

### ISSUE THREAD

**Issue by splintor** [wallabyjs/public#160] opened 2015-06-18 06:32 UTC
Take a look at the following TypeScript code:
```typescript
/// <reference path='../../../../typings/karma-jasmine/karma-jasmine.d.ts' />
declare module MyModule{
    export enum MyEnum{
        First = 1,
        Second = 2,
        Third = 3,
    }
}

describe("wallaby test", () => {
    it("should test TypeScript enums", () => {
        var a = MyModule.MyEnum.First;
        expect(a).toBe(1);
    });
});
```
Wallaby show an error on this code which says:
`ReferenceError: Can't find variable: MyModule`

This seems to be a problem with the `declare module` statement, as replacing it with `module` (with no `declare`) makes the problem go away, but this is the way the enum is declared in the d.ts file we are using.

**Comment by ArtemGovorov** [comment] 2015-06-18 08:11
I may be missing something but TypeScript declarations are not generated into JavaScript, so the JavaScript for your example [looks like this](http://www.typescriptlang.org/Playground#src=declare%20module%20MyModule%7B%0A%20%20%20%20export%20enum%20MyEnum%7B%0A%20%20%20%20%20%20%20%20First%20%3D%201%2C%0A%20%20%20%20%20%20%20%20Second%3D%202%2C%0A%20%20%20%20%20%20%20%20Third%20%3D%203%2C%0A%20%20%20%20%7D%0A%7D%0A%0Adescribe(%22wallaby%20test%22%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20it(%22should%20test%20TypeScript%20enums%22%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20var%20a%20%3D%20MyModule.MyEnum.First%3B%0A%20%20%20%20%20%20%20%20expect(a).toBe(1)%3B%0A%20%20%20%20%7D)%3B%0A%7D)%3B) and MyModule is not there, so the same error would happen.

Is it working for you without wallaby? If so, would it be possible to create a working sample, perhaps a sample Github repository so I could have a look?

**Comment by ArtemGovorov** [comment] 2015-06-18 08:14
Maybe the module that is described by the d.ts file that you are using is not loaded? Do you have it your `files` list? Could you please share your wallaby config?

**Comment by ArtemGovorov** [comment] 2015-06-18 08:40
Never mind, I think I have reproduced the issue by using a separate d.ts file.

**Comment by splintor** [comment] 2015-06-18 08:53
There seems to be a difference between the online compiler (and the [npm typescript](https://www.npmjs.com/package/typescript) version 1.5.0-beta compiler) and my tsc.exe compiler (version 1.0.3.0).

See this [simple code](http://www.typescriptlang.org/Playground#src=declare%20module%20MyModule%7B%0A%20%20%20%20export%20enum%20MyEnum%7B%0A%20%20%20%20%20%20%20%20First%20%3D%201%2C%0A%20%20%20%20%20%20%20%20Second%3D%202%2C%0A%20%20%20%20%20%20%20%20Third%20%3D%203%2C%0A%20%20%20%20%7D%0A%7D%0A%0Afunction%20test()%20%7B%0A%09return%20MyModule.MyEnum.First%3B%0A%7D):
````TypeScript
declare module MyModule{
    export enum MyEnum{
        First = 1,
        Second= 2,
        Third = 3,
    }
}

function test() {
	return MyModule.MyEnum.First;
}
````

The online compiler (and npm typescript compiler) transpiles it to:
````javascript
function test() {
    return MyModule.MyEnum.First;
}
````

But when I run it with tsc, I get this js file generated:
````javascript
function test() {
    return 1 /* First */;
}
````

What workaround can I use, provided that I can't really change my d.ts file?

**Comment by ArtemGovorov** [comment] 2015-06-18 09:17
I'll have a look why it happens, in a meantime you may use [bootstrap function](http://wallabyjs.com/docs/config/bootstrap.html) where you define the enum like:
``` JavaScript
bootstrap: function (wallaby) {
  MyModule = MyModule || {};
  MyModule.MyEnum = MyModule.MyEnum || {};
  MyModule.MyEnum.First = 1;
  MyModule.MyEnum.Second = 2;
  // etc
}
```

**Comment by ArtemGovorov** [comment] 2015-06-18 09:39
It is indeed difference between typescript compilers. 

v1.4 replaces `MyModule.MyEnum.First` with `1` and v1.5 beta doesn't. Wallaby.js is using the latest, so that's why it happens.

**Comment by ArtemGovorov** [comment] 2015-06-18 09:47
Created the [issue in TypeScript repo](https://github.com/Microsoft/TypeScript/issues/3548).

**Comment by splintor** [comment] 2015-06-18 10:52
Thanks.
It seems using `export const enum` works OK. I'll try to see if I can change my d.ts file to use `const enum`.

**Comment by ArtemGovorov** [comment] 2015-08-04 00:22
So as it looks like `const enum` is the recommended way and it works, closing the issue.

**Closed by ArtemGovorov** 2015-08-04 00:22 UTC
Labels: TypeScript

**Comment by mayuripansuriya** [comment] 2016-07-01 05:35
yes
