### ISSUE TITLE
Wallaby, TypeScript and Jest Mocks

### ISSUE THREAD

**Issue by KingHenne** [wallabyjs/public#1224] opened 2017-07-12 11:54 UTC
### Issue description or question

I can not get Jest mocks to work with wallaby. I read https://github.com/wallabyjs/public/issues/1152 as well as https://github.com/wallabyjs/public/issues/1181#issuecomment-305678360 but couldn’t find a config that works. This [minimal example](https://github.com/KingHenne/wallaby-ts-jest-mock) should help reproducing and hopefully fixing the issue. Here is also a summary of what’s configured there:

### Wallaby.js configuration file

```javascript
module.exports = function() {
  return {
    files: ["tsconfig.json", "src/**/*.ts", "!src/**/*.test.ts"],

    tests: ["src/**/*.test.ts"],

    env: {
      type: "node",
      runner: "node"
    },

    testFramework: "jest"
  };
};
```

### Jest configuration (in package.json)

```json
{
  "jest": {
    "transform": {
      ".(ts|tsx)": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ]
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.14.0

### OS name and version

macOS 10.12.5

**Comment by ArtemGovorov** [comment] 2017-07-12 13:20
Thanks for the repo!
The issue is fixed in the [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version and the fix is published. Note that after the update you'll still need the preprocessor configure similar to the issue that you have referenced (https://github.com/wallabyjs/public/issues/1181#issuecomment-305678360). I have sent you the [pull request with the change](https://github.com/KingHenne/wallaby-ts-jest-mock/pull/1).

**Closed by ArtemGovorov** 2017-07-12 13:20 UTC

**Comment by KingHenne** [comment] 2017-07-12 14:44
@ArtemGovorov Thanks a lot for the quick fix!
