### ISSUE TITLE
Wallaby Broken with Latest RubyMine update

### ISSUE THREAD

**Issue by TomPridham** [wallabyjs/public#1413] opened 2017-11-30 20:00 UTC
### Issue description or question
I updated to the latest Rubymine version and wallaby won't run anymore.
error:
```
TypeError: Cannot read property '_jasmineAdapter' of undefined
at Runtime._execModule (/Users/tom/RubymineProjects/myRepo/node_modules/jest-runtime/build/index.js:520:13)
at Runtime.requireModule (/Users/tom/RubymineProjects/myRepo/node_modules/jest-runtime/build/index.js:332:14)
at /Users/tom/RubymineProjects/myRepo/node_modules/jest-jasmine2/build/index.js:93:15
at Generator.next (<anonymous>)
at step (/Users/tom/RubymineProjects/myRepo/node_modules/jest-jasmine2/build/index.js:106:583)
at /Users/tom/RubymineProjects/myRepo/node_modules/jest-jasmine2/build/index.js:106:813
at new Promise (<anonymous>)
at /Users/tom/RubymineProjects/myRepo/node_modules/jest-jasmine2/build/index.js:106:494
at jasmine2 (/Users/tom/RubymineProjects/myRepo/node_modules/jest-jasmine2/build/index.js:106:68)
at runTest (/Users/tom/RubymineProjects/myRepo/node_modules/jest-runner/build/run_test.js:98:10)
at /Users/tom/RubymineProjects/myRepo/node_modules/jest-runner/build/index.js:71:68
at Generator.next (<anonymous>)
at step (/Users/tom/RubymineProjects/myRepo/node_modules/jest-runner/build/index.js:23:376)
at /Users/tom/RubymineProjects/myRepo/node_modules/jest-runner/build/index.js:23:536
at <anonymous>
at process._tickCallback **(internal/process/next_tick.js:188:7)**    
```

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  const babelConfig = require('./config/babel')

  return {
    files: [
      'package.json',
      { pattern: 'src/**/*.css', load: false, instrument: false },
      { pattern: 'src/**/*.snap', load: false, instrument: false },
      '!src/legacy/**',
      '!src/integration-tests/**',
      '!src/**/*.test.js',
      'src/**/*.js',
      '.storybook/config.js'
    ],

    filesWithNoCoverageCalculated: ['src/**/*.queries.js', 'src/**/*.stories.js', 'src/**/*.test.js'],

    tests: [
      'src/**/*.test.js',
      'server/src/**/*.test.js',
      { pattern: 'src/integration-tests/**', ignore: true }
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel(babelConfig)
    },

    testFramework: 'jest'
  }
}
```

### Code editor or IDE name and version

RubymineRubyMine 2017.3
Build #RM-173.3727.132, built on November 28, 2017

### OS name and version

Mac OS X 10.12.6

**Comment by TomPridham** [comment] 2017-11-30 20:08
I'm actually not sure if the update broke it or not. I was able to run wallaby in the calculator sample project you have without a problem. I have also tried deleting and reinstall node_modules a couple times to no avail.

**Comment by ArtemGovorov** [comment] 2017-12-01 00:10
From the error message looks like wallaby can't initialise Jest correctly. Could you please share you package.json file (`dependencies` and `devDependencies` section is enough) and your current `package-lock.json`/`yarn.lock` file?

**Comment by ArtemGovorov** [comment] 2017-12-01 01:15
It may also be worth trying to delete your current `package-lock.json`/`yarn.lock` file and to re-install your node_modules after it.

**Comment by TomPridham** [comment] 2017-12-03 23:21
I just tried deleting the package-lock.json and reinstalling and it's doing the same thing.
Here's my dependencies:
```"dependencies": {
    "angular-google-analytics": "1.1.8",
    "apollo-cache-inmemory": "1.1.1",
    "apollo-client": "2.0.3",
    "apollo-link-http": "1.3.0",
    "config": "1.27.0",
    "core-js": "2.5.1",
    "cropperjs": "1.1.3",
    "enzyme-to-json": "3.2.2",
    "fastclick": "1.0.6",
    "form-data": "2.3.1",
    "graphql": "0.11.7",
    "graphql-tag": "2.5.0",
    "graphql-tools": "2.7.2",
    "http-proxy": "1.16.2",
    "immutable": "3.8.2",
    "koa": "2.3.0",
    "koa-body": "2.5.0",
    "koa-bodyparser": "4.2.0",
    "koa-compress": "2.0.0",
    "koa-ctx-cache-control": "1.0.1",
    "koa-helmet": "3.2.0",
    "koa-lowercase": "0.6.2",
    "koa-router": "7.2.1",
    "koa-simple-static": "0.8.2",
    "koa-static": "4.0.1",
    "longjohn": "0.2.12",
    "moment": "2.19.1",
    "moment-timezone": "0.5.13",
    "newrelic": "2.3.1",
    "npm-run-all": "4.1.1",
    "prop-types": "15.6.0",
    "ramda": "0.25.0",
    "react": "15.6.1",
    "react-apollo": "2.0.1",
    "react-day-picker": "6.2.1",
    "react-dnd": "2.5.4",
    "react-dnd-html5-backend": "2.5.4",
    "react-dnd-scrollzone": "4.0.0",
    "react-dom": "15.6.1",
    "react-loadable": "4.0.5",
    "react-redux": "5.0.6",
    "react-router-dom": "4.2.2",
    "recompose": "0.26.0",
    "redux": "3.7.2",
    "redux-form": "7.1.2",
    "request": "2.83.0",
    "request-promise-native": "1.0.5",
    "styled-components": "2.2.3",
    "underscore": "1.8.3",
    "zeelib": "4.0.1"
  },
  "devDependencies": {
    "@storybook/addon-actions": "3.3.0-alpha.3",
    "@storybook/addon-links": "3.3.0-alpha.3",
    "@storybook/addon-storyshots": "3.3.0-alpha.3",
    "@storybook/addons": "3.3.0-alpha.3",
    "@storybook/channels": "3.3.0-alpha.3",
    "@storybook/react": "3.3.0-alpha.3",
    "babel-cli": "6.26.0",
    "babel-core": "6.26.0",
    "babel-eslint": "8.0.1",
    "babel-jest": "21.2.0",
    "babel-loader": "7.1.2",
    "babel-plugin-import-inspector": "2.0.0",
    "babel-plugin-styled-name": "1.0.0",
    "babel-plugin-syntax-dynamic-import": "6.18.0",
    "babel-plugin-transform-class-properties": "6.24.1",
    "babel-plugin-transform-es2015-modules-commonjs": "6.26.0",
    "babel-plugin-transform-export-extensions": "6.22.0",
    "babel-plugin-transform-flow-strip-types": "6.22.0",
    "babel-plugin-transform-object-rest-spread": "6.26.0",
    "babel-polyfill": "6.26.0",
    "babel-preset-env": "1.6.1",
    "babel-preset-latest-minimal": "1.1.2",
    "babel-preset-react": "6.24.1",
    "babel-register": "6.26.0",
    "babel-tape-runner": "2.0.1",
    "browser-sync": "2.18.13",
    "case-sensitive-paths-webpack-plugin": "2.1.1",
    "chromedriver": "2.33.2",
    "copy-webpack-plugin": "4.2.0",
    "coveralls": "3.0.0",
    "enzyme": "3.1.1",
    "enzyme-adapter-react-15": "1.0.5",
    "eslint": "4.9.0",
    "eslint-config-angular": "0.5.0",
    "eslint-config-jane": "0.7.0",
    "eslint-loader": "1.9.0",
    "eslint-plugin-angular": "3.1.1",
    "eslint-plugin-babel": "4.1.2",
    "eslint-plugin-flowtype": "2.39.1",
    "eslint-plugin-flowtype-errors": "3.3.4",
    "eslint-plugin-jest": "21.2.0",
    "eslint-plugin-jsx-a11y": "6.0.2",
    "eslint-plugin-promise": "3.6.0",
    "eslint-plugin-react": "7.4.0",
    "eslint-plugin-unicorn": "2.1.2",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.5",
    "files-exist": "1.0.2",
    "flow-bin": "0.58.0",
    "flow-coverage-report": "0.4.0",
    "flow-typed": "2.2.1",
    "globals": "10.1.0",
    "gulp": "3.9.1",
    "gulp-concat": "2.6.1",
    "gulp-ng-annotate": "2.0.0",
    "gulp-pug": "3.3.0",
    "gulp-uglify": "3.0.0",
    "gulp-uglifycss": "1.0.8",
    "gulp-watch": "4.3.11",
    "http-proxy-middleware": "0.17.4",
    "husky": "0.14.3",
    "import-inspector": "2.0.0",
    "jest": "21.2.1",
    "jest-diff": "21.2.1",
    "jest-in-case": "1.0.2",
    "jest-matcher-utils": "21.2.1",
    "jest-snapshot": "21.2.1",
    "jest-styled-components": "4.9.0",
    "jest-teamcity": "1.3.0",
    "luvi": "1.5.0",
    "ng-annotate-webpack-plugin": "0.2.1-pre",
    "nodemon": "1.12.1",
    "react-dnd-test-backend": "2.5.4",
    "react-test-renderer": "15.6.1",
    "redux-devtools": "3.4.0",
    "selenium-webdriver": "3.6.0",
    "supertest-koa-agent": "0.3.0",
    "tap-spec": "4.1.1",
    "tap-teamcity": "3.0.1",
    "tape-async": "2.3.0",
    "through": "2.3.8",
    "uglify-js": "3.1.5",
    "uglifyjs-webpack-plugin": "0.4.6",
    "url-loader": "0.6.2",
    "webpack": "3.8.1",
    "webpack-bundle-analyzer": "2.9.0",
    "webpack-dev-server": "2.9.3"
  },
"jest": {
    "collectCoverageFrom": [
      "src/**/*.js",
      "!**/*.stories.js",
      "!**/node_modules/**",
      "!src/legacy/scripts/**",
      "!**/index.js",
      "!**/*.queries.js"
    ],
    "coverageReporters": [
      "json-summary",
      "lcov",
      "text",
      "json"
    ],
    "moduleFileExtensions": [
      "js",
      "json"
    ],
    "moduleNameMapper": {
      "^.+\\.(jpg|png|svg)$": "<rootDir>/config/jest/file-mock.js",
      "^.+\\.css$": "<rootDir>/config/jest/style-mock.js"
    },
    "modulePaths": [
      "<rootDir>/src"
    ],
    "resetMocks": true,
    "setupFiles": [
      "<rootDir>/config/jest/setup.js"
    ],
    "testEnvironment": "jsdom",
    "testPathIgnorePatterns": [
      "<rootDir>/(assets|build|public|node_modules|server/lib|tests/integration)/"
    ],
    "testRegex": "\\.test\\.js$",
    "testResultsProcessor": "jest-teamcity"
  },
```

**Comment by ArtemGovorov** [comment] 2017-12-04 00:27
Thanks for providing the details. The issue was related to the installed `storybook` module that has been installing an older version of `jest-util` dependency, that wallaby was using instead of a correct version. The issue is fixed in the latest and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version  1.0.526.

**Closed by ArtemGovorov** 2017-12-04 00:27 UTC
Labels: bug, more info is required

**Comment by TomPridham** [comment] 2017-12-04 17:44
That fixed it. Thanks!
