### ISSUE TITLE
Wallaby Error after Core Update

### ISSUE THREAD

**Issue by jmarsh999** [wallabyjs/public#802] opened 2016-09-23 21:50 UTC
### Issue description or question
Immediately following the update to wallaby Core v1.0.294, I started getting this error when trying to run tests (No issues prior): 

​​[Error] Runtime error: Uncaught TypeError: Cannot read property 'loadTests' of undefined​​
​​[Error] at http://localhost:49997/wallaby_sandbox0.html:11​​

### Wallaby.js configuration file

```javascript
// Wallaby.js configuration

var wallabyWebpack = require('wallaby-webpack');
var wallabyPostprocessor = wallabyWebpack({});

module.exports = function (wallaby) {
  return {
    files: [
      {pattern: 'common/**/*.ts', load: false},
      {pattern: 'client/**/*.ts', load: false} 
    ],

    tests: [
      {pattern: 'tests/**/*.ts', load: false}
    ],
     env: {kind: "electron"},
    postprocessor: wallabyPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    }
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.5.3

### OS name and version

OSX Sierra

**Comment by ArtemGovorov** [comment] 2016-09-24 00:08
There're probably some other errors reported before this one.
Please try adding the `debug: true` setting yo your config:

```javascript
module.exports = function (wallaby) {
  return {
    ...

    debug: true
  };
};
```

run wallaby and paste the full output from the Wallaby Console.

**Comment by DataTables** [comment] 2016-09-26 13:40
I'm getting a potentially similar issue - with debug: true:

```js
[snip]
Mon, 26 Sep 2016 13:33:48 GMT wallaby:project Running postprocessor
Mon, 26 Sep 2016 13:33:48 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Mon, 26 Sep 2016 13:33:48 GMT wallaby:project Preparing to process helpers/i18n.js
Mon, 26 Sep 2016 13:33:48 GMT wallaby:project Processing compiled helpers/i18n.js
Mon, 26 Sep 2016 13:33:48 GMT wallaby:project Instrumenting helpers/i18n.js, via process pool: false
Mon, 26 Sep 2016 13:33:48 GMT wallaby:project No preprocessors configured for helpers/i18n.js
Mon, 26 Sep 2016 13:33:48 GMT wallaby:project Writing to disk and caching processed file helpers/i18n.js
Mon, 26 Sep 2016 13:33:48 GMT wallaby:project Postprocessor execution finished
Mon, 26 Sep 2016 13:33:48 GMT wallaby:project Test run started; run priority: 2
Mon, 26 Sep 2016 13:33:48 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Mon, 26 Sep 2016 13:33:48 GMT wallaby:workers Starting test run, priority: 2
Mon, 26 Sep 2016 13:33:48 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #3ymxw]
Mon, 26 Sep 2016 13:33:48 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #3ymxw]
Mon, 26 Sep 2016 13:33:48 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #3ymxw]
Mon, 26 Sep 2016 13:33:48 GMT wallaby:workers Running tests in sandbox [worker #0, session #3ymxw]
Runtime error: TypeError: Cannot read property '0' of undefined
    at Object.<anonymous> (./test/helpers/i81n-lang.test.js:3:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
Mon, 26 Sep 2016 13:33:48 GMT wallaby:workers Sandbox (active) [3ymxw] error: TypeError: Cannot read property '0' of undefined
Mon, 26 Sep 2016 13:33:48 GMT wallaby:workers Run 0 test(s), skipped 0 test(s)
Mon, 26 Sep 2016 13:33:48 GMT wallaby:workers Sandbox [3ymxw] is responsive, closing it
Mon, 26 Sep 2016 13:33:48 GMT wallaby:project Test run finished
Mon, 26 Sep 2016 13:33:48 GMT wallaby:project Processed console.log entries
Mon, 26 Sep 2016 13:33:48 GMT wallaby:project Processed loading sequences
Mon, 26 Sep 2016 13:33:48 GMT wallaby:project Processed executed tests
Mon, 26 Sep 2016 13:33:48 GMT wallaby:project Processed code coverage
Mon, 26 Sep 2016 13:33:48 GMT wallaby:project Test run result processed and sent to IDE
```

I've found that if I reload the Wallaby runner it works without issue the first time. If I type in the code (any file) and the runner re-runs, I get this error and no other errors shown. I need to re-run the runner to get any useful output.

My `i18n-lang.tests.ts` file is shown below and its imported with a simple `import testLang from './i18n-lang.test'.

IntelliJ IDEA - 2016.2.4
Mac OS X - 10.11.5
Wallaby - core v1.0.298
TypeScript - 2.0.3


```js

export default {
	date: {
		// Formats

	},

	datetime: {
		// Formats

	},

	dic: {
		// { royal: %s }
		param: 'Of rich and {royal} hue',

		// { ever: %s, vision: %s, view: %s }
		param3: 'An {ever} lasing {vision} of an ever changing {view}',

		plural: {
			// { people: %d, cats: %d }
			doublePlural: {
				people: {
					0: 'No people, and no cats',
					1: {
						cats: {
							0: 'I do not have any cats - thank goodness',
							1: 'One has only a single cat',
							_: 'I have {cats} cats'
						}
					},
					2: {
						cats: {
							0: 'They don\'t have any cats',
							1: 'They have one cat',
							_: 'They have {cats} cats'
						}
					}
					_: {
						cats: {
							0: 'They don\'t have any cats bewteen any of the {people} of them',
							1: 'Just one cat for {people} people',
							_: '{cats} cats for {people} people'
						}
					}
				}
			},

			// { dogs: %d }
			singlePlural: {
				dogs: {
					0: 'I don\'t have any dogs',
					1: 'I have one dog',
					2: 'I have two dogs',
					_: 'I have {dogs} dogs'
				}
			},

			// { count: %d, animal: %s }
			singlePluralWithVar: {
				count: {
					// This is a crap example since `animal` would need to be i18n anyway
					0: 'I don\'t have any {animal}s',
					1: 'I have one {animal}',
					2: 'I have two {animal}s',
					_: 'I have {count} {animal}s'
				}
			}
		},

		singular: 'My life has been a tapestry',

		simple: {
			nested: 'Carol',

			level: {
				value: 'King'
			}
		}
	},

	number: {
		decimal: '.',
		thousands: ','
	},

	time: {
		// Formats

	}
};
```

Should I open a different issue, or do you think it might be related?

**Comment by ArtemGovorov** [comment] 2016-09-26 13:45
@DataTables This looks like a different issue. Your looks like a caching issue, try [clearing the wallaby cache](https://wallabyjs.com/docs/intro/troubleshooting.html#wallaby-was-working-but-then-stopped-working). If it doesn't help, please create a separate issue and a sample project where I could reproduce it.

**Comment by ArtemGovorov** [comment] 2016-09-26 13:51
@DataTables Oh, just noticed something that could be the reason - maybe the `test/helpers/i81n-lang.test.js` file is in your `tests` list, however, it doesn't look like a file with actual tests in it. [Wallaby requires `tests` files to be file with tests (with `describe/it` inside them)](https://wallabyjs.com/docs/config/files.html#tests). Try specifying the file in the `files` list and excluding it from the `tests` list.

**Comment by DataTables** [comment] 2016-09-26 14:00
That was it - suitably embarrassing! Sorry to thread hijack!

**Comment by ArtemGovorov** [comment] 2016-09-26 14:02
@DataTables So was it the cache or the file being in the `tests` list?

**Comment by DataTables** [comment] 2016-09-26 14:04
Sorry - it was me including it as a test when it wasn't a test as you pointed out! Moving it to `files` "fixed" it. Thanks!

**Comment by jmarsh999** [comment] 2016-09-26 15:48
After the weekend everything seems to be working.  I think the issue had to do with iCloud now synching the documents folder by default in OS Sierra.  I need to figure out a way to disable that, since git is freaking out as well...  Thank you!

**Comment by ArtemGovorov** [comment] 2016-09-27 23:37
@jmarsh999 Awesome, thanks for the update!

**Closed by ArtemGovorov** 2016-09-27 23:37 UTC
