### ISSUE TITLE
Improve files configurability

### ISSUE THREAD

**Issue by medikoo** [wallabyjs/public#1113] opened 2017-04-12 14:33 UTC
I have following situation:

I want to add to `files` all .js files from a project but exclude `test` folder from it. This can be achieved via:

```javascript
files: ["**/*.js", "!test/**/*.js"],
test: ["test/**/*.js"]
```

But then, in `test/lib` folder I have some files that are not test files but are used by tests, so according to the documentation they should be mentioned in `files` and not `test`.
So while configuration for test is straightforward:

```javascript
test: ["test/**/*.js", "!test/_playground/**/*.js"]
```

There seems no sensible way to configure the `files` for such setup (apart of listing files one by one). Following obviously doesn't make `test/_playground` files to be picked.

```javascript
files: ["**/*.js", "!test/**/*.js", "test/_playground/**/*.js"]
```

I see two possible solutions that can be considered:
- Make non ignore rules that follow ignore rules to override previous ignore settings (in such case example configuration above will work).
- Provide a way to set an ignore rule so it applies only to single path setting, e.g. as:
```javascript
files: [{ pattern: "**/*.js", ignore: "!test/**/*.js" }, "test/_playground/**/*.js"]
```

**Comment by ArtemGovorov** [comment] 2017-04-13 01:51
1. We don't recommend using patterns like `**/*.js` (without the root folder, like `src` that you normally have), because wallaby copies the files to its cache and also watches the original paths. Not only it creates an [unnecessary load on the file watcher](https://github.com/wallabyjs/public/issues/1099#issuecomment-291681660), it also makes it easy to forget to exclude certain files. For example in your case, wallaby will copy all `node_modules`, that is a huge overkill and [not required](https://wallabyjs.com/docs/config/files.html), so you at least need to exclude them:

```
files: ["**/*.js", "!node_modules/**", ...
```
and if you have the source root folder, like `src`, then you may just do:
```javascript
files: ["src/**/*.js", "test/_playground/**/*.js"],
test: ["test/**/*.js", "!test/_playground/**/*.js"]
```

2. Normally, test files are named using some naming convention, like `*.spec.js`/`*Spec.js`/`*.test.js`/etc. If that is the case in your project, then you may simply do this:
```javascript
files: ["**/*.js",  "!node_modules/**", "!test/**/*.spec.js"],
test: ["test/**/*.spec.js"]
```
or, if you have the source root, like `src`, which is recommended:

```javascript
files: ["src/**/*.js",  "test/**/*.js", "!test/**/*.spec.js"],
test: ["test/**/*.spec.js"]
```
This way `test/_playground` will be in the `files`. The advantage of this approach is that you may have as many different helpers/folders in your `tests` as you like, and may add new ones without having to change your wallaby config.

3. Wallaby fully [supports glob patterns with minimatch](https://github.com/isaacs/minimatch), so there's no need to introduce any additional rules for you case, and you may simply use the pattern to exclude all files under `test`, but the `_playground` folder files:
```javascript
files: ["**/*.js",  "!node_modules/**", "!test/{!(_playground)/**,}/*.js"]
```
This pattern `test/{!(_playground)/**,}/*.js` includes all `test` files but excludes the `_playground` folder files, so prefixing it with the `!` negates it and makes it exclude all `test` files but include the `_playground` folder files.

Hope it makes sense and addresses the issue.

**Closed by ArtemGovorov** 2017-04-13 01:51 UTC

**Comment by medikoo** [comment] 2017-04-13 07:13
> root folder, like `src` that you normally have

In my experience it's quite opposite, you don't want to nest modules in `src`, as you don't want users to require your modules via`name/src/a` or `name/src/b`, but rather via `name/a` and ` name/b`, I would say that later approach is normal and more common within node ecosystem.

> wallaby will copy all `node_modules`

Yes, I quickly noticed that, and fixed it adding `"!node_modules/**"` still I was surprised that it's not the default in wallaby (you would expect that in any tool with node.js awareness). Any specific reason why `node_modules` by default are taken in?

> Normally, test files are named using some naming convention, like *.spec.js/*Spec.js/*.test.js/etc

It might be one of the popular conventions, but there is also other convention used quite widely, where test files are just placed in root`test` or `spec` folders.

I would expect wallaby to work out of a box with all majorly used conventions, and not coin one as _normal_ and other convention as _anormal_ with worse treatment, it shouldn't be that opinionated tool.

> This pattern test/{!(_playground)/**,}/*.js includes all test files but ...

Great thanks, I wasn't aware that could work. After all I came with a pattern that works perfectly with [glob](https://www.npmjs.com/package/glob) but doesn't seem to pick any files with wallaby:

```
"./{!(node_modules|test)/**,}/*.js"
```

Is there any particular reason for that?

**Comment by ArtemGovorov** [comment] 2017-04-13 08:41
> In my experience it's quite opposite

If you're writing a library (as opposed to an application), it may be the case. But again, after 5 years of using node.js, I don't see this approach being common in the ecosystem. I much more frequently see `lib` or `src` folder being used. Have a look into these projects: mocha, jest, babel, webpack, express, moment and many other popular node libs - the majority have the root folder for source code. 

Also, the majority of our users are testing applications, as opposed to libraries. In apps having a root source folder is even more common. 

> as you don't want users to require your modules via `name/src/a` or `name/src/b`

I personally wouldn't want users to require *files* of my module at all. I'd rather exported anything I'd like a user to import from a main file, and let a user do: `require('myModule').a` and `require('myModule').b`. Again, I can see it being done in a lot of popular node libs (I have listed some above).

> Any specific reason why `node_modules` by default are taken in?

`node_modules` are not taken in, nothing is taken is by default. It's when you specify `"**/*.js"`, everything is taken in, including node modules, bower components, gulp and grunt files, karma files (if any), benchmarks, examples and tests, etc. 

> I would expect wallaby to work out of a box with all majorly used conventions, and not coin one as normal and other convention as anormal with worse treatment, it shouldn't be that opinionated tool.

I didn't mean to say your approach is not normal, I just shared what I normally see wallaby users (and other devs) are doing. Even putting non wallaby tested projects aside, based on our experience, the `"**/*.js"` pattern is used by ~1% of thousands of our users, so this is not *majorly used convention* amongst our users. 

We are not an opinionated tool and your concern is heard and taken into consideration by us, it's just very few of our users are doing what you're doing, and you're the first user to raise this concern.

> `"./{!(node_modules|test)/**,}/*.js"`

I'll double check this one, but I thought you needed the `_playground` folder, so it will not work, will it?

**Comment by medikoo** [comment] 2017-04-13 08:58
> Also, the majority of our users are testing applications, as opposed to libraries

Yes, at this point I will mainly use it for open sourced libraries. It probably means I'm in a minority, but I hope it doesn't mean that support is rejected in that case.

> I'd like a user to import from a main file, and let a user do: `require('myModule').a`

With that you require the user to load logic of `b` even though he does not need it. Now imagine such approach in case of very popular [lodash](https://github.com/lodash/lodash)

> I'll double check this one, but I thought you needed the _playground folder, so it will not work, will it?

It's the only way I can have setup well configured. My current configuration is as follows:

```javascript
files: [
  { pattern: "./{!(examples|node_modules|test)/**,}/*.js", load: false }, // doesn't work :(
  { pattern: "test/_playground/**/*.js", load: false, instrument: false },
  "!wallaby.js"
],
tests: [
  "test/{!(_playground)/**,}/*.js"
]
```
If you know any other way I can achieve same, let me know,

Should I open a new issue for that?

**Comment by ArtemGovorov** [comment] 2017-04-13 12:45
Wallaby passes file paths to minimatch as `folder/file.js`, not as `./folder/file.js`, and 
```
require('minimatch')('folder/file.js', './{!(examples|node_modules|test)/**,}/*.js')
```
yields `false`.

Try this:
```javascript
files: [
  "{!(examples|node_modules|test)/**,}/*.js",
  { pattern: "test/_playground/**/*.js", instrument: false },
  "!wallaby.js"
],
tests: [
  "test/{!(_playground)/**,}/*.js"
]
```

**Comment by medikoo** [comment] 2017-04-13 12:50
> Try this: `"{!(examples|node_modules|test)/**,}/*.js"`

I've tried that initially and it doesn't work. On that both glob and wallaby are consistent, it matches only files nested in some folders.

It'll be great if files resolution works same as in [glob](https://www.npmjs.com/package/glob) (which stands on minimatch), at least I'm not sure what's the reason to make it different.

**Comment by ArtemGovorov** [comment] 2017-04-13 14:15
Indeed it didn't work. We have just released [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version where the issue is fixed, try this now:
```javascript
files: [
  "{!(examples|node_modules|test)/**,}/*.js",
  { pattern: "test/_playground/**/*.js", instrument: false },
  "!wallaby.js"
],
tests: [
  "test/{!(_playground)/**,}/*.js"
]
```

**Comment by medikoo** [comment] 2017-04-13 14:40
> We have just released the latest core version where the issue is fixed

Hmm.. I just updated wallaby, it installed again (with v1.0.413) and there's same issue, above pattern doesn't take modules from project root folder.

**Comment by medikoo** [comment] 2017-04-13 14:44
Also I think ` "{!(examples|node_modules|test)/**,}/*.js"` is not supposed to take files from root folder.

It's ` ".{!(examples|node_modules|test)/**,}/*.js"` or `"./{!(examples|node_modules|test)/**,}/*.js"` that should do it (this is where glob and wallaby differs)

**Comment by ArtemGovorov** [comment] 2017-04-13 14:45
Sorry, forgot to adjust the pattern a bit, try this:

```
"{!(examples|node_modules|test)/**,}*.js",
```

**Comment by medikoo** [comment] 2017-04-13 15:02
`"{!(examples|node_modules|test)/**,}*.js"` seems to support only one level of nesting.

`foo/some-module.js` is picked, but `foo/bar/some-module.js` is not (and it's the case also with glob, so at least wallaby is consistent)

**Comment by medikoo** [comment] 2017-04-13 15:03
Actually the only one that does the job should be: `"./{!(examples|node_modules|test)/**,}/*.js"`, at least it works with glob

**Comment by ArtemGovorov** [comment] 2017-04-13 15:40
It looks like a bug. We'll look into it, in a meantime I suggest to try
```
files: [
  { pattern: "test/_playground/**/*.js", instrument: false },
  "**/*.js",  
  "!node_modules/**", 
  "!examples/**", 
  "!wallaby.js", 
  "!test/{!(_playground)/**,}/*.js"
],

tests: [
  "test/{!(_playground)/**,}/*.js"
]
```

**Comment by medikoo** [comment] 2017-04-13 15:42
> It looks like a bug. We'll look into it, in a meantime I suggest to try

Ok thanks!

**Comment by ArtemGovorov** [comment] 2017-04-13 16:11
We have just released [the new core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version where tried make it work like `glob` does. For now it is behind the special `glob` flag, we'll make it default if it works ok. So try updating the core, and then changing your config to this:
```javascript
  return {
    glob: true, // <--
    files: [
      "{!(examples|node_modules|test)/**,}/*.js",
      { pattern: "test/_playground/**/*.js", instrument: false },
      "!wallaby.js"
    ],
    tests: [
      "test/{!(_playground)/**,}/*.js"
    ],
    ...
}
```
and let us know how it works for you.

**Comment by medikoo** [comment] 2017-04-14 06:35
> We have just released the new core version where tried make it work like glob does. For now it is behind the special glob flag, we'll make it default if it works ok.

It works well now.Thank you!
