### ISSUE TITLE
Notifications for core updates

### ISSUE THREAD

**Issue by mhelvens** [wallabyjs/public#113] opened 2015-05-18 21:44 UTC
In issue #108, I learned that Wallaby can automatically and silently update its own core. I do love frequent updates, but I'm a bit worried about a plugin that can update itself without notifying the user.

If test results change from one run to the next because you have fixed or introduced a bug, I would likely blame my own code and get lost in a fruitless search. I myself may now be prepared for something like that, but I'd much prefer the option to be notified of every update (or even to be asked).

**Comment by ArtemGovorov** [comment] 2015-05-19 04:14
There actually is a notification in the IDE status bar about wallaby core update. It can also be viewed by clicking on the status bar and opening Event Log. 

Having said that, I do agree that it should be more noticeable and perhaps wallaby core should ask if user wants to update, just like the plugin does.

**Comment by fvanwijk** [comment] 2015-05-19 08:57
I'd like to have the possibility to downgrade manually, to verify if some bug is introduced due to the updated core and to have your tests running correctly again until a fix is available.

**Comment by smcenlly** [comment] 2021-03-05 05:25
Wallaby is ever-green by design and each editor integration notifies users of the updates with in-editor notifications. Additionally, automatic updates may be disabled if desired/required (refer to our [offline installation instructions](https://wallabyjs.com/docs/intro/offline.html) for details). Closing this issue.

**Closed by smcenlly** 2021-03-05 05:25 UTC
Labels: feature request
