### ISSUE TITLE
Unpack Rejected Promises

### ISSUE THREAD

**Issue by Silvenga** [wallabyjs/public#1254] opened 2017-08-06 04:38 UTC
### Issue description or question

Consider the following Ava test:

```typescript
test('A Test', async t => {
    throw new Error('Error');
});
```

I would expect Wallaby to show that an Error with the message "Error" was thrown during the test. 

Ava shows the following:

```
telemetryTests » A Test
  E:\Development\vscode-edi-support\out\test\telemetryTests.js:4

                                      e))(function (resolve, reject) {
              function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
   5:         function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }

  Rejected promise returned by test. Reason:

  Error {
    message: 'Error',
  }
```

While not completely useful as it shows the raw Javascript, the message is much more useful then Wallaby's output, below:

```
    ​​Rejected promise returned by test​​
      at Object.<anonymous> ​test/telemetryTests.ts:34:4​
      at Test.t [as fn] ​test/telemetryTests.ts:32:0​
```

For a much more complex test (where an Error is thrown much deeper), Wallaby shows the following:

```
    ​​Rejected promise returned by test​​
      at Object.<anonymous> ​test/telemetryTests.ts:28:4​
      at Test.t [as fn] ​test/telemetryTests.ts:14:0​
```

Which, IMHO, completely useless. 😿 

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        files: [
            'src/**/*.ts',
            'test/index.ts',
        ],

        tests: [
            'test/**/*Tests.ts'
        ],

        testFramework: 'ava',

        compilers: {
            '**/*.ts': wallaby.compilers.typeScript({ })
        },
        env: {
            type: 'node',
            runner: 'node'
        },
        debug: true
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.14.2?

### OS name and version

Windows

**Comment by ArtemGovorov** [comment] 2017-08-07 03:28
Thanks for the report. The issue is fixed in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version.

**Closed by ArtemGovorov** 2017-08-07 03:28 UTC
