### ISSUE TITLE
Mocha Async tests with Rxjs failing

### ISSUE THREAD

**Issue by saralamuralikrishna** [wallabyjs/public#816] opened 2016-10-05 13:57 UTC
### Issue description or question

Mocha Async Rx js tests failing in Wallahyjs but passing using _chutzpah see screenshot
### Wallaby.js configuration file

``` javascript
{
  "files": [

    {
      "pattern": "Scripts/jquery-2.1.4.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/jquery-ui-1.11.4.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/bootstrap.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/jstests/lib/chai.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/jstests/lib/sinon*.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/angular.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/jstests/localStorageServiceFake.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/angular-ui-router.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/angular-mocks.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/lodash.compat.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/angular*.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/ng*.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/angular-toaster/*.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/rx.all.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/angular-loading-bar/loading-bar.js",
      "instrument": false
    },
    {
      "pattern": "AppScripts/Models/Availability.js",
      "instrument": true
    },
    {
      "pattern": "TestScripts/fakeApiService.js",
      "instrument": true
    },
    {
      "pattern": "Scripts/angular-datepicker/angular-moment.min.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/angular-datepicker/angular-datepicker.min.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/bliss/*.js",
      "instrument": true
    },
    {
      "pattern": "AppScripts/infos/infos-module.js",
      "instrument": true
    },
    {
      "pattern": "AppScripts/Search/*-module.ts",
      "instrument": true
    },
    {
      "pattern": "AppScripts/**/*-module.ts",
      "instrument": true
    },
    {
      "pattern": "Scripts/App/**/*-module.js",
      "instrument": true
    },
    {
      "pattern": "my-bertus-angular-app.config.js",
      "instrument": true
    },
    {
      "pattern": "my-bertus-angular-app.run.js",
      "instrument": true
    },
    {
      "pattern": "Scripts/App/my-bertus-angular-app.js",
      "instrument": true
    },
    {
      "pattern": "AppScripts/Models/ordered-model.ts",
      "instrument": true
    },
    {
      "pattern": "AppScripts/Models/order-result-summary-item-model.ts",
      "instrument": true
    },
    {
      "pattern": "AppScripts/Models/*-model*.ts",
      "instrument": true
    },
    {
      "pattern": "AppScripts/Models/*-list*.ts",
      "instrument": true
    },
    {
      "pattern": "AppScripts/Core/*.ts",
      "instrument": true
    },
    {
      "pattern": "TestScripts/fakeResourceService.js",
      "instrument": true
    },
    {
      "pattern": "AppScripts/myBertusAngularApp/*.ts",
      "instrument": true
    },
    {
      "pattern": "AppScripts/**/*service*.ts",
      "instrument": true
    },
    {
      "pattern": "Scripts/App/**/*service.js",
      "instrument": true
    },
    {
      "pattern": "AppScripts/myBertusAngularApp/LocalStorage.js",
      "instrument": true
    },
    {
      "pattern": "AppScripts/**/*.ts",
      "instrument": true
    },
    {
      "pattern": "Scripts/App/**/*.js",
      "instrument": true
    }

  ],
  "tests": [
    "Scripts/jstests/*.test*.js",
    "TestScripts/*.test.js"

  ],
  "testFramework": "mocha"
```
### Code editor or IDE name and version

Visual Studio 2015
### OS name and version

Windows
![1](https://cloud.githubusercontent.com/assets/9860533/19116033/67420df8-8b14-11e6-8454-e3c0fcf08000.png)

**Comment by ArtemGovorov** [comment] 2016-10-05 22:45
Could you please share a test that is failing, or ideally a solution where I could reproduce the issue?

**Comment by saralamuralikrishna** [comment] 2016-10-07 06:38
Here is my setup, we have a controller which will make a call to a service which will return some articles. the controller will check if we have enough articles if not it will call itself (recusive) with different parameters to get some more articles from service. Hope it is clear to reproduce.

getArticlesFromLocation(location)
{
   var obser = Rx.Observable.fromPromise(this.searchService.getArticles(location));
   this.subscription = obser.subscribe( next=> 
                                                          {
                                                                this will check if we have enoug results else call 
                                                                 getArticlesFromLocation(next);
                                                           }
}

**Comment by ArtemGovorov** [comment] 2016-10-07 07:29
Unfortunately I can't reproduce the issue. Looks like it's your project/test specific. Could you please share a sample project where I could reproduce it? It may be a Github repo, attachment or an email to hello@wallabyjs.com.

**Comment by saralamuralikrishna** [comment] 2016-10-07 08:18
I will try to create a test project but will take time, may be can you share your test?

**Comment by ArtemGovorov** [comment] 2016-10-07 08:25
@saralamuralikrishna I have just been running wallaby on RxJs tests from the [RxJs repo](https://github.com/ReactiveX/rxjs) itself (it has wallaby config). It's a bit of an overkill, but those tests are async mocha tests using RxJs (a lot of RxJs) and everything passes.

**Comment by ArtemGovorov** [comment] 2016-12-13 09:19
Closing the issue for now, please let me know if it's still valid and you can share a sample project so I may have a look.

**Closed by ArtemGovorov** 2016-12-13 09:19 UTC
Labels: question
