### ISSUE TITLE
Component Test very slow (Help Wanted)

### ISSUE THREAD

**Issue by aethiss** [wallabyjs/public#1703] opened 2018-06-11 22:27 UTC
### Issue description or question
When i try to launch wallaby, is very slow on components (only with components) using react-native.

<img width="742" alt="screen shot 2018-06-11 at 23 22 19" src="https://user-images.githubusercontent.com/1488133/41260323-ea078634-6dce-11e8-804f-9f11b5c7cee5.png">

### Wallaby.js configuration file

```javascript
/* eslint-disable */
module.exports = function (wallaby) {
  return {
    files: [
      { pattern: 'src/**/*.js?(x)', instrument: true, load: false, ignore: false },
      { pattern: 'src/**/*.spec.js?(x)', load: false, ignore: true },
      { pattern: "src/**/*.snap", load: false, instrument: false },
    ],
    tests: [
      'src/redux/**/__tests__/*.spec.js',
      'src/libs/**/__tests__/*.spec.js',
      'src/components/**/__tests__/*.spec.js'
    ],

    env: {
      type: 'node',
      runner: 'node',
    },

    testFramework: 'jest',

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        babel: require('babel-core')
      }),
    },

    setup: (wallaby) => {
      wallaby.testFramework.configure(require('./package.json').jest);
    },
  };
};

```

### Code editor or IDE name and version

WebStorm v2018.1

### OS name and version

OSX

Here the github example 
https://github.com/aethiss/Nexgon-2.0.1

**Comment by ArtemGovorov** [comment] 2018-06-12 00:51
Thanks for providing the repo link. I've cloned it, ran `npm i`, but getting this error instantly when I run the tests in the repo:
```
 FAIL  src/components/containers/register/__tests__/Register.spec.js
  ● Test suite failed to run

    Cannot find module 'react-dom' from 'ReactSixteenAdapter.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:210:17)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:13:17)

```

The error is reported when running Wallaby and `npm test`. Could you please fix the repo or advice if I'm missing something and let me know when I can try to run it?

**Comment by aethiss** [comment] 2018-06-12 08:45
tnx for fast answer @ArtemGovorov .

sorry probably yesterday night the master branch i link you was not perfectly update, now should be fine.
I launch jest right now, and all test pass

NODE 8.9.4, OSX.

<img width="1047" alt="screen shot 2018-06-12 at 09 42 20" src="https://user-images.githubusercontent.com/1488133/41279682-0fd29e48-6e25-11e8-9f49-03f8e2940dcb.png">

But, like you can see, seems also jest is very slow on components.
I think i need move my focus on that, the problem seems somewhere there.

Any advice/help still welcome :)

**Comment by ArtemGovorov** [comment] 2018-06-12 09:18
Just got latest but I'm still getting the `Cannot find module 'react-dom' from 'ReactSixteenAdapter.js'` error.

But yep, looks like the issue is not related to Wallaby because your Wallaby config runs Jest behind the scenes, and the performance issue seems to be originating from Jest running components tests. 

I'll close the issue as it doesn't seem to be wallaby related, but when I can run your repo tests, I'm happy to take a look if I can spot why Jest is taking so long to run tests (I don't have much experience with react-native though and it seems to be the reason).

**Closed by ArtemGovorov** 2018-06-12 09:18 UTC
Labels: configuration question, reproducible example is required
