### ISSUE TITLE
Suddenly multiple node-instances with high CPU (hanging)

### ISSUE THREAD

**Issue by rvanzon** [wallabyjs/public#1970] opened 2019-01-17 11:33 UTC
### Issue description or question
I am using Jest with Wallaby in VS Code. When Wallaby starts it works fine (some node-instances are running fire up and after compiling they reduce to idling). Then after some saves multiple node-instances keep running with about 100% CPU (hanging?). Testing is very sluggish now and they only stop if I stop Wallaby (in VS Code).

Any ideas?
Thank you!

<img width="915" alt="screenshot 2019-01-17 at 12 27 19" src="https://user-images.githubusercontent.com/815029/51316142-172e5c00-1a54-11e9-8df3-f3a3cb49b85d.png">

### Wallaby.js configuration file
```javascript
require('dotenv').config()

module.exports = function (wallaby) {
  process.env.NODE_ENV = 'test'

  return {
    files: ['src/**/*.js', 'package.json', '!src/**/*.test.js', 'src/**/*.mjml'],
    tests: ['src/**/*.test.js'],

    compilers: {
      'src/**/*.js': wallaby.compilers.babel()
    },

    env: {
      type: 'node',
      runner: 'node'
    },

    collectCoverage: false,
    debug: true,
    delays: {
      // run: 3000
    },

    testFramework: 'jest',
    setup: function (wallaby) {
      var jestConfig = {
        testEnvironment: 'node',
        collectCoverage: false
        // collectCoverageFrom: ['src/**/*.{js,jsx}'],
      }
      // for example:
      // jestConfig.globals = { "__DEV__": true };
      wallaby.testFramework.configure(jestConfig)
    }
  }
}
```

### Code editor or IDE name and version
Visual Studio Code v1.30.2

### OS name and version
OSX

### The Wallaby log
https://pastebin.com/vVcgPwhL

**Comment by rvanzon** [comment] 2019-01-17 11:43
I read the Wallaby log again and at line 645 an error occurs, because a function does not exist (in a test). Commenting out the faulty code the node-instances go away (without restarting Wallaby). Turning the code back on, still good. After changing and saving some other tests the node-instances appear again.

**Comment by foxbunny** [comment] 2019-01-17 11:43
Not sure if it's Wallaby or Jest or VS Code, but I observed the same behavior on Linux and Windows since 1.30.1. In one instance, Linux literally crashed to login shortly after starting Wallaby. I haven't looked into it too deeply because I don't really use VS Code all that much.

**Comment by rvanzon** [comment] 2019-01-17 11:57
Sigh...of course. Trying to fix and ignore this problem for days. Then file an issue. And it seems I found a solution within minutes.

The test-function is an async-function. So I think the Promise is never resolved, because of the error, and keeps the node-instance running. Jest can detect open handles and exit the node-instance.

Adding this:
```
detectOpenHandles: true,
forceExit: true
```

seems to work. Will do some more testing to verify.

**Comment by rvanzon** [comment] 2019-01-17 11:58
> Not sure if it's Wallaby or Jest or VS Code, but I observed the same behavior on Linux and Windows since 1.30.1. In one instance, Linux literally crashed to login shortly after starting Wallaby. I haven't looked into it too deeply because I don't really use VS Code all that much.

@foxbunny I think your problem is different, as it occurs at startup. I think it's similar to https://github.com/wallabyjs/public/issues/907

**Comment by foxbunny** [comment] 2019-01-17 13:41
@rvanzon Quite possibly. As I said I haven't looked too deep into it.

**Comment by rvanzon** [comment] 2019-01-17 18:13
Too bad, this doesn't solve the problem...

Any ideas?

**Comment by rvanzon** [comment] 2019-01-17 18:32
@foxbunny you mean VS Code, right? I tried 1.30.0...same issues :(

**Comment by foxbunny** [comment] 2019-01-17 18:44
@rvanzon Yeah, that's what I meant. Can't say I have any other bright ideas.

**Comment by foxbunny** [comment] 2019-01-17 18:45
On a side note, I had CPU usage spikes on VS Code even with all extensions disabled. So I've switched to WebStorm. Project has some 50k lines of JS.

**Comment by rvanzon** [comment] 2019-01-17 18:47
@foxbunny \Thanks for your time, man. Appreciated! :)

hm yes. In my case It really seems that Wallaby or Jest tries to loop the test or something. As when I fix the syntax error the CPU-usage goes down shortly after.

**Comment by smcenlly** [comment] 2019-01-17 22:55
@rvanzon - do you still have the problem? Are you able to provide us with a sample repo and steps to duplicate? We'd be happy to investigate further for you.

**Comment by rvanzon** [comment] 2019-01-18 09:12
@smcenlly unfortunately I still face the problem. During development I keep an eye on the MacOS' activity monitor and when the node-instances hang (which is kinda random, but often) I restart Wallaby in VS Code.

It's hard for me to provide a sample repo, because the project is closed source. But I can try to mimic it in a new project. But I don't think it's that easy to do.

Is there maybe something I can try? Is my config-file correct?

So, too sum up: when using Wallaby with Jest, sometimes tests seem to hang if code (can be in tests or program) contains errors. Mostly if the errors are fixed the node-instances go back to idle, but sometimes only restarting Wallaby helps.

**Comment by foxbunny** [comment] 2019-01-18 09:21
I've just fired up VS Code 1.30.2 with latest version of wallaby. Opened my ES6 + jest project, deliberately introduced a syntax error on one of the modules, and it works fine for me. Is there a specific type of syntax error or specific execution path that could be causing this?

**Comment by foxbunny** [comment] 2019-01-18 09:31
> Suddenly the instances go to 100%. So, it's unfortunately not, make an error, save it, and 100% CPU. It works for some time.

That's definitely one of those problems that are going to be hard to track down. I had similar behavior in VS Code in general, reported it, and they asked for a repro. Like it's easy to reproduce these things. :D As you can imagine from my previous comments, it's not resolved yet.

**Comment by rvanzon** [comment] 2019-01-18 09:35
@foxbunny I am afraid for that :( Which is really bad, because I love my workflow with Wallaby.

But I think it should be solvable. I will keep trying. Hopefully someone is facing the same or has some tips to try out.

**Comment by ArtemGovorov** [comment] 2019-01-18 09:46
The issue may be in Jest, may be in Wallaby, but it is impossible to tell/fix without some repro (I do understand that it is hard to create one).

Try adding this setting:

```diff
module.exports = function (wallaby) {
  ...

  return {
+   workers: { restart: true },
    ...
  }
```

It'll make Wallaby restart Jest workers as opposed to be re-using them by default. It may make things a bit slower, but if it helps with the issue itself (ie. node processes will stop hanging) it likely means the issue is somewhere in Jest.

**Comment by rvanzon** [comment] 2019-01-18 19:18
@ArtemGovorov thank you for your answer. This indeed seems to work. But it doesn't really speed things up. As the problem is not always there, restarting all workers is much slower (5-10 seconds) against instant changes... So, I better keep an eye on my CPU-usage and restart Wallaby when necessary.

I tried Jest --watch and this works fine. I am not sure if this is comparable with Wallaby.

- The weird thing is that, if the error is solved, the node-instance 'repairs' itself.
- Could it be something with Express? That it doesn't 
- I read about some solutions with Jest involving running it with --forceExit and --detectOpenHandles. Is this possible with Wallaby?

Will try to reproduce the repo...

**Comment by rvanzon** [comment] 2019-01-20 13:19
> Any chance any of your code is calling process.exit?

No. I double checked. I also removed the `forceExit` now from the configs. 

>Can you reliably reproduce the issue in your repo, or it sometimes shows up and sometimes doesn't even if making the same change over again?

The latter, unfortunately. I actually found an open handle (the Redis-connection was not closed) which Jest reported with a single file test. I had high hopes this was the problem. After rewriting the code it seemed to go well for some time. But then, suddenly, after a change and a syntax-error occurred (as Wallaby is triggered immediately, even with an incomplete function name) one node instance keeps on 100% again.

>Could you please try cloning this sample repo: https://github.com/wallabyjs/wallaby-jest-snapshots, and running Wallaby in it to see if you could reproduce the error in it? Try adding a dummy test with a similar structure to yours (ie. async).

This one works fine. But I think the problem is that my project is complexer/bigger than this (for now I have 140 unit- and integration- tests).

Could it have something to do with the fact that some tests require other methods, which have tests themselves? For example I have a module with `createUser()`, `validateUser()` and `saveUser()` in separate files, bundled (require/export) by an` index.js`. The saveUser-tests use `validateUser()` to ensure expectations. This is done with `const userDB = require('.')` and then calling it with `userDB.validateUser(...)`. When tests need users, I use `userDB.createUser(...)` in the `beforeEach()`.

Could it be that the problems happen if a syntax-error happens in `validateUser()` or `createUser()`, for example? Maybe wallaby keeps running Jest in a loop or something?

**Comment by ArtemGovorov** [comment] 2019-01-21 00:11
> But I think the problem is that my project is complexer/bigger than this (for now I have 140 unit- and integration- tests).

Apart from the initial run (that doesn't cause any issues in your case), Wallaby runs tests incrementally (ie. only tests affected by a change in your code). So the number of tests to reproduce the issue shouldn't matter. Hopefully, it's just one test is enough to reproduce the issue. Please try this next time you see the issue:
- add `it.only` to the test to make Wallaby/Jest only run this test. With the `.only` call, Wallaby will also make sure Jest doesn't run any other files with tests.
- try repeating the same steps you've made prior to the issue showing up to see if it is reproducible with running that test only.

> Could it have something to do with the fact that some tests require other methods, which have tests themselves? 

This should not affect Wallaby.

> Could it be that the problems happen if a syntax-error happens in validateUser() or createUser(), for example? Maybe wallaby keeps running Jest in a loop or something?

When Wallaby detects a syntax error (that prevents it from parsing the original JavaScript), it should not even run tests/Jest.

**Comment by rvanzon** [comment] 2019-01-29 21:37
@ArtemGovorov thanks for your responds. Unfortunately, I am not able to reproduce the problem constantly. After fixing the open handle (by closing the Redis-connection) I face the problems less. It's not gone. But I think it's much less. 

Also, it's possible to just kill the node-instance. After resaving the file a new worker is started. This saves the time of Wallaby to restart everything.

**Comment by foxbunny** [comment] 2019-01-29 21:52
@rvanzon Are you using promises in your code? If so, could it be that a promise gets stuck in a never-resolving or long-resolving state for some reason?

Something like this:

> You’ll find that the result appears after a few milliseconds, yet the process remains alive for another 20 seconds just because some no-longer-needed subroutine is still occupying the event loop. (from [here](https://medium.com/@avaq/broken-promises-2ae92780f33))

**Comment by rvanzon** [comment] 2019-02-05 07:53
@foxbunny well, maybe. But I think I solved them, was mostly redis keeping things up. Also, it's weird that it only happens with syntax errors and not always...

**Comment by smcenlly** [comment] 2019-03-12 23:02
@rvanzon - I'm closing this issue as your last comment indicated you may have solved the problem and we haven't heard from you since.

**Closed by smcenlly** 2019-03-12 23:02 UTC
