### ISSUE TITLE
Hide code coverage / test indicator when debugging in VSCode

### ISSUE THREAD

**Issue by soates** [wallabyjs/public#780] opened 2016-09-09 06:26 UTC
Its hard to see your current breakpoints if your debugging and have have wallabyjs enabled.

I cant speak for other IDE's but on vscode the indicators appear above the break points.

Visual Studio Code v1.5.1

Cheers,
Ste.

**Comment by ArtemGovorov** [comment] 2016-09-09 06:31
Duplicate of https://github.com/wallabyjs/public/issues/279#issuecomment-215271539. There's this issue in VS Code repo to make it possible to see both icons: https://github.com/Microsoft/vscode/issues/5923, please feel free to vote for it and subscribe to updates.

**Closed by ArtemGovorov** 2016-09-09 06:31 UTC
Labels: duplicate
