### ISSUE TITLE
Wallaby: Jest + PollyJS creates error on re-run: [TypeError: req.setHeader is not a function] 

### ISSUE THREAD

**Issue by jrobber** [wallabyjs/public#2819] opened 2021-09-28 22:52 UTC
I'm running wallaby using automatic configuration with node, and typescript via jest-babel.
This is a node server/project, no fancy framework files.
The test works the first time, passes flawlessly.  Save or type anything to have the page re-run, and I get this error:
`[TypeError: req.setHeader is not a function] `
It is thrown by the call to fetch.

Why am I starting here?  Because this test works on the command line using jest, and it works in Wallaby on the first execution.  My theory is that there is something in the instrumentation that is leading this test to fail on repeated runs.

My jest tests are setup this way:

```
/** @jest-environment setup-polly-jest/jest-environment-node */

import path from "path";
import { setupPolly } from "setup-polly-jest";
import { MODES } from "@pollyjs/utils";
import fs from "fs";

describe("nextPage test", () => {
	let context = setupPolly({
		/* default configuration options */
		mode: MODES.REPLAY,
		recordIfMissing: process.env.POLLY_RECORD || true,
		adapters: [require("@pollyjs/adapter-node-http")],

		persister: require("@pollyjs/persister-fs"),
		persisterOptions: {
			fs: {
				recordingsDir: path.resolve(__dirname, "./recordings")
			}
		}
	});
	it.only("nextPage test", done => {
		context.polly.configure({ recordIfMissing: true });

		getNextPage(
			`urlToGetDataFromInternetHere`
		).then(resp => {
			done();
		});
	});
});
```

getNextPage looks like this
```
const fetch = require("node-fetch");

export async function getNextPage(nextPageUrl) {
	const headers = {
		Authorization: process.env.BEARER_TOKEN || ""
	};
	if (!process.env.BEARER_TOKEN ) {
		throw new Error("Missing BEARER TOKEN");
	}
	if (!nextPageUrl) {
		throw new Error("Missing page Url");
	}
	console.log("1️⃣ fetching: ", nextPageUrl);

	let resp;
	try {
		resp= await fetch(nextPageUrl, {
			headers: headers
		});
	} catch (err) {
		console.log("🚀 err", err);
		throw err;
	}
	if (resp) {
		const body = await resp.json();

		return body;
	}

	return resp;
}
```

### Wallaby diagnostics report

[wallaby.diagnostics.txt](https://github.com/wallabyjs/public/files/7247697/wallaby.diagnostics.txt)

**Comment by smcenlly** [comment] 2021-09-29 00:03
I tried to reproduce your problem by creating a project with your dependencies and similar code and it appears to be working for me. Would you mind trying the repo I created to confirm it's also working for you? https://github.com/wallabyjs/wallaby-2819

If it works for you, there may be some configuration that I've missed that wasn't in your diagnostics report. In that case, could you please compare the repo we created with your project to try identify the differences? If you can reproduce the problem in our repo, please create a pull request (or else send us the updates) so we can see the problem for ourselves.

**Comment by jrobber** [comment] 2021-09-30 15:48
So, I managed to accidently fix this.  The problem was that I had other tests that were throwing an error I was swallowing.  Once I found that and fixed it this error went away.

It was extra confusing because I was using .only and the error throwing test wasn't included within the .only filter, but still caused the runner to get into this weird/bad state.

I could work on adding the case needed if you'd like.  This is I guess technically a bug, but probably a super rare one.

**Comment by smcenlly** [comment] 2021-10-01 01:39
I'm going to close the issue but we would appreciate knowing how to reproduce your problem if you have the time to provide details (we will investigate whether we can better handle your scenario if we are able).

**Closed by smcenlly** 2021-10-01 01:39 UTC
Labels: more info is required

**Comment by jrobber** [comment] 2021-10-01 18:41
@smcenlly Here is an updated version of the repo with reproduction capability:
https://github.com/wallabyjs/wallaby-2819/pull/1

To reproduce:
* Start wallaby
* Open `getNextPage.ts`
* Delete line 17 `throw new Error('BOOO')`

Usually happens pretty fast for me, but sometimes I have to add and remove that line a few times.
You should see the error on 1 out of 2 of the tests.

A second minor error also happens where one of the tests is failing an except statement, but doesn't end.  Instead it just hangs and times out.

**Comment by smcenlly** [comment] 2021-10-05 02:07
Thanks for the reproducible example. By default, when Wallaby runs your `jest` tests it reuses node worker processes for subsequent test executions. From what we can tell, there is something in the [`nock`](https://github.com/nock/nock) code (or its use from `pollyjs` that is not always resetting things correctly when a subsequent test is executed immediately after the current test. This could be caused for example by some asynchronous clean up code that's a part of `nock` or `pollyjs`.

You would need to identify the cause of this and fix it in the relevant library. If you wanted to do this, you would need to set up a test-harness to repeatedly call/use the same code over and over again. Probably not something you would want to do unless you really need to.

While these problems are fairly rare, Wallaby does have a setting ([`workers.restart`](https://wallabyjs.com/docs/config/workers.html)) that allows you to tell Wallaby to restart each worker process for subsequent test executions to get around such problems. The draw back of this setting is that subsequent test executions will be a little slower because a process needs to be stopped/started between test runs.
