### ISSUE TITLE
Corruption of non-instrumented files

### ISSUE THREAD

**Issue by zubivan** [wallabyjs/public#1177] opened 2017-05-31 14:49 UTC
### Issue description or question
I bumped into a strange issue using wallaby. So, at one of the projects I'm working on we store some test data in sqllite DBs and if I run our tests with jest it works just fine, but with wallaby all test files are getting corrupted. I tested it with some other binary file types and it seems to work fine.

I created a small sample project here => https://github.com/zubivan/wallaby-data-corruption

### Wallaby.js configuration file

Wallaby.js Core v1.0.431

```javascript
module.exports = function (wallaby) {
    return {
        files: [
            { pattern: './node_modules/**/*.*', instrument: false, load: false, ignore: true },
            { pattern: './**/*.spec.+(ts|tsx)', instrument: false, load: false, ignore: true },
            { pattern: './**/*.test.+(ts|tsx)', instrument: false, load: false, ignore: true },

            { pattern: './files/**/*.*', instrument: false, load: false, ignore: false },
            { pattern: './**/*.snap', instrument: false, load: false, ignore: false },
            { pattern: './**/*.+(ts|tsx)', instrument: true, load: false, ignore: false },
            "package.json",
            "tsconfig.json"
        ],
        tests: [
            '/**/*.spec.+(ts|tsx)',
        ],
        env: {
            type: 'node',
            runner: 'node',
        },
        testFramework: 'jest',
        debug: true
    }
};
```

### Code editor or IDE name and version
Visual Studio Code v1.1.2

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment] 2017-06-01 01:33
Thanks for the repo. 
The issue is fixed in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). I have also [sent you the PR](https://github.com/zubivan/wallaby-data-corruption/pull/1) that you may use as a workaround.

**Closed by ArtemGovorov** 2017-06-01 01:33 UTC

**Comment by zubivan** [comment] 2017-06-01 07:21
@ArtemGovorov thanks for the quick fix! So, should I specifically mark these files as `binary` all the time? Or wallaby is going to recognize it by default?

**Comment by ArtemGovorov** [comment] 2017-06-01 07:35
@zubivan  With the fix you may omit marking the `.db` files as binary. If some binary files in future don't work for you as is, please let us know (extension/type), but while we're fixing the new file types, please feel free to use the `binary` flag.
