### ISSUE TITLE
Having the wallaby.js config file in a sub-directory

### ISSUE THREAD

**Issue by flegall** [wallabyjs/public#2718] opened 2021-05-28 13:16 UTC
Reproduction : https://github.com/flegall/wallaby-try-pnp

### Issue description or question
Hi, I'm trying to set up a config file for wallaby.js :
I don't want to the config file to be at the root of the repository, there are plenty of files there, we would rather hide it.
So I've moved the wallaby.js file to build/jest/wallaby.js
I can properly select it in VsCode, but it doesn't load Wallaby.

I have the following error : 
```
‍[Info]  Started Wallaby.js Core v1.0.1084
[Error] Failed to load configuration file: Automatic Jest configuration error: Module jest-cli is not found in '.'. 
```

My wallaby.js file is : 
```
module.exports = () => {
  return {
      // Setup auto detect based on jest config
      autoDetect: true,
      testFramework: {
          configFile: '../../jest-config.js'
      },

      // Ensure not all tests are run on start
      addModifiedTestFileToExclusiveTestRun: false
  };
};

```

Is this configuration supported ? Can you fix it ?

You can reproduce it here : https://github.com/flegall/wallaby-try-pnp

### Wallaby diagnostics report

The Copy Diagnosis Report was not found since Wallaby did not start : 
![image](https://user-images.githubusercontent.com/1051458/119989311-51667b80-bfc7-11eb-93ae-2d619d08f335.png)

**Comment by smcenlly** [comment] 2021-05-28 22:09
Wallaby does not support putting configuration files in nested folders beneath the project root, **all Wallaby.js configuration files must live in your project root**. If you are using `Automatic Configuration` without a config file then you may use the `Automatic Configuration <custom directory>...` command.

Closing this issue as it is a duplicate of feature request https://github.com/wallabyjs/public/issues/1422. From #1422:

> [...this is] a bit tricky to implement, because at the moment some of wallaby core logic (as well as various integrations, like Webpack/Jest) assume that wallaby config is located in the project's root.

**Closed by smcenlly** 2021-05-28 22:09 UTC
