### ISSUE TITLE
Ava beforeEach only runs first time

### ISSUE THREAD

**Issue by drewschrauf** [wallabyjs/public#1012] opened 2017-02-13 11:02 UTC
### Issue description or question

When testing with Ava, it appears that `beforeEach` hooks only run the first time tests are executed. When code or tests are changed, any references to `t.context` properties become undefined. Modifying the `beforeEach` hook will fix all tests until the next modification.

This is a screenshot of my test file after deleting/adding the semicolon at the end of the line.
![wallaby-ava-error](https://cloud.githubusercontent.com/assets/596128/22880789/b43f1bd4-f237-11e6-957e-5ce23377bb9b.png)
 
Running ava from the terminal with `npm test` executes the test successfully.

### Example Project

https://github.com/drewschrauf/wallaby-ava-issue

### Code editor or IDE name and version

Visual Studio Code v1.9.1

### OS name and version

Linux/MacOS

**Comment by ArtemGovorov** [comment] 2017-02-13 11:16
Thanks for reporting the bug. The issue is fixed and the fix fixed in published in 
[the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version.

**Closed** 2017-02-13 11:16 UTC
Labels: bug

**Comment by drewschrauf** [comment] 2017-02-13 11:19
Fix confirmed. Thanks!
