### ISSUE TITLE
How can deal with the VSIXinstaller.exe stopped when update the VS2015?

### ISSUE THREAD

**Issue by muguangyuze** [wallabyjs/public#720] opened 2016-08-02 03:38 UTC
### Issue description or question

hello,
When my update the VS2015 enterprise using KB3165756, the VSIXinstaller.exe is stopped result to the update stop.It waste much time,but can not make a step forward.

And I find the contents of the log VSIXInstaller_ ID.log from %temp% is empty,obviously it's not working well. But opening the task manager , I find the progress of VSIXinstaller.exe is running and  consuming much CPU and I can not close it even in Administrator because of showing 'there is no permission ’.

So, I must  forced shutdown my computer, but when restart the computer , it may be also running because of failure of install Microsoft visio 2013 which showing the installing of VS 2015   hang up.

I cant find the method to solve it.
And I am shocked by the fact that  VSIXinstller.exe can not be forced close and when restarted computer  it also running.

Can any one help me?
### Wallaby.js configuration file

``` javascript
// paste your config here
```
### Code editor or IDE name and version

Visual Studio 2015
### OS name and version

Windows 10 professional

**Comment by ArtemGovorov** [comment] 2016-08-02 07:40
Hi, we can't reproduce the issue in a similar environment, so it may not be wallaby specific.
Can you install any other extensions other than wallaby.js in your VS?

**Comment by ArtemGovorov** [comment] 2016-08-02 08:39
You may also check if this issue is related: https://github.com/wallabyjs/public/issues/238

**Comment by ArtemGovorov** [comment] 2016-12-13 09:23
Closing the issue for now, please let me know if it's still valid.

**Closed** 2016-12-13 09:22 UTC
Labels: Visual Studio
