### ISSUE TITLE
Thread is blocked in webstorm windows

### ISSUE THREAD

**Issue by kvernon** [wallabyjs/public#2572] opened 2020-11-22 18:12 UTC
### webStorm's terminal is blocked by wallabyjs on windows

I run WebStorm at work and at home. Equally I run WallabyJS in both places too. At work I use a macbook pro (Catalina), and at home it's Windows 10 pro 64x. Both use latest WebStorm and wallabyjs.

When I run WallabyJS, and then I'm terminal, I run and install commamd, `npm i -D ts-jest` in mac, both run; meaning WallabyJS continues to test and the bash terminal continues to install the new dependency.

The problem is within windows environment. When I do the same scenario, WallabyJS runs (first), and in terminal, which is powershell, the npm i command hangs because the thread is locked by WallabyJS. 

The work around is to stop WallabyJS, and then run the command. Finally start WallabyJS back up.

I did try to open a ticket with logs with jetbrains, but they said the issue is with you all. 

I'd like to share logs, but I don't want them to be public.

**Comment by smcenlly** [comment] 2020-11-22 22:34
We have tried the same on Windows 10 Pro 64-bit (Version	10.0.19041 Build 19041) and the command does not hang for us. We were using node version '14.13.0' and WebStorm 2020.3 EAP (Build #WS-203.5981.31, built on November 19, 2020)

We would be happy to take a look at your Wallaby Diagnostics report but I don't think there is going to be anything in it that indicates what is going on. You may email the report to us: hello@wallabyjs.com.

In order to diagnose what is going wrong, you may like to use [Microsoft's Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) and use the `Find -> File Handle or DLL...` to search for `node_modules` or `package.json` to try and determine which process is locking your file(s). It's also possible that your system's virus scanner is locking the file so you may also try disabling that temporarily to see if that is the cause of your problem.

**Comment by smcenlly** [comment] 2021-03-08 00:46
Closing this issue as we never heard back.

**Closed by smcenlly** 2021-03-08 00:46 UTC
Labels: more info is required, solution suggested
