### ISSUE TITLE
Inline test failures for Jasmine results show some newlines as `←[` on Windows

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [wallabyjs/public#1365] opened 2017-10-25 15:07 UTC
### Issue description or question

Although the failure renders correctly in the VS Code Wallaby.js Tests output window, the inline complaint swallows the first newline and puts `←[` for the rest.

![image](https://user-images.githubusercontent.com/3335181/32006211-fa658356-b95a-11e7-9765-2c759be29965.png)

```
​​​​​1 failing tests, 17 passing​​​​​
  
  ​​​​ sets a width with hidden overflow when given a width​​​​ ​​​[9 ms]​​​​
    ​​​​
    ​​Error: Expected <div> component style values to match for key "width", but they didn't​​
    ​​Expected: width: "width"​​
    ​​Actual: width: 7​​
      at Object.<anonymous> ​src/Views/Crop.test.tsx:39:1​
```

_(the language is TypeScript (`.tsx)`, but that's probably unrelated)_

### Wallaby.js configuration file

```javascript
module.exports = (wallaby) => ({
    compilers: {
        "**/*.ts?(x)": wallaby.compilers.typeScript({
            compilerOptions: {
                target: "es3",
            },
        }),
    },

    env: {
        type: "node",
    },

    files: [
        "package.json",
        "src/**/*.ts",
        "!src/**/*.test.ts",
        "src/**/*.tsx",
        "!src/**/*.test.tsx",
    ],

    setup: () => {
        const jestConfig = require("./package.json").jest;

        // Necessary: create-react-app doesn't support overriding this in package.json
        jestConfig.setupTestFrameworkScriptFile = "./src/testSetup";

        wallaby.testFramework.configure(jestConfig);
    },

    testFramework: "jest",

    tests: [
        "src/**/*.test.ts",
        "src/**/*.test.tsx",
    ],
});
```

### Code editor or IDE name and version

Visual Studio Code v1.17.2

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment] 2017-10-26 01:24
Thanks for the report. The issue was caused by the `jest-enzyme` package, it is now fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) v1.0.508.

**Closed by ArtemGovorov** 2017-10-26 01:24 UTC

**Comment by JoshuaKGoldberg** [comment] 2017-10-26 01:35
@ArtemGovorov your level of customer support is incredible. Thank you!
