### ISSUE TITLE
Constant prompting for license details in WebStorm

### ISSUE THREAD

**Issue by carlansley** [wallabyjs/public#810] opened 2016-09-29 17:01 UTC
### Issue description or question

Wallaby is asking me (and my co-workers) to re-enter license details a little too often for our liking.  i.e. the "No valid wallaby.js license found... etc etc" dialog.   Not just on every patch/upgrade of WebStorm, and macOS, but sometimes also randomly.  This morning, booting up my desktop, yet another license dialog box.  It has become more of an issue the past few months.   We don't see these issues with other licenses such as our JetBrains IDEs.

Would be nice if the license was more "sticky", in particular dealing with IDE/OS updates better.

### Wallaby.js configuration file

N/A

### Code editor or IDE name and version

WebStorm v2016.3 EAP (and earlier)

### OS name and version

macOS Sierra (but also El Capitan)

**Comment by ArtemGovorov** [comment] 2016-09-30 01:18
Wallaby stores its license key [in the IDE cache folder](https://github.com/wallabyjs/public/issues/273), perhaps there's some cache cleaner installed on your machine that cleans up the folder?

**Comment by carlansley** [comment] 2016-09-30 18:53
No nothing like that.  Maybe WebStorm is doing something?

What I've done for now is made a copy of the ~/Library/Caches/WebStorm2016.3/wallaby directory so next time it happens I can work out what changed.

**Comment by ArtemGovorov** [comment] 2016-10-07 09:06
@carlansley Awesome, thanks! Please let me know how the content of the folder changed next time it happens (specifically the `~/Library/Caches/WebStorm2016.3/wallaby/key.lic` file).

**Comment by carlansley** [comment] 2016-10-24 20:36
Ok got to the bottom of this.  What's going on is macOS is deleting the contents of ~/Library/Caches when OS updates are performed.  I just came back to my desk and the wallaby directory is empty after it updated from 10.12 to 10.12.1.

I have these updates configured to occur automatically and mostly I never notice the update has happened.  They're particularly frequent if you're part of the Apple macOS beta program (which I have been in the past, not right now).

This may be new behavior with macOS 10.12 (Sierra), don't recall this happening with prior versions of OS X.

**Comment by ArtemGovorov** [comment] 2016-10-25 01:30
@carlansley Thanks for the investigation and your help! We have changed the location of the license key for IntelliJ platform to address the issue. It'll ask you to re-enter the license key one more time after the next OS update, but after that it should not bother you anymore with the key re-entering dialog.

**Comment by ArtemGovorov** [comment] 2016-10-25 01:31
Forgot to mention, the issue is fixed in wallaby WebStorm plugin v1.0.77.

**Closed by ArtemGovorov** 2016-10-25 01:30 UTC
