### ISSUE TITLE
Wallaby.js is updating and will be started automatically when the update is complete

### ISSUE THREAD

**Issue by sgariepy** [wallabyjs/public#2584] opened 2020-12-12 21:04 UTC
### Wallaby.js is updating and will be started automatically when the update is complete

Using any command (start, stop, select configuration, etc) from Wallaby results in this message:

    Wallaby.js is updating and will be started automatically when the update is complete.

Very similar to issue #2547 except I'm not in a corpo network, and tried the suggested resolution, ie: remove Wallaby extension and remove related files in `~/.vscode/extensions/wallaby*` without success.

VS Code version is 1.52.0
Wallaby-vscode extension: 1.0.251
Wallaby version: 1.0.991

I had the Wallaby license with support until last november, now I'm supposed to be in the "perpetual" license without support or update but extension is still trying to update to 1.0.991 each time I open VSCode.

No output in Wallaby Console.

<img width="536" alt="wallaby-updating" src="https://user-images.githubusercontent.com/38040297/101994730-8a699880-3c92-11eb-9c6d-a1fce04e3838.png">

**Comment by smcenlly** [comment] 2020-12-13 22:16
It sounds like your installation has somehow been corrupted. We tried your license key on our own machines and everything is working.

Could you please uninstall and remove all Wallaby artifacts and then reinstall by following these instructions:
1. Uninstall the Wallaby extension in VS Code
2. Close all instances of VS Code
3. Delete the `~/.vscode/extensions/wallaby*` directories as you had previously done.
4. Delete the `~/.wallaby` directory
5. Start VS Code
6. Install the Wallaby extension from the VS Code marketplace
7. Enter your license (either through the VS Code dialog, or via the command: `Wallaby.js: Manage License Key`
8. Wait about 1 minute while Wallaby downloads the correct version (v1.0.991)
9. Start Wallaby

If you're still have problems, you may also follow our [offline installation instructions](https://wallabyjs.com/docs/intro/offline.html). Please make sure that you uninstall and delete all Wallaby artifacts first before following these instructions.

**Comment by sgariepy** [comment] 2020-12-14 17:02
Both methods does not work (uninstall/reinstall and offline install), I reused an old installation from a previous installation of macOS (now on Big Sur).

**Comment by ArtemGovorov** [comment] 2020-12-15 00:21
Can you please:
- attach (or email to hello@wallabyjs.com) an archived `~/.wallaby` folder,
- share the contents of VS Code Dev Tools Console (`Help - Toggle Developer Tools` or command with the same name) for the scenario when it shows the `Wallaby.js is updating and will be started automatically when the update is complete.` message and other commands don't work.

>  I reused an old installation from a previous partition of macOS (now on Big Sur).

Do you mean you just copied it over and it's working now?

**Comment by sgariepy** [comment] 2020-12-15 14:24
> Do you mean you just copied it over and it's working now?

Yes, uninstalled Wallaby Extension, closed VC Code, deleted `~/.wallaby` and `~/.vscode/extensions/wallaby*`, copied those directories from previous partition at their proper places, and I can now start Wallaby (also let `"wallaby.noAutomaticInstall": true,` setting as suggested in offline installation documentation. 

----

My steps now to reproduce _Wallaby.js is updating_:

1. Remove extension and close VS Code
1. Delete folders `~/.wallaby` and `~/.vscode/extensions/wallaby*`
1. Open VS Code, commented `"wallaby.noAutomaticInstall": true,`,  and open Dev Tools console
1. Reinstall Wallaby.js Extention, wait 1-2 minutes and provide license key.
1. Execute command **Wallaby Start**

Console output:

```
[Extension Host] Error: ENOENT: no such file or directory, stat '/Users/sgariepy/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.252/wallaby_missing/package.json'
    at statSync (fs.js:915:3)
    at Object.fs.statSync (electron/js2c/asar.js:278:27)
    at m.<anonymous> (/Users/sgariepy/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.252/dist/index.js:15:12652)
    at /Users/sgariepy/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.252/dist/index.js:15:2002
    at Object.next (/Users/sgariepy/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.252/dist/index.js:15:2107)
    at i (/Users/sgariepy/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.252/dist/index.js:15:824)

[Extension Host] Error: Cannot find module '/Users/sgariepy/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.252/wallaby_missing/package.json'Require stack:- /Users/sgariepy/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.252/index.js- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at Function.r.resolve (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:16:406)
    at Function.m._requireNoCache (/Users/sgariepy/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.252/dist/index.js:15:14626)
    at m.<anonymous> (/Users/sgariepy/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.252/dist/index.js:15:11531)
    at /Users/sgariepy/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.252/dist/index.js:15:2002
    at Object.next (/Users/sgariepy/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.252/dist/index.js:15:2107)
    at i (/Users/sgariepy/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.252/dist/index.js:15:824)
```

Extension is now on version 1.0.252

You will notice that it's looking for a `wallaby_missing` directory, I don't have this directory, I have many `wallaby[a-f0-9]{6}` folders.

I have sent archive of `~/.wallaby` to hello@wallabyjs.com.

**Comment by smcenlly** [comment] 2020-12-16 00:07
Thanks for sending through the `.wallaby` directory via email. Everything in your folder appears OK.

The `wallaby_missing` error is expected; this is what happens on initial installation when the Wallaby core runtime needs to be downloaded.

It's also expected to have one or more `/wallaby[a-f0-9]{6}/` folders - this is where the Wallaby core version is downloaded to and sourced from. You should also have a `core.json` file in the extension root folder. You will find that after a period of time, old `/wallaby[a-f0-9]{6}/` are cleaned up once Wallaby is sure that these are not in use any more.

In your case, Wallaby's process of extracting the latest version and then reading those files is failing on your environment. We have seen similar errors in the past and they have either been caused by file permission issues (e.g. did you copy the `.vscode` folder from your old installation - if so, this might be causing the problem) or by virus scanner issues where your virus scanner does not allow our process to read files extracted from the download zip file. If you have a virus scanner running, you may try excluding the VS Code Wallaby extension directory.

Given that you have everything working now, I'm going to close this issue. If you have further problems, please let us know. As a first step, we'd suggest uninstalling, deleting and then reinstalling VS Code and also disabling your virus scanner on the extensions folder.

**Closed by smcenlly** 2020-12-16 00:07 UTC

**Comment by sgariepy** [comment] 2020-12-16 04:30
For further information, I did not copied the `.vscode` folder from an old installation or any files of VS Code itself.  This "resolution" was only for Wallaby Extension (as mentioned, only `~/.wallaby` and `~/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.251` was copied).

File permissions as seen in terminal seems to be fine and no virus scanner is concerned.

I'm aware that support part of my license is expired, your help goes very beyond what I expected, it's appreciated.  Thank you for your time and help 😊

**Comment by sgariepy** [comment] 2020-12-18 15:09
Now I'm having the same problem on my work computer.

**Comment by smcenlly** [comment] 2020-12-18 23:43
We've identified that the problem is a time-zone related issue caused by one of our dependencies [`adm-zip-mit`](https://www.npmjs.com/package/adm-zip-mit) not correctly treating times in our zip file extraction as UTC time (using local time instead). This meant that Wallaby thought your on-disk files had an incorrect date for your expired license and your local Wallaby instance always thought an update was required vs. Wallaby's update service giving you the correct Wallaby core version. Your license expiry date coupled with the time the last version eligible for your license was released meant that you had back luck running into this problem.

We've updated the Wallaby extension for VS Code (v1.0.254) to work around `adm-mit-zip`'s incorrect time handling problem.

Please update your Wallaby extension for VS Code to the latest version and everything should work for you.

**Comment by sgariepy** [comment] 2020-12-21 15:28
Extention has been updated to 1.0.254 and everything is working as expected now.
