### ISSUE TITLE
Wallaby.js in VS Code Failed to set up project file system: Error: not opened​​

### ISSUE THREAD

**Issue by BBlackwo** [wallabyjs/public#1075] opened 2017-03-21 03:52 UTC
### Issue description or question

Wallaby won't start. Fails with the following error:

```
[Error] Failed to set up project file system: Error: not opened​​
​​[Error]   at WebSocket.send (/Users/blackwoodb/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.48/wallaby/node_modules/ws/lib/WebSocket.js:219:16)​​

​​[Error]   at Object.send (/Users/blackwoodb/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.48/wallaby/server.js:19:13100)​​
​​[Error]   at i.<anonymous> (/Users/blackwoodb/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.48/wallaby/server.js:14:3154)​​
​​[Error]   at emitOne (events.js:96:13)​​
​​[Error]   at i.emit (events.js:188:7)​​
​​[Error]   at i.value (/Users/blackwoodb/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.48/wallaby/node_modules/phantom/receiver.js:1:23446)​​
​​[Error]   at i.value (/Users/blackwoodb/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.48/wallaby/node_modules/phantom/receiver.js:1:22807)​​
​​[Error]   at i.value (/Users/blackwoodb/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.48/wallaby/node_modules/phantom/receiver.js:1:17915)​​
​​[Error]   at _combinedTickCallback (internal/process/next_tick.js:67:7)​​
​​[Error]   at process._tickCallback (internal/process/next_tick.js:98:9)​​
​​[Error] From previous event:​​
​​[Error]   at i.value (/Users/blackwoodb/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.48/wallaby/node_modules/phantom/receiver.js:1:14381)​​
​​[Error]   at EventEmitter.<anonymous> (/Users/blackwoodb/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.48/wallaby/node_modules/phantom/receiver.js:1:12248)​​
​​[Error]   at emitOne (events.js:101:20)​​
​​[Error]   at EventEmitter.emit (events.js:188:7)​​
​​[Error]   at EventEmitter._emit (/Users/blackwoodb/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.48/wallaby/server.js:16:28582)​​
​​[Error]   at /Users/blackwoodb/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.48/wallaby/server.js:16:18149​​
​​[Error]   at _combinedTickCallback (internal/process/next_tick.js:67:7)​​
​​[Error]   at process._tickCallback (internal/process/next_tick.js:98:9)​​
```

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'src/wallabyTest.js',
    'src/**/*spec.js'
  ],

  module: {
    loaders: [
      {test: /\.css$/, loader: 'raw-loader'},
      {test: /\.html$/, loader: 'raw-loader'},
      {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
      {test: /\.json$/, loader: 'json-loader'},
      {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
      {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
      {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
      {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
    ]
  }
});

var compilerOptions = require('./src/tsconfig.spec.json').compilerOptions;

module.exports = function (wallaby) {

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.less', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*.sass', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.x

### OS name and version

OSX

**Comment by ArtemGovorov** [comment] 2017-03-21 04:12
Could you please try re-installing the extension and trying again? Also please try running [this sample](https://github.com/wallabyjs/calculator-sample) to see if the issue is project specific or not.

**Comment by BBlackwo** [comment] 2017-03-21 04:53
I tried reinstalling and the sample app and still have the same issue =/

**Comment by ArtemGovorov** [comment] 2017-03-21 06:04
It looks like for something is closing the WebSocket connection between the wallaby core and the editor. We have never seen anything like this, neither any of our users had ever hit it. 

Is there any special network configuration you have on your machine that could be causing the local WebSocket connection (`ws://localhost:...`) loss that you may think of? Do you have another machine to try running wallaby?

I have also added some logging to the latest wallaby core, try
- [updating the core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), 
- restarting your VS Code,
- starting wallaby,
- then opening the VS Code Dev Tools console (`Help - Toggle Developer Tools`) to see what's there (please paste the output here).

**Comment by BBlackwo** [comment] 2017-03-21 07:27
No special network configuration that I can think of, sorry.

Did those steps. Here's the output from the console:

```
[Extension Host] [Wallaby Console] VS Code extension v1.0.47
workbench.main.js:136 [Extension Host] [Wallaby Console] Core v1.0.396
workbench.main.js:136 [Extension Host] Uncaught Exception:  Error: Parse Errord.logExtensionHostMessage @ workbench.main.js:136
workbench.main.js:136 [Extension Host] Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)d.logExtensionHostMessage @ workbench.main.js:136
workbench.main.js:136 [Extension Host] Uncaught Exception:  Error: socket hang upd.logExtensionHostMessage @ workbench.main.js:136
workbench.main.js:136 [Extension Host] Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)d.logExtensionHostMessage @ workbench.main.js:136
workbench.main.js:142 Parse Error: Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)e.onUnexpectedError @ workbench.main.js:142
workbench.main.js:142 socket hang up: Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)e.onUnexpectedError @ workbench.main.js:142
```

**Comment by ArtemGovorov** [comment] 2017-03-21 07:38
Interesting, there are some error messages but not from wallaby, from VS Code itself, however may be related to the issue. It looks to me that there's something special in your network configuration that VS Code (and wallaby) doesn't like. Are you behind some corporate proxy/firewall?

**Comment by BBlackwo** [comment] 2017-03-21 09:30
Okay. No -- not behind any proxy or firewall. I completely reset my network settings and still an issue. Though the latest is slightly different.

```
​​[Error] Failed to set up project file system: Error: not opened​​
​​[Error]   at emitOne (events.js:96:13)​​
​​[Error]   at i.emit (events.js:188:7)​​
​​[Error]   at _combinedTickCallback (internal/process/next_tick.js:67:7)​​
​​[Error]   at process._tickCallback (internal/process/next_tick.js:98:9)​​
​​[Error]   at emitOne (events.js:101:20)​​
​​[Error]   at EventEmitter.emit (events.js:188:7)​​
​​[Error]   at _combinedTickCallback (internal/process/next_tick.js:67:7)​​
​​[Error]   at process._tickCallback (internal/process/next_tick.js:98:9)​​
```

**Comment by ArtemGovorov** [comment] 2017-03-21 12:49
I'm running out of ideas what can possible be wrong. We have thousands of users running the tool on the same OS and in the same editor without any issues, so I'm really puzzled.

Do you have any other machine to try running wallaby on?

**Comment by BBlackwo** [comment] 2017-03-23 23:06
Yes! Thanks @anibe! I had some [filtering software](http://www.x3pure.com/) running that was causing the issue. Disabled that and it's working great!

Thanks @ArtemGovorov for all the help as well. Really appreciate the the prompt responses.

**Comment by ArtemGovorov** [comment] 2017-03-24 00:45
Awesome, thanks for the update!
@anibe You rock!

**Closed by ArtemGovorov** 2017-03-24 00:45 UTC
Labels: VS Code
