### ISSUE TITLE
Wallaby App missing tests

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#1278] opened 2017-08-29 12:23 UTC
### Issue description or question

The wallaby web application seems to be missing off tests within it's report. The IDE is correct, and even the top right corner of the Wallaby App correctly reports *13* tests. But 3 are missing from the tree....

I've tried reloading the browser, and a full re-start of Wallaby. But the issue still persists

![image](https://user-images.githubusercontent.com/1374775/29820676-2fe791d8-8cbd-11e7-87c1-3dbd8d05baa9.png)

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        name: "galaxy",
        files: [
            { pattern: "node_modules/jquery/dist/jquery.js", instrument: false },
            { pattern: "node_modules/babel-polyfill/dist/polyfill.js", instrument: false },
            { pattern: "packages/ui-core/src/**/*.js", load: false },
            { pattern: "packages/javascript-core/src/**/*.js", load: false },
            { pattern: "packages/context/src/**/*.js", load: false },
            { pattern: "packages/galaxy/src/**/*.js", load: false, instrument: true },
            { pattern: "packages/galaxy/tests/data/*.json", load: false },
            { pattern: "packages/galaxy/tests/preProcessors/*.js", load: false },
            { pattern: "packages/galaxy/tests/mocks/*.js", load: false },
            { pattern: "packages/galaxy/tests/*.js", load: false },
            { pattern: "packages/galaxy/tests/**/*.snap", load: false, instrument: false },
            { pattern: "packages/galaxy/src/**/*.less", load: false, instrument: false },
        ],
        tests: [
            { pattern: "packages/galaxy/tests/specs/**/*.unit.js" },
        ],
        filesWithNoCoverageCalculated: [
            "!packages/galaxy/**/*.js",
        ],
        env: {
            type: "node",
            runner: "node",
        },
        testFramework: "jest",
        compilers: {
            "**/*.js": wallaby.compilers.babel({ babel: require("babel-core") }),
        },
        setup: (target) => {
            target.testFramework.configure({
                moduleNameMapper: {
                    ".*.(less|css)$": require("path").join(target.localProjectDir, "/packages/galaxy/tests/preProcessors/jest.js"),
                },
            });
        },
    };
};
```

### Code editor or IDE name and version

Sublime Text v3 build 3142

### OS name and version

Windows 10 x64

**Comment by IPWright83** [comment] 2017-08-29 13:08
Seems that using

**Comment by ArtemGovorov** [comment] 2017-08-29 23:40
Thanks for the report! Was able to easily reproduce it. It is certainly a bug, will be looking into it shortly.

**Comment by ArtemGovorov** [comment] 2017-08-30 02:17
The issue is fixed in the latest core and wallaby app updates. Update to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version (if not yet done automatically), restart wallaby and refresh your wallaby app to get v1.0.33 of the app - everything should be working with `constructor` name now.

**Closed by ArtemGovorov** 2017-08-30 02:17 UTC
Labels: bug
