### ISSUE TITLE
File ordering is wrong when a file matches multiple patterns

### ISSUE THREAD

**Issue by rochdev** [wallabyjs/public#245] opened 2015-08-28 17:34 UTC
I am trying to configure an app which requires module definition files to load before all other files. To achieve that, I am using the following patterns:

```js
[
  'src/**/*.module.js',
  'src/**/*.js'
]
```

However, this doesn't seem to work in wallaby.js as module files are mixed with the other files. Since module files match both patterns maybe that could be the cause, but the same glob patterns in the same order work properly for both gulp and karma.

**Comment by ArtemGovorov** [comment] 2015-08-29 02:17
I can't reproduce the issue on [this simple sample](https://github.com/wallabyjs/file-order-test). It has the structure you've described, everything seems to load as expected. Could you please try to make it fail for me and send the pull request or share some code that fails so I could reproduce the issue? Could you please also share your full wallaby.js config?

Another thing we may try to verify your assumption about the incorrect order is to inspect the generated sandbox page. To do that, set [`debug` flag to `true`](http://wallabyjs.com/docs/intro/troubleshooting.html#more-debug-information) in your config, run wallaby, [find the link to the sandbox](http://wallabyjs.com/docs/intro/troubleshooting.html#instrumented-code-and-generated-test-page) (see the second paragraph) and open it in Chrome with DevTools to inspect the generated HTML.

**Comment by rochdev** [comment] 2015-08-29 12:28
Looks like I cannot reproduce it at home actually. The sandbox shows all files in the correct order and the tests pass.

I have exactly the same environment and there were no changes to the code. Is there any kind of file caching maybe? I will try again at the office on Monday and report my findings.

**Comment by ArtemGovorov** [comment] 2015-08-29 12:37
Wallaby does cache files to make restarts faster and there're [some known issues with the cache](https://github.com/wallabyjs/public/issues/81), especially when [everything was working but then stopped](http://wallabyjs.com/docs/intro/troubleshooting.html#wallaby-was-working-but-then-stopped-working) even though there were no code changes or when rolling back to a version that certainly worked. Currently the file cache can be invalidated by changing your wallaby config (any, even meaningful change like a space will do) or just deleting the cache folder (whatever is easier). Please try that at work and let me know if it helps.

**Comment by rochdev** [comment] 2015-08-31 11:39
Clearing the cache indeed fixed the problem, however that behaviour makes tests unpredictable.

Please note that I am using version 1.0.27 so the fix for #81 doesn't seem to be working (at least for my scenario).

**Comment by ArtemGovorov** [comment] 2015-08-31 11:47
Agreed, it's a bit annoying, though doesn't happen frequently and from what I have heard only happens after some significant file manipulations, like moving source folders around, etc. I'd love to fix it, but so far couldn't reproduce it. Is the issue reproducible on some code that you could share, ideally a small sample repo on GitHub?

**Comment by rochdev** [comment] 2015-08-31 21:10
Unfortunately I don't know exactly at what point it started doing it, but now that I know about the problem I will be more alert to try and identify the cause next time. We did indeed significantly modify the structure of our application which caused many file manipulations in a very short amount of time, so hopefully this will not happen too often as of now.

**Comment by ArtemGovorov** [comment] 2015-09-01 01:11
@rochdev Thanks, let me know if you see it again.

**Comment by ArtemGovorov** [comment] 2015-09-02 13:31
Closing this one, when I'll reproduce it - will be fixing it as a part of #81, which is still open.

**Closed by ArtemGovorov** 2015-09-02 13:31 UTC
