### ISSUE TITLE
Snapshot testing does not work in ava

### ISSUE THREAD

**Issue by jhnns** [wallabyjs/public#996] opened 2017-02-07 17:39 UTC
### Issue description or question

If I use ava's snapshot testing feature, wallaby reports:

![bildschirmfoto 2017-02-07 um 18 29 07](https://cloud.githubusercontent.com/assets/781746/22703126/58f4397c-ed63-11e6-86f0-75f435012662.jpg)

Executing ava directly does work though.

After digging ava's source code, I found that they are trying to [read the current file path from their own globals.options object](https://github.com/avajs/ava/blob/415cd2fa0ec4bd2db585cffd8d9ba372e6f05a05/lib/snapshot-state.js#L11). This options object, however, is empty in case the test is executed by wallaby.

If executed with ava, the option object looks like:

```javascript
{ file: '/Users/jhnns/dev/peerigon/webpack-universal-dev-server/test/wire/wireAppServer.test.js',
  baseDir: '/Users/jhnns/dev/peerigon/webpack-universal-dev-server',
  tty: { columns: 160, rows: 76 },
  cwd: '/Users/jhnns/dev/peerigon/webpack-universal-dev-server',
  resolveTestsFrom: '/Users/jhnns/dev/peerigon/webpack-universal-dev-server',
  match: [],
  failFast: false,
  serial: false,
  require: [ '/Users/jhnns/dev/peerigon/webpack-universal-dev-server/node_modules/babel-register/lib/node.js' ],
  cacheEnabled: true,
  powerAssert: true,
  explicitTitles: false,
  babelConfig: 'default',
  pkgDir: '/Users/jhnns/dev/peerigon/webpack-universal-dev-server',
  concurrency: 0,
  updateSnapshots: false,
  cacheDir: '/Users/jhnns/dev/peerigon/webpack-universal-dev-server/node_modules/.cache/ava',
  precompiled: { '/Users/jhnns/dev/peerigon/webpack-universal-dev-server/test/wire/wireAppServer.test.js': 'd449eefd79cc76006629a724c9971d28' } }
```

If I add these lines at the beginning of my test file:

```js
require("ava/lib/globals").options = {
    file: __filename
};
```

snapshot testing does also work in wallaby.

I'm using `ava@0.18.1` and `wallaby@1.0.43`

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        env: {
            type: "node"
        },
        files: [
            "lib/**/**.js"
        ],
        tests: [
            "test/**/**.test.js"
        ],
        compilers: {
            "**/*.js": wallaby.compilers.babel()
        },
        testFramework: "ava"
    };
};


```

### Code editor or IDE name and version

Visual Studio Code v1.x

### OS name and version

OSX

**Comment by ArtemGovorov** [comment] 2017-02-08 03:31
Thanks for the report, the issue is fixed in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

Please note, that in order to correctly work, wallaby needs the local snapshots to be copied to its cache, so you'll need to add your snapshots to the `files` list:

```javascript
        ...
        files: [
            "lib/**/**.js",
            "test/**/*.snap"
        ],
        ...
```

**Closed by ArtemGovorov** 2017-02-08 03:31 UTC
