### ISSUE TITLE
Glob patterns not supporting exclusions

### ISSUE THREAD

**Issue by rochdev** [wallabyjs/public#241] opened 2015-08-23 14:24 UTC
Usually with node-glob you can do this:

```js
[
  src/**/!(*.spec).js`
]
```

However, with wallaby.js you are forced to rely on 2 separate patterns:

```js
[
  'src/**/*.js',
  '!src/**/*.spec.js'
]
```

While not necessarily a big deal, it means wallaby.js does not work the same as the JavaScript implementation of glob which makes writing patterns less intuitive. It also prevents using the same file patterns for Karma and wallaby.js

**Comment by fvanwijk** [comment] 2015-08-23 19:21
Duplicate of #69

**Comment by ArtemGovorov** [comment] 2015-08-23 22:56
Wallaby.js core is using `minimatch/glob`, but we also use an implementation of pattern matching on the IDE side (in Java) and the library we use is not a direct port, it unfortunately doesn't yet support patterns like this.

**Closed by ArtemGovorov** 2015-08-23 22:56 UTC
Labels: duplicate

**Comment by szarouski** [comment] 2015-10-28 19:35
Hi @ArtemGovorov, I often need to do something like following:
```
{pattern: 'bower_components/**/!(jquery-validate).js', instrument: false, load: false},
{pattern: 'bower_components/**/jquery-validate.js', instrument: true, load: false}
```

Is there a way to archive this with current version of wallaby?

Thank you.

**Comment by fvanwijk** [comment] 2015-10-28 20:28
Instead of this:
```
files: ['scripts/**/!(*Spec).js'],
tests: ['scripts/**/*Spec.js']
```
you could do:
```
files: [
  'scripts/**/*.js',
  { pattern: 'scripts/**/*Spec.js', ignore: true }
],
tests: ['scripts/**/*Spec.js']
```

Now you want to do the same, but with instrument yes or no.
I'm not sure how internal globbing of Wallaby is working, but you could try this:

```
files: [
  { pattern: 'bower_components/**/*.js', instrument: false, load: false },
  { pattern: 'bower_components/**/jquery-validate.js', instrument: true, load: false }
]
```

I hope that this overwrites the 'instrument' flag to true, because the pattern is defined after the first full matching pattern.

**Comment by szarouski** [comment] 2015-10-28 21:12
@fvanwijk thanks, that is what I tried initially and it doesn't look like wallaby overwrites instrument value.

**Comment by ArtemGovorov** [comment] 2015-10-29 00:42
@szarouski Internally wallaby just goes through the list of patterns from top to bottom and first satisfying pattern gets applied. So @fvanwijk  almost got it right, except the order. This should work:

``` JavaScript
files: [
  { pattern: 'bower_components/**/jquery-validate.js', instrument: true, load: false },
  { pattern: 'bower_components/**/*.js', instrument: false, load: false }
]
```

**Comment by ArtemGovorov** [comment] 2015-10-29 00:56
The pattern checking order logic was implemented the [same way as in Karma config](http://karma-runner.github.io/0.12/config/files.html) (see Ordering section) to make it easier for existing Karma users to re-use their config for wallaby. There's a note about it in the [file object docs (pattern section)](http://wallabyjs.com/docs/config/files.html#file-object).

**Comment by szarouski** [comment] 2015-10-29 01:38
Thank you Artem, very useful!
