### ISSUE TITLE
Unreliable test execution using Jest

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#1179] opened 2017-06-01 07:57 UTC
### Issue description or question

This is a very broad issue that I've created off the back of https://github.com/wallabyjs/public/issues/1127#issuecomment-305372645 . I'm going to caveat with "We don't have reliable steps to reproduce" which is why I've not raised this before, but it might be interesting to see if others have similar issues. Here are some of the things we see:

- Wallaby App gets out of sync with the IDE (https://github.com/wallabyjs/public/issues/798)
- Wallaby doesn't seem to re-run a particular test when code changes (e.g. changing the it)
- Wallaby running old versions of code (stale cache?)
- When using Jest the performance feels very sluggish compared to true unit tests.

Most of these problems only become apparent when we're dealing with slightly larger projects (e.g. the config below has 170 JavaScript files and currently 534 tests). I would also say these issues crop up when developing - you often have to stop/start Wallaby to get things going again properly, however just opening a project fresh and running the tests will be fine.

### Wallaby.js configuration file

This is an example from one of our many projects

```javascript
module.exports = function (wallaby) {
    process.env.NODE_ENV = 'wallaby';
    process.env.BABEL_DISABLE_CACHE=1;

    return {
        files: [
            { pattern: "./tests/**/*.snap", load: false, instrument: false },
            { pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false },
            { pattern: 'src/**/*.css', load: false },
            { pattern: 'src/**/*.js', load: false },
            { pattern: 'tests/utils/*.js', load: false },
            { pattern: 'tests/samples/*.js', load: true },
            { pattern: 'tests/data/*.js', load: false },
            { pattern: 'topology/**/*.json', load: false }

        ],
        tests: [
            // Exclude specific tests, that won't run in Jest (since they require a browserr object)
            { pattern: './tests/d3/utils/spark-points.test.js', ignore: true },
            { pattern: './tests/d3/utils/tooltips.test.js', ignore: true },
            // Load all other tests
            { pattern: './tests/**/*.test.js' }
        ],
        filesWithNoCoverageCalculated: ['src/**/index.js', 'tests/**/*.js'],
        hints: {
            ignoreCoverage: /ignore coverage/
        },
        env: {
            type: "node",
            runner: "node"
        },
        debug: false,
        testFramework: 'jest',
        compilers: {
            '**/*.js': wallaby.compilers.babel({ babel: require('babel-core') })
        },
        setup: (target) => {
           // process.env.BABEL_ENV = 'test';
           if (!global._babelPolyfill) {
               require("./node_modules/babel-polyfill/dist/polyfill.js");
           }
           target.testFramework.configure({
               moduleNameMapper: {
                   '.*\.(less|css)$': require('path').join(target.localProjectDir, '/tests/preProcessors/jest.js')
               },
           });
       },
    };
};

```

### Code editor or IDE name and version

Atom v1.17.2
Visual Studio Code v1.?
Sublime Text v3 build 3132

### OS name and version

Windows 10 x64

**Comment by ArtemGovorov** [comment] 2017-06-01 08:58
> When using Jest the performance feels very sluggish compared to true unit tests.

This sounds like a memory leak (possibly in Jest or Babel), will run some memory profiling.

As for other issues, we'll need a way to reproduce them because all of our tests/samples are working fine, so it may be something project specific.

**Comment by IPWright83** [comment] 2017-06-01 11:48
@ArtemGovorov yeah fully understand the need to try and reproduce. We encounter this across various projects with different tech, although they'll all use a similar webpack process.

**Comment by lgandecki** [comment] 2017-10-19 16:55
Same here - restarting wallabyjs become our habit, because of wallaby not reloading tests, or running old code.
as I mentioned in #789 we've had this problem with a lot of our codebases, and our client codebases. My company, along with xolv.io ( @sam_hatoum ) do quite a bit of consulting that involves making our clients codebases testable, and it's harder to sell them on wallabyjs when we have to constantly restart it to have desirable results. 
We've noticed that this problem occurs particularly often when there are syntax error in the code, while changing it, or just coding. (so when we don't have proper bracket/parentheses closings yet)
is that your experience also @IPWright83 ?

**Comment by IPWright83** [comment] 2017-10-24 08:26
Unfortunately I've not had much success in reproducing this consistently but I'll also try to answer those questions. I've not seen the problem in a little while (but I find my use of Wallaby comes and goes in bursts) which probably explains that.

> How frequently does the issue show up - few times an hour, once an hour, once a day?

I would have this happen several times, between restarts of Wallaby and then it would be OK for a day or two. Typically I believe I was writing tests at the time of breakages.

> What's your node.js version?

v6.9.4

> Does the issue show up when using different testing frameworks, or only in some, or more frequently in some?

I've found more problems using `Jest` than anything else. I don't recall ever having these issues when running in `Jasmine`.

> Are there any errors reported in the Wallaby Console prior/closer to the moment when wallabyjs "dies"?

I think I'd agree with @lgandecki in that I'd often be writing tests, so Wallaby would be spitting out failures to parse a file while I was writing the test. I'd then try a run all in file or similar and it would be inconsistent. Restarting wallaby sometimes fixed it (I have had to kill all node processes in the past). 

I think typically when I've seen it, I've been writing Async tests, which I know Jest has some issue with.  




Obviously if I get a reproduction again (going to be writing a lot of tests shortly) I'll update this issue. Unfortunately my employer isn't keen on sharing the code as these are quite significant packages, and I've failed to get reproductions on smaller packages.

**Comment by lgandecki** [comment] 2017-10-24 09:55
> wallaby stops running tests after some code changes (that often include breaking syntax),
> Is this a correct summary of the issue?
Yes
> Do you observe any other issues apart from this one?
No
> How frequently does the issue show up - few times an hour, once an hour, once a day?
It feels like multiple times a day. But when I ran debug and paid attention it was eventually consistent with jest results. (sometimes it would take extra time to get a correct result)
One thing that would a lot here is to have the reloading tests not show previous results. Change the color, or make it blink. Since there is no way of knowing if the test finished rerunning or not, this increased the feeling of not trusting the wallabyjs dots.
If they keep blinking at least I know something is wrong.

I'll be working on projects that use wallabyjs more in the next few weeks (doing more of a architecture, scaling work currently), and I will definitely be watching for this 

> What IDE/editor you're using?
Webstorm

> What's your node.js version?

Many different ones. At this moment 8.3.0 is my default.

> Does the issue show up when using different testing frameworks, or only in some, or more frequently in some?

I almost exclusively use jest.

> Could you please share your wallaby config from the simplest project where you've hit the issue?

I haven't been collecting this in a meaningful way, although I'll start now.
This is a typical config I use: https://github.com/lgandecki/modifyjs/blob/master/.wallaby.js

> Are there any errors reported in the Wallaby Console prior/closer to the moment when wallabyjs "dies"?

Can't say now. Will report when I see it again.

> When wallabyjs "dies", apart from the tool restart,
> does editing a file with tests (that are supposed to be red) help,
> or using Run file tests/Run project tests actions help,
> or no file editing helps and only wallaby restart helps?

As far as my experience goes, only hard restart (which takes more time than to just run the tests with jest)

> Could you please share a step by step example of any recent issue encounter? I.e. what you have been doing with your code, what exactly happened, what test errors you've been expecting to see when wallaby went permanently green?

I will get back to you with this next time I see it. But. The problem is, that I don't realize the problem, for a while, because there is no indication in the IDE. Everything keeps green, until I know for a sure that it shouldn't, and then I realize it got stuck sometime in the past.

Sorry if my posts sounded a bit harsh. I hate to submit issues without reproduction (especially since I'm myself an author/maintainer of a few libraries/tools, and I know the feeling). I've been having this problems for a long time, with all the other problems with wallabyjs I report them, with a repro if needed, and you fix them quickly. I haven't made a ticket since without a repro I know this is impossible to fix. But, also, talking with other devs I know I'm not the only one with the problems (otherwise I wouldn't even mention).

How difficult would be to add either (or both) of those things:
a) indicator that a given test is reloading
b) reload on save? (I realize that then you have to keep track of all changes that have been made up to the save point)

**Comment by ArtemGovorov** [comment] 2017-10-24 12:57
Thanks for your feedback!

I have a suspicion that the issue may actually be not wallaby specific, but Jest specific. Unfortunately there's no way to tell for sure without a repro.

@lgandecki 
> Since there is no way of knowing if the test finished rerunning or not

Wallaby displays status indicator at the bottom right corner of WebStorm IDE. If some tests are running, the status indicator should be displayed as a spinner.

> One thing that would a lot here is to have the reloading tests not show previous results. Change the color, or make it blink.

Unfortunately, in order to get specific code regions (including inside a test) that are rerunning/reloading, a test runner has to run them. So it's only when wallaby gets test run results back from a test runner, it can update them in the editor.

> How difficult would be to add either (or both) of those things:
> a) indicator that a given test is reloading

I don't see how it's possible for a test, but wallaby status indicator is supposed to be spinning if something is running.

> b) reload on save? (I realize that then you have to keep track of all changes that have been made up to the save point)

It is possible to implement, however, as I have mentioned, it will not help. The issue is not related to tracking changes - currently we're keeping track of all changes anyway and basically waiting for an inactivity period to try and run tests. Running on save will essentially be the same thing from the changes tracking perspective.

I'll need some debug logs to tell for sure, but all the described symptoms, especially this:

>>When wallabyjs "dies", apart from the tool restart,
>>does editing a file with tests (that are supposed to be red) help,
>>or using Run file tests/Run project tests actions help,
>>or no file editing helps and only wallaby restart helps?

> **As far as my experience goes, only hard restart (which takes more time than to just run the tests with jest)**

are pointing to the test runner, specifically Jest (that doesn't seem to return up-to-date results for some reason). If the issue was in wallaby tracking, then changing a test/file with tests would have immediately helped (as well as `using Run file tests/Run project tests`).

Other test runners are pretty much stateless, while Jest gets initialised once and keeps its internal state between test runs (just like it does in watch mode). I suspect something may break its state. An easy way to figure out whether it is Jest or not, is to turn on [`workers: {recycle: true}` option](https://wallabyjs.com/docs/config/workers.html), to recycle the whole node process, but doing so definitely affects test run performance because Jest will have to be initialised very frequently (and it's not cheap to start up, especially in larger projects).

Please keep the `debug: true` option set in your config, and as soon as you realise there's an issue, please share the Wallaby Console output (with some description of what you've been doing prior to the issue showing up).

**Comment by IPWright83** [comment] 2017-10-25 14:17
@ArtemGovorov I'm in agreement that I think it's Jest specific. I'd be interested to know if there's any sort of API for Wallaby/that it could hook into. If it weren't for the incredibly seamless snapshot functionality, we'd probably drop Jest and use something else.

**Comment by lgandecki** [comment] 2017-11-12 07:01
I have an Enrollment.js file:
```javascript
export default (response) => {
    const relevantData = response[0].schoolClass.name.split("-");
    const grade = parseInt(relevantData[0]);
    const section = relevantData[1];
    return { grade, section }
}
```

And test:
```javascript
import enrollmentTransform from '../Enrollment'

describe('transform response', () => {
    const transformed  = enrollmentTransform(responseData());
    it('should return school grade', () => {
        expect(transformed.grade).toEqual(6)
    })
    it('should return students section', () => {
        expect(transformed.section).toEqual('H')
    })
})


function responseData() {
    return [
        {
            "schoolClass": {
                "name": "6-H",
                "school": {}
            },
            "student": {}
        }
    ]
}
```

I was showcasing this to a guy that I was trying to convince to use wallaby in his new microservice, changed "-" in split to ";", test and the code kept green, and the spinner keeps going, this is the debug (not very helpful, I think)


console.log: Test Suites: 1 passed, 1 total
Tests:       23 passed, 23 total
Snapshots:   0 total
Time:        0.412s
Ran all test suites.

Sun, 12 Nov 2017 06:41:44 GMT wallaby:workers Run 23 test(s), skipped 0 test(s)
Sun, 12 Nov 2017 06:41:44 GMT wallaby:workers Sandbox [jp8k4] is responsive, closing it
console.log:   ● Console

    console.warn ../../../../../../../project/node_modules/react/lib/lowPriorityWarning.js:38
      Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs


console.log: PASS src/message/__tests__/dhabiws.test.js

console.log: 

console.log: Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   1 passed, 1 total
Time:        0.563s
Ran all test suites.

Sun, 12 Nov 2017 06:41:44 GMT wallaby:workers Sandbox [8r9c7] is responsive, closing it
Sun, 12 Nov 2017 06:41:44 GMT wallaby:workers Loaded unknown number of test(s)
Sun, 12 Nov 2017 06:41:44 GMT wallaby:workers Test executed: renders correctly given a serverTime prop
console.log: PASS src/component/DayPage/__tests__/AnalyseControls.test.js

console.log:   ● Console

    console.warn ../../../../../../../project/node_modules/react/lib/lowPriorityWarning.js:38
      Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs


Sun, 12 Nov 2017 06:41:44 GMT wallaby:workers Loaded unknown number of test(s)
Sun, 12 Nov 2017 06:41:44 GMT wallaby:workers Test executed: should execute the callback function
console.log: PASS src/message/__tests__/dhabiws.test.js

console.log: 

console.log: Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   1 passed, 1 total
Time:        0.519s
Ran all test suites.

Sun, 12 Nov 2017 06:41:44 GMT wallaby:workers Run 2 test(s), skipped 0 test(s)
Sun, 12 Nov 2017 06:41:44 GMT wallaby:workers Sandbox [341q2] is responsive, closing it
Sun, 12 Nov 2017 06:41:44 GMT wallaby:workers Sandbox [x67xp] is not responsive, recycling worker instance
Some long running code has been detected: one of your tests is taking more than 5000ms to execute.





When I tried changing the file under test, it kept spinning. I changed         expect(transformed.grade).toEqual(6)
 to toEqual(7) and it broke the test (meaning, things started to work properly)
I change it back to 6 - green, go back to the split method, and keep changing the argument from ";" to "-" back and forth, and once in ~3 changes I get the spinner.

Sun, 12 Nov 2017 06:54:41 GMT wallaby:workers Run 2 test(s), skipped 0 test(s)
Sun, 12 Nov 2017 06:54:41 GMT wallaby:workers Sandbox [pvi1r] is responsive, closing it
Sun, 12 Nov 2017 06:54:41 GMT wallaby:workers Sandbox [t1gwo] is not responsive, recycling worker instance
Sun, 12 Nov 2017 06:54:41 GMT wallaby:workers Sandbox [undefined] closing error, not opened

(here I make a change to the test file, which restarts everything:)

Sun, 12 Nov 2017 06:55:56 GMT wallaby:workers Sandbox [k3idz] can not be pinged: not opened
Sun, 12 Nov 2017 06:55:56 GMT wallaby:workers Cancelling test run, cancel requester priority: 2, current run priority: 2
Sun, 12 Nov 2017 06:55:56 GMT wallaby:project Test run was cancelled
Sun, 12 Nov 2017 06:55:57 GMT wallaby:workers Sandbox [k3idz] is not responsive, recycling worker instance
Sun, 12 Nov 2017 06:55:57 GMT wallaby:workers Sandbox [undefined] closing error, not opened
Sun, 12 Nov 2017 06:55:57 GMT wallaby:project Test run cancelled, re-queueing run data
Sun, 12 Nov 2017 06:55:57 GMT wallaby:project Test run finished
Sun, 12 Nov 2017 06:55:57 GMT wallaby:project Test run data re-queued
(..)



wallabyjs config:

```javascript
module.exports = function (wallaby) {

    return {
        files: [
            {pattern: 'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)', load: false},
            {pattern: '!src/**/*.test.js?(x)', load: false},
            {pattern: '.eslintrc', load: false},
        ],

        tests: [
            {pattern: 'src/**/*.test.js?(x)', load: true}
        ],

        compilers: {
            '**/*.js*': wallaby.compilers.babel()
        },

        env: {
            type: 'node',
            runner: 'node'
        },

        testFramework: 'jest',
        debug: 'true'

    };
};
```

jest itself works everytime:

Test Suites: 1 skipped, 19 passed, 19 of 20 total
Tests:       1 skipped, 103 passed, 104 total
Snapshots:   21 passed, 21 total
Time:        3.047s


There is no long running code here (no talking to a db - even mocked up, or external services).

Please let me know if there is anything you would like me to try here. Not sure if you do things like that, but we could try pairing if you wanted to see the internals?

**Comment by ArtemGovorov** [comment] 2017-11-12 09:01
@lgandecki Thanks for providing the details! Will analyse the log to see what we can find, I can already see a couple of strange things there. 

Could you please share what version of Jest you're using?

**Comment by lgandecki** [comment] 2017-11-12 09:05
Looks like in this particular case it is the newest ( I think ). -
```
$ ./node_modules/.bin/jest --version
v21.2.1
```

**Comment by ArtemGovorov** [comment] 2017-11-13 02:25
> I was showcasing this to a guy that I was trying to convince to use wallaby in his new microservice, changed "-" in split to ";", test and the code kept green

Actually this

> the code kept green

is expected. Your code (the function inside the `Enrollment.js` file) is not executed by any of your tests. Tests are supposed to turn red, but the code is not. Code turns red if there's a failing test that executes the code. In your case none of the two tests are executing any code in the `Enrollment.js` module.

If your test code was organised like this:

```javascript
describe('transform response', () => {
  let transformed;
  beforeEach(() => {
    transformed  = enrollmentTransform(responseData());
  })

  it('should return school grade', () => {
    expect(transformed.grade).toEqual(6)
  })
  it('should return students section', () => {
    expect(transformed.section).toEqual('H')
  })
})
```

then you'd get the code red when breaking it. Because now the code gets executed by both of your tests. So now when a test fails (for any reason), all code that was executed from the test will be marked pink.

> I changed expect(transformed.grade).toEqual(6) to toEqual(7) and it broke the test (meaning, things started to work properly)


In fact the `expect(transformed.grade).toEqual(6)` assertion will be green regardless of whether you are splitting by `-` or by `;`, (or by anything else). So your change to `;` is not breaking the test. Because (given your test data) this code

```javascript
const grade = parseInt(relevantData[0]);
```

always results in `6` (`parseInt('6-H')` is `6`), so your first test is passing.

Hope it makes sense. However, the notes above arenot related to the issue with the spinner. Also the second test should always get red when changing `-` to `;`, regardless of where the function is exercised.

I have also tried to analyse the attached log. 

Unfortunately, the largest past of it (part 1) is not related to the enrollment function test. As I can see from the log, it's related to editing/running the `src/message/__tests__/dhabiws.test.js` spec. 

I suspect that the `dhabiws.test.js` spec file may be related to the issue (or other specs in the project). Because when I [created the repo with all the provided file](https://github.com/ArtemGovorov/wallaby-1179), I can't break it by changing the code/tests. 

Could you please try [the repo](https://github.com/ArtemGovorov/wallaby-1179) to see if the issue shows up when editing the [`split` function argument](https://github.com/ArtemGovorov/wallaby-1179/blob/master/src/Enrollment.js#L2), or making other code changes?

I have also spotted a couple of anomalies in the provided log file - it looks like for some reason not one, but 2 or more sandboxes get created for each test run. See how within a single second Wallaby tries to inteact with different sandboxes:

```
Sun, 12 Nov 2017 06:41:44 GMT wallaby:workers Sandbox [341q2] is responsive, closing it
Sun, 12 Nov 2017 06:41:44 GMT wallaby:workers Sandbox [x67xp] is not responsive, recycling
```
and
```
Sun, 12 Nov 2017 06:54:41 GMT wallaby:workers Sandbox [pvi1r] is responsive, closing it
Sun, 12 Nov 2017 06:54:41 GMT wallaby:workers Sandbox [t1gwo] is not responsive, recycling worker instance
```

It is strange and shouldn't really happen. Normally a test run creates (and later recycles) only one sandbox.
This may very well be the root cause of all issues. Will investigate the source code to see how it could possibly happen.

> jest itself works everytime:

> Test Suites: 1 skipped, 19 passed, 19 of 20 total
> Tests: 1 skipped, 103 passed, 104 total
> Snapshots: 21 passed, 21 total
> Time: 3.047s

This looks like the log written when you run Jest for all tests. It's essentially like restarting Wallaby for every run - it'll also work everytime.

**Comment by ArtemGovorov** [comment] 2017-11-13 03:32
@lgandecki Any chance you have a full (not truncated log) of the log you've shared? If not, could you please trying the exact same thing in your real project one more time, and once the issue (spinner keeps going for more than 5 seconds) shows up - please copy/share the full log.

**Comment by ArtemGovorov** [comment] 2017-11-13 03:44
@lgandecki After spending some more time analysing the provided log, it looks to me like something  is crashing or forcing exit of test node process at the end of *some* test runs, so wallaby doesn't get a chance to report the results (and because it doesn't receive the results - it also displays the spinner). 

Not sure what could be doing it and why it only happens sometimes, but I have just published [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) where we're intercepting all `process.exit` calls within a test runner process. Try the latest version to see if it helps at all.

**Comment by lgandecki** [comment] 2017-11-13 04:58
I've just tried, and I see the same (or similar problem).
I'm not very comfortable sharing the whole log, as it has names of components etc that I'm not sure if my client would be comfortable with me sharing in a public, google-searchable place. Is there a different way for me to send it to you? I could make a secret gist and email. We can keep the discussion here, but, to be honest, I already feel a bit uneasy that I left the "dhabi" in the log.. ;-) 

I'm really hopefull we can figure out those problems one by one.. having trust in wallabyjs again / not having to restart it every once in a while (which is much slower than just using reliable jest watch mode) would be sooo fantastic. I'm so addicted to it, that it's hard for me to program in other languages now :) So, yeah.. thanks for that.

As for the explanation about how the wallabyjs should / should not behave depending on the structure of the test, I think this is a bit of misunderstanding, caused by me not explaining exactly what I expected to see - as I felt it was a bit irrelevant. But, when the wallabyjs works (the spinner stops working and I get the results back), I get the results I expected - code turns pink when I change the split from ";" to "-" , and yes, the grade keeps green, but the H doesn't, etc. Anyway - thanks for replicating and getting deep into the problem.

btw, huge offtop, but are you aware of projects like this for different languages? There is something like http://www.ncrunch.net for C# .. I would like to see sometihing like this for python, java, clojure, go.. At first I didn't think this would be possible for compiled languages, but seeing that someone done it for C# - blows my mind..  If not (if you are not aware, I mean), with the IntelliJ part done, maybe you would be interested in "expanding"?

**Comment by ArtemGovorov** [comment] 2017-11-13 05:08
> I've just tried, and I see the same (or similar problem).

Ok, thanks for trying it.

> I could make a secret gist and email. 

Great, please send the link (or the log) to hello@wallabyjs.com.

> but are you aware of projects like this for different languages?

We know NCrunch for C#, but aren't aware of any other commercial products for other languages. May consider expanding in future, but for now the plan is to keep improving the core product and keep adding more features to it.

**Comment by lgandecki** [comment] 2017-11-13 05:16
Sent it

**Comment by ArtemGovorov** [comment] 2017-11-14 07:06
@lgandecki Thanks again for sending the logs. We have just published [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) v1.0.517 where we have fixed the issue that we have found thanks to your logs.

Please try it to see how it goes now.

**Comment by lgandecki** [comment] 2017-11-14 07:18
@ArtemGovorov great! I tried about a hundred times, and I can't replicate this problem anymore. I will be doing quite a bit of programming with jest/wallabyjs this week so will definitely let you know if it feels reliable :) 
I'm excited. Thanks a lot!

Btw, I thought you might enjoy this - my colleague @bombellos slacked me this morning saying:
"I got the wallabyjs license.. and now I feel an inner urge to test the whole world! 😄 "

**Comment by ArtemGovorov** [comment] 2017-11-14 07:22
Awesome, thanks for checking and sharing your colleague's feedback! 😄  Let us know how goes for you throughout the week (and please record/keep the logs if you find something suspicious).

**Comment by ArtemGovorov** [comment] 2017-11-23 02:39
@lgandecki Wondering how is Wallaby going for you? Had the hanging spinner issue been fixed for you in your other projects?

**Comment by lgandecki** [comment] 2017-11-23 04:05
I’m cautiusly optimistic, but yeah, I’ve worked intensively with jest this week and no problems with jest being stuck. I’ve seen the tests staying green even though I had syntax error in my code, like, missing }. But since code was green I didn’t realize that and went further. No spinner, Wallabyjs throws an error in a console in that case, but if it’s not open then it’s easy to miss. I think those might be two separate issues that in my eyes were part of one, and you fixed the most problematic one already (since the syntax errors are caught by linters as well, assuming they are configured correctly). The moment I fix the syntax error tests rerun. 
So, yeah. This week was a bliss, thanks a lot again :)

**Comment by ArtemGovorov** [comment] 2017-11-23 04:07
Awesome, thanks for the update! I'm closing the issue as resolved for now. Let us know if hit any reliability issues with Jest, happy to have a look.

**Closed by ArtemGovorov** 2017-11-23 04:07 UTC
Labels: reproducible example is required
