### ISSUE TITLE
Doesn't work properly with Jests's '<rootDir>' option

### ISSUE THREAD

**Issue by meskill** [wallabyjs/public#2662] opened 2021-03-15 15:35 UTC
In my project i have root folder named `test` that I want to exclude from parsing by jest runner, so I have this in `jest.config.js`:
```
  testPathIgnorePatterns: [
    '<rootDir>/test/',
  ],
```

Also I have folder named `packages/test` that is not excluded by Jest as setting state that only root test folder should be ignored.

I am using Wallaby with automatic configuration and wallaby ignores both folders so I cannot see wallaby result from `packages/test`: 
- wallaby console shows `0 failing tests, 1889 passing, 8 skipped`
- running jest shows `8 skipped, 1898 passed, 1906 total`

So 9 tests are missing for wallaby and thats exact number of tests inside `packages/test`.

After removing  `'<rootDir>/test/` from `jest.config.js` wallaby will parse tests from `packages/test` as normally, showing `‌0 failing tests, 1898 passing, 8 skipped`

### Wallaby diagnostics report
<details> 
<summary>diagnostic (info about test run is stripped)</summary> 
  <pre>
  {
    editorVersion: '1.54.2',
    pluginVersion: '1.0.274',
    editorType: 'VSCode',
    osVersion: 'linux 4.19.104-microsoft-standard',
    nodeVersion: 'v14.15.1',
    coreVersion: '1.0.1045',
    checksum: 'YmUwNjIyOTcxN2NjNTYxZDhkMWJjYTRiNGU3MGZjYjIsMTY0Mzg0NjQwMDAwMCww',
    config: {
      diagnostics: {
        jest: {
          config: {
            configs: [
              {
                automock: false,
                cache: true,
                cacheDirectory: '<rootDir>/node_modules/.cache/jest',
                clearMocks: false,
                coveragePathIgnorePatterns: [ '/node_modules/' ],
                cwd: '<rootDir>',
                dependencyExtractor: undefined,
                detectLeaks: undefined,
                detectOpenHandles: undefined,
                displayName: undefined,
                errorOnDeprecated: false,
                extraGlobals: [],
                filter: undefined,
                forceCoverageMatch: [],
                globalSetup: undefined,
                globalTeardown: undefined,
                globals: {},
                haste: { computeSha1: false, throwOnModuleCollision: false },
                injectGlobals: true,
                moduleDirectories: [ 'node_modules' ],
                moduleFileExtensions: [ 'js', 'json', 'jsx', 'ts', 'tsx', 'node' ],
                moduleLoader: undefined,
                moduleNameMapper: [ [ '\\.(css|CSS)$', 'identity-obj-proxy' ], [ '\\.(svg|png)$', '<rootDir>/test/emptyModule.js' ] ],
                modulePathIgnorePatterns: [ '<rootDir>/tools/depscheck/.*/__fixtures__/' ],
                modulePaths: undefined,
                name: 'd12dac7be1d4458722c9181be4814950',
                prettierPath: 'prettier',
                resetMocks: false,
                resetModules: false,
                resolver: undefined,
                restoreMocks: false,
                rootDir: '<rootDir>',
                roots: [ '<rootDir>' ],
                runner: 'jest-runner',
                setupFiles: [ '<rootDir>/node_modules/jest-date-mock/lib/index.js' ],
                setupFilesAfterEnv: [],
                skipFilter: false,
                skipNodeResolution: undefined,
                slowTestThreshold: 5,
                snapshotResolver: undefined,
                snapshotSerializers: [],
                testEnvironment: '<rootDir>/node_modules/jest-environment-node/build/index.js',
                testEnvironmentOptions: {},
                testLocationInResults: false,
                testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
                testPathIgnorePatterns: [
                  '<rootDir>/node_modules/',
                  '<rootDir>/test/',
                  '<rootDir>/examples',
                  'lib/',
                  'node_modules/',
                  '__integration__',
                  '<rootDir>/.cache',
                  '<rootDir>/.npm'
                ],
                testRegex: [],
                testRunner: '<rootDir>/node_modules/jest-circus/runner.js',
                testURL: 'http://localhost',
                timers: 'fake',
                transform: [ [ '^.+\\.tsx?$', '<rootDir>/node_modules/ts-jest/dist/index.js', {} ] ],
                transformIgnorePatterns: [ '/node_modules/', '\\.pnp\\.[^\\/]+$' ],
                unmockedModulePathPatterns: undefined,
                watchPathIgnorePatterns: []
              }
            ],
            globalConfig: {
              bail: 0,
              changedFilesWithAncestor: false,
              changedSince: undefined,
              collectCoverage: false,
              collectCoverageFrom: [ 'packages/**/*.{ts,tsx,js,jsx}', '!**/lib/**/*' ],
              collectCoverageOnlyFrom: undefined,
              coverageDirectory: '<rootDir>/coverage',
              coverageProvider: 'babel',
              coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
              coverageThreshold: undefined,
              detectLeaks: undefined,
              detectOpenHandles: undefined,
              enabledTestsMap: undefined,
              errorOnDeprecated: false,
              expand: false,
              filter: undefined,
              findRelatedTests: false,
              forceExit: false,
              globalSetup: undefined,
              globalTeardown: undefined,
              json: false,
              lastCommit: false,
              listTests: undefined,
              logHeapUsage: false,
              maxConcurrency: 5,
              maxWorkers: 7,
              noSCM: undefined,
              noStackTrace: false,
              nonFlagArgs: undefined,
              notify: false,
              notifyMode: 'failure-change',
              onlyChanged: false,
              onlyFailures: false,
              outputFile: undefined,
              passWithNoTests: undefined,
              projects: [],
              replname: undefined,
              reporters: undefined,
              rootDir: '<rootDir>',
              runTestsByPath: false,
              silent: undefined,
              skipFilter: false,
              testFailureExitCode: 1,
              testNamePattern: undefined,
              testPathPattern: '',
              testResultsProcessor: undefined,
              testSequencer: '<rootDir>/node_modules/@jest/test-sequencer/build/index.js',
              testTimeout: undefined,
              updateSnapshot: 'new',
              useStderr: false,
              verbose: undefined,
              watch: false,
              watchAll: false,
              watchPlugins: undefined,
              watchman: true
            },
            hasDeprecationWarnings: false,
            wallaby: {
              roots: [],
              watchPathIgnorePatterns: [
                '/node_modules/',
                '\\./dist/|\\./build/|\\./coverage/|/\\..+/',
                '/test/',
                '/examples',
                'lib/',
                'node_modules/',
                '__integration__',
                '/.cache',
                '/.npm',
                '/tools/depscheck/.*/__fixtures__/'
              ],
              testPathIgnorePatterns: [
                '/node_modules/',
                '\\./dist/|\\./build/|\\./coverage/|/\\..+/',
                '/test/',
                '/examples',
                'lib/',
                'node_modules/',
                '__integration__',
                '/.cache',
                '/.npm',
                '/tools/depscheck/.*/__fixtures__/'
              ],
              testMatch: [ '**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)' ],
              testRegex: []
            }
          }
        }
      },
      testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
      filesWithCoverageCalculated: [ 'packages/**/*.{ts,tsx,js,jsx}', '!**/lib/**/*' ],
      filesWithNoCoverageCalculated: [],
      globalSetup: false,
      micromatch: true,
      files: [
        { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true },
        { pattern: '\\./dist/|\\./build/|\\./coverage/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\/\..+\//, ignore: true, trigger: true, load: true },
        { pattern: '/test/', regexp: /\/test\//, ignore: true, trigger: true, load: true },
        { pattern: '/examples', regexp: /\/examples/, ignore: true, trigger: true, load: true },
        { pattern: 'lib/', regexp: /lib\//, ignore: true, trigger: true, load: true },
        { pattern: 'node_modules/', regexp: /node_modules\//, ignore: true, trigger: true, load: true },
        { pattern: '__integration__', regexp: /__integration__/, ignore: true, trigger: true, load: true },
        { pattern: '/.cache', regexp: /\/.cache/, ignore: true, trigger: true, load: true },
        { pattern: '/.npm', regexp: /\/.npm/, ignore: true, trigger: true, load: true },
        { pattern: '/tools/depscheck/.*/__fixtures__/', regexp: /\/tools\/depscheck\/.*\/__fixtures__\//, ignore: true, trigger: true, load: true },
        { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
        { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: true, trigger: true, load: true },
        { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: true, trigger: true, load: true }
      ],
      tests: [
        { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true },
        { pattern: '\\./dist/|\\./build/|\\./coverage/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\/\..+\//, ignore: true, trigger: true, load: true, test: true },
        { pattern: '/test/', regexp: /\/test\//, ignore: true, trigger: true, load: true, test: true },
        { pattern: '/examples', regexp: /\/examples/, ignore: true, trigger: true, load: true, test: true },
        { pattern: 'lib/', regexp: /lib\//, ignore: true, trigger: true, load: true, test: true },
        { pattern: 'node_modules/', regexp: /node_modules\//, ignore: true, trigger: true, load: true, test: true },
        { pattern: '__integration__', regexp: /__integration__/, ignore: true, trigger: true, load: true, test: true },
        { pattern: '/.cache', regexp: /\/.cache/, ignore: true, trigger: true, load: true, test: true },
        { pattern: '/.npm', regexp: /\/.npm/, ignore: true, trigger: true, load: true, test: true },
        { pattern: '/tools/depscheck/.*/__fixtures__/', regexp: /\/tools\/depscheck\/.*\/__fixtures__\//, ignore: true, trigger: true, load: true, test: true },
        { pattern: '**/__tests__/**/*.[jt]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 2 },
        { pattern: '**/?(*.)+(spec|test).[tj]s?(x)', ignore: false, trigger: true, load: true, test: true, order: 3 }
      ],
      runAllTestsInAffectedTestFile: false,
      updateNoMoreThanOneSnapshotPerTestFileRun: false,
      addModifiedTestFileToExclusiveTestRun: true,
      compilers: {},
      preprocessors: {},
      maxConsoleMessagesPerTest: 100,
      autoConsoleLog: true,
      delays: { run: 0, edit: 100, update: 0 },
      workers: { initial: 0, regular: 0, recycle: false },
      teardown: undefined,
      hints: {
        ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
        ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
        commentAutoLog: '?',
        testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
      },
      automaticTestFileSelection: true,
      runSelectedTestsOnly: false,
      extensions: {},
      env: { type: 'node', params: {}, runner: '/usr/local/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
      reportUnhandledPromises: true,
      slowTestThreshold: 75,
      lowCoverageThreshold: 80,
      loose: true,
      configCode: 'auto.detect#1240307442'
    },
    packageJSON: {
      dependencies: { 'hoist-non-react-statics': '^3.3.2', react: '^17.0.1', 'react-dom': '^17.0.1', 'react-universal-component': '^4.5.0', 'webpack-flush-chunks': '^2.0.3' },
      devDependencies: {
        '@commitlint/cli': '^8.3.5',
        '@commitlint/config-conventional': '^8.3.4',
        '@delivery-ci/quality': '^1.4.0',
        '@pvm/gitlab': '0.46.7',
        '@pvm/plugin-conventional-changelog': '0.46.7',
        '@pvm/pvm': '0.46.7',
        '@revizor/adapter-packages-size': '0.1.21',
        '@revizor/client': '^0.1.20',
        '@revizor/reporter-console': '^0.1.20',
        '@revizor/reporter-gitlab': '^0.1.21',
        '@revizor/strategy-size': '^0.1.21',
        '@slack/web-api': '^5.6.0',
        '@testing-library/jest-dom': '^5.11.6',
        '@testing-library/react': '^10.0.1',
        '@testing-library/react-hooks': '^3.2.1',
        '@types/execa': '^2.0.0',
        '@types/hoist-non-react-statics': '^3.3.1',
        '@types/jest': '^26.0.19',
        '@types/lru-cache': '^5.1.0',
        '@types/node': '^13.13.2',
        '@types/react': '^17.0.0',
        '@types/react-dom': '^17.0.0',
        '@types/webpack-env': '^1.13.16',
        '@types/yandex-maps': '^2.1.9',
        '@wojtekmaj/enzyme-adapter-react-17': '^0.4.1',
        benchmark: '^2.1.4',
        commitizen: '^4.0.3',
        'conventional-changelog-angular': '^5.0.6',
        'cross-env': '^7.0.2',
        'cz-conventional-changelog': '^3.1.0',
        enzyme: '^3.11.0',
        execa: '^4.0.3',
        husky: '^4.2.3',
        'identity-obj-proxy': '^3.0.0',
        jest: '^26.6.3',
        'jest-circus': '^26.6.3',
        'jest-date-mock': '^1.0.8',
        'jest-environment-jsdom': '^26.6.2',
        'jest-environment-jsdom-global': '^2.0.4',
        json: '^9.0.6',
        'lint-staged': '^10.1.0',
        'node-mocks-http': '^1.8.1',
        plop: '^2.6.0',
        'promise-police': '^0.1.7',
        'recursive-readdir': '^2.2.2',
        'remark-cli': '^7.0.1',
        'remark-lint-no-dead-urls': '^1.0.2',
        'remark-lint-no-empty-sections': '^3.0.0',
        'remark-preset-lint-recommended': '^3.0.3',
        rimraf: '^3.0.2',
        'ts-jest': '26.4.1',
        'ts-node': '^8.8.1',
        tslib: '^2.0.3',
        typescript: '^4.1.3',
        walker: '^1.0.7',
        wsrun: '^5.2.0'
      }
    },
    fs: { numberOfFiles: 2578 },
    debug: [
      '2021-03-15T15:04:44.824Z angular/cli config Angular CLI not found.\n',
      '2021-03-15T15:04:45.064Z jest/config Detected Jest.\n',
      '2021-03-15T15:04:45.065Z jest/config Configured Jest.\n',
      '2021-03-15T15:04:45.067Z project Wallaby Node version: v14.15.1\n',
      '2021-03-15T15:04:45.067Z project Wallaby config: <rootDir>/auto.detect\n',
      '2021-03-15T15:04:47.372Z project File cache: <homeDir>/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.274/projects/2dbe8ef70fcf36f2\n',
      '2021-03-15T15:04:47.516Z uiService Listening port 51235\n',
      '2021-03-15T15:04:47.562Z project Config file change detected, invalidating local cache\n',
      '2021-03-15T15:04:47.872Z workers Parallelism for initial run: 6, for regular run: 3\n',
      '2021-03-15T15:04:47.872Z workers Starting run worker instance #0\n',
      '2021-03-15T15:04:47.872Z workers Starting run worker instance #1\n',
      '2021-03-15T15:04:47.872Z workers Starting run worker instance #2\n',
      '2021-03-15T15:04:47.872Z workers Starting run worker instance #3\n',
      '2021-03-15T15:04:47.872Z workers Starting run worker instance #4\n',
      '2021-03-15T15:04:47.872Z workers Starting run worker instance #5\n',
      '2021-03-15T15:04:47.873Z workers Web server is listening at 45021\n',
      '2021-03-15T15:04:47.873Z project File cache requires some updates, waiting required files from IDE\n',
      '2021-03-15T15:04:48.248Z workers Started run worker instance (delayed) #0\n',
      '2021-03-15T15:04:48.249Z workers Started run worker instance (delayed) #4\n',
      '2021-03-15T15:04:48.250Z workers Started run worker instance (delayed) #2\n',
      '2021-03-15T15:04:48.251Z workers Started run worker instance (delayed) #3\n',
      '2021-03-15T15:04:48.251Z workers Started run worker instance (delayed) #5\n',
      '2021-03-15T15:04:48.252Z workers Started run worker instance (delayed) #1\n',
      '2021-03-15T15:04:48.397Z project Stopping process pool\n',
      '2021-03-15T15:04:48.399Z project Test run started; run priority: 3\n',
      '2021-03-15T15:04:48.407Z project Running all tests\n',
      '2021-03-15T15:04:48.448Z workers Starting test run, priority: 3\n',
      '2021-03-15T15:04:48.449Z workers Distributing tests between 6 workers\n',
      '2021-03-15T15:04:48.453Z workers Running tests in parallel\n',
      '2021-03-15T15:04:48.453Z nodeRunner Starting sandbox [worker #0, session #259ta]\n',
      '2021-03-15T15:04:48.453Z nodeRunner Starting sandbox [worker #1, session #27kok]\n',
      '2021-03-15T15:04:48.453Z nodeRunner Starting sandbox [worker #2, session #e8bby]\n',
      '2021-03-15T15:04:48.453Z nodeRunner Starting sandbox [worker #3, session #wbzz5]\n',
      '2021-03-15T15:04:48.453Z nodeRunner Starting sandbox [worker #4, session #m7xch]\n',
      '2021-03-15T15:04:48.453Z nodeRunner Starting sandbox [worker #5, session #6n26p]\n',
      '2021-03-15T15:04:48.453Z nodeRunner Preparing sandbox [worker #0, session #259ta]\n',
      '2021-03-15T15:04:48.453Z nodeRunner Preparing sandbox [worker #1, session #27kok]\n',
      '2021-03-15T15:04:48.453Z nodeRunner Preparing sandbox [worker #2, session #e8bby]\n',
      '2021-03-15T15:04:48.453Z nodeRunner Preparing sandbox [worker #3, session #wbzz5]\n',
      '2021-03-15T15:04:48.453Z nodeRunner Preparing sandbox [worker #4, session #m7xch]\n',
      '2021-03-15T15:04:48.453Z nodeRunner Preparing sandbox [worker #5, session #6n26p]\n',
      '2021-03-15T15:04:48.453Z nodeRunner Prepared sandbox [worker #0, session #259ta]\n',
      '2021-03-15T15:04:48.454Z nodeRunner Prepared sandbox [worker #1, session #27kok]\n',
      '2021-03-15T15:04:48.454Z nodeRunner Prepared sandbox [worker #2, session #e8bby]\n',
      '2021-03-15T15:04:48.454Z nodeRunner Prepared sandbox [worker #3, session #wbzz5]\n',
      '2021-03-15T15:04:48.454Z nodeRunner Prepared sandbox [worker #4, session #m7xch]\n',
      '2021-03-15T15:04:48.454Z nodeRunner Prepared sandbox [worker #5, session #6n26p]\n',
      '2021-03-15T15:04:48.454Z workers [worker #0, session #259ta] Running tests in sandbox\n',
      '2021-03-15T15:04:48.459Z workers [worker #1, session #27kok] Running tests in sandbox\n',
      '2021-03-15T15:04:48.464Z workers [worker #2, session #e8bby] Running tests in sandbox\n',
      '2021-03-15T15:04:48.470Z workers [worker #3, session #wbzz5] Running tests in sandbox\n',
      '2021-03-15T15:04:48.473Z workers [worker #4, session #m7xch] Running tests in sandbox\n',
      '2021-03-15T15:04:48.477Z workers [worker #5, session #6n26p] Running tests in sandbox\n',
      '2021-03-15T15:05:08.171Z workers Scheduling Jest Test Run: 2021-03-15T15:04:57.424Z\n',
      '2021-03-15T15:05:08.187Z workers [e8bby] Loaded unknown number of test(s)\n',
      '2021-03-15T15:05:08.753Z workers Scheduling Jest Test Run: 2021-03-15T15:04:57.446Z\n',
      '2021-03-15T15:05:08.844Z workers [259ta] Loaded unknown number of test(s)\n',
      '2021-03-15T15:05:28.289Z project Processed executed tests\n',
      '2021-03-15T15:05:28.356Z project Processed code coverage\n',
      '2021-03-15T15:05:28.634Z project Test run result processed and sent to IDE\n'
    ]
  }
  </pre>
</details>

**Comment by ArtemGovorov** [comment] 2021-03-16 03:38
Thanks for the report, the issue is fixed in [the latest core 1.0.1047](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Closed by ArtemGovorov** 2021-03-16 03:38 UTC
