### ISSUE TITLE
jasmine 2.5.2

### ISSUE THREAD

**Issue by dkuida** [wallabyjs/public#793] opened 2016-09-19 11:55 UTC
### Wallaby.js configuration file
```javascript
'use strict';
module.exports = function () {
    return {
        files: [
            'config/**/*',
            'spec/helpers/*',
            'server/**/*.js',
            'routes/**/*',
            'dal/**/*.js',
            'handler/**/*.js'
        ],

        tests: [
            'spec/*[sS]pec.js',
            'spec/*[iI]nteg.js'
        ],
        env: {
            type: 'node',
            runner: 'node',
            report4040AsError: true,
            params: {
                env: 'CONFIG_LOGGER_PATH=integ/assets/logger-config.js'
            }
        },
        testFramework: 'jasmine',
        workers: {
            recycle: true
        }
    };
};
```

### Code editor or IDE name and version

WebStorm v11

### OS name and version
osx and windows

took me long time to nail it down
but tests running nromally on 2.4.1
and on new projects ( where I just installed npm install jasmine) the spinner was spining endlesly even on trivial expect(2).toBe(2)

so in the end there is an issue with jasmine 2.5.2

**Comment by ArtemGovorov** [comment] 2016-09-19 23:44
Thanks for the report. We've had a [similar issue with jasmine 2.5.1](https://github.com/wallabyjs/public/issues/768), looks 2.5.2 had broken the fix. 

The issue is fixed now in core v1.0.289. The core will be updated automatically, to get the change ASAP, you [may force the update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Closed by ArtemGovorov** 2016-09-19 23:44 UTC
