### ISSUE TITLE
Not updating test results

### ISSUE THREAD

**Issue by TeaBough** [wallabyjs/public#3274] opened 2023-09-21 09:23 UTC
### Issue description or question
When running my tests with intellij I get the errors in the console : 
![image](https://github.com/wallabyjs/public/assets/2129896/11941ffd-a277-452e-9370-c91053b52a3f)

But not in the test results : 

![image](https://github.com/wallabyjs/public/assets/2129896/406f26c5-5038-4bdb-bb19-0f828068bce1)

I've tried removing node_modules, updating intellij and clear wallaby cache...

### Wallaby diagnostics report

```
{
  editorVersion: 'IntelliJ IDEA 2023.2.2',
  pluginVersion: '1.0.274',
  editorType: 'IntelliJ',
  osVersion: 'linux 6.2.6-76060206-generic',
  nodeVersion: 'v16.14.0',
  coreVersion: '1.0.1475',
  checksum: 'NjFjNGQ4NGNlZWE4Y2RlZmI0MWQwMWVhODdmMjcyNTUsMTcwMjA4MDAwMDAwMCww',
  config: {
    localProjectDir: '<homeDir>/src/my-app/app/',
    projectCacheDir: '<homeDir>/.cache/JetBrains/IntelliJIdea2023.2/wallaby/projects/5ace56e8f3a13773/instrumented',
    compilers: { coffeeScript: [Function (anonymous)], babel: [Function (anonymous)], typeScript: [Function: typeScript] },
    postprocessors: { typeScript: [Function (anonymous)], webpack: [Function (anonymous)] },
    override: [Function: override],
    defaults: { files: { ignore: false, trigger: true, load: true, instrument: true }, tests: { ignore: false, trigger: true, load: true } },
    files: [
      { pattern: 'src/**/*.js', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
      { pattern: 'src/**/*.tsx', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
      { pattern: 'src/**/*.ts', ignore: false, trigger: true, load: true, instrument: true, order: 3 },
      { pattern: 'src/**/*.test.ts', ignore: true, trigger: true, load: true, instrument: true, file: true },
      { pattern: 'src/**/*.test.tsx', ignore: true, trigger: true, load: true, instrument: true, file: true }
    ],
    tests: [
      { pattern: 'src/**/*.test.ts', ignore: false, trigger: true, load: true, test: true, order: 4 },
      { pattern: 'src/**/*.test.tsx', ignore: false, trigger: true, load: true, test: true, order: 5 }
    ],
    diagnostics: {
      vitest: {
        file: {
          config: '/// <reference types="vitest" />\n' +
            "import { defineConfig } from 'vite';\n" +
            "import tsconfigPaths from 'vite-tsconfig-paths';\n" +
            '// @ts-ignore\n' +
            "import svgrPlugin from 'vite-plugin-svgr';\n" +
            "import react from '@vitejs/plugin-react';\n" +
            '\n' +
            "const path = require('path');\n" +
            '\n' +
            '// https://vitejs.dev/config/\n' +
            'export default defineConfig({\n' +
            '  resolve: {\n' +
            '  },\n' +
            '  optimizeDeps: {\n' +
            "    include: ['@tailwindConfig'],\n" +
            '  },\n' +
            '  plugins: [\n' +
            '    react({\n' +
            '      babel: {\n' +
            '        presets: [\n' +
            '          [\n' +
            "            '@babel/preset-react',\n" +
            "            { runtime: 'automatic', importSource: '@emotion/react' },\n" +
            '          ],\n' +
            '        ],\n' +
            '\n' +
            '        plugins: [\n' +
            "          '@emotion/babel-plugin',\n" +
            '          [\n' +
            "            'babel-plugin-twin',\n" +
            '            {\n' +
            '              // cf https://github.com/ben-rogerson/babel-plugin-twin/issues/9\n' +
            '              exclude: [\n' +
            "                '\\x00commonjsHelpers.js', // Avoid build error\n" +
            '              ],\n' +
            '            },\n' +
            '          ],\n' +
            "          'babel-plugin-macros',\n" +
            '        ],\n' +
            '      },\n' +
            '    }),\n' +
            '    tsconfigPaths(),\n' +
            '    svgrPlugin(),\n' +
            '  ],\n' +
            '  server: {\n' +
            '    port: 9003,\n' +
            '  },\n' +
            '  test: {\n' +
            '    globals: true,\n' +
            '    testTimeout: 120000,\n' +
            '    // maxThreads: 1,\n' +
            '    // minThreads: 1,\n' +
            "    environment: 'jsdom',\n" +
            "    setupFiles: ['./src/testing/setupTests.ts'],\n" +
            '    exclude: [\n' +
            "      './e2e',\n" +
            "      '**/node_modules/**',\n" +
            "      '**/dist/**',\n" +
            "      '**/.{idea,git,cache,output,temp}/**',\n" +
            "      '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,tsup,build}.config.*',\n" +
            '    ],\n' +
            '  },\n' +
            '});\n'
        },
        config: {
          config: {
            allowOnly: true,
            watch: true,
            globals: true,
            environment: 'jsdom',
            threads: true,
            clearMocks: false,
            restoreMocks: false,
            mockReset: false,
            include: [ '**/*.{test,spec}.?(c|m)[jt]s?(x)' ],
            exclude: [ './e2e', '**/node_modules/**', '**/dist/**', '**/.{idea,git,cache,output,temp}/**', '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,tsup,build}.config.*' ],
            testTimeout: 120000,
            hookTimeout: 10000,
            teardownTimeout: 10000,
            isolate: true,
            watchExclude: [ '**/node_modules/**', '**/dist/**' ],
            forceRerunTriggers: [ '**/package.json/**', '**/{vitest,vite}.config.*/**', '<homeDir>/src/my-app/app/src/testing/setupTests.ts' ],
            update: false,
            reporters: [ 'default' ],
            silent: false,
            hideSkippedTests: false,
            ui: false,
            uiBase: '/__vitest__/',
            open: true,
            css: { include: [], modules: { classNameStrategy: 'stable' } },
            coverage: {
              provider: 'v8',
              enabled: false,
              clean: true,
              cleanOnRerun: true,
              reportsDirectory: './coverage',
              exclude: [
                'coverage/**',
                'dist/**',
                'packages/*/test?(s)/**',
                '**/*.d.ts',
                '**/virtual:*',
                '**/__x00__*',
                '**/\x00*',
                'cypress/**',
                'test?(s)/**',
                'test?(-*).?(c|m)[jt]s?(x)',
                '**/*{.,-}{test,spec}.?(c|m)[jt]s?(x)',
                '**/__tests__/**',
                '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*',
                '**/.{eslint,mocha,prettier}rc.{?(c|m)js,yml}',
                'src/testing/setupTests.ts',
                'src/testing/setupTests.ts'
              ],
              reportOnFailure: false,
              reporter: [ [ 'text', {} ], [ 'html', {} ], [ 'clover', {} ], [ 'json', {} ] ],
              extension: [
                '.js',  '.cjs',
                '.mjs', '.ts',
                '.mts', '.cts',
                '.tsx', '.jsx',
                '.vue', '.svelte'
              ]
            },
            fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
            maxConcurrency: 5,
            dangerouslyIgnoreUnhandledErrors: false,
            typecheck: {
              checker: 'tsc',
              include: [ '**/*.{test,spec}-d.?(c|m)[jt]s?(x)' ],
              exclude: [
                '**/node_modules/**',
                '**/dist/**',
                '**/cypress/**',
                '**/.{idea,git,cache,output,temp}/**',
                '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*'
              ]
            },
            slowTestThreshold: 300,
            setupFiles: [ '<homeDir>/src/my-app/app/src/testing/setupTests.ts' ],
            defines: {},
            root: '<homeDir>/src/my-app/app',
            mode: [],
            inspect: false,
            inspectBrk: false,
            singleThread: false,
            deps: { moduleDirectories: [ '/node_modules/' ] },
            server: { deps: { inline: [ {}, {}, {}, '@nuxt/test-utils' ], moduleDirectories: [ '/node_modules/' ], cacheDir: 'node_modules/.vitest' } },
            snapshotOptions: { snapshotFormat: {}, updateSnapshot: 'new', snapshotEnvironment: null },
            experimentalVmWorkerMemoryLimit: 8410462720,
            cache: { dir: '<homeDir>/src/my-app/app/node_modules/.vitest' },
            sequence: { hooks: 'parallel' },
            environmentMatchGlobs: [],
            browser: { enabled: false, headless: false, slowHijackESM: true, api: { port: 63315 } },
            testTransformMode: {}
          },
          projects: [
            {
              path: '<homeDir>/src/my-app/app',
              config: {
                allowOnly: true,
                watch: true,
                globals: true,
                environment: 'jsdom',
                threads: true,
                clearMocks: false,
                restoreMocks: false,
                mockReset: false,
                include: [ '**/*.{test,spec}.?(c|m)[jt]s?(x)' ],
                exclude: [ 'e2e', '**/node_modules/**', '**/dist/**', '**/.{idea,git,cache,output,temp}/**', '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,tsup,build}.config.*' ],
                testTimeout: 120000,
                hookTimeout: 10000,
                teardownTimeout: 10000,
                isolate: true,
                watchExclude: [ '**/node_modules/**', '**/dist/**' ],
                forceRerunTriggers: [ '**/package.json/**', '**/{vitest,vite}.config.*/**', '<homeDir>/src/my-app/app/src/testing/setupTests.ts' ],
                update: false,
                reporters: [ 'default' ],
                silent: false,
                hideSkippedTests: false,
                ui: false,
                uiBase: '/__vitest__/',
                open: true,
                css: { include: [], modules: { classNameStrategy: 'stable' } },
                coverage: {
                  provider: 'v8',
                  enabled: false,
                  clean: true,
                  cleanOnRerun: true,
                  reportsDirectory: './coverage',
                  exclude: [
                    'coverage/**',
                    'dist/**',
                    'packages/*/test?(s)/**',
                    '**/*.d.ts',
                    '**/virtual:*',
                    '**/__x00__*',
                    '**/\x00*',
                    'cypress/**',
                    'test?(s)/**',
                    'test?(-*).?(c|m)[jt]s?(x)',
                    '**/*{.,-}{test,spec}.?(c|m)[jt]s?(x)',
                    '**/__tests__/**',
                    '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*',
                    '**/.{eslint,mocha,prettier}rc.{?(c|m)js,yml}',
                    'src/testing/setupTests.ts',
                    'src/testing/setupTests.ts'
                  ],
                  reportOnFailure: false,
                  reporter: [ [ 'text', {} ], [ 'html', {} ], [ 'clover', {} ], [ 'json', {} ] ],
                  extension: [
                    '.js',  '.cjs',
                    '.mjs', '.ts',
                    '.mts', '.cts',
                    '.tsx', '.jsx',
                    '.vue', '.svelte'
                  ]
                },
                fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
                maxConcurrency: 5,
                dangerouslyIgnoreUnhandledErrors: false,
                typecheck: {
                  checker: 'tsc',
                  include: [ '**/*.{test,spec}-d.?(c|m)[jt]s?(x)' ],
                  exclude: [
                    '**/node_modules/**',
                    '**/dist/**',
                    '**/cypress/**',
                    '**/.{idea,git,cache,output,temp}/**',
                    '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*'
                  ]
                },
                slowTestThreshold: 300,
                setupFiles: [ '<homeDir>/src/my-app/app/src/testing/setupTests.ts' ],
                defines: {},
                root: '<homeDir>/src/my-app/app',
                mode: [],
                inspect: false,
                inspectBrk: false,
                singleThread: false,
                deps: { moduleDirectories: [ '/node_modules/' ] },
                server: { deps: { inline: [ {}, {}, {}, '@nuxt/test-utils' ], moduleDirectories: [ '/node_modules/' ] } },
                snapshotOptions: { snapshotFormat: {}, updateSnapshot: 'new', snapshotEnvironment: null },
                experimentalVmWorkerMemoryLimit: 8410462720,
                cache: { dir: '<homeDir>/src/my-app/app/node_modules/.vitest' },
                sequence: { hooks: 'parallel' },
                environmentMatchGlobs: [],
                browser: { enabled: false, headless: false, slowHijackESM: true, api: { port: 63315 } },
                testTransformMode: {}
              }
            }
          ],
          package: {
            version: '0.34.1',
            urls: { hooks: 'file://<homeDir>/.cache/JetBrains/IntelliJIdea2023.2/wallaby/wallaby/runners/node/hooks.mjs' },
            paths: {
              root: '<homeDir>/src/my-app/node_modules/.pnpm/vitest@0.34.1_@vitest+ui@0.34.1_jsdom@22.0.0_terser@5.17.3/node_modules/vitest',
              dist: '<homeDir>/src/my-app/node_modules/.pnpm/vitest@0.34.1_@vitest+ui@0.34.1_jsdom@22.0.0_terser@5.17.3/node_modules/vitest/dist'
            }
          }
        }
      }
    },
    testFramework: { version: 'vitest@0.14.0', configurator: 'vitest@0.14.0', reporter: 'vitest@0.14.0', starter: 'vitest@0.14.0', autoDetected: true },
    preserveComments: false,
    extractComments: true,
    workers: { initial: 1, regular: 1, recycle: false },
    dot: true,
    captureConsoleLog: true,
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore|c8 ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: {
      type: 'node',
      params: { runner: '--experimental-loader=file://<homeDir>/.cache/JetBrains/IntelliJIdea2023.2/wallaby/wallaby/runners/node/hooks.mjs' },
      runner: '<homeDir>/.nvm/versions/node/v16.14.0/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    runAllTestsWhenNoAffectedTests: true,
    symlinkNodeModules: undefined,
    configCode: 'module.exports = wallaby => ({\n' +
      '  ...wallaby,\n' +
      '  autoDetect: true,\n' +
      '  files: [\n' +
      "    './src/**/*.js',\n" +
      "    './src/**/*.tsx',\n" +
      "    './src/**/*.ts',\n" +
      "    { pattern: 'src/**/*.test.ts', ignore: true },\n" +
      "    { pattern: 'src/**/*.test.tsx', ignore: true },\n" +
      '  ],\n' +
      "  tests: ['src/**/*.test.ts', 'src/**/*.test.tsx'],\n" +
      '});\n'
  },
  packageJSON: {
    dependencies: {
      '@floating-ui/react-dom': '^2.0.1',
      '@emotion-icons/emotion-icon': '^4.1.0',
      '@emotion-icons/heroicons-outline': '^3.18.0',
      '@emotion-icons/heroicons-solid': '^3.18.0',
      '@emotion/is-prop-valid': '^1.2.1',
      '@emotion/react': '^11.11.0',
      '@emotion/serialize': '^1.1.2',
      '@emotion/styled': '^11.11.0',
      '@emotion/weak-memoize': '^0.3.1',
      '@headlessui/react': '^1.7.15',
      '@sentry/react': '^7.51.2',
      '@stripe/react-stripe-js': '^2.1.0',
      '@stripe/stripe-js': '^1.52.1',
      axios: '^1.4.0',
      clsx: '^1.2.1',
      'date-arithmetic': '^4.1.0',
      'date-fns': '^2.30.0',
      'date-fns-tz': '^2.0.0',
      downshift: '^7.6.0',
      'fathom-client': '^3.5.0',
      'file-saver': '^2.0.5',
      filesize: '^10.0.7',
      'final-form': '^4.20.9',
      'final-form-calculate': '^1.3.2',
      qs: '^6.11.0',
      react: '^18.2.0',
      'react-dom': '^18.2.0',
      'shallow-equal': '^3.1.0',
      'twin.macro': '^3.1.0',
      'typeface-inter': '^3.18.1',
      'use-debounce': '^9.0.4',
      'use-fit-text': '^2.4.0',
      uuid: '^9.0.0',
      validator: '^13.9.0',
      'workbox-window': '^6.5.4'
    },
    devDependencies: {
      '@babel/core': '^7.21.8',
      '@babel/preset-env': '^7.21.5',
      '@babel/preset-react': '7.18.6',
      '@dnd-kit/core': '^6.0.7',
      '@dnd-kit/sortable': '^7.0.2',
      '@dnd-kit/utilities': '^3.2.1',
      '@emotion/babel-plugin': '^11.11.0',
      '@emotion/babel-plugin-jsx-pragmatic': '^0.2.1',
      '@playwright/test': '^1.33.0',
      '@popperjs/core': '^2.11.7',
      '@remix-run/web-fetch': '^4.3.4',
      '@tailwindcss/forms': '^0.5.3',
      '@tailwindcss/typography': '^0.5.9',
      '@testing-library/dom': '9.3.0',
      '@testing-library/jest-dom': '5.16.5',
      '@testing-library/react': '14.0.0',
      '@testing-library/user-event': '^14.4.3',
      '@types/lodash-es': '4.17.7',
      '@types/node': '16.18.12',
      '@types/react': '18.2.6',
      '@types/react-beautiful-dnd': '13.1.4',
      '@types/react-dom': '18.2.4',
      '@sentry/vite-plugin': '^2.7.1',
      '@types/testing-library__jest-dom': '^5.14.5',
      '@typescript-eslint/eslint-plugin': '5.59.5',
      '@typescript-eslint/parser': '5.59.5',
      '@vitejs/plugin-legacy': '^4.1.1',
      '@vitejs/plugin-react': '^4.0.4',
      '@vitest/ui': '^0.34.1',
      'babel-plugin-macros': '^3.1.0',
      'babel-plugin-preval': '^5.1.0',
      'babel-plugin-twin': '^1.1.0',
      'cross-env': '^7.0.3',
      dns: '^0.2.2',
      dotenv: '^16.0.3',
      eslint: '8.40.0',
      'eslint-config-airbnb-typescript': '17.0.0',
      'eslint-config-prettier': '8.8.0',
      'eslint-import-resolver-typescript': '3.5.5',
      'eslint-plugin-import': '2.27.5',
      'eslint-plugin-jsx-a11y': '6.7.1',
      'eslint-plugin-react': '7.32.2',
      'eslint-plugin-react-hooks': '4.6.0',
      'eslint-plugin-react-refresh': '^0.4.1',
      'eslint-plugin-testing-library': '^5.11.0',
      esm: '3.2.25',
      'froala-editor': '4.0.18',
      'intersection-observer': '^0.12.2',
      jsdom: '^22.0.0',
      'lint-staged': '13.2.2',
      'prop-types': '^15.8.1',
      rimraf: '^5.0.0',
      tailwindcss: '^3.2.7',
      typescript: '^5.0.4',
      'utility-types': '^3.10.0',
      vite: '^4.4.9',
      'vite-node': '^0.34.1',
      'vite-plugin-pwa': '^0.16.4',
      'vite-plugin-svgr': '^3.2.0',
      'vite-tsconfig-paths': '^4.2.0',
      vitest: '^0.34.1'
    }
  },
  fs: { numberOfFiles: 2078 },
  debug: [
    '2023-09-21T09:16:35.241Z config Attempting automatic configuration for angular\n',
    '2023-09-21T09:16:35.244Z angular/cli config Angular CLI not found.\n',
    '2023-09-21T09:16:35.244Z config Finished attempting automatic configuration for angular (3ms)\n',
    '2023-09-21T09:16:35.244Z config Attempting automatic configuration for jest\n',
    "2023-09-21T09:16:35.245Z jest/config Error: Module jest-cli is not found in '<homeDir>/src/my-app/app'.\n" +
      '    at Object.loadJest (<homeDir>/.cache/JetBrains/IntelliJIdea2023.2/wallaby/wallaby/server.js:496:1070)\n' +
      '    at n (<homeDir>/.cache/JetBrains/IntelliJIdea2023.2/wallaby/wallaby/server.js:184:23339)\n' +
      '    at Object.configure (<homeDir>/.cache/JetBrains/IntelliJIdea2023.2/wallaby/wallaby/server.js:184:26449)\n' +
      '    at automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.cache/JetBrains/IntelliJIdea2023.2/wallaby/wallaby/server.js:132:12015)\n' +
      '    at async automaticConfigurationProviders.reduce.Promise.resolve.success (<homeDir>/.cache/JetBrains/IntelliJIdea2023.2/wallaby/wallaby/server.js:132:11892)\n' +
      '    at async Config.load (<homeDir>/.cache/JetBrains/IntelliJIdea2023.2/wallaby/wallaby/server.js:132:11832)\n',
    '2023-09-21T09:16:35.245Z config Finished attempting automatic configuration for jest (1ms)\n',
    '2023-09-21T09:16:35.245Z config Attempting automatic configuration for vitest\n',
    '2023-09-21T09:16:35.247Z vitest/config Detected Vitest (0.34.1).\n',
    '2023-09-21T09:16:35.777Z config Finished attempting automatic configuration for vitest (532ms)\n',
    '2023-09-21T09:16:35.779Z project Wallaby Node version: v16.14.0\n',
    '2023-09-21T09:16:35.779Z project Wallaby config: <homeDir>/src/my-app/app/wallaby.js\n',
    '2023-09-21T09:16:35.790Z fs File system starting\n',
    '2023-09-21T09:16:36.250Z fs File system scan completed\n',
    '2023-09-21T09:16:36.262Z project File cache: <homeDir>/.cache/JetBrains/IntelliJIdea2023.2/wallaby/projects/5ace56e8f3a13773\n',
    '2023-09-21T09:16:36.300Z uiService Listening port 51235\n',
    '2023-09-21T09:16:36.305Z project package.json file change detected, invalidating local cache\n',
    '2023-09-21T09:16:36.338Z workers Parallelism for initial run: 1, for regular run: 1\n',
    '2023-09-21T09:16:36.338Z workers Starting run worker instance #0\n',
    '2023-09-21T09:16:36.338Z workers Web server is listening at 34127\n',
    '2023-09-21T09:16:36.338Z project File cache requires some updates, waiting required files from IDE\n',
    '2023-09-21T09:16:37.247Z workers Started run worker instance (delayed) #0\n',
    '2023-09-21T09:16:37.456Z project Stopping process pool\n',
    '2023-09-21T09:16:37.457Z project Promoting test run to full run because of test selection changes\n',
    '2023-09-21T09:16:37.457Z project Test run started; run priority: 3\n',
    '2023-09-21T09:16:37.461Z project Running all tests\n',
    '2023-09-21T09:16:37.480Z workers Starting test run, priority: 3\n',
    '2023-09-21T09:16:37.480Z nodeRunner Starting sandbox [worker #0, session #77bw6]\n',
    '2023-09-21T09:16:37.480Z nodeRunner Preparing sandbox [worker #0, session #77bw6]\n',
    '2023-09-21T09:16:37.480Z nodeRunner Prepared sandbox [worker #0, session #77bw6]\n',
    '2023-09-21T09:16:37.480Z workers [worker #0, session #77bw6] Running tests in sandbox\n',
    '2023-09-21T09:16:38.079Z workers Scheduling Vitest Run (77bw6): 2023-09-21T09:16:38.062Z\n',
    '2023-09-21T09:16:48.304Z workers Vitest Run Complete (77bw6): 2023-09-21T09:16:48.300Z\n',
    '2023-09-21T09:16:48.304Z workers [77bw6] Run 0 test(s), skipped 0 test(s)\n',
    '2023-09-21T09:16:48.306Z workers [77bw6] Sandbox is responsive, closing it\n',
    '2023-09-21T09:16:48.307Z project Test run finished\n',
    '2023-09-21T09:16:48.308Z project Processed console.log entries\n',
    '2023-09-21T09:16:48.308Z project Processed loading sequences\n',
    '2023-09-21T09:16:48.308Z project Processed executed tests\n',
    '2023-09-21T09:16:48.317Z project Processed code coverage\n',
    '2023-09-21T09:16:48.341Z project Test run result processed and sent to IDE\n',
    '2023-09-21T09:17:43.627Z uiService UI client connected\n',
    '2023-09-21T09:17:43.628Z uiService Outgoing message ui:handshake\n',
    '2023-09-21T09:17:43.636Z uiService Incoming message ui:start\n',
    '2023-09-21T09:17:43.637Z uiService Outgoing message ui:summary\n',
    '2023-09-21T09:17:43.646Z uiService Outgoing message ui:files\n',
    '2023-09-21T09:17:43.650Z uiService Incoming message ui:tests:resultsRequested\n',
    '2023-09-21T09:17:43.652Z uiService Outgoing message ui:tests:allResultsUpdated\n',
    '2023-09-21T09:17:48.677Z uiService Incoming message ui:tests:resultsAbandoned\n',
    '2023-09-21T09:17:52.610Z uiService Incoming message ui:tests:resultsRequested\n',
    '2023-09-21T09:17:52.610Z uiService Outgoing message ui:tests:allResultsUpdated\n'
  ]
}
```

**Comment by smcenlly** [comment] 2023-09-22 03:42
Unfortunately we were not able to identify the cause of the problem from your diagnostics report.

We generated a [sample repo]( that has the same structure as your project, but that also worked for us. Could you please check if our repo works for you?

To setup the repo:

1. `git clone https://github.com/wallabyjs/wallaby-3274`
2. `cd wallaby-3274`
3. `pnpm install`
4. Open IntelliJ IDEA
5. Create a Wallaby Run Configuration and point to `wallaby.js`, update your node path if required.
6. Start Wallaby by right-clicking on `computeDefaultDate.test.ts` and select `Start Exclusive Test Run`

If this works for you, could you also try deleting your `node_modules` and your `pnpm-lock.yaml` on your project and then reinstall your project dependencies?

If things are still not working after trying that, can you please try updating the sample repo to break in the same way as your project? I may not have some of your `vite` or `vitest` configuration that is relevant to it failing.

**Comment by smcenlly** [comment] 2023-10-02 23:37
@TeaBough - did you get this working? 

I'm going to close the issue since we haven't heard back, but we can open it if you're still having problems.

If things are still not working for you, please update the sample repo to break in the same way as your project.

**Comment by TeaBough** [comment] 2023-10-03 07:27
Actually no... the sample repo you provided was working though... I don't know how to furthur try to fix that issue...

**Comment by smcenlly** [comment] 2023-10-03 23:36
You should be able to diff your project's configuration / tests with our sample project and then try updating our sample with your configuration until our sample project breaks in the same way as your project.

Alternatively, you could create a minimal reproducible repo based on your current project. If you current project is open source, or you're able to share with us, we can take a look at that also.

**Comment by TeaBough** [comment] 2023-10-20 12:08
Here is a minimal repo with the bug... It looks like it's due to the pnpm workspace, if I remove the website folder or if I remove `website` from the `pnpm.workspace.yml`, it works...
https://github.com/TeaBough/wallaby-test2

**Comment by smcenlly** [comment] 2023-10-20 23:09
Thanks for the sample repo. It looks like the issue is caused by `pnpm` hoisting `vitest` and so Wallaby integration doesn't work when you're running for the nested project.

You *should* be able to fix this by [updating your hoist patterns](https://pnpm.io/npmrc#hoist-pattern) to **not** hoist `vitest`. Next week we will investigate whether we can update Wallaby to automatically accommodate this for you.

**Comment by TeaBough** [comment] 2023-10-22 10:26
So if I've understood correctly you suggest having a `.npmrc` that looks like this in `./app`

```
public-hoist-pattern[]=!*vitest*
public-hoist-pattern[]=vite-node
```

The problem is that now I fall into a previous problem : 

```
Failed to initialize wallaby vitest.
Required dependency '@vitest/runner' not found. If you are using pnpm, please refer to our docs: (https://wallabyjs.com/docs/integration/vitest.html#using-pnpm)
Error: Required dependency '@vitest/runner' not found. If you are using pnpm, please refer to our docs: (https://wallabyjs.com/docs/integration/vitest.html#using-pnpm)
```

**Comment by smcenlly** [comment] 2023-10-24 00:01
We have determined the cause of your problem, your project has multiple versions of `vitest` installed. This results in Wallaby using the wrong version at runtime and so your test results are not correctly reported.

To fix the problem, you can update your **./website/package.json** vitest version to be the same as your **./app/package.json**. (`"vitest": "^0.34.6"`).

Alternatively, you can explicitly install the dependencies that are not resolving correctly in each `package.json`. For example:

```shell
projectDir/app> `pnpm install -D @vitest/runner @vitest/snapshot` 
```

**Closed by smcenlly** 2023-10-24 00:01 UTC

**Comment by smcenlly** [comment] 2023-10-24 00:08
One more item to note, you may need to reset your Wallaby cache with the `Help | Wallaby.js | Reset Wallaby Cache` menu item after fixing your dependency versions.
