### ISSUE TITLE
IntelliJ stops saving before running tasks when the Wallaby plugin is on

### ISSUE THREAD

**Issue by ntrrgc** [wallabyjs/public#773] opened 2016-09-02 13:30 UTC
### Issue description or question

Usually IntelliJ saves files before running tasks. You can create a JavaScript file, write `console.log("foo")`, run it, see `foo` in the output console, change it to `bar`, click run and see `bar` in the console.

Having the Wallaby plugin enable breaks this feature. After changing it to bar you still see it showing `foo`. Workarounds are saving every time before running a task or disabling the Wallaby plugin.

### Code editor or IDE name and version

PhpStorm 2016.2.1

### OS name and version

Arch Linux

**Comment by ArtemGovorov** [comment] 2016-09-02 14:41
Thanks for the report, the issue is fixed in wallaby plugin 1.0.73 (you'll be prompted to update after you restart the IDE).

**Closed** 2016-09-02 14:40 UTC

**Comment by ntrrgc** [comment] 2016-09-02 15:48
Thanks for the quick update!

I've not received the update yet even though I've reenabled the plugin and restarted the IDE three times.

**Comment by ArtemGovorov** [comment] 2016-09-03 00:25
The plugin should display popup to suggest install the latest version, unless you have wallaby notifications turned off:
<img width="619" alt="screen shot 2016-09-03 at 10 23 07 am" src="https://cloud.githubusercontent.com/assets/979966/18221428/706c1a94-71c0-11e6-9bda-283c08d81da5.png">

If it doesn't show the popup, just install the latest plugin version [from our website](http://download.wallabyjs.com/intellij).
