### ISSUE TITLE
ReferenceError: Promise is not defined on Node 4.2.2 & Jest-CLI 0.5.10

### ISSUE THREAD

**Issue by alexanderzubarev** [wallabyjs/public#332] opened 2015-11-12 11:46 UTC
Hi. We updated our node from 0.10.x to 4.2.2 and jest from 0.4.3 to next version (that will works with new node) and wallaby stopped to work.

Error with jest-cli 0.5.10:
Runtime error: ReferenceError: Promise is not defined
    at TestRunner._createInBandTestRun (SOME_PROJECT_PATH/node_modules/jest-cli/src/TestRunner.js:562:22)
    at TestRunner._createTestRun (SOME_PROJECT_PATH/node_modules/jest-cli/src/TestRunner.js:553:17)
    at TestRunner.runTests (SOME_PROJECT_PATH/node_modules/jest-cli/src/TestRunner.js:536:22)
    at WebSocket.emit (events.js:98:17)

Error with jest-cli 0.7.1:
Runtime error: jest-cli node module is not found, missing `npm install jest-cli --save-dev`?

Without wallaby Jest works fine and tests worked correctly.

wallaby.js file in attachments.
[wallaby.txt](https://github.com/wallabyjs/public/files/32814/wallaby.txt)

**Comment by ArtemGovorov** [comment] 2015-11-12 12:03
Can't reproduce on this sample - https://github.com/wallabyjs/wallaby-jest-sample, both jest-cli 0.5.10 and jest-cli 0.7.1 work for me. Could you please clone the sample, change package.json to 
```
{
  "devDependencies": {
    "jest-cli": "0.5.10"
  }
}
```
then `npm install` and run with wallaby to see if the issue is reproduced?

Could you please also add `console.log('Node version', process.version);` to your `bootstrap` function in wallaby config and have a look what version does it print in Wallaby Console in IDE?

**Comment by ArtemGovorov** [comment] 2015-11-12 12:12
From the symptoms it looks like your local node.js version may not be 4.2.2. Could you also try running `node -v` in your terminal?

**Comment by alexanderzubarev** [comment] 2015-11-12 12:21
same error with this sample:
ReferenceError: Promise is not defined
    at TestRunner._createInBandTestRun (/home/alex/temp/wallaby-jest-sample/node_modules/jest-cli/src/TestRunner.js:562:22)
    at TestRunner._createTestRun (/home/alex/temp/wallaby-jest-sample/node_modules/jest-cli/src/TestRunner.js:553:17)
    at TestRunner.runTests (/home/alex/temp/wallaby-jest-sample/node_modules/jest-cli/src/TestRunner.js:536:22)
    at WebSocket.emit (events.js:98:17)

alex@alex-G31M-ES2L:~/temp/wallaby-jest-sample$ node -v
v4.2.2

BUT!
console.log: Node version v0.10.40

very strange

**Comment by ArtemGovorov** [comment] 2015-11-12 12:28
It is strange indeed. Could you please upgrade your plugin to 1.0.46 (if not already) and commenting out `runner`:
``` JavaScript
        env: {
            type: 'node',
            //runner: 'node',
            params: {
                runner: '--harmony'
            }
        },
```
Since v1.0.46 wallaby for IntelliJ uses 4.2.2, so let's check what happens.

**Comment by alexanderzubarev** [comment] 2015-11-12 12:29
it works, thanks!

**Comment by ArtemGovorov** [comment] 2015-11-12 12:37
It should work with `runner: 'node',` as well. We just do `require('child_process').spawn(your_runner_value, ...)` internally and for some reason on your machine it spawns v0.10.40 and not v4.2.2. Not sure why it happens. By a chance, did you reboot after your node upgrade?

**Comment by ArtemGovorov** [comment] 2015-11-12 12:46
After rebooting, could you please also try 
```
node
> require('child_process').spawn('node', ['-v']).stdout.on('data', function (data) {console.log(data.toString());}),'Node version:'
```
in your terminal?

**Comment by ArtemGovorov** [comment] 2015-11-12 13:52
I'll close the issue as it's working for you now. Please let me know the results when you have some time to try my suggestions above.

**Closed by ArtemGovorov** 2015-11-12 13:52 UTC

**Comment by ArtemGovorov** [comment] 2015-11-13 04:06
You may also check if your local v0.10.40 is still somewhere in your `/etc/paths`. May also check your `~/.bashrc`, `~/.bash_profile`, `~/.profile`, etc.

**Comment by alexanderzubarev** [comment] 2015-11-13 04:41
> require('child_process').spawn('node', ['-v']).stdout.on('data', function (data) {console.log(data.toString());}),'Node version:'
'Node version:'
> v4.2.2

**Comment by ArtemGovorov** [comment] 2015-11-13 04:44
Is v0.10.40 installed somewhere on your machine and perhaps it's in one for your `/etc/paths`? Try deleting/moving v0.10.40 to see what happens.
