### ISSUE TITLE
Typescript | Moving helper functions to external file causes flaky inline code coverage 

### ISSUE THREAD

**Issue by FlippieCoetser** [wallabyjs/public#2800] opened 2021-09-18 12:32 UTC
### Before 

I use the following helper function to get length of a typescript enum:

```typescript
let getEnumLength = (typescriptEnum): number => Object.keys(typescriptEnum).length;
```

In my test I use the helper as follows:

```typescript
describe('Given Type Enum', () => {
    it('Then Type Enum should contain two enums', () => {
        let enumLength = getEnumLength(Type)
        expect(enumLength).toBe(2)
    })
})
```

**Inline Code Coverage is fast and work as expected**

### After

When I move the helper function to an external utility class like so:

```typescript
export class Utils {
    static getEnumLength = (typescriptEnum) => Object.keys(typescriptEnum).length
}
```
import and use the utility as follows: 

```typescript
import { Utils } from "./Utils.js"

describe('Given Type Enum', () => {
    it('Then Type Enum should contain two enums', () => {
        let enumLength = Utils.getEnumLength(Type)
        expect(enumLength).toBe(2)
    })
})
```

**Inline Code Coverage fails to work instantly. I have to stop and start Wallaby to get the Inline Code Coverage to work**

Notes:
1. VS Code 
2. Wallaby version V1.0.313
3. Wallaby.js file:

```javascript
module.exports = function(wallaby) {
  return {
    files: [
      "src/**/*.ts"
    ],

    tests: [
      "test/**/*.ts"
    ],
    
    compilers: {
      '**/*.ts': wallaby.compilers.typeScript({
        "module": "es2020",
        "target": "es2020",
        "sourceMap": true,
        "inlineSources": true
      })
    }
  };
}
```

Any suggestions to improve the performance of the inline code coverage or how to avoid having to stop and start wallbyjs?

**Comment by ArtemGovorov** [comment] 2021-09-20 01:57
According to your config file, Wallaby looks for tests in `test/**/*.ts` and for source files in `src/**/*.ts`.

From this import in your test file:

> import { Utils } from "./Utils.js"

it looks like the `Utils` is not a file with tests, but rather a source file, so should not be in the `tests/` folder, but in the `src/` folder (or the config paths should be fixed to accomodate the exception).

Can you please try your scenario with placing `Utils` in the `src` folder to see if it works? I have tried and everything worked as expected for me. If the solution doesn't work, can you please provide some more details about the exact steps to reproduce the issue and some details about what exactly happens to inline coverage (ie. are the indicators disappearing completely or something else happens)?

**Comment by FlippieCoetser** [comment] 2021-09-20 16:42
@ArtemGovorov I moved the `Utils` from the `test/` to the `src/` folder. This change did improve the performance.
However, it feels somewhat strange to add a utility class used **only for testing** to my source directory where my main code base sits. Is there some other technique I can try which does not contaminate my code base with test utilities?

**Comment by smcenlly** [comment] 2021-09-20 23:25
> Is there some other technique I can try which does not contaminate my code base with test utilities?

Yes, you can include the utils file in the `files` section of your configuration. You will need to ensure that it is excluded from your `tests` in this case. For example, if the utils is called `utils.ts` and is located in `test` root, you would have:

```javascript
module.exports = function(wallaby) {
  return {
    files: [
      "src/**/*.ts",
      "test/utils.ts"
    ],

    tests: [
      "test/**/*.ts",
      "!test/utils.ts"
    ],
    
    compilers: {
      '**/*.ts': wallaby.compilers.typeScript({
        "module": "es2020",
        "target": "es2020",
        "sourceMap": true,
        "inlineSources": true
      })
    }
  };
}
```

**Closed by smcenlly** 2021-09-20 23:25 UTC
Labels: solution suggested, more info is required
