### ISSUE TITLE
Version 1.0.10 doesn't run any tests and shows them all as uncovered

### ISSUE THREAD

**Issue by okonet** [wallabyjs/public#98] opened 2015-05-05 13:06 UTC
wallaby console is showing:

```
wallaby.js started
Runtime error: TypeError: 'undefined' is not an object (evaluating 'a.$_$coverage[c][d][this._spec]=b++')
Runtime error: TypeError: 'undefined' is not an object (evaluating 'a.$_$coverage[c][d][this._spec]=b++')
Finished executing 0 affected test(s)
```

**Comment by fvanwijk** [comment] 2015-05-05 13:47
Duplicate of #81

**Comment by ArtemGovorov** [comment] 2015-05-05 22:50
Yep, seems like the cache issue. Try to clear the cache: make any change (even just a space) to wallaby config and restart it.

**Closed by ArtemGovorov** 2015-05-05 22:50 UTC
Labels: duplicate
