### ISSUE TITLE
"Maximum call stack size exceeded" error with Wallaby core v1.0.207

### ISSUE THREAD

**Issue by Sanjo** [wallabyjs/public#526] opened 2016-03-21 16:03 UTC
### Issue description

Since the latest versions of Wallaby (core v1.0.207 or something that was released in the last 10 days) my unit tests no longer run with Wallaby. All I get is a "Maximum call stack size exceeded" without stack trace.

Wallaby log: https://gist.github.com/Sanjo/2b85b7ef353282ef87b3

### Wallaby.js configuration file & Reproduce

__Config:__ https://github.com/xolvio/automated-testing-best-practices/blob/031b3ac51c5e8fedc8f1f5539f17dfd837cb68b3/wallaby_server.js

__Reproduce:__

Use OS X or Ubuntu for reproducing this.

1) Install Meteor if not already installed. https://www.meteor.com/install

2) Run the commands to install the repo:
```sh
git clone https://github.com/xolvio/automated-testing-best-practices.git
cd automated-testing-best-practices
npm install
npm start
```

3) Run the Wallaby config wallaby_server.js in Webstorm.

### Code editor or IDE name and version

WebStorm v11.0.3 and WebStorm 2016.1

### OS name and version

OSX
Ubuntu 14.04

**Comment by ArtemGovorov** [comment] 2016-03-22 01:43
Thanks for the repo. The issue is fixed in core v1.0.208.

P.S. You should probably add `fibers` and `underscrore` modules to devDependencies (wallaby config is using them).

**Closed** 2016-03-22 01:42 UTC
Labels: bug
