### ISSUE TITLE
Slows down VSCode

### ISSUE THREAD

**Issue by DanielZlotin** [wallabyjs/public#983] opened 2017-01-30 10:54 UTC
### Issue description or question

I can't pin point it exactly, but when running in VSCode everything becomes really sluggish. Writing code, autocomplete etc.

### Wallaby.js configuration file

```javascript
/*eslint-disable*/
'use strict';
process.env.BABEL_ENV = 'test';
const babelOptions = require('./package.json').babel.env.test;
module.exports = function(wallaby) {
  return {
    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    files: [
      'package.json',
      'src/**/*.js',
      '!src/**/*.test.js',
      'integration/**/*.js',
      '!integration/**/*.test.js'
    ],

    tests: [
      'src/**/*.test.js',
      'integration/**/*.test.js'
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel(babelOptions)
    },

    setup: function(w) {
      require('babel-polyfill');
      w.testFramework.configure(require('./package.json').jest);
    }
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.8.1

### OS name and version

OSX Sierra 10.12.2

**Comment by ArtemGovorov** [comment] 2017-01-30 11:37
Wallaby.js works is a separate process and doesn't do anything in the VS Code UI process, so it's highly unlikely that the extension itself can affect writing code, autocomplete.

What is possible is some heavy work in the core (that affects the performance of the whole machine, not just VS Code). Could you check the CPU load during writing code to see what processes are taking the most of the CPU time?

Also try to set [the `workers` count to 1](https://wallabyjs.com/docs/config/workers.html) to disable the parallelisation in the core to see if helps:

```javascript
 module.exports = function () {
   return {
     ...
     workers: {
       initial: 1,
       regular: 1
     }
   };
 };
```

As we we have never got any reports about wallaby extension slowing down VS Code, perhaps there are some other extensions that you have installed that may be affecting the performance?

**Comment by DanielZlotin** [comment] 2017-01-30 12:09
Thanks for the quick response.
This only happens in VSCode. Webstorm behaves well.

Setting the workers to 1 reduced the lag significantly.
I found the process `Code Helper` going up to 380% CPU (heh) without the `workers` config

**Comment by ArtemGovorov** [comment] 2017-01-30 12:48
Interesting. Worker count should only affect node processes, not the `Code Helper` (which is the background extension host on VS Code). I don't understand what's going on. Could you please answer/try the following things for me:

- How many files do you have opened in VS Code? 
- Try closing all of them but one, restarting wallaby (without the`workers` setting) and see if it affects the VS Code performance.
- Try installing [VS Code insiders build](https://code.visualstudio.com/insiders) to see if anything had changed there for you.
- And last, [try this sample project](https://github.com/wallabyjs/wallaby-jest-sample) in VS Code to see if editing its files also causing lags.

**Comment by DanielZlotin** [comment] 2017-01-30 13:33
I can't reproduce it in your example project..
In my project:
reproduced with 1 file open.
reproduced with VSCode insiders (with no other plugins installed).

If you want to try and reproduce it, clone this project and switch to branch `v2`:
https://github.com/wix/react-native-navigation.git
then `yarn install`, and run in VSCode

Thanks!

**Comment by DanielZlotin** [comment] 2017-01-30 13:47
OK I think I found the problem: I have an inner project with node_modules and react and react-native inside. It blows up the console with duplicate jest mocks etc.

**Comment by ArtemGovorov** [comment] 2017-01-30 14:00
>  I have an inner project with node_modules and react and react-native inside.

I have tried the repo - https://github.com/wix/react-native-navigation.git, but can't reproduce the issue. I also don't see any inner project with node_modules and react and react-native inside the project (using `v2` branch). I'm trying to edit this file - https://github.com/wix/react-native-navigation/blob/v2/src/index.test.js, but don't see much data in the console:

![vsc](https://cloud.githubusercontent.com/assets/979966/22425703/22ca2986-e748-11e6-9b95-ecc7099d2048.gif)

What am I missing?

**Comment by DanielZlotin** [comment] 2017-01-30 14:14
go to `./playground` and run `yarn run quickinstall`, then restart wallaby.

**Comment by ArtemGovorov** [comment] 2017-01-30 14:32
Thanks, I can see a lot of output now, but still no visible lags (though I see the increased CPU load). We can try and somehow throttle the console output, though not sure it'll help much with so much output from Jest. 

Anyway, I think the most efficient way to solve the issue is to add this to your wallaby setup function:
```javascript
    setup: function(w) {
      require('babel-polyfill');
      let jestConfig = require('./package.json').jest;
      jestConfig.modulePathIgnorePatterns = ['playground'];
      w.testFramework.configure(require('./package.json').jest);
    }
```
Please try it to see if it helps.

**Comment by DanielZlotin** [comment] 2017-01-30 14:41
This solved it, but I had to manually remove jest's cache folder because otherwise it was screaming about some files which he can't find.
I wonder why does it happen only in wallaby?

**Closed** 2017-01-30 14:47 UTC
Labels: VS Code

**Comment by ArtemGovorov** [comment] 2017-01-31 02:25
Awesome, thanks for the update!

> I wonder why does it happen only in wallaby?

It is a very good question. We are launching Jest test runner a bit differently comparing to how Jets itself launches it, I'm going to investigate it further.

**Comment by ArtemGovorov** [comment] 2017-01-31 06:14
> I wonder why does it happen only in wallaby?

We have found out why it was happening - we have been overriding `testPathDirs` not correctly. We have fixed the issue and published the fix in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), so once updated, you may revert back to your original wallaby config and it should work without the issue for you.

**Comment by DanielZlotin** [comment] 2017-01-31 09:15
It works! thanks!
