### ISSUE TITLE
bug: multiple configurations re-use cache

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#461] opened 2016-02-14 07:39 UTC
I know Wallaby doesn't support multiple configurations running at once, however:

1.  Run a configuration (e.g. `.wallaby.browser.js`)
2.  Stop it
3.  Run a different configuration in the same module (e.g. `.wallaby.node.js`)
4.  The second one doesn't seem to do, well, much of anything--until you delete the cache folder.  In my case, this was `/Users/boneskull/Library/Caches/PyCharm50/wallaby/projects/486cd4addda3d022`

**Comment by ArtemGovorov** [comment] 2016-02-15 00:13
Can't reproduce this one. To get the cache folder name, we calculate a hash from the full path of the config file, so 2 different configs should not end up using the same cache folder. 

Could you please [try running wallaby on this project](https://github.com/wallabyjs/wallaby-coffeescript-sample) (for browser and for node) to see if you can reproduce the issue there?

Could you also have a look when you start the `.wallaby.browser.js` config (with `debug: true` in it), does it use the same cache folder (the cache folder path will be in the Wallaby Console) as when you start the `.wallaby.node.js` config?

**Comment by ArtemGovorov** [comment] 2016-02-15 00:15
BTW, are you running the latest (v1.0.46) version of wallaby plugin for PyCharm?

**Comment by boneskull** [comment] 2016-02-15 02:42
I think. I'll try to determine a better reproduction plan. And logs too
On Sun, Feb 14, 2016 at 16:15 Artem Govorov <notifications@github.com>
wrote:

> BTW, are you running the latest (v1.0.46) version of wallaby plugin for
> PyCharm?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wallabyjs/public/issues/461#issuecomment-184010674>.
>
-- 
Christopher Hiller
https://boneskull.com | https://github.com/boneskull

**Comment by ArtemGovorov** [comment] 2016-05-03 02:23
I'll close the issue for now as there's been no activity on it for a while. If the issue is still valid for you, please share a repo where I could reproduce it, happy to have a look.

**Closed by ArtemGovorov** 2016-05-03 02:23 UTC
