### ISSUE TITLE
Tests not associated with correct file ...?

### ISSUE THREAD

**Issue by breathe** [wallabyjs/public#2122] opened 2019-06-27 00:10 UTC
### Issue description or question

Wallaby Logs -- shows execution of two test files: 

`src/Doordash/ExtractOrdersFromDoordashPdf.test.js` `src/Bytesquad/ExtractOrdersFromByteSquadPdf.test.js`

```
[Info]  Started Wallaby.js Core v1.0.697
[Info]  console.log: PASS src/Bytesquad/ExtractOrdersFromByteSquadPdf.test.js
[Info]  Execution progress: 50 tests
[Info]  Execution progress: 100 tests
[Info]  Execution progress: 150 tests
[Info]  console.log: PASS src/Doordash/ExtractOrdersFromDoordashPdf.test.js (16.494s)
[Info]  console.log:   ● Console
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]      console.log ../../../../../../software/itsacheckmate.com/Web/lib/pdf-api/node_modules/pdfjs-dist/build/pdf.worker.js:1014
[Info]        Warning: Indexing all PDF objects
[Info]  console.log:  › 18 snapshots obsolete.
[Info]  console.log:    • Doordash Exercise test pdfs Exercise pdf file: delivery-220481440.pdf Verify extracted data 1
[Info]  console.log:    • Doordash Exercise test pdfs Exercise pdf file: delivery-220481440.pdf Verify text extraction 1
[Info]  console.log:    • Doordash Exercise test pdfs Exercise pdf file: delivery-220600765.pdf Verify extracted data 1
[Info]  console.log:    • Doordash Exercise test pdfs Exercise pdf file: delivery-220600765.pdf Verify text extraction 1
[Info]  console.log:    • Doordash Exercise test pdfs Exercise pdf file: delivery-220736424.pdf Verify extracted data 1
[Info]  console.log:    • Doordash Exercise test pdfs Exercise pdf file: delivery-220736424.pdf Verify text extraction 1
[Info]  console.log:    • Doordash Exercise test pdfs Exercise pdf file: delivery-223541579.pdf Verify extracted data 1
[Info]  console.log:    • Doordash Exercise test pdfs Exercise pdf file: delivery-223541579.pdf Verify text extraction 1
[Info]  console.log:    • Doordash Exercise test pdfs Exercise pdf file: delivery-228830183.pdf Verify extracted data 1
[Info]  console.log:    • Doordash Exercise test pdfs Exercise pdf file: delivery-228830183.pdf Verify text extraction 1
[Info]  console.log:    • Doordash Exercise test pdfs Exercise pdf file: delivery-234111183.pdf Verify extracted data 1
[Info]  console.log:    • Doordash Exercise test pdfs Exercise pdf file: delivery-234111183.pdf Verify text extraction 1
[Info]  console.log:    • Doordash Exercise test pdfs Exercise pdf file: delivery-236283327.pdf Verify extracted data 1
[Info]  console.log:    • Doordash Exercise test pdfs Exercise pdf file: delivery-236283327.pdf Verify text extraction 1
[Info]  console.log:    • Doordash Exercise test pdfs Exercise pdf file: delivery-238867904.pdf Verify extracted data 1
[Info]  console.log:    • Doordash Exercise test pdfs Exercise pdf file: delivery-238867904.pdf Verify text extraction 1
[Info]  console.log:    • Doordash Exercise test pdfs Exercise pdf file: delivery-239004554.pdf Verify extracted data 1
[Info]  console.log:    • Doordash Exercise test pdfs Exercise pdf file: delivery-239004554.pdf Verify text extraction 1
[Info]  Finished executing 199 affected test(s)
```

But the wallaby app looks like this

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/434034/60223004-a11cf500-983c-11e9-99cc-ec78076840a9.png">

With test suites both listed as coming from one of the two files ...

I have code in a file testSuiteHelper's that is imported into each of these test files -- it contains functions which call describe() and it() ... something like this

file1.test.ts
```

import {sharedTests} from "./sharedTestSuite"

describe("Test 1 tests", () => {
   sharedTests("someparameters")
}
```

file2.test.ts
```

import {sharedTests} from "./sharedTestSuite"

describe("Test 2 tests", () => {
   sharedTests("someparameters")
}
```

Is that kind of usage not supported in jest?

### Wallaby.js configuration file

```javascript
module.exports = function() {
  return {
    files: ["**/*", "!src/**/*.test.ts", "!lib/**/*", "!node_modules/**/*"],
    tests: ["src/**/*.test.ts"],
    env: {
      type: "node",
      runner: "node"
    },
    testFramework: "jest"
  };
};
```

### Code editor or IDE name and version

Visual Studio Code Version 1.35.1 (1.35.1)

### OS name and version

OSX

**Comment by ArtemGovorov** [comment] 2019-06-27 01:10
Thanks for the report. The issue is fixed and will be released soon in wallaby core.

**Closed** 2019-06-27 01:09 UTC
