### ISSUE TITLE
Codecoverage fails: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by lcorneliussen** [wallabyjs/public#547] opened 2016-04-05 10:40 UTC
### Issue description or question

I ran a working test set with a new version of wallaby. Still trying to find out, which test exactly causes the problem.

### Wallaby.js configuration file

```javascript
Tue, 05 Apr 2016 10:38:13 GMT wallaby:project Failed to process test run results TypeError: Cannot read property 'push' of undefined
  at C:\Users\Lars Corneliussen\.wallaby\core\server.js:16:28950
  at arrayEach (C:\Users\Lars Corneliussen\.wallaby\core\node_modules\lodash\index.js:1286:13)Failed to process test run results Cannot read property 'push' of undefined

  at Function.forEach (C:\Users\Lars Corneliussen\.wallaby\core\node_modules\lodash\index.js:5700:11)
  at EventEmitter._.extend._processCoverageResult (C:\Users\Lars Corneliussen\.wallaby\core\server.js:16:28130)
  at C:\Users\Lars Corneliussen\.wallaby\core\server.js:16:22010
  at _fulfilled (C:\Users\Lars Corneliussen\.wallaby\core\node_modules\q\q.js:787:54)
  at self.promiseDispatch.done (C:\Users\Lars Corneliussen\.wallaby\core\node_modules\q\q.js:816:30)
  at Promise.promise.promiseDispatch (C:\Users\Lars Corneliussen\.wallaby\core\node_modules\q\q.js:749:13)
  at C:\Users\Lars Corneliussen\.wallaby\core\node_modules\q\q.js:557:44
  at flush (C:\Users\Lars Corneliussen\.wallaby\core\node_modules\q\q.js:108:17)
```

### Code editor or IDE name and version

Visual Studio 2015 Update 1

### OS name and version

Windows 10

**Comment by lcorneliussen** [comment] 2016-04-05 10:47
Looks like this test is causing the problem. Will look at the details later:

```javascript
describe("two different dates are set to same when updating aggregate", function (done) {

        var date = new Date();
        var d1 = ko.observable(date);
        var d2 = ko.observable(new Date(date + 1));

        beforeEach(function(done) {
            var dates = ko.observable([
                ko.computed({ read: d1, write: d2 }),
                ko.computed({
                    read: d2,
                    write: function(value) {
                        console.log(value);
                        d2(value);
                    }
                })
            ]);
            var aggr = ko.aggregate(dates);
            aggr(new Date(date));

            _.delay(done, 500);
        });

        it("should be", function() {
            expect(d1().getTime()).toBe(date.getTime());
            expect(d2().getTime()).toBe(date.getTime());
        });

    });
```

**Comment by ArtemGovorov** [comment] 2016-04-05 11:25
Perhaps it's a caching issue, try changing wallaby.js config file (even a space anywhere will do), restart wallaby and see if the issue goes away.

I'm trying to create the sample to run your tests locally, but can't run it yet.
It's been a long time since I have used knockout, what is `ko.aggregate`? It says `'undefined' is not a function (evaluating 'ko.aggregate...`? I'm using knockout 3.4.0.

One (most likely unrelated) thing I have noticed is that you are passing `done` as an argument the `describe` function body and jasmine doesn't support it (you're not using it anyway).

**Comment by ArtemGovorov** [comment] 2016-04-05 11:28
I have also reviewed few latest versions of wallaby and didn't find any changes that might affect this scenario, are you sure the test suite was running fine earlier? Perhaps you have changed something else in your project recently?

**Comment by lcorneliussen** [comment] 2016-04-05 12:43
Hi. Back now.

Found out about it: A colleague added a new test which also passed when he added it - but restarting wallaby afterwords failed. That happens if a `it` and a `describe` have the same name.

Running incrementally it is no problem, but when loading initially it fails with the error I gave you:

```javascript
describe("desc", function() {
    it("duplicate", function() {
        
    });
    describe("duplicate", function() {
        it("test", function () {

        });
    });
});
```

**Comment by lcorneliussen** [comment] 2016-04-05 12:47
I don't know what the spec says, but tryjasmine.com doesn't bother complaining

**Comment by ArtemGovorov** [comment] 2016-04-05 12:55
>  That happens if a it and a describe have the same name.

Great catch! Thanks a lot for isolating it.
The issue is fixed in the latest core v1.0.212. Will be updated automatically within the next 20 minutes after the some of wallaby restart. To force the update to happen now, just restart your IDE and start wallaby.js.

**Closed by ArtemGovorov** 2016-04-05 12:55 UTC
Labels: bug

**Comment by lcorneliussen** [comment] 2016-04-05 12:58
np. i fixed the names :)

**Comment by lcorneliussen** [comment] 2016-04-05 13:00
but thx for fixing that fast. and thanks for the great product.
wallaby has dramatically changed my approach to javascript testing

actually, I'm now writing tests :)

**Comment by ArtemGovorov** [comment] 2016-04-05 13:02
@lcorneliussen Hehe, thanks! Glad to hear it makes testing easier for you.
