### ISSUE TITLE
"[Iterator]" text inside arrays

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1208] opened 2017-06-26 14:57 UTC
### Issue description or question
When using ``console.log()`` on an array or ``show difference`` of a failed test that compares arrays, the word ``[Iterator]`` is printed inside every array. This is only happening inside of Wallaby. Any ideas what could be causing this / how to disable?

```js
it('should not print Iterator', () => {
    const files = [
        'js/chunks/0.bundle.js',
        'js/chunks/1.bundle.js',
        'js/bundle.js',
    ];

    console.log(files); // prints: [ [Iterator] 'js/chunks/0.bundle.js', 'js/chunks/1.bundle.js', 'js/bundle.js' ] 

    expect(files).toEqual([]);
});
```

<img width="829" alt="screen shot 2017-06-26 at 7 47 21 am" src="https://user-images.githubusercontent.com/1595871/27545126-e50a9e9a-5a43-11e7-8ea7-9debb0fccc98.png">
<img width="809" alt="screen shot 2017-06-26 at 7 46 44 am" src="https://user-images.githubusercontent.com/1595871/27545131-e7f12af2-5a43-11e7-9808-994f447748ce.png">

### Wallaby.js configuration file
```js
/* eslint-disable global-require,strict */

'use strict';

module.exports = wallaby => {
    return {
        files: [
            'src/**/*.js',
            'jest.config.js',
            // '__sandbox__/**/*', // I don't think this is necessary because it is created by the tests
            '!src/**/*.test.js',
        ],

        tests: ['src/**/*.test.js'],

        env: {
            type: 'node',
            runner: 'node',
        },

        compilers: {
            '**/*.js': wallaby.compilers.babel(),
        },

        testFramework: 'jest',

        // https://github.com/wallabyjs/public/issues/465
        workers: { initial: 1, regular: 1 },

        setup: w => {
            const jestConfig = require('./jest.config');
            w.testFramework.configure(jestConfig);
        },
    };
};
```

### Code editor or IDE name and version

```
WebStorm 2017.2 EAP
Build #WS-172.3095.13, built on June 21, 2017
WebStorm EAP User
Expiration date: July 21, 2017
JRE: 1.8.0_152-release-915-b3 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5
```

### OS name and version

``OSX 10.12.5``

**Comment by ArtemGovorov** [comment] 2017-06-26 22:59
Thanks for the report. The issue is fixed in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Closed by ArtemGovorov** 2017-06-26 22:59 UTC
Labels: bug
