### ISSUE TITLE
Incorrect line jump when clicking on TestName failure

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1547] opened 2018-03-07 04:01 UTC
### Issue description or question

I have a typescript project and when I CMD+click on failed test name it takes me to incorrect address, but only if I call any function 

Example:

```js
function fn(organisations = defaultOrganisations) {
   // JUMPS HERE
   return 1;
}

it('ok jump', () => {
  true.should.be.false; // jump here when clicked 
})

it('bad jump', () => {
  fn();
  true.should.be.false; // jumps to "JUMPS HERE" mentioned above.
})
```
### Wallaby.js configuration file

Not important

### Code editor or IDE name and version

Visual Studio Code 

### OS name and version

OSX

**Comment by ArtemGovorov** [comment] 2018-03-07 06:11
Thanks for the report. The issue is fixed in the [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version.

**Closed by ArtemGovorov** 2018-03-07 06:11 UTC
Labels: bug

**Comment by tomitrescak** [comment] 2018-03-07 10:08
@ArtemGovorov it is noe pointing me to line 1 of the file :(

**Comment by tomitrescak** [comment] 2018-03-07 10:18
Nevermind ... VS Code Restart helped.
