### ISSUE TITLE
‌[Error] TypeError: Cannot read properties of undefined (reading 'pattern') 

### ISSUE THREAD

**Issue by JoshWhite** [wallabyjs/public#3243] opened 2023-07-21 10:44 UTC
### Issue description or question
As of this morning, I'm getting the titled error in all Vitest apps I have running on my machine. 
I've tried previous versions & clearning the wallaby cache, but I can't get it to work. 

### Wallaby diagnostics report

![image](https://github.com/wallabyjs/public/assets/1931725/fc01282e-0124-44fb-9e3d-0f9fd701756f)

I don't have this option. Am I doing something wrong?

Here's all the info I can think of:

- Wallaby Version: v1.0.1445
- Windows 11
- VSCode
- Vitest
- Automatic config

And here's my trace:
```
‍​[Info]​ 2023-07-21T10:32:00.232Z config Attempting automatic configuration for angular
​[Info]​ 2023-07-21T10:32:00.233Z angular/cli config Detecting Angular CLI.
​[Info]​ Started Wallaby.js Core v1.0.1445
​[Info]​ 2023-07-21T10:32:00.237Z angular/cli config Angular CLI not found.
​[Info]​ 2023-07-21T10:32:00.237Z config Finished attempting automatic configuration for angular (5ms)
​[Info]​ 2023-07-21T10:32:00.237Z config Attempting automatic configuration for jest
​[Info]​ 2023-07-21T10:32:00.238Z jest/config Detecting Jest.
​[Info]​ 2023-07-21T10:32:00.242Z jest/config Error: Module jest-cli is not found in 'C:\repos\***\***'.
​[Info]​     at Object.loadJest (c:\Users\JoshWhite\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.364\wallabydd6461\server.js:496:1070)
​[Info]​     at n (c:\Users\JoshWhite\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.364\wallabydd6461\server.js:184:23339)
​[Info]​     at Object.configure (c:\Users\JoshWhite\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.364\wallabydd6461\server.js:184:26449)
​[Info]​     at automaticConfigurationProviders.reduce.Promise.resolve.success (c:\Users\JoshWhite\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.364\wallabydd6461\server.js:132:12015)
​[Info]​     at async automaticConfigurationProviders.reduce.Promise.resolve.success (c:\Users\JoshWhite\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.364\wallabydd6461\server.js:132:11892)
​[Info]​     at async Config.load (c:\Users\JoshWhite\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.364\wallabydd6461\server.js:132:11832)
​[Info]​ 2023-07-21T10:32:00.242Z config Finished attempting automatic configuration for jest (5ms)
​[Info]​ 2023-07-21T10:32:00.242Z config Attempting automatic configuration for vitest
​[Info]​ 2023-07-21T10:32:00.243Z vitest/config Detecting Vitest.
​[Info]​ 2023-07-21T10:32:00.246Z vitest/config Detected Vitest (0.29.8).
​[Info]​ 2023-07-21T10:32:00.860Z vitest/config Configured Vitest.
​[Info]​ 2023-07-21T10:32:00.861Z config Finished attempting automatic configuration for vitest (619ms)
​​[Error] Failed to load configuration file: TypeError: Cannot read properties of undefined (reading 'pattern')​​
​​[Error] Please refer to our docs: https://wallabyjs.com/docs/config/overview.html ​​
​[Info]​ 2023-07-21T10:32:00.868Z extended-core Setting preferences
​[Info]​ 2023-07-21T10:32:16.087Z extended-core Setting preferences
```

**Comment by epszaw** [comment] 2023-07-21 12:00
Same here

**Comment by azat-io** [comment] 2023-07-21 15:31
Same problem after updating to v1.0.1445

**Comment by vritant24** [comment] 2023-07-21 15:47
likewise. Facing a similar issue here

**Comment by pjm60** [comment] 2023-07-21 17:13
Have same error. 

‍​[Info]​ Started Wallaby.js Core v1.0.1445
​​[Error] Failed to load configuration file: TypeError: Cannot read properties of undefined (reading 'pattern')​​

SvelteKit application using typescript and vitest. Using Autoconfig project.

Would the wallaby team please update the docs to at least suggest a wallaby.ts file that might work. Since I'm not using javascript nor commonjs. All the wallaby website docs are years old and completely unhelpful.  I've been in the mode of if you just use autoconfig then everything just works--LIKE MAGIC--except when it doesn't.

Please help.

**Comment by smcenlly** [comment] 2023-07-21 22:33
Thanks for reporting the problem and sorry for the inconvenience. 

Yesterday we updated our `vitest` integration to support fully qualified paths in the `include` and `exclude` file patterns. We inadvertently broke other parts of Wallaby's `vitest` integration at the same time.

The problem is fixed in the latest version of Wallaby core, `v1.0.1446`. 

---

For future reference you may use a different version of Wallaby if you need by following our [offline installation instructions](https://wallabyjs.com/docs/intro/offline.html).

---

> Would the wallaby team please update the docs to at least suggest a wallaby.ts file that might work.

In this case, there was a bug in the product, and our docs/configuration would not help you. The architectural changes we have made to Wallaby over the last few years with automatic configuration have changed how Wallaby integrates with most testing frameworks and a configuration file truly is not required.

**Closed by smcenlly** 2023-07-21 22:33 UTC

**Comment by azat-io** [comment] 2023-07-23 12:03
I'm sorry. Looks like the latest Wallaby version is v1.0.364.

<img width="285" alt="image" src="https://github.com/wallabyjs/public/assets/5698350/ee7d4d99-9b31-4f29-ab22-40f3cf10ceeb">

Have you released the version with the fix yet?

**Comment by smcenlly** [comment] 2023-07-23 22:44
Yes - the fix was released with my [previous comment](https://github.com/wallabyjs/public/issues/3243#issuecomment-1646301917).

There are two components to Wallaby. The extension version, and the core runtime version. 

The fix is in the Wallaby core runtime, `v1.0.1446`.

**Comment by azat-io** [comment] 2023-08-05 15:00
Can you give instructions on how to update Wallaby? I haven't been able to use it for weeks now.

**Comment by Merott** [comment] 2023-08-05 15:01
@azat-io 

"Force Core Update" from the command palette.

<img width="653" alt="CleanShot 2023-08-05 at 16 01 12@2x" src="https://github.com/wallabyjs/public/assets/1757708/61b16b88-fd76-407f-93e7-1bf567ae2e60">

**Comment by azat-io** [comment] 2023-08-05 15:07
> @azat-io
> 
> "Force Core Update" from the command palette.
> 
> <img alt="CleanShot 2023-08-05 at 16 01 12@2x" width="653" src="https://user-images.githubusercontent.com/1757708/258592309-61b16b88-fd76-407f-93e7-1bf567ae2e60.png">

@Merott Awesome! Thanks you!

**Comment by smcenlly** [comment] 2023-08-06 22:21
@azat-io - Wallaby should update automatically for you. Are you still having problems after using `Force Core Update`?
