### ISSUE TITLE
Wallaby Runner Doesn't Work in Firefox

### ISSUE THREAD

**Issue by benjaminjackman** [wallabyjs/public#1667] opened 2018-05-22 20:01 UTC
### Issue description or question
I am using vscode and the wallaby app works ok in chrome but it doesn't work in firefox.

### Wallaby.js configuration file

```javascript
module.exports = function () {
  //See: https://wallabyjs.com/docs/integration/jest.html#jest-configuration
    return {
      files: [
        'tsconfig.json', // <--
        'src/**/*.json',
        'src/**/*.js',
        'src/**/*.ts',
        'src/**/*.tsx',
        'package.json', // <--
        'src/**/__resources__/**/*',
        '!src/**/__tests__/*.js',
        '!src/**/__tests__/*.ts',
        '!src/**/*.test.js',
        '!src/**/*.test.ts',
        ],
  
      tests: [
        'src/**/__tests__/*.ts',
        'src/**/*.test.ts',
        'src/**/__tests__/*.js',
        'src/**/*.test.js',
      ],
  
      env: {
        type: 'node',
        runner: 'node'
      },
  
      testFramework: 'jest',
  
      setup: function (wallaby) {
        var jestConfig = require('./package.json').jest;
        // for example:
        // jestConfig.globals = { "__DEV__": true };
        wallaby.testFramework.configure(jestConfig);
      }
    };
  };
```
### Code editor or IDE name and version
Visual Studio Code v1.23.1

### OS name and version
Linux

Here is the stack trace I am seeing in firefox
```
EXCEPTION: t is undefined vendor.31fadcd40eb6091fa9ce.js:15:19459
./node_modules/@angular/core/bundles/core.umd.js/</</Wn</e.prototype.handleError
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:15:19459
Ie/<
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:14:25195
./node_modules/zone.js/dist/zone.js/</</C</_</e.prototype.invoke
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:26197
onInvoke
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:15:26967
./node_modules/zone.js/dist/zone.js/</</C</_</e.prototype.invoke
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:26124
./node_modules/zone.js/dist/zone.js/</</C</m</t.prototype.run
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:23041
p/<
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:20539
./node_modules/zone.js/dist/zone.js/</</C</_</e.prototype.invokeTask
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:26865
onInvokeTask
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:15:26867
./node_modules/zone.js/dist/zone.js/</</C</_</e.prototype.invokeTask
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:26778
./node_modules/zone.js/dist/zone.js/</</C</m</t.prototype.runTask
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:23659
i
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:19580
s
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:27:1617
O/<
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:27:1739
c
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:25:4800
ORIGINAL STACKTRACE: vendor.31fadcd40eb6091fa9ce.js:15:19593
./node_modules/@angular/core/bundles/core.umd.js/</</Wn</e.prototype.handleError
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:15:19593
Ie/<
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:14:25195
./node_modules/zone.js/dist/zone.js/</</C</_</e.prototype.invoke
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:26197
onInvoke
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:15:26967
./node_modules/zone.js/dist/zone.js/</</C</_</e.prototype.invoke
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:26124
./node_modules/zone.js/dist/zone.js/</</C</m</t.prototype.run
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:23041
p/<
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:20539
./node_modules/zone.js/dist/zone.js/</</C</_</e.prototype.invokeTask
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:26865
onInvokeTask
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:15:26867
./node_modules/zone.js/dist/zone.js/</</C</_</e.prototype.invokeTask
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:26778
./node_modules/zone.js/dist/zone.js/</</C</m</t.prototype.runTask
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:23659
i
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:19580
s
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:27:1617
O/<
http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:27:1739
c

Unhandled Promise rejection: t is undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: "t is undefined"
valuehttp://wallabyjs.com/app/main.778c9606056b56e0fba1.js:1:5759ngDoCheck/e/e/wrapper.ngfactory.js:18:60detectChangesInternal/e/e/host.ngfactory.js:28:3detectChangeshttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:17:30286detectChangeshttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:17:7272tickhttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:16:28866tickhttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:16:28827_loadComponenthttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:16:28424bootstraphttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:16:28207_moduleDoBootstraphttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:16:26068_moduleDoBootstraphttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:16:26020_bootstrapModuleFactoryWithZonehttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:16:25365invokehttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:26197onInvokehttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:15:26967invokehttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:26124runhttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:23041phttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:20539invokeTaskhttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:26865onInvokeTaskhttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:15:26867invokeTaskhttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:26778runTaskhttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:23659ihttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:19580shttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:27:1617Ohttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:27:1739chttp://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:25:4800 value@http://wallabyjs.com/app/main.778c9606056b56e0fba1.js:1:5759
anonymous/Wrapper_e.prototype.ngDoCheck@/e/e/wrapper.ngfactory.js:18:60
anonymous/View_e_Host0.prototype.detectChangesInternal@/e/e/host.ngfactory.js:28:3
./node_modules/@angular/core/bundles/core.umd.js/</</qi</e.prototype.detectChanges@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:17:30286
./node_modules/@angular/core/bundles/core.umd.js/</</Jo</e.prototype.detectChanges@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:17:7272
./node_modules/@angular/core/bundles/core.umd.js/</</To</t.prototype.tick/<@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:16:28866
./node_modules/@angular/core/bundles/core.umd.js/</</To</t.prototype.tick@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:16:28827
./node_modules/@angular/core/bundles/core.umd.js/</</To</t.prototype._loadComponent@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:16:28424
./node_modules/@angular/core/bundles/core.umd.js/</</To</t.prototype.bootstrap@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:16:28207
./node_modules/@angular/core/bundles/core.umd.js/</</Co</t.prototype._moduleDoBootstrap/<@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:16:26068
./node_modules/@angular/core/bundles/core.umd.js/</</Co</t.prototype._moduleDoBootstrap@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:16:26020
./node_modules/@angular/core/bundles/core.umd.js/</</Co</t.prototype._bootstrapModuleFactoryWithZone/</</<@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:16:25365
./node_modules/zone.js/dist/zone.js/</</C</_</e.prototype.invoke@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:26197
onInvoke@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:15:26967
./node_modules/zone.js/dist/zone.js/</</C</_</e.prototype.invoke@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:26124
./node_modules/zone.js/dist/zone.js/</</C</m</t.prototype.run@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:23041
p/<@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:20539
./node_modules/zone.js/dist/zone.js/</</C</_</e.prototype.invokeTask@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:26865
onInvokeTask@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:15:26867
./node_modules/zone.js/dist/zone.js/</</C</_</e.prototype.invokeTask@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:26778
./node_modules/zone.js/dist/zone.js/</</C</m</t.prototype.runTask@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:23659
i@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:55:19580
s@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:27:1617
O/<@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:27:1739
c@http://wallabyjs.com/app/vendor.31fadcd40eb6091fa9ce.js:25:4800
```

**Comment by ArtemGovorov** [comment] 2018-05-22 23:13
Could you please share your FF version?

**Comment by benjaminjackman** [comment] 2018-05-22 23:28
61.0b7 (64-bit)
Firefox Developer Edition
Aurora Update Channel

**Comment by ArtemGovorov** [comment] 2018-05-22 23:32
Thanks for sharing the details. 

Are you opening Wallaby App as via the wallabyjs.com/app URL or via the http://localhost:51245 URL (try the second URL if you haven't to see if its working).

**Comment by ArtemGovorov** [comment] 2018-05-23 00:06
We have been able to reproduce the issue. 

It looks like something may be broken in Firefox Developer Edition, because the stable 60.0.1 (64-bit) is working as expected. The issue comes from Angular, so we'll see if it may be fixed by updating Wallaby App dependencies, but it may not solve it.

**Comment by benjaminjackman** [comment] 2018-05-23 00:14
Ok thanks for the fast response.

To answer the previous question I've was using the localhost url

**Comment by ArtemGovorov** [comment] 2018-05-23 00:39
Thanks. We have been able to locate the reason and fix the issue for FF 61. The new Wallaby App v1.0.39 with the fix has just been published.

**Closed by ArtemGovorov** 2018-05-23 00:39 UTC

**Comment by benjaminjackman** [comment] 2018-05-23 01:32
Works on my side now, thanks for the fast response! 

though not sure how to find that version number in vscode, 
I see `​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.591` in the console
and `Wallaby.js 1.0.84` in the extensions panel

**Comment by ArtemGovorov** [comment] 2018-05-23 01:38
@benjaminjackman Thanks for checking and confirming ten fix. Wallaby App is versioned separately and the version of the app is displayed at the bottom left corner of the app:

<img width="757" alt="screen shot 2018-05-23 at 11 33 48 am" src="https://user-images.githubusercontent.com/979966/40398902-addae76a-5e7d-11e8-91ed-f1cc8cb14bd2.png">

**Comment by benjaminjackman** [comment] 2018-05-23 01:43
Ok that makes sense, yep I see it now in the app:

![image](https://user-images.githubusercontent.com/62048/40399023-ae78e226-5e00-11e8-9dd0-86a694c64057.png)

Thanks again!
