### ISSUE TITLE
SymLinked Files Not Copied to Project Cache

### ISSUE THREAD

**Issue by nickjoseph** [wallabyjs/public#416] opened 2016-01-22 22:53 UTC
First off, wallaby.js is awesome!  I will be purchasing a license as soon as I can get all the kinks worked out.  Now onto the potential bug...

We use `npm` for managing dependencies.  When I'm working in both the main project and a dependent project, I use `npm link` to create a symlink in the `node_modules` folder of the main project that points to my working copy of the dependent project.

When I run wallaby.js (`v1.0.7 - VS Code`), it won't copy symlinked files from the `node_modules` folder to the `projectCache` folder, even though I've explicitly added it to the files list.  It copies other files from `node_modules`, it just won't follow the symlinks.

Is this a bug, or is there a flag I need to set somewhere?

**Comment by ArtemGovorov** [comment] 2016-01-22 23:01
@nickjoseph Thanks! Could you please share your wallaby config?

**Comment by nickjoseph** [comment] 2016-01-25 16:32
```
module.exports = function (wallaby) {
  return {
    files: [
      { pattern: 'src/**/tests/mocha/**/*_spec.js', ignore: true },
      'src/client/**/*.js',
      'node_modules/webapijsclient/**/*.js',
      'node_modules/spec/**/*.js'
    ],
    tests: [
      'src/**/tests/mocha/**/*_spec.js'
    ],
    env: {
        type: 'node',
        runner: 'node'
    },
    testFramework: 'mocha',
    debug: true,
    workers: {
        recycle: true
    }
  };
};
```

**Comment by ArtemGovorov** [comment] 2016-01-26 00:40
Confirmed, looks like symlink following doesn't work in VS Code version, will have a look how we can fix it.

Quick question, why do you need to list `node_modules/webapijsclient` in your `files` list? It should work for you even if you don't. The code coverage for `node_modules/webapijsclient` will not be reported, but as you have mentioned, it is a separate dependent project, so it probably has its own tests and coverage and it doesn't make sense to report it for the main project?

**Comment by ArtemGovorov** [comment] 2016-01-26 03:55
The issue is fixed in the latest core (v.1.0.165) which should be updated automatically if not already, then within a few minutes after your next wallaby (re-)start.

**Closed by ArtemGovorov** 2016-01-26 03:55 UTC

**Comment by nickjoseph** [comment] 2016-01-26 15:48
Wow, thanks for the quick fix!

In regards to your question, the main project is a web app that uses RequireJS to load AMD modules.  RequireJS is configured to pull some dependencies from the `node_modules` folder.  When wallaby runs the tests, RequireJS is looking for the dependencies relative to the project cache.

Ideally, the unit tests would just mock out all the dependencies, but I inherited this project and haven't had time to de-tangle everything yet.

**Comment by ArtemGovorov** [comment] 2016-01-27 01:26
@nickjoseph Got it, thanks for the update!
