### ISSUE TITLE
Support Sublime Text 3

### ISSUE THREAD

**Issue by axefrog** [wallabyjs/public#206] opened 2015-07-18 00:40 UTC
I know a lot of devs are using Atom, but a tonne also use (and have a licenses) Sublime. I know I do, and a lot of my colleagues and colleagues-of-friends use it too. As soon as you have support for Sublime, you get my business. Programming JavaScript in Visual Studio is ... not the best.

**Comment by ArtemGovorov** [comment] 2015-07-18 00:44
Closing as a duplicate of https://github.com/wallabyjs/public/issues/45

A very significant chunk of work, that we had to do to support Atom and Sublime, is actually editor agnostic. So even though Atom is planned first, when we finish it, Sublime integration will re-use a lot of what we've done and will need much less time to be released.

**Closed by ArtemGovorov** 2015-07-18 00:44 UTC
Labels: duplicate

**Comment by axefrog** [comment] 2015-07-18 02:17
Sounds good, can't wait!
