### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Jarvis1010** [wallabyjs/public#2643] opened 2021-03-01 09:07 UTC
- Issue Type: `Performance`
- Extension Name: `wallaby-vscode`
- Extension Version: `1.0.269`
- OS Version: `Darwin x64 20.3.0`
- VSCode version: `1.53.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/d_/spzz1p2s3ks6q6gcpv01w50m0000gp/T/WallabyJs.wallaby-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smcenlly** [comment] 2021-03-01 21:57
> :warning: Make sure to **attach** this file from your *home*-directory:

The CPU profile is missing from this issue.

---

This is expected to be a duplicate of https://github.com/wallabyjs/public/issues/2403.

> Your CPU profile shows that the high CPU load is operating system time during file copy operations when Wallaby is updating itself. This is likely caused by your virus scanner as Wallaby is extracting .js files that your virus scanner is processing. 

To confirm, you may try disabling your virus scanner during an update and then create a virus scanner exclude pattern to ignore files within the Wallaby VS Code extension.

**Closed by smcenlly** 2021-03-01 21:57 UTC
