### ISSUE TITLE
last console.out sometimes is not shown

### ISSUE THREAD

**Issue by DinisCruz** [wallabyjs/public#240] opened 2015-08-23 10:05 UTC
I have noticed this a couple times and here is a good example of it

![image](https://cloud.githubusercontent.com/assets/656739/9427792/d4e1b7d0-4986-11e5-8d26-568aa761a7e7.png)

**Comment by ArtemGovorov** [comment] 2015-08-24 03:56
Nice find! The issue is fixed in core v1.0.88

**Closed by ArtemGovorov** 2015-08-24 03:56 UTC
Labels: bug
