### ISSUE TITLE
Support ... Ember js!

### ISSUE THREAD

**Issue by bennycwong** [wallabyjs/public#269] opened 2015-09-18 17:46 UTC

**Comment by ArtemGovorov** [comment] 2015-09-19 02:18
Thanks for the suggestion. Closing as a duplicate of https://github.com/wallabyjs/public/issues/13. Unless you mean testing ember.js apps with jasmine/mocha - it should just work in the current version of wallaby.js.

**Closed by ArtemGovorov** 2015-09-19 02:18 UTC
Labels: duplicate
