### ISSUE TITLE
WebStorm update to 2019.3.3 broke wallaby

### ISSUE THREAD

**Issue by fr0** [wallabyjs/public#2350] opened 2020-02-20 21:54 UTC
### Issue description or question

<img width="809" alt="Screen Shot 2020-02-20 at 4 53 37 PM" src="https://user-images.githubusercontent.com/435418/74982199-a9e0bd80-5401-11ea-9218-732d5c1701dc.png">

**Comment by smcenlly** [comment] 2020-02-20 22:17
@fr0 - thanks for reporting your problem. This is working for us, so we're wondering if there's some other problem.

Could you please copy your WebStorm version and paste it below, `Help -> About`, then click the copy icon that appears when you hover over the WebStorm version. We're using:

```
WebStorm 2019.3.3
Build #WS-193.6494.34, built on February 11, 2020
Licensed to ---------------
Subscription is active until  ---------------
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: 
Non-Bundled Plugins: wallaby.js
```

Could you also please review and provide us with your WebStorm logs, `Help -> Show Log in Explorer` (I'm using Windows so it may be a little different on Mac). We expect that there's some additional detail in your log file.

Another possibility is that your configuration file has been corrupted somehow. Are you able to create and use a new Run Configuration for Wallaby?

**Comment by fr0** [comment] 2020-02-20 22:24
I just downloaded and reinstalled wallaby from the zip file and now it's working, so I've at least gotten past the issue. However, here's the relevant info:

[logs.zip](https://github.com/wallabyjs/public/files/4233278/logs.zip)

```
WebStorm 2019.3.3
Build #WS-193.6494.34, built on February 10, 2020
Licensed to Beckman Coulter / Christopher Frolik
Subscription is active until May 20, 2020
Runtime version: 11.0.5+10-b520.38 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: 
Non-Bundled Plugins: String Manipulation, com.alayouni.ansiHighlight, com.krylysov.nsisplugin, mobi.hsz.idea.latex, nl.rubensten.texifyidea, quokka.js, wallaby.js
```

**Comment by smcenlly** [comment] 2020-02-20 22:34
I can't see anything in your logs that would indicate the cause of the problems. Perhaps this was caused by a corrupt download/install. Given that everything is working for you, I'm going to close this issue.

**Closed by smcenlly** 2020-02-20 22:34 UTC
