### ISSUE TITLE
Webpack v5: Wallaby not including all CSS

### ISSUE THREAD

**Issue by jljorgenson18** [wallabyjs/public#2679] opened 2021-04-01 18:35 UTC
### Issue description or question

I'm getting many test failures that are due to CSS not being included. I used this trick to open Chrome to confirm

```
        env: {
            kind: 'chrome',
            /** Uncomment these params to debug weird Wallaby issues in a browser instance */
            params: {
                runner: '--disable-gpu'
            },
            keepTabsOpened: true
        },
```

And I can visually see that only a small portion of my CSS is included in the style tag. This was working just fine in Webpack v4 and only started failing after upgrading to v5. My style rules for testing can be seen below

```js
const styleLoader = {
        loader: 'style-loader',
        options: {
            injectType: 'singletonStyleTag'
        }
};

const moduleCSSLoader = {
    loader: 'css-loader',
    options: {
        importLoaders: 2,
        modules: {
            exportLocalsConvention: 'camelCase',
            localIdentName: `${isDev ? '[local]_' : ''}[hash:base64:5]`
        }
    }
};

const globalCSSLoader = {
    loader: 'css-loader',
    options: {
        importLoaders: 2,
        modules: false
    }
};
const postCSSLoader = {
    loader: 'postcss-loader'
};
const lessLoader = {
    loader: 'less-loader',
    options: {
        sourceMap: false,
        lessOptions: {
            relativeUrls: false,
            strictMath: true
        }
    }
};
const sassLoader = {
    loader: 'sass-loader',
    options: {
        sourceMap: false,
        sassOptions: {
            includePaths: [path.join(__dirname, 'src'), path.join(__dirname, 'node_modules')]
        }
    }
};

const styleRules = [
    {
        test: /.less$/,
        oneOf: [
            {
                resourceQuery: /module/,
                use: [styleLoader, moduleCSSLoader, postCSSLoader, lessLoader]
            },
            {
                use: [styleLoader, globalCSSLoader, postCSSLoader, lessLoader]
            }
        ]
    },
    {
        test: /.s?css$/,
        oneOf: [
            {
                resourceQuery: /module/,
                use: [styleLoader, moduleCSSLoader, postCSSLoader, sassLoader]
            },
            {
                use: [styleLoader, globalCSSLoader, postCSSLoader, sassLoader]
            }
        ]
    }
];
```

### Wallaby diagnostics report

For security reasons I can't share the full report, but here is my wallaby config.
```
/* eslint-disable import/no-extraneous-dependencies */
const path = require('path');
const webpackConfig = require('./webpack.config.js');

const getWallabyWebpackConfig = () => {
    const wallabyWebpackConfig = {
        ...webpackConfig[0],
        devtool: undefined,
        // This helps speed up the build so we don't add these files to the bundle each time
        externals: {
            // Use external version of React and ReactDOM
            react: 'React',
            'react-dom': 'ReactDOM',
            yjs: 'Y',
            chai: 'chai',
            sinon: 'sinon'
        }
    };
    delete wallabyWebpackConfig.entry;
    delete wallabyWebpackConfig.watchOptions;
    delete wallabyWebpackConfig.output;
    delete wallabyWebpackConfig.optimization;
    const allowedPlugins = {
        ProvidePlugin: true,
        DefinePlugin: true,
        IgnorePlugin: true,
        CopyPlugin: true,
        MiniCssExtractPlugin: true
    };
    wallabyWebpackConfig.plugins = wallabyWebpackConfig.plugins.filter(
        plugin => allowedPlugins[plugin.constructor.name]
    );
    wallabyWebpackConfig.resolve.alias.tests = path.join(__dirname, 'tests');
    return wallabyWebpackConfig;
};

/**
 * NOTES:
 *
 * If you get an OOM error, try executing this `launchctl setenv NODE_OPTIONS --max_old_space_size=8192`
 * in your console, then restart your text editor (https://github.com/wallabyjs/public/issues/2618 for reference)
 */

module.exports = wallaby => {
    return {
        files: [
            // Files we want loaded via script tag for performance reasons
            { pattern: 'node_modules/react/umd/react.development.js', instrument: false },
            { pattern: 'node_modules/react-dom/umd/react-dom.development.js', instrument: false },
            { pattern: 'node_modules/yjs/y.js', instrument: false },
            { pattern: 'node_modules/chai/chai.js', instrument: false },
            { pattern: 'node_modules/sinon/pkg/sinon-no-sourcemaps.js', instrument: false },
            // Extra stuff
            { pattern: 'images/**/*', instrument: false, load: false, binary: true },
            // Test Files
            { pattern: 'tests/**/*.+(css|less|scss|svg)', instrument: false, load: false },
            { pattern: 'tests/auxiliary/**/*', instrument: true, load: false },
            { pattern: 'tests/resources/**/*', instrument: false, load: false },
            { pattern: 'tests/qa/resources/**/*', instrument: false, load: false, binary: true },
            { pattern: 'tests/images/**/*', instrument: false, load: false, binary: true },
            { pattern: 'tests/setup.ts', instrument: true, load: false },
            { pattern: 'tests/wallabySetup.js', instrument: true, load: false },
            // Primary Code
            { pattern: 'src/**/*.+(css|less|scss|svg)', instrument: false, load: false },
            { pattern: 'src/apps/uno/**/*', instrument: false, load: false }, // Speed up the build by not instrumenting uno code
            { pattern: 'src/**/*', instrument: true, load: false }
        ],

        tests: [
            { pattern: 'tests/unit/**/*', load: false },
            { pattern: 'tests/sys/peso/**/*', load: false },
            { pattern: 'tests/qa/peso/**/*', load: false }
        ],

        testFramework: 'mocha',

        env: {
            kind: 'chrome',
            /** Uncomment these params to debug weird Wallaby issues in a browser instance */
            params: {
                runner: '--disable-gpu'
            },
            keepTabsOpened: true
        },

        postprocessor: wallaby.postprocessors.webpack(getWallabyWebpackConfig(), {
            setupFiles: ['tests/wallabySetup.js']
        }),

        debug: false,

        setup() {
            mocha.setup({ timeout: 20000 });
            EN.listenTo('ready', () => window.__moduleBundler.loadTests());
        }
    };
};
```

I am using the latest versions for webpack and all of the various style loaders. There is nothing special about my output section of the webpack config but I am using various dynamic imports chunks as the result of dynamic imports. If you need more information that I can't provide for privacy reasons, I'd be happy to email you.

**Comment by smcenlly** [comment] 2021-04-01 23:20
> If you need more information that I can't provide for privacy reasons, I'd be happy to email you.

We completely understand your need for privacy but would really like to see the complete webpack configuration. Are you able to email that to us or else create a new repo that doesn't include any privileged information so we can see a similar failing config? Ideally we'd like to understand how/where the dynamic chunks are generated and see an example of where your css is included and where it is not included.

Please send your email to hello@wallabyjs.com

**Comment by smcenlly** [comment] 2021-04-06 22:40
@jljorgenson18 - just letting you know that we haven't received any email from you yet. If you have sent it and we have not received it, please let us know via this issue.

Since we haven't heard back, I'm going to close this issue and assume you'll contact us via email. Otherwise, we can re-open this issue if you prefer.

**Comment by jljorgenson18** [comment] 2021-04-07 01:38
@smcenlly I was on vacation for Easter so I wasn't around. I can email you guys tomorrow but I doubt there would be much here that would be illuminated from the full webpack config. It was working just fine in Webpack v4 and it broke in Webpack v5 and with the various loader updates. I have a strong suspicion based on how Webpack works that the following conditions would cause this issue

* Webpack v5 and up to date style loaders
* The style loader configuration above
* Multiple JS chunks
* An import of a number of style files with each of the various import types (.scss, .less, .scss?module, .less?module)
* A similar Wallaby configuration above

**Comment by NikGovorov** [comment] 2021-04-08 00:44
Hi @jljorgenson18,

When you open Chrome with `keepTabsOpened: true` could you please check what specific styles are not loaded and share how those styles are imported from your code?

**Comment by NikGovorov** [comment] 2021-04-08 08:16
@jljorgenson18 I've created a sample repo where I tried to reproduce the issue, no success. 
Could you please elaborate on ` various dynamic imports chunks as the result of dynamic imports` or even better fork the repo and demonstrate the issue there?

**Comment by jljorgenson18** [comment] 2021-04-08 16:08
@NikGovorov Thank you for taking a look at this. I had a few things come up so I haven't been able to give this a deeper look quite yet. The one thing that stands out in that repo is that the .ts chunks are not loaded with a dynamic import. When I open up tabs and see what Wallaby is loaded, it looks as if it is only loading the styles that are imported via the entry point module but **not** the styles that are loaded inside of the modules that are dynamically imported.

I could try to fork that repo later and do this, but I would propose the following changes to repro the issue

* Use a single setup file as an entry point. (e.g. `setupFiles: ['tests/wallabySetup.js']`)
* Inside of that setup file, use a dynamic import (e.g. `const byeModule = import('./bye');`)
* Inside of that module you dynamically imported, import a style

**Comment by NikGovorov** [comment] 2021-04-09 04:12
I've changed the repo to use [dynamic import](https://github.com/wallabyjs/wallaby-2679/blob/main/test/bye.spec.ts) and it works for me, however it is not 100% what you listed in your steps because I don't understand the first two steps.

> Use a single setup file as an entry point. (e.g. `setupFiles: ['tests/wallabySetup.js']`)

Wallaby always generates single entry point and one chunk, [setupFiles](https://wallabyjs.com/docs/integration/webpack-built-in.html#setup-files) are regular modules that are loaded before test modules.

>Inside of that setup file, use a dynamic import (e.g. `const byeModule = import('./bye');`)

`import('./bye');` returns `Promise<byeModule>` not `byeModule ` itself, so you would have to `await` for the promise that would require (top-level-await)[https://github.com/tc39/proposal-top-level-await] support. Do you use webpack's [experimental features](https://webpack.js.org/configuration/experiments/)?

**Comment by smcenlly** [comment] 2021-04-12 23:19
@jljorgenson18 - have you had a chance to read @NikGovorov's latest reply? We need some more information to assist you. Perhaps you could check out the [sample repo](https://github.com/wallabyjs/wallaby-2679) we created and fork it to demonstrate your problem to us?

**Comment by jljorgenson18** [comment] 2021-04-13 18:52
@NikGovorov I was under the impression that setupFiles are loaded before each test and then there are multiple test chunks to help with parallelization. Did that change? Regardless of the underlying implementation, I was just trying to get us aligned between the repro case and my project so we don't have to continually translate what my setup is and what the sample setup is. My setup uses a setupFile that imports a module with a number of dynamic imports. I then wait for that module to be ready, 

```
        setup() {
            mocha.setup({ timeout: 20000 });
            EN.listenTo('ready', () => window.__moduleBundler.loadTests());
        }
```

I am not using top level dynamic imports and I am not using experimental features. My primary entry point file instantiates a type of mediator class that loads in each of our dynamic import modules that are needed for tests. It works sort of like this

```
class SomeMediator {
   activate() {
      return Promise.all([/* dynamic imports here */]);
   }

}
```

I can try to fork it and tweak the sample repo but I've been really bogged down the past few days and I was dealing with health issues.

**Comment by jljorgenson18** [comment] 2021-04-13 19:39
Ok, I got it to break

https://github.com/jljorgenson18/wallaby-2679

From what I can tell, only one css chunk chunk is loaded at a time when they should all be loaded simultaneously. I am getting a failing test case for bye.spec.ts because the CSS module is not loaded.

<img width="1370" alt="Screen Shot 2021-04-13 at 2 39 00 PM" src="https://user-images.githubusercontent.com/5751354/114610861-00dcce00-9c66-11eb-932d-e5009a00fa87.png">

<img width="1198" alt="Screen Shot 2021-04-13 at 2 39 15 PM" src="https://user-images.githubusercontent.com/5751354/114610885-0803dc00-9c66-11eb-851d-5bab4f00736f.png">

**Comment by smcenlly** [comment] 2021-04-14 02:56
Thanks so much for creating the reproduceable sample. It took us a little while to find and understand the cause but this is now fixed in Wallaby core `v1.0.1060`. Wallaby should update to the latest version for you automatically and everything should now work for you. If Wallaby does not update automatically, you may [force a core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Closed by smcenlly** 2021-04-14 02:56 UTC

**Comment by NikGovorov** [comment] 2021-04-14 03:14
> @NikGovorov I was under the impression that setupFiles are loaded before each test and then there are multiple test chunks to help with parallelization.  Did that change? 

No, that didn't change,  `setupFiles` are loaded before each tests run i.e. new browser tab.

**Comment by jljorgenson18** [comment] 2021-04-14 03:31
Awesome! Glad you guys got to the bottom of it. This widdled my test failures down from about 100 to 11 so I think there may be one more issue to deal with but I'll file a separate issue if needed.

**Comment by jljorgenson18** [comment] 2021-04-14 03:56
Here is the other issue https://github.com/wallabyjs/public/issues/2685

I was able to find a quick workaround and now all my tests are passing. Thanks again!
