### ISSUE TITLE
Your test suite must contain at least one test

### ISSUE THREAD

**Issue by Almenit** [wallabyjs/public#1642] opened 2018-05-04 08:54 UTC
### Issue description or question
Randomly fails in different files with "Your test suite must contain at least one test
### Wallaby.js configuration file

```javascript
"use strict";
process.env.BABEL_ENV = "test";
module.exports = function (wallaby) {
    return {
        files: [
            "package.json",
            "tsconfig.json",
            "setup-jest.js",
            "fileMock.js",
            "Capish.Reflect.Web/Content/Scripts/**/*.+(ts|tsx|snap|svg|json)",
            "!Capish.Reflect.Web/Content/Scripts/**/__tests__/test.*.ts?(x)",
            "Capish.Reflect.ConfigurationBuilders/**/*.ts?(x)",
            "!Capish.Reflect.ConfigurationBuilders/**/__tests__/test.*.ts?(x)"
        ],

        tests: [
            "Capish.Reflect.Web/Content/Scripts/**/__tests__/test.*.ts?(x)",
            "Capish.Reflect.ConfigurationBuilders/**/__tests__/test.*.ts?(x)"
        ],

        debug: true,

        preprocessors: {
            'Capish.Reflect.Web/Content/Scripts/**/*.js?(x)': file =>
                require("@babel/core")
                    .transform(file.content, {
                        sourceMap: true,
                        compact: false,
                        babelrc: true,
                        filename: file.path
                    })
        ,
            'Capish.Reflect.ConfigurationBuilders/**/*.js?(x)': file =>
                require("@babel/core")
                    .transform(file.content, {
                        sourceMap: true,
                        compact: false,
                        babelrc: true,
                        filename: file.path
                    })
        },
        env: {
            type: "node",
            runner: "node"
        },
        testFramework: "jest"
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.22.2

### OS name and version

Windows 10

We have no snapshot tests (yet).
Jest version: 22.4.3

**Comment by ArtemGovorov** [comment] 2018-05-04 08:59
> Your test suite must contain at least one test

The error is coming from Jest, so in order to troubleshoot it we need a reproducible example. Please try creating a sample repo where the issue can be reproduced.

My only guess without a sample would be that some of your files under
```
Capish.Reflect.Web/Content/Scripts/**/__tests__/test.*.ts?(x)
Capish.Reflect.ConfigurationBuilders/**/__tests__/test.*.ts?(x)
```
don't contain any tests (ie. `it`/`describe` blocks).

**Comment by Almenit** [comment] 2018-05-22 08:04
It looks like it's the Auto Save option in VS Code that causes the issue.

**Comment by ArtemGovorov** [comment] 2018-05-22 08:26
Could you please open your VS Code settings and share the value of the `"files.autoSave"` from there?

**Comment by ArtemGovorov** [comment] 2018-05-22 08:33
Also the `"files.autoSaveDelay": ...` if you have it.

**Comment by Almenit** [comment] 2018-05-22 09:01
`"files.autoSave": "afterDelay",`
I dont' have `"files.autoSaveDelay"`

**Comment by ArtemGovorov** [comment] 2018-05-22 23:51
Thanks. Tried to play for a while with the `"files.autoSave": "afterDelay"` setting, and can't seem to reproduce the issue.

You have mentioned that you're randomly getting the issue on different files:
- are those only spec files or source files as well that you are editing when getting the issue?
- how frequently are you getting it? Once a minute, several minutes, hour/hours? I'd like to understand whether I've spent enough time trying to reproduce it.

**Comment by ThomasKlessen** [comment] 2018-05-25 13:20
Not sure if this is helpful:
I'am using Webstorm with autosave enabled and get the same error if i create a new test file. 
Obviously because it is empty. After adding test everything works like a charm.

**Comment by ArtemGovorov** [comment] 2018-05-26 00:33
> i create a new test file.
Obviously because it is empty. After adding test everything works like a charm.

Yep, this is expected.

**Comment by Almenit** [comment] 2018-11-13 08:35
I still get this issue. It doesn't look like it is related to autosave (since I have it disabled now). Don't know if it is the amount of files/tests. We have 1750 tests and aprox. 750 files and 150 folders.

But it looks like something happens when you save. I sometimes get `xxx.default is not a constructor​​` in my recent edited test file, after I do an Save All. I have abstract class as base class. So I got `​​TypeError: Class extends value [object Object] is not a constructor or null​​` when I commented out the creation of the class xxx in my test. If I then edit the base class and remove the comment. The tests run after that but then I get
`​​Error: Your test suite must contain at least one test.​​
​​    at C:\Dev\Repos\Reflect\Source\node_modules\jest\node_modules\jest-cli\build\TestScheduler.js:256:22​​
​​    at Generator.next (<anonymous>)​​`

It looks like it works as long as you don't save. But I'm not 100% sure on that.

**Comment by smcenlly** [comment] 2018-11-16 00:10
@Almenit - Can you please provide us with a sample repo of your project's structure (removing any application code you can't share) so that we can analyze your package.json, jest setup, use of babel, etc?

**Comment by Almenit** [comment] 2018-11-16 07:59
Sorry but I'm not allowed to share any code. But I can share config for jest, wallaby etc. But my guess is that you need a larger code base to get this kind of error, otherwise I guess you should have seen them more.

**Comment by Almenit** [comment] 2018-11-19 07:42
[tsconfig.json.txt](https://github.com/wallabyjs/public/files/2594183/tsconfig.json.txt)
[package.json.txt](https://github.com/wallabyjs/public/files/2594198/package.json.txt)
[setup-jest.js.txt](https://github.com/wallabyjs/public/files/2594207/setup-jest.js.txt)

**Comment by pearljamik** [comment] 2018-11-26 10:16
I have the same problem, my config is:

`module.exports = function(w) {
  return {

    files: [
      'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)',
      'jest.json',
      '!src/**/*spec.+(ts)',
      '@types/**/*',
      'swagger/swagger.json',
      '__mocks__/**/*',
      './.env',
      'tsconfig.json'
    ],

    tests: ['src/**/*spec.ts'],

    testFramework: 'jest',

    env: {
      type: 'node',
      runner: 'node'
    },

    workers: {
      initial: 1,
      regular: 1
    },

    debug: true
  };
};`

**Comment by couellet** [comment] 2019-02-22 17:20
I'm having this issue too, any workarounds have been found?

**Comment by smcenlly** [comment] 2019-02-22 22:14
@couellet - are you able to provide us with a sample repo that has the problem? We'd be happy to take a look.

**Comment by smcenlly** [comment] 2019-03-12 22:55
Closing this issue as we need more information to reproduce. We will re-open the issue if more detail is provided.

**Closed by smcenlly** 2019-03-12 22:55 UTC
Labels: configuration question, more info is required, reproducible example is required

**Comment by smcenlly** [comment] 2019-03-28 05:22
The problem was caused by a combination of Windows file system changed events and the way that VS Code flushes content to disk after write.

This has now been fixed. Please download the latest version of Wallaby for VS Code, v1.0.121. This will also download the latest version of Wallaby core, which is also necessary.
