### ISSUE TITLE
Cannot read property indexOf of undefined

### ISSUE THREAD

**Issue by tinovyatkin** [wallabyjs/public#1032] opened 2017-02-21 13:42 UTC
![screen shot 2017-02-21 at 09 38 34 am](https://cloud.githubusercontent.com/assets/5350898/23167262/1334c728-f81a-11e6-86b1-3796645f45c7.png)

**Comment by ArtemGovorov** [comment] 2017-02-21 13:44
Duplicate of https://github.com/wallabyjs/public/issues/1031. Jest 19 support is added in  [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update)

**Closed by ArtemGovorov** 2017-02-21 13:44 UTC
Labels: duplicate
