### ISSUE TITLE
Make it possible to disable code coverage for selected functions

### ISSUE THREAD

**Issue by eggyal** [wallabyjs/public#468] opened 2016-02-20 22:42 UTC
Unit tests should only cover a module's public API.  Where code exists that is not exported, but is only reachable from elsewhere in a module, it's effectively "private" implementation detail that shouldn't be covered by unit tests.  Warnings that such code is uncovered only adds noise and encourages bad practice.

Whether automatically or through explicit (inline?) demarcation, it would be ideal if these warnings could be disabled for private code.

**Comment by ArtemGovorov** [comment] 2016-02-20 23:02
By coverage warnings, do you mean grey indicators in the editor gutter?

I don't think I understand what exactly you wouldn't like to see covered. If some code is "is not exported, but is only reachable from elsewhere in a module" how can we automatically tell if it's "private" or just not yet tested code that's supposed to be tested?  Could you please provide an example of such private methods?

Having said that, I think it'd be a good enhancement to provide a way to disable coverage for certain functions via some manual demarcation.

**Comment by eggyal** [comment] 2016-02-20 23:21
Yes, I do mean the grey indicators in the gutter.

The pattern that I adopt for "private" methods is:

```javascript
// SomeThing.js

function privateMethod()
{
    // do private stuff
}

export class
{
  publicMethod()
  {
    // do stuff
    privateMethod.call(this);
    // do more stuff
  }
}
```

Then, a module that imports the above would do something like:

```javascript
import SomeThing from './SomeThing';

const theThing = new SomeThing();
theThing.publicMethod();  // publicMethod is accessible
theThing.privateMethod(); // throws TypeError: ‘undefined’ is not a function
```

Basically, I'm only interested in testing methods that are defined on exports from my modules, not on functions that aren't exported.

**Comment by ArtemGovorov** [comment] 2016-02-20 23:30
Thanks for the example.

> Basically, I'm only interested in testing methods that are defined on exports from my modules, not functions that aren't exported.

I understand why you don't want to expose these private functions for your tests (or other modules), but I don't understand why you don't want to see the coverage for it. 
One may write the whole module in a way that all public methods do is calling some private functions. If some important logic of your app resides in these private functions, why ignoring the coverage for them?

**Comment by eggyal** [comment] 2016-02-20 23:45
Perhaps I'm misunderstanding what the coverage indicators are showing—I've literally only just started playing with Wallaby.  If one tests only `publicMethod()`, might that cover code in `privateMethod()`?

**Comment by ArtemGovorov** [comment] 2016-02-21 00:11
> If one tests only `publicMethod()`, might that cover code in `privateMethod()`?
Yes. `publicMethod` calls `privateMethod`, so the code covered by a test that calls `publicMethod` includes `privateMethod` and whatever it calls. The coverage indicators are displaying the fact that some particular line/statement/expression has been exercised by one of your tests.

**Comment by ArtemGovorov** [comment] 2016-02-21 00:14
And "exercised by one of your tests" doesn't only mean the immediate function invoked by a test, but also any code on the execution path.

**Comment by eggyal** [comment] 2016-02-21 18:31
Ah right, I feel pretty silly now!

That being the case, I see no benefit whatsoever in this "feature" request.  I'd close, except you've expressed some interest in providing means of manually disabling coverage in certain places anyway?  I'll leave in your court.

**Comment by ArtemGovorov** [comment] 2016-02-21 23:06
@eggyal In order to collect code coverage, wallaby instruments the source code (by changing it) and sometimes it may not be desirable. For example, when a function is defined in one context, but is passed to some other context where there's no infrastructure to execute instrumentation instructions. Another example is when some code relies on some function original source code, so instrumenting the code may not be desirable.

**Comment by DanielSands** [comment] 2016-02-24 08:28
+1 for code-block disable option. 

A unit test should only really test the logic of your own application, if you have methods which are effectively just wrapping functions for a library, or otherwise, then testing this block would have no impact on your application integrity, but would be detrimental to code coverage stats and thus may lead to bad practices as dev's try to fudge together nonsensical tests which don't actually test anything!

**Comment by grantbowering** [comment] 2016-11-07 17:54
I have this problem right now with the `render()` method of tsx files in a react/redux typescript project.  I like to be able to use the wallaby app's code coverage metrics to assess what components have at least minimal test coverages, but the majority of a TSX or JSX file is going to be the render() method that emits a bunch of markup.  
Other methods that appear in that file may contain calculated display logic that should be tested, so I do want to see those files factored into the percentages and badges shown for files and folders in the wallaby app, but in the render() method itself, it's generally just things like ternary statements to show a chunk of html or not, over a bool whose value should be covered by other tests.  Calling render() and digging through the markup we get back from it is a laborious task of often pretty low value, and the team has ruled out writing tests like that for complex components.  So I'd love to be able to just tell wallaby to skip the whole function when calculating the coverage metric.
The Istanbul coverage tool uses [ignore comments](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md) to skip certain sections:
```
someFunMemberFunction: () => {
    // coverage assessed as normal
}

/* istanbul ignore next*/
render() {
    // this whole body would not be factored for code coverage at all
}
```

If you were to support that same syntax, people already using that approach would get the code coverage they already set up for other tools in wallaby as well.

**Comment by ArtemGovorov** [comment] 2016-11-10 05:50
The [feature support](https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-code-blocks-inside-a-file) is landed in the core v1.0.321. Note that wallaby config change is required to enable it (specifying the hint). You may either wait for the automatic core update or [force the update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Closed by ArtemGovorov** 2016-11-10 05:50 UTC
Labels: enhancement

**Comment by ArtemGovorov** [comment] 2016-11-10 23:50
@grantbowering It has definitely been published with the 1.0.321 version. I have just copy/pasted the sample from the docs to [our React sample repo](https://github.com/ArtemGovorov/wallaby-webpack-es6-react/blob/master/wallaby.js#L37) and tried to [disable the `render` function coverage](https://github.com/ArtemGovorov/wallaby-webpack-es6-react/blob/master/src/Label.jsx#L4) and it works for me in all supported editors.

So the config like:
```javascript
  module.exports = function () {

    return {
      ...
      hints: {
        ignoreCoverage: /ignore coverage/
      }
    };
  };
```
is working as expected:

![vsc](https://cloud.githubusercontent.com/assets/979966/20199087/f8ffc112-a7f3-11e6-8848-7ab9a7ff0eb9.gif)

Could you please check if the sample is working for you? If it is, could you please share a sample project with your config and a file where it doesn't working for you so we may have a look?

**Comment by grantbowering** [comment] 2016-11-14 22:15
I can confirm the React sample repo works for me as well, so it must be a specific combination of things.  I'll try to put together a broken one based on the real project that isn't working...  One possible culprit off the top of my head, though, is that the React sample is in javascript and the project in question is in Typescript?

**Comment by ArtemGovorov** [comment] 2016-11-15 01:28
> that the React sample is in javascript and the project in question is in Typescript?

Thanks for checking and for the note, I think it was it.

Wallaby.js used to configure TS compiler with `removeComments` set to `true` by default, so coverage hints were lost during the compilation. I have changed it in the latest core version v1.0.323 to be `false` by default. You may either [update the core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) or set `removeComments` to `false` in your `tsconfig.json` and see if it works for you.

**Comment by grantbowering** [comment] 2016-11-15 16:56
In hindsight, the fact it was a comment-scrubbing problem probably should have been obvious to me.  Sorry for not figuring that out on my own! :)
I can confirm that v1.0.323 works as expected.  Thanks!
(I'm still working on isolating a weird unrelated problem where a few tests fail on first run with a JSON parse problem but then pass as soon as you touch the test file, but then once I have a cleaned-up repro for that I'll open a new issue)

**Comment by mdebruijne** [comment] 2016-11-21 11:34
@ArtemGovorov 

I have tested the sample repo and it works fine. However, it doesn't work for other projects.

Is it possible that the ignoreCoverage string in JSON isn't converted to a RegEx correctly? (examples use native RegEx in JavaScript)

Is the RegEx matching based on partial match or exact match? (I have also tried "ignoreCoverage": "/.\*istanbul ignore.\*/" just to be sure)

Any ideas how to troubleshoot?


Code;
``` javascript
'use strict'

// istanbul ignore next
function ignoreMe() {
  return true
}
```

wallaby.json;
``` javascript
{
  "env": {
    "type": "node",
    "runner": "node",
    "params": {
      "runner": "--harmony_async_await"
    }
  },
  "files": [
    "lib/*.js"
  ],
  "hints": {
    "ignoreCoverage": "/istanbul ignore/"
  },
  "testFramework": "jest",
  "tests": [
    "test/*.js"
  ]
}
```

**Comment by mdebruijne** [comment] 2016-11-21 13:32
@ArtemGovorov 

I have tested without the slashes and everything is working as expected now. Thanks for your quick support!

**Comment by potz** [comment] 2017-08-06 03:38
I have a weird bug with this feature in VsCode/TypeScript where the setting works everywhere except in a line that calls `fs.unlinkSync(socketName)` inside an async function.

If I try to move the line somewhere else (non-async method) it works...

<img width="569" alt="screen shot 2017-08-06 at 00 35 50" src="https://user-images.githubusercontent.com/5178184/29000386-4b914838-7a3f-11e7-91fa-1a389ef1a13b.png">

notice the uncovered white square on the async method?

I'm using this wallaby.conf file:

```js
module.exports = function (wallaby) {
    return {
        files: [
            'tsconfig.json',
            'src/**/*',
            { pattern: 'src/**/*Test.ts', ignore: true }
        ],

        tests: [
            'src/**/*Test.ts'
        ],

        hints: {
            ignoreCoverage: /uncovered/
        },

        env: {
            type: 'node'
        },

        compilers: {
            '**/*.ts': wallaby.compilers.typeScript({ module: 'commonjs', experimentalDecorators: true })
        },

        testFramework: 'mocha',

        setup: function (wallaby) {
            require('ts-node/register')
            require('./src/testHelpers/_setup')
            const mocha = wallaby.testFramework
            mocha.ui('tdd')
            mocha.reporter('spec')
            mocha.timeout(900)
        }
    }
}

```

**Comment by ArtemGovorov** [comment] 2017-08-06 12:16
@potz It's weird indeed. Also we can't reproduce it, could you please share a sample repo where we could reproduce the issue?
