### ISSUE TITLE
Support of other languages and frameworks

### ISSUE THREAD

**Issue by comerc** [wallabyjs/public#2867] opened 2021-12-05 10:07 UTC
Thanks for the great tool! What about other languages and frameworks? GoLang, Dart, Flutter...

**Comment by smcenlly** [comment] 2021-12-05 23:18
Closing as a duplicate of https://github.com/wallabyjs/public/issues/2516.

We don't have any immediate plans to support other languages at this point in time.

**Closed by smcenlly** 2021-12-05 23:18 UTC
