### ISSUE TITLE
No inline coverage when ReSharper is enabled

### ISSUE THREAD

**Issue by jamiehumphries** [wallabyjs/public#134] opened 2015-05-28 11:16 UTC
I have just installed the Visual Studio extension and on first trial I didn't get any inline coverage.

The *Wallaby.js - Console* ouput reads:

    wallaby.js started
    core v1.0.53
    Finished executing 9 affected test(s)

But the progress indicator in the bottom corner never stopped spinning and the inline coverage did not show up.

After a bit of experimenting I found that if I suspended [ReSharper](https://www.jetbrains.com/resharper/) and restarted Visual Studio everything worked as expected (the VS restart was necessary, simply suspending ReSharper was not enough). It was even possible to re-enable ReSharper at this point and continue working, but if I restarted Visual Studio again with ReSharper still enabled I got the same issue as before.

I love Wallaby.js but I couldn't work without ReSharper, so for now this is a dealbreaker for me :cry:

I am running:
- Visual Studio 2013 Premium Update 4
- ReSharper 9.1.1
- Wallaby extension 1.0.1 (downloaded 28/05/15)
- (Windows 8.1)

**Comment by ArtemGovorov** [comment] 2015-05-28 11:23
@jamiehumphries Thanks for the detailed steps, I'm working on it.

**Comment by ArtemGovorov** [comment] 2015-05-28 13:10
Looks like wallaby.js version of json.net and the latest ReSharper version of json.net had some conflicts. The issue is fixed now. Please try the latest version (should prompt you to install next time you start wallaby.js).

**Closed** 2015-05-28 13:10 UTC
Labels: Visual Studio

**Comment by jamiehumphries** [comment] 2015-05-28 13:33
That's done it, thanks @ArtemGovorov!
