### ISSUE TITLE
vscode 'jump to error source' command fails with error

### ISSUE THREAD

**Issue by breathe** [wallabyjs/public#1291] opened 2017-09-06 16:05 UTC
### Issue description or question

Wallaby.js console prints this

```
​​[Error] Failed to start location operation, TypeError: Cannot read property 'stack' of undefined​​
​​[Error]   at t.locationByRequest (/Users/bcohen/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.56/wallaby/node_modules/phantom/receiver.js:2:20653)​​
​​[Error]   at n.location (/Users/bcohen/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.56/wallaby/node_modules/phantom/receiver.js:1:18624)​​
​​[Error]   at Object.n.receive (/Users/bcohen/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.56/wallaby/server.js:14:3516)​​
​​[Error]   at WebSocket.<anonymous> (/Users/bcohen/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.56/wallaby/server.js:19:31991)​​
​​[Error]   at emitTwo (events.js:106:13)​​
​​[Error]   at WebSocket.emit (events.js:194:7)​​
​​[Error]   at Receiver.ontext (/Users/bcohen/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.56/wallaby/node_modules/ws/lib/WebSocket.js:841:10)​​
​​[Error]   at /Users/bcohen/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.56/wallaby/node_modules/ws/lib/Receiver.js:536:18​​
​​[Error]   at /Users/bcohen/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.56/wallaby/node_modules/ws/lib/Receiver.js:368:7​​
​​[Error]   at /Users/bcohen/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.56/wallaby/node_modules/ws/lib/PerMessageDeflate.js:249:5​​
​​[Error]   at afterWrite (_stream_writable.js:383:3)​​
​​[Error]   at onwrite (_stream_writable.js:374:7)​​
​​[Error]   at afterTransform (_stream_transform.js:79:3)​​
​​[Error]   at Zlib.callback (zlib.js:625:5)​​
```

when I type cmd-shift-R then P or invoke 'jump to error source' command

### Wallaby.js configuration file

```javascript
module.exports = function() {
  return {
    files: [
      "!lib/**",
      "!src/**/*.test.ts",
      "package.json",
      "tsconfig.json",
      ".secrets/*",
      "resources/**/*",
      "src/**/*.yml",
      "src/**/*.ts",
      "serverless-services/*",
      "serverless-services/**/*.yml"
    ],

    tests: ["src/**/*.test.ts", "!src/service-tests/**/*"],

    env: {
      type: "node",
      runner: "node"
    },

    debug: true,
    testFramework: "jest",

    setup: function(wallaby) {
      var jestConfig = require("./package.json").jest;
      jestConfig.moduleNameMapper = {
        "^.*/Configuration/(.*)-shim.js$":
          wallaby.projectCacheDir + "/src/Configuration/$1",
        "^.*/lib/ServerlessPlugins/(.*)$":
          wallaby.projectCacheDir + "/src/ServerlessPlugins/$1"
      };
      wallaby.testFramework.configure(jestConfig);
    }
  };
};
```

I haven't upgraded to Jest 21 yet -- still using:
```
 "jest": "^20.0.4"
```
### Code editor or IDE name and version

Visual Studio Version 1.15.1 (1.15.1)

### OS name and version

OSX

**Comment by ArtemGovorov** [comment] 2017-09-07 04:34
Thanks for the report.

The issue is fixed in the latest VS Code extension v1.0.57.

**Closed by ArtemGovorov** 2017-09-07 04:34 UTC
Labels: bug
