### ISSUE TITLE
Repro for bind issue

### ISSUE THREAD

**Issue by aaronjensen** [wallabyjs/public#260] opened 2015-09-12 06:50 UTC
Ok, I've got a repro. It's a bit strange, but it repros for me consistently. 

Using the bind-repro branch: https://github.com/aaronjensen/wallaby-line-number-repro/tree/bind-repro

1. Before starting wallaby, delete `lib/bar.js`
1. Start wallaby, it may say the cache is corrupt, restart if so.
1. `git checkout lib/bar.js` to bring the file back.
1. :boom:

![bind](https://cloud.githubusercontent.com/assets/8588/9830352/e30448a6-58df-11e5-8859-60b99332c9f1.gif)

**Comment by ArtemGovorov** [comment] 2015-09-12 13:31
Thanks a lot for the repro, the issue is fixed in core v1.0.104.

**Closed by ArtemGovorov** 2015-09-12 13:31 UTC
Labels: bug
