### ISSUE TITLE
Time tracking feature with progress bar 

### ISSUE THREAD

**Issue by hellboy81** [wallabyjs/public#267] opened 2015-09-18 11:32 UTC
Please add feature to enable time estimate "Unit tests are ready in DD days, HH hours, MM minutes",
"XX percents of unit tests are ready to cover all business valued lines of code", "XX percents of unit tests are rewritten using new assertion lib", etc..

;-)

**Comment by fvanwijk** [comment] 2015-09-18 12:54
+1 I was planning to post this enhancement suggestion as well :)
I have about 6000 tests running in a minute or so... I have to switch to the console tab to see the "Execution progress" messages, while the test results will be eventually in the other tab. I'd like to have intermediate results in the "Failing tests" tab (which still should be renamed to "Test results" anyway).

**Comment by hellboy81** [comment] 2015-09-18 17:06
I mea (re)wriiting unit tests by developer for existing code, not running ,-)

**Comment by ArtemGovorov** [comment] 2015-09-19 02:29
Yes, it seems like a duplicate of https://github.com/wallabyjs/public/issues/38. 

@hellboy81 Feel free to suggest some algorithms how to calculate "Unit tests are ready in DD days, HH hours, MM minutes" :) in this issue https://github.com/wallabyjs/public/issues/38

@fvanwijk 6k tests is impressive! How many cores/wallaby workers do you use and how large is your app in LoC, if I may ask? Regarding the progress, please feel free to create a separate issue for it with some description how you would like to see the progress on the tests tab.

**Closed by ArtemGovorov** 2015-09-19 02:29 UTC
Labels: duplicate

**Comment by fvanwijk** [comment] 2015-09-21 11:03
Angular app is about 26000 LOC and 68000 LOC specs (coverage about 97.5%). It takes 30 secs to load all files and 40 secs to run the tests. Running on Mac with 2.8Ghz i7 and 16GB mem.

Wallaby worker settings are the defaults, so no idea how many cores, but we're pushing the Phantom (1.9.8) memory limits. It usually crashes around 5000 tests. Time to split things up in components... (microservices ;-))
